MODULE CPG_OPTS_TYPE_MOD

USE PARKIND1, ONLY : JPIM, JPRB

IMPLICIT NONE

TYPE CPG_BNDS_TYPE
  INTEGER(KIND=JPIM) :: KIDIA 
  INTEGER(KIND=JPIM) :: KFDIA 
  INTEGER(KIND=JPIM) :: KFDIE 
  INTEGER(KIND=JPIM) :: KIDIE
  INTEGER(KIND=JPIM) :: KBL 
  INTEGER(KIND=JPIM) :: KSTGLO 

  INTEGER(KIND=JPIM) :: KLON 
  INTEGER(KIND=JPIM) :: KGPTOT 
  INTEGER(KIND=JPIM) :: KGPCOMP 

CONTAINS
  GENERIC :: INIT => CPG_BNDS_TYPE_INIT_OPTS, CPG_BNDS_TYPE_INIT
  PROCEDURE, PRIVATE :: CPG_BNDS_TYPE_INIT_OPTS 
  PROCEDURE, PRIVATE :: CPG_BNDS_TYPE_INIT
  PROCEDURE :: UPDATE => CPG_BNDS_TYPE_UPDATE
END TYPE CPG_BNDS_TYPE

TYPE CPG_OPTS_TYPE

  INTEGER(KIND=JPIM) :: KLON 
  INTEGER(KIND=JPIM) :: KFLEVG 
  INTEGER(KIND=JPIM) :: KGPTOT 
  INTEGER(KIND=JPIM) :: KGPBLKS
  INTEGER(KIND=JPIM) :: KGPCOMP 
  INTEGER(KIND=JPIM) :: JBLKMIN
  INTEGER(KIND=JPIM) :: JBLKMAX

CONTAINS

  PROCEDURE :: INIT => CPG_OPTS_TYPE_INIT

END TYPE CPG_OPTS_TYPE

CONTAINS

  SUBROUTINE CPG_BNDS_TYPE_INIT_OPTS (SELF, YDCPG_OPTS)
    CLASS(CPG_BNDS_TYPE) :: SELF
    TYPE(CPG_OPTS_TYPE), INTENT(IN) :: YDCPG_OPTS

    SELF%KBL          =  1
    SELF%KLON         =  YDCPG_OPTS%KLON
    SELF%KIDIA        =  1
    SELF%KIDIE        =  1
    SELF%KFDIA        =  YDCPG_OPTS%KLON
    SELF%KFDIE        =  YDCPG_OPTS%KLON
    SELF%KGPTOT       =  YDCPG_OPTS%KGPTOT
    SELF%KGPCOMP      =  YDCPG_OPTS%KGPCOMP

  END SUBROUTINE CPG_BNDS_TYPE_INIT_OPTS

  SUBROUTINE CPG_BNDS_TYPE_INIT (SELF, KLON, KGPTOT)
    CLASS(CPG_BNDS_TYPE) :: SELF
    INTEGER (KIND=JPIM), INTENT (IN) :: KLON
    INTEGER (KIND=JPIM), INTENT (IN) :: KGPTOT

    SELF%KBL          =  1
    SELF%KLON         =  KLON
    SELF%KIDIA        =  1
    SELF%KIDIE        =  1
    SELF%KFDIA        =  KLON
    SELF%KFDIE        =  KLON
    SELF%KGPTOT       =  KGPTOT
    SELF%KGPCOMP      =  KGPTOT

  END SUBROUTINE CPG_BNDS_TYPE_INIT

  SUBROUTINE CPG_BNDS_TYPE_UPDATE(SELF, IBL)
    CLASS(CPG_BNDS_TYPE) :: SELF
    INTEGER(KIND=JPIM), INTENT(IN) :: IBL

    SELF%KBL    = IBL
    SELF%KSTGLO = 1 + (IBL - 1) * SELF%KLON
    SELF%KFDIA  = MIN (SELF%KLON, SELF%KGPCOMP - SELF%KSTGLO + 1)
    SELF%KFDIE  = MIN (SELF%KLON, SELF%KGPTOT  - SELF%KSTGLO + 1)

  END SUBROUTINE CPG_BNDS_TYPE_UPDATE

  SUBROUTINE CPG_OPTS_TYPE_INIT (SELF, KLON, KFLEVG, KGPBLKS)
    CLASS (CPG_OPTS_TYPE) :: SELF
    INTEGER(KIND=JPIM) :: KLON, KFLEVG, KGPBLKS

    SELF%KLON    = KLON 
    SELF%KFLEVG  = KFLEVG 
    SELF%KGPTOT  = KLON * KGPBLKS
    SELF%KGPBLKS = KGPBLKS
    SELF%KGPCOMP = SELF%KGPTOT
    SELF%JBLKMIN = 1
    SELF%JBLKMAX = KGPBLKS

  END SUBROUTINE

END MODULE CPG_OPTS_TYPE_MOD
