
SUBROUTINE CUASCN_OPENACC (YDTHF, YDCST, YDEPHLI, YDECLDP, YDECUMF, YDSPP_CONFIG, YGFL, KIDIA&
&, KFDIA, KLON, KLEV, LDTDKMF, PTSPHY, PTENH, PQENH, PUEN, PVEN, PTEN, PQEN, PQSEN, PLITOT, PGEO&
&, PGEOH, PAP, PAPH, PVERVEL, PWUBASE, PGP2DSPP, LDLAND, LDCUM, KTYPE, KLAB, LSCVFLAG, PTU, PQU&
&, PLU, PLRAIN, PMFU, PMFUB, PLGLAC, PMFUS, PMFUQ, PMFUL, PLUDE, PLUDELI, PDMFUP, PLCRIT_AER&
&, PDMFEN, KCBOT, KCTOP, KCTOP0, KDPL, PMFUDE_RATE, PKINEU, PWU, PWMEAN, YDSTACK)
!$acc routine (CUASCN_OPENACC) seq
USE PARKIND1,ONLY:JPIM, JPRB

USE YOMCST,ONLY:TCST
USE YOETHF,ONLY:TTHF
USE YOECUMF,ONLY:TECUMF
USE YOEPHLI,ONLY:TEPHLI
USE YOECLDP,ONLY:TECLDP
USE YOM_YGFL,ONLY:TYPE_GFLD
USE SPP_MOD,ONLY:TSPP_CONFIG
USE SPP_GEN_MOD,ONLY:SPP_PERT
USE ABOR1_ACC_MOD
USE STACK_MOD
#include "stack.h"

IMPLICIT NONE

TYPE (TTHF), INTENT (IN)::YDTHF
TYPE (TCST), INTENT (IN)::YDCST
TYPE (TECLDP), INTENT (IN)::YDECLDP
TYPE (TECUMF), INTENT (IN)::YDECUMF
TYPE (TEPHLI), INTENT (IN)::YDEPHLI
TYPE (TSPP_CONFIG), INTENT (IN)::YDSPP_CONFIG
TYPE (TYPE_GFLD), INTENT (IN)::YGFL
INTEGER (KIND=JPIM), INTENT (IN)::KLON
INTEGER (KIND=JPIM), INTENT (IN)::KLEV
INTEGER (KIND=JPIM), INTENT (IN)::KIDIA
INTEGER (KIND=JPIM), INTENT (IN)::KFDIA
REAL (KIND=JPRB), INTENT (IN)::PTSPHY
REAL (KIND=JPRB), INTENT (IN)::PLCRIT_AER (KLON, KLEV)
REAL (KIND=JPRB), INTENT (INOUT)::PTENH (KLON, KLEV)
REAL (KIND=JPRB), INTENT (INOUT)::PQENH (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PUEN (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PVEN (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PTEN (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PQEN (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PQSEN (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PLITOT (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PGEO (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PGEOH (KLON, KLEV+1)
REAL (KIND=JPRB), INTENT (IN)::PAP (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PAPH (KLON, KLEV+1)
REAL (KIND=JPRB), INTENT (IN)::PVERVEL (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PWUBASE (KLON)
REAL (KIND=JPRB), INTENT (IN)::PGP2DSPP (KLON, YDSPP_CONFIG%SM%NRFTOTAL)
LOGICAL, INTENT (IN)::LDLAND (KLON)
LOGICAL, INTENT (INOUT)::LDCUM (KLON)
LOGICAL, INTENT (IN)::LDTDKMF
LOGICAL, INTENT (OUT)::LSCVFLAG (KLON)
INTEGER (KIND=JPIM), INTENT (INOUT)::KTYPE (KLON)
INTEGER (KIND=JPIM), INTENT (INOUT)::KLAB (KLON, KLEV)
REAL (KIND=JPRB), INTENT (INOUT)::PTU (KLON, KLEV)
REAL (KIND=JPRB), INTENT (INOUT)::PQU (KLON, KLEV)
REAL (KIND=JPRB), INTENT (INOUT)::PLU (KLON, KLEV)
REAL (KIND=JPRB), INTENT (INOUT)::PLRAIN (KLON, KLEV)
REAL (KIND=JPRB), INTENT (INOUT)::PMFU (KLON, KLEV)
REAL (KIND=JPRB), INTENT (INOUT)::PMFUB (KLON)
REAL (KIND=JPRB), INTENT (OUT)::PLGLAC (KLON, KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PMFUS (KLON, KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PMFUQ (KLON, KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PMFUL (KLON, KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PLUDE (KLON, KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PLUDELI (KLON, KLEV, 2)
REAL (KIND=JPRB), INTENT (OUT)::PDMFUP (KLON, KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PDMFEN (KLON, KLEV)
INTEGER (KIND=JPIM), INTENT (INOUT)::KCBOT (KLON)
INTEGER (KIND=JPIM), INTENT (OUT)::KCTOP (KLON)
INTEGER (KIND=JPIM), INTENT (INOUT)::KCTOP0 (KLON)
INTEGER (KIND=JPIM), INTENT (IN)::KDPL (KLON)
REAL (KIND=JPRB), INTENT (OUT)::PMFUDE_RATE (KLON, KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PKINEU (KLON, KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PWU (KLON, KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PWMEAN (KLON)
TYPE(STACK) :: YDSTACK
TYPE(STACK) :: YLSTACK

REAL (KIND=JPRB)::ZLUOLD 
temp (REAL (KIND=JPRB), ZBUO, (KLON, KLEV))
REAL (KIND=JPRB)::ZPRECIP 
REAL (KIND=JPRB)::ZQOLD 
REAL (KIND=JPRB)::ZDMFDE 
REAL (KIND=JPRB)::ZDMFEN 
REAL (KIND=JPRB)::ZDPMEAN 

REAL (KIND=JPRB)::ZPH 
REAL (KIND=JPRB)::ZOENTR 

LOGICAL::LLO3
LOGICAL::LLO1 
LOGICAL::LLFLAGUV 
LOGICAL::LLFLAG 

INTEGER (KIND=JPIM)::IKB
INTEGER (KIND=JPIM)::JLON
INTEGER (KIND=JPIM)::JLEV
INTEGER (KIND=JPIM)::IS
INTEGER (KIND=JPIM)::IK

INTEGER (KIND=JPIM)::JLX 
INTEGER (KIND=JPIM)::JLM
INTEGER (KIND=JPIM)::JLL

REAL (KIND=JPRB)::ZGLAC
REAL (KIND=JPRB)::ZOCUDET
REAL (KIND=JPRB)::ZZCO
REAL (KIND=JPRB)::ZVW
REAL (KIND=JPRB)::ZVV
REAL (KIND=JPRB)::ZVI
REAL (KIND=JPRB)::ZSEEN
REAL (KIND=JPRB)::ZSCDE
REAL (KIND=JPRB)::ZROLD
REAL (KIND=JPRB)::ZRNEW
REAL (KIND=JPRB)::ZQUDE
REAL (KIND=JPRB)::ZQEEN
REAL (KIND=JPRB)::ZPRCON
REAL (KIND=JPRB)::ZPRCDGW
REAL (KIND=JPRB)::ZOEALFAP
REAL (KIND=JPRB)::ZOEALFA
REAL (KIND=JPRB)::ZMFUSK
REAL (KIND=JPRB)::ZMFUQK
REAL (KIND=JPRB)::ZMFUN
REAL (KIND=JPRB)::ZMFULK
REAL (KIND=JPRB)::ZMFTEST
REAL (KIND=JPRB)::ZMFMAX
REAL (KIND=JPRB)::ZLNEW
REAL (KIND=JPRB)::ZLEEN
REAL (KIND=JPRB)::ZLCRIT
REAL (KIND=JPRB)::ZKEDKE
REAL (KIND=JPRB)::ZINT
REAL (KIND=JPRB)::ZFACBUO
REAL (KIND=JPRB)::ZFAC
REAL (KIND=JPRB)::ZDT
REAL (KIND=JPRB)::ZORCPD
REAL (KIND=JPRB)::ZRG
REAL (KIND=JPRB)::ZDNOPRC
REAL (KIND=JPRB)::ZDKEN
REAL (KIND=JPRB)::ZDKBUO
REAL (KIND=JPRB)::ZDFI
REAL (KIND=JPRB)::ZD
REAL (KIND=JPRB)::ZCONS2
REAL (KIND=JPRB)::ZCBF
REAL (KIND=JPRB)::ZC
REAL (KIND=JPRB)::ZBUOC
REAL (KIND=JPRB)::ZBE
REAL (KIND=JPRB)::ZBC
REAL (KIND=JPRB)::ZALFAW
REAL (KIND=JPRB)::Z_CWIFRAC
REAL (KIND=JPRB)::Z_CWDRAG
REAL (KIND=JPRB)::Z_CPRC2
REAL (KIND=JPRB)::Z_CLDMAX

REAL (KIND=JPRB)::ZXPRCDGW
REAL (KIND=JPRB)::ZXENTSHALP
REAL (KIND=JPRB)::ZXENTRORG

LOGICAL::LLPERT_RPRCON
LOGICAL::LLPERT_ENTSHALP
LOGICAL::LLPERT_ENTRORG

INTEGER (KIND=JPIM)::IPRPRCON
INTEGER (KIND=JPIM)::IPENTSHALP
INTEGER (KIND=JPIM)::IPENTRORG
INTEGER (KIND=JPIM)::IPN

TYPE (SPP_PERT)::PN1RPRCON
TYPE (SPP_PERT)::PN1ENTSHALP
TYPE (SPP_PERT)::PN1ENTRORG

REAL (KIND=JPRB)::ZXE
REAL (KIND=JPRB)::ZXS
REAL (KIND=JPRB)::ZCHANGE

LOGICAL::LLKLAB 
#include "cuadjtq.func.h"

REAL (KIND=JPRB)::ZQP
REAL (KIND=JPRB)::ZTARG
REAL (KIND=JPRB)::ZQSAT
REAL (KIND=JPRB)::ZQMAX
REAL (KIND=JPRB)::ZOEALFA_CUADJTQ000
REAL (KIND=JPRB)::ZFOEEWL
REAL (KIND=JPRB)::ZFOEEWI
REAL (KIND=JPRB)::ZCOR
REAL (KIND=JPRB)::ZCOND1
REAL (KIND=JPRB)::ZCOND
REAL (KIND=JPRB)::Z2S
REAL (KIND=JPRB)::Z1S
REAL (KIND=JPRB)::ZF
REAL (KIND=JPRB)::ZI
REAL (KIND=JPRB)::ZL
LOGICAL::LLFLAG_CUADJTQ000 
REAL (KIND=JPRB)::ZOEALFA_CUADJTQ001
LOGICAL::LLFLAG_CUADJTQ001 
REAL (KIND=JPRB)::ZORCPD_CUBASMCN
REAL (KIND=JPRB)::ZRG_CUBASMCN
REAL (KIND=JPRB)::ZZZMB
LOGICAL::LLO1_CUENTR
LOGICAL::LLPERT_DETRPEN
INTEGER (KIND=JPIM)::IPDETRPEN
INTEGER (KIND=JPIM)::IPN_CUENTR
TYPE (SPP_PERT)::PN1
REAL (KIND=JPRB)::ZXDETRPEN
REAL (KIND=JPRB)::ZRG_CUENTR
REAL (KIND=JPRB)::ZMF
REAL (KIND=JPRB)::ZENTR 
REAL (KIND=JPRB)::ZDZ
#include "fcttre.func.h"

YLSTACK = YDSTACK


IF (KIND (ZBUO) == 8) THEN
    alloc8 (ZBUO)
ELSEIF (KIND (ZBUO) == 4) THEN
    alloc4 (ZBUO)
ELSE
    STOP 1
ENDIF




JLON = KIDIA


ZCONS2=YDECUMF%RMFCFL/(YDCST%RG*PTSPHY)
ZRG=1.0_JPRB/YDCST%RG
ZORCPD=1.0_JPRB/YDCST%RCPD
ZFACBUO=0.5_JPRB/1.5
ZPRCDGW=YDECUMF%RPRCON/YDCST%RG
ZDNOPRC=3.E-4_JPRB
Z_CLDMAX=5.E-3_JPRB
Z_CWIFRAC=0.5_JPRB
Z_CPRC2=0.5_JPRB
Z_CWDRAG=(3._JPRB/8._JPRB)*0.506_JPRB/0.2_JPRB

IF (YDECUMF%LMFGLAC) THEN
  ZGLAC=1.0_JPRB
ELSE
  ZGLAC=0.0_JPRB
ENDIF

LLO3=.FALSE.

ZLUOLD =0.0_JPRB

IF (.NOT.LDCUM (JLON)) THEN
  KCBOT (JLON)=-1
  PMFUB (JLON)=0.0_JPRB
  PQU (JLON, KLEV)=0.0_JPRB
  KTYPE (JLON)=0
ENDIF

PWMEAN (JLON)=0.0_JPRB
ZDPMEAN =0.0_JPRB
ZOENTR =0.0_JPRB
LSCVFLAG (JLON)=.FALSE.

IF (KTYPE (JLON)>1.AND.YDECUMF%LSCVLIQ)  THEN
    LSCVFLAG (JLON)=.TRUE.
ENDIF



LLPERT_ENTRORG=.FALSE.
LLPERT_ENTSHALP=.FALSE.
LLPERT_RPRCON=.FALSE.


LLKLAB =.FALSE.

IF (.NOT.LDCUM (JLON).OR.KTYPE (JLON)==3)  THEN
    LLKLAB =.TRUE.
ENDIF



DO JLEV=1, KLEV

  

  IF (JLEV/=KCBOT (JLON)) THEN
    PLU (JLON, JLEV)=0.0_JPRB
  ENDIF

  PKINEU (JLON, JLEV)=0.0_JPRB
  
  
  PMFU (JLON, JLEV)=0.0_JPRB
  PMFUS (JLON, JLEV)=0.0_JPRB
  PMFUQ (JLON, JLEV)=0.0_JPRB
  PMFUL (JLON, JLEV)=0.0_JPRB
  PWU (JLON, JLEV)=0.0_JPRB
  
  
  PLUDE (JLON, JLEV)=0.0_JPRB
  PLUDELI (JLON, JLEV, 1)=0.0_JPRB
  PLUDELI (JLON, JLEV, 2)=0.0_JPRB
  PLGLAC (JLON, JLEV)=0.0_JPRB
  PDMFUP (JLON, JLEV)=0.0_JPRB
  PLRAIN (JLON, JLEV)=0.0_JPRB
  
  
  ZBUO (JLON, JLEV)=0.0_JPRB

  IF (LLKLAB )  THEN
      KLAB (JLON, JLEV)=0
  ENDIF


  IF (.NOT.LDCUM (JLON).AND.PAPH (JLON, JLEV)<4.E4_JPRB)  THEN
      KCTOP0 (JLON)=JLEV
  ENDIF

  PDMFEN (JLON, JLEV)=0.0_JPRB
  PMFUDE_RATE (JLON, JLEV)=0.0_JPRB
  
ENDDO



IF (KTYPE (JLON)==3)  THEN
    LDCUM (JLON)=.FALSE.
ENDIF



KCTOP (JLON)=KCBOT (JLON)

IF (LDCUM (JLON)) THEN
  IKB=KCBOT (JLON)
  PKINEU (JLON, IKB)=0.5*PWUBASE (JLON)**2
  PMFU (JLON, IKB)=PMFUB (JLON)
  PMFUS (JLON, IKB)=PMFUB (JLON)*(YDCST%RCPD*PTU (JLON, IKB)+PGEOH (JLON, IKB))
  PMFUQ (JLON, IKB)=PMFUB (JLON)*PQU (JLON, IKB)
  PMFUL (JLON, IKB)=PMFUB (JLON)*PLU (JLON, IKB)
ENDIF



DO JLEV=KLEV-1, 3,-1
  IK=JLEV
  
  
  
  
  
  
  
  ZRG_CUBASMCN=1.0_JPRB/YDCST%RG
  ZORCPD_CUBASMCN=1.0_JPRB/YDCST%RCPD

  

  IF (.NOT.LDCUM (JLON).AND.KLAB (JLON, IK+1)==0) THEN

    IF (YDECUMF%LMFMID.AND.IK>YDECUMF%NJKT7.AND.PQEN (JLON, IK)>0.80_JPRB*PQSEN (JLON, IK)) THEN
      PTU (JLON, IK+1)=(YDCST%RCPD*PTEN (JLON, IK)+PGEO (JLON, IK)-PGEOH (JLON, IK+1))*ZORCPD_CUBASMCN
      PQU (JLON, IK+1)=PQEN (JLON, IK)
      PLU (JLON, IK+1)=0.0_JPRB
      ZZZMB=MAX (1.E-6_JPRB,-PVERVEL (JLON, IK)*ZRG_CUBASMCN)
      ZZZMB=MIN (ZZZMB, YDECUMF%RMFLIA)
      PMFUB (JLON)=ZZZMB
      PMFU (JLON, IK+1)=PMFUB (JLON)
      PMFUS (JLON, IK+1)=PMFUB (JLON)*(YDCST%RCPD*PTU (JLON, IK+1)+PGEOH (JLON, IK+1))
      PMFUQ (JLON, IK+1)=PMFUB (JLON)*PQU (JLON, IK+1)
      PMFUL (JLON, IK+1)=0.0_JPRB
      PDMFUP (JLON, IK+1)=0.0_JPRB
      PLRAIN (JLON, IK+1)=0.0_JPRB
      KCBOT (JLON)=IK
      KLAB (JLON, IK+1)=1
      KTYPE (JLON)=3
    ENDIF

  ENDIF

  
  
  
  
  
  IS=0
  JLM=0
  
  LLFLAG =.FALSE.
  ZPRECIP =0.0_JPRB
  LLO1 =.FALSE.
  IS=IS+KLAB (JLON, JLEV+1)

  IF (KLAB (JLON, JLEV+1)==0)  THEN
      KLAB (JLON, JLEV)=0
  ENDIF


  IF ((LDCUM (JLON).AND.KLAB (JLON, JLEV+1)==2).OR.(KTYPE (JLON)==3.AND.KLAB (JLON, JLEV+1)==1)) THEN
    LLFLAG =.TRUE.
    JLM=JLM+1
    JLX =JLON
  ENDIF


  IF (KLAB (JLON, JLEV+1)>0) THEN
    LLFLAGUV =.TRUE.
  ELSE
    LLFLAGUV =.FALSE.
  ENDIF

  ZPH =PAPH (JLON, JLEV)

  IF (KTYPE (JLON)==3.AND.JLEV==KCBOT (JLON)) THEN
    ZMFMAX=(PAPH (JLON, JLEV)-PAPH (JLON, JLEV-1))*ZCONS2

    IF (PMFUB (JLON)>ZMFMAX) THEN
      ZFAC=ZMFMAX/PMFUB (JLON)
      PMFU (JLON, JLEV+1)=PMFU (JLON, JLEV+1)*ZFAC
      PMFUS (JLON, JLEV+1)=PMFUS (JLON, JLEV+1)*ZFAC
      PMFUQ (JLON, JLEV+1)=PMFUQ (JLON, JLEV+1)*ZFAC
      PMFUB (JLON)=ZMFMAX
    ENDIF

  ENDIF


  

  IF (IS>0)  THEN
      LLO3=.TRUE.
  ENDIF

  IK=JLEV

  

  

  

  

  

  

  

  IF (LLO3) THEN
    ZRG_CUENTR=1.0_JPRB/YDCST%RG
    
    LLPERT_DETRPEN=.FALSE.
    
    
    ZDMFEN =0.0_JPRB
    ZDMFDE =0.0_JPRB
    ZENTR =0.0

    

    

    IF (LDCUM (JLON)) THEN
      ZDZ=(PGEOH (JLON, IK)-PGEOH (JLON, IK+1))*ZRG_CUENTR
      ZMF=PMFU (JLON, IK+1)*ZDZ
      LLO1_CUENTR=IK<KCBOT (JLON)

      IF (LLO1_CUENTR) THEN
        
        ZXDETRPEN=YDECUMF%DETRPEN
        
        ZDMFEN =ZENTR *ZMF
        ZDMFDE =ZXDETRPEN*ZMF
      ENDIF

    ENDIF

  
  ENDIF


  

  

  

  

  IF (LLO3) THEN
    
    ZQOLD =0.0_JPRB

    

    DO JLL=1, JLM
      JLON=JLX 
      ZDMFDE =MIN (ZDMFDE , 0.75_JPRB*PMFU (JLON, JLEV+1))

      IF (JLEV==KCBOT (JLON)) THEN
        
        ZXENTRORG=YDECUMF%ENTRORG
        
        ZOENTR =-ZXENTRORG*(MIN (1.0_JPRB, PQEN (JLON, JLEV)/PQSEN (JLON, JLEV&
        &))-YDECUMF%ENTR_RH)*(PGEOH (JLON, JLEV)-PGEOH (JLON, JLEV+1))*ZRG
        ZOENTR =MIN (0.4_JPRB, ZOENTR )*PMFU (JLON, JLEV+1)
      ENDIF


      IF (JLEV<KCBOT (JLON)) THEN
        ZMFMAX=(PAPH (JLON, JLEV)-PAPH (JLON, JLEV-1))*ZCONS2
        ZXS=MAX (PMFU (JLON, JLEV+1)-ZMFMAX, 0.0_JPRB)
        PWMEAN (JLON)=PWMEAN (JLON)+PKINEU (JLON, JLEV+1)*(PAP (JLON, JLEV+1)-PAP (JLON, JLEV))
        ZDPMEAN =ZDPMEAN +PAP (JLON, JLEV+1)-PAP (JLON, JLEV)
        ZDMFEN =ZOENTR 

        IF (KTYPE (JLON)>=2) THEN
          
          ZXENTSHALP=YDECUMF%ENTSHALP
          
          ZDMFEN =ZXENTSHALP*ZDMFEN 
          ZDMFDE =ZDMFEN 
        ENDIF

        ZDMFDE =ZDMFDE *(1.6_JPRB-MIN (1.0_JPRB, PQEN (JLON, JLEV)/PQSEN (JLON, JLEV)))
        ZMFTEST=PMFU (JLON, JLEV+1)+ZDMFEN -ZDMFDE 
        ZCHANGE=MAX (ZMFTEST-ZMFMAX, 0.0_JPRB)
        ZXE=MAX (ZCHANGE-ZXS, 0.0_JPRB)
        ZDMFEN =ZDMFEN -ZXE
        ZCHANGE=ZCHANGE-ZXE
        ZDMFDE =ZDMFDE +ZCHANGE
      ENDIF

      PDMFEN (JLON, JLEV)=ZDMFEN -ZDMFDE 
      PMFU (JLON, JLEV)=PMFU (JLON, JLEV+1)+ZDMFEN -ZDMFDE 
      ZQEEN=PQENH (JLON, JLEV+1)*ZDMFEN 
      ZSEEN=(YDCST%RCPD*PTENH (JLON, JLEV+1)+PGEOH (JLON, JLEV+1))*ZDMFEN 

      IF (PLITOT (JLON, JLEV)>YDECLDP%RLMIN) THEN
        ZLEEN=PLITOT (JLON, JLEV)*ZDMFEN 
      ELSE
        ZLEEN=0.0_JPRB
      ENDIF

      ZSCDE=(YDCST%RCPD*PTU (JLON, JLEV+1)+PGEOH (JLON, JLEV+1))*ZDMFDE 
      ZQUDE=PQU (JLON, JLEV+1)*ZDMFDE 
      PLUDE (JLON, JLEV)=PLU (JLON, JLEV+1)*ZDMFDE 
      ZMFUSK=PMFUS (JLON, JLEV+1)+ZSEEN-ZSCDE
      ZMFUQK=PMFUQ (JLON, JLEV+1)+ZQEEN-ZQUDE
      ZMFULK=PMFUL (JLON, JLEV+1)+ZLEEN-PLUDE (JLON, JLEV)
      ZFAC=1.0_JPRB/MAX (YDECUMF%RMFCMIN, PMFU (JLON, JLEV))
      PLU (JLON, JLEV)=ZMFULK*ZFAC
      PQU (JLON, JLEV)=ZMFUQK*ZFAC
      PTU (JLON, JLEV)=(ZMFUSK*ZFAC-PGEOH (JLON, JLEV))*ZORCPD
      PTU (JLON, JLEV)=MAX (100._JPRB, PTU (JLON, JLEV))
      PTU (JLON, JLEV)=MIN (400._JPRB, PTU (JLON, JLEV))
      ZQOLD =PQU (JLON, JLEV)
      PLRAIN (JLON, JLEV)=PLRAIN (JLON, JLEV+1)*MAX (0.0_JPRB, PMFU (JLON, JLEV+1)-ZDMFDE )*ZFAC
      ZLUOLD =PLU (JLON, JLEV)
    ENDDO


    

    IF (JLEV>KDPL (JLON)) THEN
      PTU (JLON, JLEV)=PTENH (JLON, JLEV)
      PQU (JLON, JLEV)=PQENH (JLON, JLEV)
      PLU (JLON, JLEV)=0.0_JPRB
      ZLUOLD =PLU (JLON, JLEV)
    ENDIF

    
    IK=JLEV

    IF (JLM>0) THEN

      IF (YDECUMF%LSCVLIQ) THEN
        
        
        
        
        
        
        
        ZQMAX=0.5_JPRB

        IF (.NOT.YDEPHLI%LPHYLIN) THEN
          
          LLFLAG_CUADJTQ000 =LLFLAG 
          
          
          LLFLAG_CUADJTQ000 =LLFLAG_CUADJTQ000 .AND..NOT.LSCVFLAG (JLON)

          

          

          

          IF (LLFLAG_CUADJTQ000 ) THEN
            ZQP=1.0_JPRB/ZPH 
            ZL=1.0_JPRB/(PTU (JLON, IK)-YDTHF%R4LES)
            ZI=1.0_JPRB/(PTU (JLON, IK)-YDTHF%R4IES)
            ZQSAT=YDTHF%R2ES*(FOEALFCU (PTU (JLON, IK))*EXP (YDTHF%R3LES*(PTU (JLON, IK)-YDCST%RTT)*ZL&
            &)+(1.0_JPRB-FOEALFCU (PTU (JLON, IK)))*EXP (YDTHF%R3IES*(PTU (JLON, IK)-YDCST%RTT)*ZI))
            ZQSAT=ZQSAT*ZQP
            ZQSAT=MIN (0.5_JPRB, ZQSAT)
            ZCOR=1.0_JPRB-YDCST%RETV*ZQSAT
            ZF=FOEALFCU (PTU (JLON, IK))*YDTHF%R5ALVCP*ZL**2+(1.0_JPRB&
            &-FOEALFCU (PTU (JLON, IK)))*YDTHF%R5ALSCP*ZI**2
            ZCOND=(PQU (JLON, IK)*ZCOR**2-ZQSAT*ZCOR)/(ZCOR**2+ZQSAT*ZF)
            ZCOND=MAX (ZCOND, 0.0_JPRB)
            PTU (JLON, IK)=PTU (JLON, IK)+FOELDCPMCU (PTU (JLON, IK))*ZCOND
            PQU (JLON, IK)=PQU (JLON, IK)-ZCOND
            ZL=1.0_JPRB/(PTU (JLON, IK)-YDTHF%R4LES)
            ZI=1.0_JPRB/(PTU (JLON, IK)-YDTHF%R4IES)
            ZQSAT=YDTHF%R2ES*(FOEALFCU (PTU (JLON, IK))*EXP (YDTHF%R3LES*(PTU (JLON, IK)-YDCST%RTT)*ZL&
            &)+(1.0_JPRB-FOEALFCU (PTU (JLON, IK)))*EXP (YDTHF%R3IES*(PTU (JLON, IK)-YDCST%RTT)*ZI))
            ZQSAT=ZQSAT*ZQP
            ZQSAT=FMINJ (0.5_JPRB, ZQSAT)
            ZCOR=1.0_JPRB-YDCST%RETV*ZQSAT
            ZF=FOEALFCU (PTU (JLON, IK))*YDTHF%R5ALVCP*ZL**2+(1.0_JPRB&
            &-FOEALFCU (PTU (JLON, IK)))*YDTHF%R5ALSCP*ZI**2
            ZCOND1=(PQU (JLON, IK)*ZCOR**2-ZQSAT*ZCOR)/(ZCOR**2+ZQSAT*ZF)

            IF (ZCOND==0.0_JPRB)  THEN
                ZCOND1=0.0_JPRB
            ENDIF

            PTU (JLON, IK)=PTU (JLON, IK)+FOELDCPMCU (PTU (JLON, IK))*ZCOND1
            PQU (JLON, IK)=PQU (JLON, IK)-ZCOND1
          ENDIF


          

          

          

          IF (LLFLAG .AND.LSCVFLAG (JLON)) THEN
            ZQP=1.0_JPRB/ZPH 
            ZL=1.0_JPRB/(PTU (JLON, IK)-YDTHF%R4LES)
            ZQSAT=YDTHF%R2ES*EXP (YDTHF%R3LES*(PTU (JLON, IK)-YDCST%RTT)*ZL)
            ZQSAT=ZQSAT*ZQP
            ZQSAT=MIN (0.5_JPRB, ZQSAT)
            ZCOR=1.0_JPRB-YDCST%RETV*ZQSAT
            ZF=YDTHF%R5ALVCP*ZL**2
            ZCOND=(PQU (JLON, IK)*ZCOR**2-ZQSAT*ZCOR)/(ZCOR**2+ZQSAT*ZF)
            ZCOND=MAX (ZCOND, 0.0_JPRB)
            PTU (JLON, IK)=PTU (JLON, IK)+YDTHF%RALVDCP*ZCOND
            PQU (JLON, IK)=PQU (JLON, IK)-ZCOND
            ZL=1.0_JPRB/(PTU (JLON, IK)-YDTHF%R4LES)
            ZQSAT=YDTHF%R2ES*EXP (YDTHF%R3LES*(PTU (JLON, IK)-YDCST%RTT)*ZL)
            ZQSAT=ZQSAT*ZQP
            ZQSAT=FMINJ (0.5_JPRB, ZQSAT)
            ZCOR=1.0_JPRB-YDCST%RETV*ZQSAT
            ZF=YDTHF%R5ALVCP*ZL**2
            ZCOND1=(PQU (JLON, IK)*ZCOR**2-ZQSAT*ZCOR)/(ZCOR**2+ZQSAT*ZF)

            IF (ZCOND==0.0_JPRB)  THEN
                ZCOND1=0.0_JPRB
            ENDIF

            PTU (JLON, IK)=PTU (JLON, IK)+YDTHF%RALVDCP*ZCOND1
            PQU (JLON, IK)=PQU (JLON, IK)-ZCOND1
          ENDIF

        
        
        
        
        
        
        
        
        ELSE
        
        
        
        
        ENDIF

      
      
      
      ELSE
        
        
        
        
        
        
        
        ZQMAX=0.5_JPRB

        IF (.NOT.YDEPHLI%LPHYLIN) THEN
          
          LLFLAG_CUADJTQ001 =LLFLAG 

          

          

          IF (LLFLAG_CUADJTQ001 ) THEN
            ZQP=1.0_JPRB/ZPH 
            ZL=1.0_JPRB/(PTU (JLON, IK)-YDTHF%R4LES)
            ZI=1.0_JPRB/(PTU (JLON, IK)-YDTHF%R4IES)
            ZQSAT=YDTHF%R2ES*(FOEALFCU (PTU (JLON, IK))*EXP (YDTHF%R3LES*(PTU (JLON, IK)-YDCST%RTT)*ZL&
            &)+(1.0_JPRB-FOEALFCU (PTU (JLON, IK)))*EXP (YDTHF%R3IES*(PTU (JLON, IK)-YDCST%RTT)*ZI))
            ZQSAT=ZQSAT*ZQP
            ZQSAT=MIN (0.5_JPRB, ZQSAT)
            ZCOR=1.0_JPRB-YDCST%RETV*ZQSAT
            ZF=FOEALFCU (PTU (JLON, IK))*YDTHF%R5ALVCP*ZL**2+(1.0_JPRB&
            &-FOEALFCU (PTU (JLON, IK)))*YDTHF%R5ALSCP*ZI**2
            ZCOND=(PQU (JLON, IK)*ZCOR**2-ZQSAT*ZCOR)/(ZCOR**2+ZQSAT*ZF)
            ZCOND=MAX (ZCOND, 0.0_JPRB)
            PTU (JLON, IK)=PTU (JLON, IK)+FOELDCPMCU (PTU (JLON, IK))*ZCOND
            PQU (JLON, IK)=PQU (JLON, IK)-ZCOND
            ZL=1.0_JPRB/(PTU (JLON, IK)-YDTHF%R4LES)
            ZI=1.0_JPRB/(PTU (JLON, IK)-YDTHF%R4IES)
            ZQSAT=YDTHF%R2ES*(FOEALFCU (PTU (JLON, IK))*EXP (YDTHF%R3LES*(PTU (JLON, IK)-YDCST%RTT)*ZL&
            &)+(1.0_JPRB-FOEALFCU (PTU (JLON, IK)))*EXP (YDTHF%R3IES*(PTU (JLON, IK)-YDCST%RTT)*ZI))
            ZQSAT=ZQSAT*ZQP
            ZQSAT=FMINJ (0.5_JPRB, ZQSAT)
            ZCOR=1.0_JPRB-YDCST%RETV*ZQSAT
            ZF=FOEALFCU (PTU (JLON, IK))*YDTHF%R5ALVCP*ZL**2+(1.0_JPRB&
            &-FOEALFCU (PTU (JLON, IK)))*YDTHF%R5ALSCP*ZI**2
            ZCOND1=(PQU (JLON, IK)*ZCOR**2-ZQSAT*ZCOR)/(ZCOR**2+ZQSAT*ZF)

            IF (ZCOND==0.0_JPRB)  THEN
                ZCOND1=0.0_JPRB
            ENDIF

            PTU (JLON, IK)=PTU (JLON, IK)+FOELDCPMCU (PTU (JLON, IK))*ZCOND1
            PQU (JLON, IK)=PQU (JLON, IK)-ZCOND1
          ENDIF

        
        
        
        
        
        
        
        
        ELSE

          

          

          IF (LLFLAG ) THEN
            ZQP=1.0_JPRB/ZPH 
            ZTARG=PTU (JLON, IK)
            ZOEALFA_CUADJTQ001=0.5_JPRB*(TANH (YDEPHLI%RLPAL1*(ZTARG-YDEPHLI%RLPTRC))+1.0_JPRB)
            ZFOEEWL=YDTHF%R2ES*EXP (YDTHF%R3LES*(ZTARG-YDCST%RTT)/(ZTARG-YDTHF%R4LES))
            ZFOEEWI=YDTHF%R2ES*EXP (YDTHF%R3IES*(ZTARG-YDCST%RTT)/(ZTARG-YDTHF%R4IES))
            ZQSAT=ZQP*(ZOEALFA_CUADJTQ001*ZFOEEWL+(1.0_JPRB-ZOEALFA_CUADJTQ001)*ZFOEEWI)
            Z1S=TANH (YDEPHLI%RLPAL2*(ZQSAT-ZQMAX))
            ZQSAT=0.5_JPRB*((1.0_JPRB-Z1S)*ZQSAT+(1.0_JPRB+Z1S)*ZQMAX)
            ZCOR=1.0_JPRB/(1.0_JPRB-YDCST%RETV*ZQSAT)
            ZQSAT=ZQSAT*ZCOR
            Z2S=ZOEALFA_CUADJTQ001*YDTHF%R5ALVCP*(1.0_JPRB/(ZTARG-YDTHF%R4LES)**2)+(1.0_JPRB&
            &-ZOEALFA_CUADJTQ001)*YDTHF%R5ALSCP*(1.0_JPRB/(ZTARG-YDTHF%R4IES)**2)
            ZCOND=(PQU (JLON, IK)-ZQSAT)/(1.0_JPRB+ZQSAT*ZCOR*Z2S)
            ZCOND=MAX (ZCOND, 0.0_JPRB)

            IF (ZCOND/=0.0_JPRB) THEN
              PTU (JLON, IK)=PTU (JLON, IK)+(ZOEALFA_CUADJTQ001*YDTHF%RALVDCP&
              &+(1.0_JPRB-ZOEALFA_CUADJTQ001)*YDTHF%RALSDCP)*ZCOND
              PQU (JLON, IK)=PQU (JLON, IK)-ZCOND
              ZTARG=PTU (JLON, IK)
              ZOEALFA_CUADJTQ001=0.5_JPRB*(TANH (YDEPHLI%RLPAL1*(ZTARG-YDEPHLI%RLPTRC))+1.0_JPRB)
              ZFOEEWL=YDTHF%R2ES*EXP (YDTHF%R3LES*(ZTARG-YDCST%RTT)/(ZTARG-YDTHF%R4LES))
              ZFOEEWI=YDTHF%R2ES*EXP (YDTHF%R3IES*(ZTARG-YDCST%RTT)/(ZTARG-YDTHF%R4IES))
              ZQSAT=ZQP*(ZOEALFA_CUADJTQ001*ZFOEEWL+(1.0_JPRB-ZOEALFA_CUADJTQ001)*ZFOEEWI)
              Z1S=TANH (YDEPHLI%RLPAL2*(ZQSAT-ZQMAX))
              ZQSAT=0.5_JPRB*((1.0_JPRB-Z1S)*ZQSAT+(1.0_JPRB+Z1S)*ZQMAX)
              ZCOR=1.0_JPRB/(1.0_JPRB-YDCST%RETV*ZQSAT)
              ZQSAT=ZQSAT*ZCOR
              Z2S=ZOEALFA_CUADJTQ001*YDTHF%R5ALVCP*(1.0_JPRB/(ZTARG-YDTHF%R4LES)**2)+(1.0_JPRB&
              &-ZOEALFA_CUADJTQ001)*YDTHF%R5ALSCP*(1.0_JPRB/(ZTARG-YDTHF%R4IES)**2)
              ZCOND1=(PQU (JLON, IK)-ZQSAT)/(1.0_JPRB+ZQSAT*ZCOR*Z2S)
              PTU (JLON, IK)=PTU (JLON, IK)+(ZOEALFA_CUADJTQ001*YDTHF%RALVDCP&
              &+(1.0_JPRB-ZOEALFA_CUADJTQ001)*YDTHF%RALSDCP)*ZCOND1
              PQU (JLON, IK)=PQU (JLON, IK)-ZCOND1
            ENDIF

          ENDIF

        
        
        
        
        
        ENDIF

      
      
      
      ENDIF

    ENDIF


    IF (YDEPHLI%LPHYLIN) THEN

      DO JLL=1, JLM
        JLON=JLX 

        IF (PQU (JLON, JLEV)/=ZQOLD ) THEN
          ZOEALFA=MIN (1.0_JPRB, 0.545_JPRB*(TANH (0.17_JPRB*(PTU (JLON, JLEV)-YDEPHLI%RLPTRC))+1.0_JPRB))
          ZOEALFAP=MIN (1.0_JPRB, 0.545_JPRB*(TANH (0.17_JPRB*(PTU (JLON, JLEV+1)-YDEPHLI%RLPTRC))+1.0_JPRB))
          PLGLAC (JLON, JLEV)=PLU (JLON, JLEV)*((1.0_JPRB-ZOEALFA)-(1.0_JPRB-ZOEALFAP))
          ZFAC=0.545_JPRB*(TANH (0.17_JPRB*(PTEN (JLON, JLEV)-YDEPHLI%RLPTRC))+1.0_JPRB)
          PLGLAC (JLON, JLEV)=PLGLAC (JLON, JLEV)+ZFAC*PDMFUP (JLON, JLEV+1)/MAX (YDECUMF%RMFCMIN&
          &, PMFU (JLON, JLEV+1))*(0.5_JPRB+SIGN (0.5_JPRB, YDCST%RTT-PTEN (JLON, JLEV)))*ZGLAC
          PTU (JLON, JLEV)=PTU (JLON, JLEV)+YDTHF%RALFDCP*PLGLAC (JLON, JLEV)
        ENDIF

      ENDDO

    ELSE

      DO JLL=1, JLM
        JLON=JLX 

        IF (PQU (JLON, JLEV)/=ZQOLD ) THEN
          PLGLAC (JLON, JLEV)=PLU (JLON, JLEV)*((1.0_JPRB-FOEALFCU (PTU&
          & (JLON, JLEV)))-(1.0_JPRB-FOEALFCU (PTU (JLON, JLEV+1))))

          IF (LSCVFLAG (JLON))  THEN
              PLGLAC (JLON, JLEV)=0.0_JPRB
          ENDIF

          ZFAC=FOEALFCU (PTEN (JLON, JLEV))
          PLGLAC (JLON, JLEV)=PLGLAC (JLON, JLEV)+ZFAC*PDMFUP (JLON, JLEV+1)/MAX (YDECUMF%RMFCMIN&
          &, PMFU (JLON, JLEV+1))*(0.5_JPRB+SIGN (0.5_JPRB, YDCST%RTT-PTEN (JLON, JLEV)))*ZGLAC
          PTU (JLON, JLEV)=PTU (JLON, JLEV)+YDTHF%RALFDCP*PLGLAC (JLON, JLEV)
        ENDIF

      ENDDO

    ENDIF


    DO JLL=1, JLM
      JLON=JLX 

      IF (PQU (JLON, JLEV)/=ZQOLD ) THEN
        KLAB (JLON, JLEV)=2
        PLU (JLON, JLEV)=PLU (JLON, JLEV)+ZQOLD -PQU (JLON, JLEV)
        ZBC=PTU (JLON, JLEV)*(1.0_JPRB+YDCST%RETV*PQU (JLON, JLEV)-PLU (JLON, JLEV+1)-PLRAIN (JLON, JLEV+1))
        ZBE=PTENH (JLON, JLEV)*(1.0_JPRB+YDCST%RETV*PQENH (JLON, JLEV))
        ZBUO (JLON, JLEV)=ZBC-ZBE

        IF (KTYPE (JLON)==3.AND.KLAB (JLON, JLEV+1)==1) THEN

          IF (ZBUO (JLON, JLEV)>-0.5_JPRB) THEN
            LDCUM (JLON)=.TRUE.
            KCTOP (JLON)=JLEV
            PKINEU (JLON, JLEV)=0.5_JPRB
          ELSE
            KLAB (JLON, JLEV)=0
            PMFU (JLON, JLEV)=0.0_JPRB
            PLUDE (JLON, JLEV)=0.0_JPRB
            PLU (JLON, JLEV)=0.0_JPRB
          ENDIF

        ENDIF


        IF (KLAB (JLON, JLEV+1)==2) THEN

          IF (ZBUO (JLON, JLEV)<-0.1_JPRB) THEN
            PTENH (JLON, JLEV)=0.5_JPRB*(PTEN (JLON, JLEV)+PTEN (JLON, JLEV-1))
            PQENH (JLON, JLEV)=0.5_JPRB*(PQEN (JLON, JLEV)+PQEN (JLON, JLEV-1))
            ZBUO (JLON, JLEV)=ZBC-PTENH (JLON, JLEV)*(1.0_JPRB+YDCST%RETV*PQENH (JLON, JLEV))
          ENDIF

          ZBUOC=0.5*(ZBUO (JLON, JLEV)+ZBUO (JLON, JLEV+1))/(PTENH &
          &(JLON, JLEV)*(1.0_JPRB+YDCST%RETV*PQENH (JLON, JLEV)))
          ZDKBUO=(PGEOH (JLON, JLEV)-PGEOH (JLON, JLEV+1))*ZFACBUO*ZBUOC

          IF (ZDMFEN >0.0_JPRB) THEN
            ZDKEN=MIN (1.0_JPRB,(1+Z_CWDRAG)*ZDMFEN /MAX (YDECUMF%RMFCMIN, PMFU (JLON, JLEV+1)))
          ELSE
            ZDKEN=MIN (1.0_JPRB,(1+Z_CWDRAG)*ZDMFDE /MAX (YDECUMF%RMFCMIN, PMFU (JLON, JLEV+1)))
          ENDIF


          IF (LDTDKMF) THEN
            PKINEU (JLON, JLEV)=(PKINEU (JLON, JLEV+1)*(1-ZDKEN)+ZDKBUO)/(1+ZDKEN)
            ZBUOC=ZBUO (JLON, JLEV)
          ELSE
            PKINEU (JLON, JLEV)=MAX (-1.E3_JPRB,(PKINEU (JLON, JLEV+1)*(1-ZDKEN)+ZDKBUO)/(1+ZDKEN))
          ENDIF


          IF (ZBUOC<0.0_JPRB) THEN
            ZKEDKE=PKINEU (JLON, JLEV)/MAX (1.E-3_JPRB, PKINEU (JLON, JLEV+1))
            ZKEDKE=MAX (0.0_JPRB, MIN (1.0_JPRB, ZKEDKE))
            ZOCUDET=(1.6_JPRB-MIN (1.0_JPRB, PQEN (JLON, JLEV)/PQSEN (JLON, JLEV)))
            ZMFUN=ZOCUDET*SQRT (ZKEDKE)
            ZDMFDE =MAX (ZDMFDE , PMFU (JLON, JLEV+1)*(1.0_JPRB-ZMFUN))
            PLUDE (JLON, JLEV)=PLU (JLON, JLEV+1)*ZDMFDE 
            PMFU (JLON, JLEV)=PMFU (JLON, JLEV+1)+ZDMFEN -ZDMFDE 
          ENDIF


          IF (ZBUO (JLON, JLEV)>-0.2_JPRB) THEN
            IKB=KCBOT (JLON)
            
            ZXENTRORG=YDECUMF%ENTRORG
            
            ZOENTR =ZXENTRORG*(0.3_JPRB-(MIN (1.0_JPRB, PQEN (JLON, JLEV-1)/PQSEN &
            &(JLON, JLEV-1))-YDECUMF%ENTR_RH))*(PGEOH (JLON, JLEV-1)-PGEOH (JLON, JLEV&
            &))*ZRG*MIN (1.0_JPRB, PQSEN (JLON, JLEV)/PQSEN (JLON, IKB))**3
            ZOENTR =MIN (0.4_JPRB, ZOENTR )*PMFU (JLON, JLEV)
          ELSE
            ZOENTR =0.0_JPRB
          ENDIF


          IF (JLEV>KDPL (JLON)) THEN
            PMFU (JLON, JLEV)=PMFU (JLON, JLEV+1)
            PKINEU (JLON, JLEV)=0.5_JPRB
          ENDIF


          IF (PKINEU (JLON, JLEV)>0.0_JPRB.AND.PMFU (JLON, JLEV)>0.0_JPRB.AND.(ZBUO&
            & (JLON, JLEV)>-2._JPRB.OR.(PTEN (JLON, JLEV-1)-PTEN (JLON, JLEV))/(ZRG&
            &*(PGEO (JLON, JLEV-1)-PGEO (JLON, JLEV)))<-3.E-3_JPRB)) THEN
            KCTOP (JLON)=JLEV
            LLO1 =.TRUE.
          ELSE
            KLAB (JLON, JLEV)=0
            PMFU (JLON, JLEV)=0.0_JPRB
            PKINEU (JLON, JLEV)=0.0_JPRB
            ZDMFDE =PMFU (JLON, JLEV+1)
            PLUDE (JLON, JLEV)=PLU (JLON, JLEV+1)*ZDMFDE 
          ENDIF


          IF (PMFU (JLON, JLEV+1)>0.0_JPRB) THEN
            PMFUDE_RATE (JLON, JLEV)=ZDMFDE 
          ENDIF

        ENDIF

      ELSEIF (KTYPE (JLON)==2.AND.PQU (JLON, JLEV)==ZQOLD ) THEN
        KLAB (JLON, JLEV)=0
        PMFU (JLON, JLEV)=0.0_JPRB
        PKINEU (JLON, JLEV)=0.0_JPRB
        ZDMFDE =PMFU (JLON, JLEV+1)
        PLUDE (JLON, JLEV)=PLU (JLON, JLEV+1)*ZDMFDE 
        PMFUDE_RATE (JLON, JLEV)=ZDMFDE 
      ENDIF

    ENDDO


    

    IF (LLO1 ) THEN

      IF (PLU (JLON, JLEV)>ZDNOPRC) THEN
        PWU (JLON, JLEV)=MIN (15._JPRB, SQRT (2.0_JPRB*MAX (0.5_JPRB, PKINEU (JLON, JLEV+1))))

        IF (LDTDKMF) THEN
          ZZCO=FOEALFCU (PTU (JLON, JLEV))*1.3_JPRB+(1.0_JPRB-FOEALFCU (PTU (JLON, JLEV)))
        ELSE
          ZZCO=1.0_JPRB+0.3_JPRB*FOEALFCU (PTU (JLON, JLEV))
        ENDIF

        
        ZXPRCDGW=ZPRCDGW
        
        ZPRCON=ZXPRCDGW/(0.75_JPRB*PWU (JLON, JLEV))*ZZCO
        ZDT=MIN (YDTHF%RTBERCU-YDTHF%RTICECU, MAX (YDTHF%RTBERCU-PTU (JLON, JLEV), 0.0_JPRB))
        ZCBF=1+Z_CPRC2*SQRT (ZDT)
        ZZCO=ZPRCON*ZCBF

        IF (YGFL%NACTAERO>0) THEN

          IF (YDECLDP%LAERLIQAUTOCP) THEN
            ZALFAW=FOEALFCU (PTU (JLON, JLEV))
            ZLCRIT=ZALFAW*PLCRIT_AER (JLON, JLEV)+(1.0_JPRB-ZALFAW)*ZDNOPRC
          ELSEIF (YDECLDP%LAERLIQAUTOCPB) THEN
            ZALFAW=FOEALFCU (PTU (JLON, JLEV))
            ZLCRIT=ZALFAW*PLCRIT_AER (JLON, KCBOT (JLON))+(1.0_JPRB-ZALFAW)*ZDNOPRC
          ELSE
            ZLCRIT=ZDNOPRC/ZCBF
          ENDIF

        ELSE
          ZLCRIT=ZDNOPRC/ZCBF
        ENDIF

        ZDFI=PGEOH (JLON, JLEV)-PGEOH (JLON, JLEV+1)
        ZC=(PLU (JLON, JLEV)-ZLUOLD )
        ZD=ZZCO*(1.0_JPRB-EXP (-(PLU (JLON, JLEV)/ZLCRIT)**2))*ZDFI
        ZINT=EXP (-ZD)
        ZLNEW=ZLUOLD *ZINT+ZC/ZD*(1.0_JPRB-ZINT)
        ZLNEW=MAX (0.0_JPRB, MIN (PLU (JLON, JLEV), ZLNEW))
        ZLNEW=MIN (Z_CLDMAX, ZLNEW)
        ZPRECIP =MAX (0.0_JPRB, ZLUOLD +ZC-ZLNEW)
        PDMFUP (JLON, JLEV)=ZPRECIP *PMFU (JLON, JLEV)
        PLRAIN (JLON, JLEV)=PLRAIN (JLON, JLEV)+ZPRECIP 
        PLU (JLON, JLEV)=ZLNEW
      ENDIF

    ENDIF


    

    IF (YDEPHLI%LPHYLIN) THEN

      

      IF (LLO1 ) THEN

        IF (PLRAIN (JLON, JLEV)>0.0_JPRB) THEN
          ZVW=21.18_JPRB*PLRAIN (JLON, JLEV)**0.2_JPRB
          ZVI=Z_CWIFRAC*ZVW
          ZALFAW=MIN (1.0_JPRB, 0.545_JPRB*(TANH (0.17_JPRB*(PTU (JLON, JLEV)-YDEPHLI%RLPTRC))+1.0_JPRB))
          ZVV=ZALFAW*ZVW+(1.0_JPRB-ZALFAW)*ZVI
          ZROLD=PLRAIN (JLON, JLEV)-ZPRECIP 
          ZC=ZPRECIP 
          PWU (JLON, JLEV)=MIN (15._JPRB, SQRT (2.0_JPRB*MAX (0.1_JPRB, PKINEU (JLON, JLEV))))
          ZD=ZVV/PWU (JLON, JLEV)
          ZINT=EXP (-ZD)
          ZRNEW=ZROLD*ZINT+ZC/ZD*(1.0_JPRB-ZINT)
          ZRNEW=MAX (0.0_JPRB, MIN (PLRAIN (JLON, JLEV), ZRNEW))
          PLRAIN (JLON, JLEV)=ZRNEW
        ENDIF

      ENDIF

    
    ELSE

      

      IF (LLO1 ) THEN

        IF (PLRAIN (JLON, JLEV)>0.0_JPRB) THEN
          ZVW=21.18_JPRB*PLRAIN (JLON, JLEV)**0.2_JPRB
          ZVI=Z_CWIFRAC*ZVW
          ZALFAW=FOEALFCU (PTU (JLON, JLEV))

          IF (LSCVFLAG (JLON))  THEN
              ZALFAW=1.0_JPRB
          ENDIF

          ZVV=ZALFAW*ZVW+(1.0_JPRB-ZALFAW)*ZVI
          ZROLD=PLRAIN (JLON, JLEV)-ZPRECIP 
          ZC=ZPRECIP 
          PWU (JLON, JLEV)=MIN (15._JPRB, SQRT (2.0_JPRB*MAX (0.1_JPRB, PKINEU (JLON, JLEV))))
          ZD=ZVV/PWU (JLON, JLEV)
          ZINT=EXP (-ZD)
          ZRNEW=ZROLD*ZINT+ZC/ZD*(1.0_JPRB-ZINT)
          ZRNEW=MAX (0.0_JPRB, MIN (PLRAIN (JLON, JLEV), ZRNEW))
          PLRAIN (JLON, JLEV)=ZRNEW
        ENDIF

      ENDIF

    
    ENDIF


    DO JLL=1, JLM
      JLON=JLX 
      PMFUL (JLON, JLEV)=PLU (JLON, JLEV)*PMFU (JLON, JLEV)
      PMFUS (JLON, JLEV)=(YDCST%RCPD*PTU (JLON, JLEV)+PGEOH (JLON, JLEV))*PMFU (JLON, JLEV)
      PMFUQ (JLON, JLEV)=PQU (JLON, JLEV)*PMFU (JLON, JLEV)
      ZALFAW=FOEALFCU (PTU (JLON, JLEV))

      IF (LSCVFLAG (JLON))  THEN
          ZALFAW=1.0_JPRB
      ENDIF

      PLUDELI (JLON, JLEV, 1)=ZALFAW*PLUDE (JLON, JLEV)
      PLUDELI (JLON, JLEV, 2)=(1.0_JPRB-ZALFAW)*PLUDE (JLON, JLEV)
    ENDDO

  ENDIF

ENDDO



IF (KCTOP (JLON)==-1)  THEN
    LDCUM (JLON)=.FALSE.
ENDIF

KCBOT (JLON)=MAX (KCBOT (JLON), KCTOP (JLON))

IF (LDCUM (JLON)) THEN
  PWMEAN (JLON)=MAX (1.E-2_JPRB, PWMEAN (JLON)/MAX (1.0_JPRB, ZDPMEAN ))
  PWMEAN (JLON)=SQRT (2.0_JPRB*PWMEAN (JLON))
ENDIF




ENDSUBROUTINE CUASCN_OPENACC

! e56ac8e1f86b1a9cc13b38d73abbf48f96ba2f2a
