SUBROUTINE CUBASEN_OPENACC (PPLDARE, PPLRG, YDTHF, YDCST, YDEPHLI, YDECLDP, YDECUMF&
&, YDSPP_CONFIG, KIDIA, KFDIA, KLON, KLEV, KINDEX, LDMIXS, LDTDKMF, PTENH, PQENH, PGEOH&
&, PAPH, PQHFL, PAHFS, PGP2DSPP, PKMFL, PTEN, PQEN, PQSEN, PGEO, PTU, PQU, PLU, PWU2H&
&, PWUBASE, KLAB, LDCUM, LDSC, KCBOT, KBOTSC, KCTOP, KDPL, PCAPE, YDSTACK)
!$acc routine (CUBASEN_OPENACC) seq
USE YOEPHLI,ONLY:TEPHLI
USE PARKIND1,ONLY:JPIM, JPRB

USE YOMCST,ONLY:TCST
USE PARPHY,ONLY:RKAP
USE YOECUMF,ONLY:TECUMF
USE YOECLDP,ONLY:TECLDP
USE YOETHF,ONLY:TTHF
USE SPP_MOD,ONLY:TSPP_CONFIG
USE SPP_GEN_MOD,ONLY:SPP_PERT
USE ABOR1_ACC_MOD
USE STACK_MOD
#include "stack.h"

IMPLICIT NONE

REAL (KIND=JPRB), INTENT (IN)::PPLDARE
REAL (KIND=JPRB), INTENT (IN)::PPLRG
TYPE (TECLDP), INTENT (IN)::YDECLDP
TYPE (TECUMF), INTENT (IN)::YDECUMF
TYPE (TTHF), INTENT (IN)::YDTHF
TYPE (TCST), INTENT (IN)::YDCST
TYPE (TEPHLI), INTENT (IN)::YDEPHLI
TYPE (TSPP_CONFIG), INTENT (IN)::YDSPP_CONFIG
INTEGER (KIND=JPIM), INTENT (IN)::KLON
INTEGER (KIND=JPIM), INTENT (IN)::KLEV
INTEGER (KIND=JPIM), INTENT (IN)::KIDIA
INTEGER (KIND=JPIM), INTENT (IN)::KFDIA
INTEGER (KIND=JPIM), INTENT (IN)::KINDEX
LOGICAL, INTENT (IN)::LDMIXS
LOGICAL, INTENT (IN)::LDTDKMF
REAL (KIND=JPRB), INTENT (IN)::PTENH (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PQENH (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PGEOH (KLON, KLEV+1)
REAL (KIND=JPRB), INTENT (IN)::PAPH (KLON, KLEV+1)
REAL (KIND=JPRB), INTENT (IN)::PQHFL (KLON, KLEV+1)
REAL (KIND=JPRB), INTENT (IN)::PAHFS (KLON, KLEV+1)
REAL (KIND=JPRB), INTENT (IN)::PGP2DSPP (KLON, YDSPP_CONFIG%SM%NRFTOTAL)
REAL (KIND=JPRB), INTENT (IN)::PKMFL (KLON)
REAL (KIND=JPRB), INTENT (IN)::PTEN (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PQEN (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PQSEN (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PGEO (KLON, KLEV)
REAL (KIND=JPRB), INTENT (INOUT)::PTU (KLON, KLEV)
REAL (KIND=JPRB), INTENT (INOUT)::PQU (KLON, KLEV)
REAL (KIND=JPRB), INTENT (INOUT)::PLU (KLON, KLEV)
REAL (KIND=JPRB), INTENT (INOUT)::PWU2H (KLON, KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PWUBASE (KLON)
INTEGER (KIND=JPIM), INTENT (INOUT)::KLAB (KLON, KLEV)
LOGICAL, INTENT (INOUT)::LDCUM (KLON)
LOGICAL, INTENT (OUT)::LDSC (KLON)
INTEGER (KIND=JPIM), INTENT (INOUT)::KCBOT (KLON)
INTEGER (KIND=JPIM), INTENT (OUT)::KBOTSC (KLON)
INTEGER (KIND=JPIM), INTENT (OUT)::KCTOP (KLON)
INTEGER (KIND=JPIM), INTENT (OUT)::KDPL (KLON)
REAL (KIND=JPRB), INTENT (OUT)::PCAPE (KLON)
TYPE(STACK) :: YDSTACK
TYPE(STACK) :: YLSTACK

INTEGER (KIND=JPIM)::IDPL 
temp (INTEGER (KIND=JPIM), ILAB, (KLON, KLEV))
INTEGER (KIND=JPIM)::IBOTSC 
INTEGER (KIND=JPIM)::ICBOT 
INTEGER (KIND=JPIM)::ICTOP 

LOGICAL::LLFIRST 
LOGICAL::LLDSC 
LOGICAL::LLDCUM 
LOGICAL::LLDEEP 
LOGICAL::LLGO_ON 
LOGICAL::LL_LDBASE 

LOGICAL::LLRESETJL 
LOGICAL::LLRESET

LOGICAL::LLPERT_ENTSTPC1
LOGICAL::LLPERT_ENTRORG

INTEGER (KIND=JPIM)::JKB
INTEGER (KIND=JPIM)::JKT
INTEGER (KIND=JPIM)::JKT2
INTEGER (KIND=JPIM)::JKT1
INTEGER (KIND=JPIM)::JKK
INTEGER (KIND=JPIM)::JLON
INTEGER (KIND=JPIM)::JLEV
INTEGER (KIND=JPIM)::IS
INTEGER (KIND=JPIM)::IK

INTEGER (KIND=JPIM)::IPENTSTPC1
INTEGER (KIND=JPIM)::IPENTRORG

temp (REAL (KIND=JPRB), ZWU2H, (KLON, KLEV))
temp (REAL (KIND=JPRB), ZBUOH, (KLON, KLEV))
temp (REAL (KIND=JPRB), ZSUH, (KLON, KLEV))
temp (REAL (KIND=JPRB), ZQENH, (KLON, KLEV+1))
temp (REAL (KIND=JPRB), ZSENH, (KLON, KLEV+1))
temp (REAL (KIND=JPRB), ZS, (KLON, KLEV))

REAL (KIND=JPRB)::ZPH 
REAL (KIND=JPRB)::ZQOLD 
REAL (KIND=JPRB)::ZMIX 

REAL (KIND=JPRB)::ZCBASE 
REAL (KIND=JPRB)::ZDZ 

temp (REAL (KIND=JPRB), ZTU, (KLON, KLEV))
temp (REAL (KIND=JPRB), ZQU, (KLON, KLEV))
temp (REAL (KIND=JPRB), ZLU, (KLON, KLEV))
temp (REAL (KIND=JPRB), ZCAPE, (KLON, KLEV))
REAL (KIND=JPRB)::ZBUOF
REAL (KIND=JPRB)::ZRHO
REAL (KIND=JPRB)::ZKHVFL
REAL (KIND=JPRB)::ZWS
REAL (KIND=JPRB)::ZUST

REAL (KIND=JPRB)::ZQEXC
REAL (KIND=JPRB)::ZQEX 

REAL (KIND=JPRB)::ZTEXC
REAL (KIND=JPRB)::ZTEX 
REAL (KIND=JPRB)::ZEPS
REAL (KIND=JPRB)::ZTVENH
REAL (KIND=JPRB)::ZTVUH
REAL (KIND=JPRB)::ZLGLAC

REAL (KIND=JPRB)::ZBW
REAL (KIND=JPRB)::ZAW
REAL (KIND=JPRB)::ZQF
REAL (KIND=JPRB)::ZSF
REAL (KIND=JPRB)::ZPDIFFBOT
REAL (KIND=JPRB)::ZPDIFFTOP
REAL (KIND=JPRB)::ZDP
REAL (KIND=JPRB)::ZDTDP
REAL (KIND=JPRB)::ZDQSDT
REAL (KIND=JPRB)::ZESDP
REAL (KIND=JPRB)::ZFAC
REAL (KIND=JPRB)::ZFACI
REAL (KIND=JPRB)::ZFACW
REAL (KIND=JPRB)::ZALFAW
REAL (KIND=JPRB)::ZDQ
REAL (KIND=JPRB)::ZCOR
REAL (KIND=JPRB)::ZQSU

REAL (KIND=JPRB)::ZWORK2
REAL (KIND=JPRB)::ZWORK1

REAL (KIND=JPRB)::ZTMP
REAL (KIND=JPRB)::ZRG
REAL (KIND=JPRB)::ZRCPD

REAL (KIND=JPRB)::ZXENTSTPC1
REAL (KIND=JPRB)::ZXENTRORG
INTEGER (KIND=JPIM)::IPN

TYPE (SPP_PERT)::PN2
TYPE (SPP_PERT)::PN1

#include "cuadjtq.func.h"

REAL (KIND=JPRB)::ZQP
REAL (KIND=JPRB)::ZTARG
REAL (KIND=JPRB)::ZQSAT
REAL (KIND=JPRB)::ZQMAX
REAL (KIND=JPRB)::ZOEALFA
REAL (KIND=JPRB)::ZFOEEWL
REAL (KIND=JPRB)::ZFOEEWI
REAL (KIND=JPRB)::ZCOR_CUADJTQ
REAL (KIND=JPRB)::ZCOND1
REAL (KIND=JPRB)::ZCOND
REAL (KIND=JPRB)::Z2S
REAL (KIND=JPRB)::Z1S
REAL (KIND=JPRB)::ZF
REAL (KIND=JPRB)::ZI
REAL (KIND=JPRB)::ZL
LOGICAL::LLFLAG 
#include "fcttre.func.h"

YLSTACK = YDSTACK


IF (KIND (ILAB) == 8) THEN
    alloc8 (ILAB)
ELSEIF (KIND (ILAB) == 4) THEN
    alloc4 (ILAB)
ELSE
    STOP 1
ENDIF


IF (KIND (ZWU2H) == 8) THEN
    alloc8 (ZWU2H)
ELSEIF (KIND (ZWU2H) == 4) THEN
    alloc4 (ZWU2H)
ELSE
    STOP 1
ENDIF


IF (KIND (ZBUOH) == 8) THEN
    alloc8 (ZBUOH)
ELSEIF (KIND (ZBUOH) == 4) THEN
    alloc4 (ZBUOH)
ELSE
    STOP 1
ENDIF


IF (KIND (ZSUH) == 8) THEN
    alloc8 (ZSUH)
ELSEIF (KIND (ZSUH) == 4) THEN
    alloc4 (ZSUH)
ELSE
    STOP 1
ENDIF


IF (KIND (ZQENH) == 8) THEN
    alloc8 (ZQENH)
ELSEIF (KIND (ZQENH) == 4) THEN
    alloc4 (ZQENH)
ELSE
    STOP 1
ENDIF


IF (KIND (ZSENH) == 8) THEN
    alloc8 (ZSENH)
ELSEIF (KIND (ZSENH) == 4) THEN
    alloc4 (ZSENH)
ELSE
    STOP 1
ENDIF


IF (KIND (ZS) == 8) THEN
    alloc8 (ZS)
ELSEIF (KIND (ZS) == 4) THEN
    alloc4 (ZS)
ELSE
    STOP 1
ENDIF


IF (KIND (ZTU) == 8) THEN
    alloc8 (ZTU)
ELSEIF (KIND (ZTU) == 4) THEN
    alloc4 (ZTU)
ELSE
    STOP 1
ENDIF


IF (KIND (ZQU) == 8) THEN
    alloc8 (ZQU)
ELSEIF (KIND (ZQU) == 4) THEN
    alloc4 (ZQU)
ELSE
    STOP 1
ENDIF


IF (KIND (ZLU) == 8) THEN
    alloc8 (ZLU)
ELSEIF (KIND (ZLU) == 4) THEN
    alloc4 (ZLU)
ELSE
    STOP 1
ENDIF


IF (KIND (ZCAPE) == 8) THEN
    alloc8 (ZCAPE)
ELSEIF (KIND (ZCAPE) == 4) THEN
    alloc4 (ZCAPE)
ELSE
    STOP 1
ENDIF




JLON = KIDIA


ZAW=1.0_JPRB
ZBW=1.0_JPRB

PWUBASE (JLON)=0.0_JPRB
LLGO_ON =.TRUE.
LLFIRST =.TRUE.
KDPL (JLON)=KLEV

JKT1=KINDEX
JKT2=YDECUMF%NJKT2
ZRG=1.0_JPRB/YDCST%RG
ZRCPD=1.0_JPRB/YDCST%RCPD

DO JLEV=1, KLEV
  
  ZTU (JLON, JLEV)=PTU (JLON, JLEV)
  ZQU (JLON, JLEV)=PQU (JLON, JLEV)
  ZLU (JLON, JLEV)=PLU (JLON, JLEV)
  ILAB (JLON, JLEV)=KLAB (JLON, JLEV)
  ZCAPE (JLON, JLEV)=0.0_JPRB
  
ENDDO


LLPERT_ENTSTPC1=.FALSE.
LLPERT_ENTRORG=.FALSE.


DO JLEV=1, KLEV
  
  PWU2H (JLON, JLEV)=0.0_JPRB
  ZWU2H (JLON, JLEV)=0.0_JPRB
  ZS (JLON, JLEV)=YDCST%RCPD*PTEN (JLON, JLEV)+PGEO (JLON, JLEV)
  ZQENH (JLON, JLEV)=PQENH (JLON, JLEV)
  ZSENH (JLON, JLEV)=YDCST%RCPD*PTENH (JLON, JLEV)+PGEOH (JLON, JLEV)
  
ENDDO


DO JKK=KLEV, JKT1,-1
  IS=0

  

  IF (LLGO_ON ) THEN
    IS=IS+1
    IDPL =JKK
    ICBOT =JKK
    IBOTSC =KLEV-1
    ICTOP =KLEV-1
    LLDCUM =.FALSE.
    LLDSC =.FALSE.
    LL_LDBASE =.FALSE.
  ENDIF


  

  IF (IS/=0) THEN

    IF (JKK==KLEV) THEN
      ZTEXC=0.2_JPRB
      ZQEXC=1.E-4_JPRB

      

      IF (LLGO_ON ) THEN
        ZRHO=PAPH (JLON, JKK+1)/(YDCST%RD*(PTEN (JLON, JKK)*(1.0_JPRB+YDCST%RETV*PQEN (JLON, JKK))))
        ZKHVFL=(PAHFS (JLON, JKK+1)*ZRCPD+YDCST%RETV*PTEN (JLON&
        &, JKK)*PQHFL (JLON, JKK+1))/(ZRHO*PPLRG*PPLDARE)
        ZUST=MAX (SQRT (PKMFL (JLON)), 0.1_JPRB)
        ZWS=ZUST**3._JPRB-1.5_JPRB*RKAP*ZKHVFL*(PGEOH (JLON, KLEV)-PGEOH (JLON, KLEV+1))/PTEN (JLON, KLEV)
        ZTEX =0.0_JPRB
        ZQEX =0.0_JPRB

        IF (ZKHVFL<0.0_JPRB) THEN
          ZWS=1.2_JPRB*ZWS**.3333_JPRB
          ILAB (JLON, JKK)=1
          ZTEX =MAX (-1.5_JPRB*PAHFS (JLON, JKK+1)/(ZRHO*ZWS*YDCST%RCPD*PPLRG*PPLDARE), ZTEXC)
          ZQEX =MAX (-1.5_JPRB*PQHFL (JLON, JKK+1)/(ZRHO*ZWS*PPLRG*PPLDARE), ZQEXC)
          ZQU (JLON, JKK)=ZQENH (JLON, JKK)+ZQEX 
          ZSUH (JLON, JKK)=ZSENH (JLON, JKK)+YDCST%RCPD*ZTEX 
          ZTU (JLON, JKK)=(ZSENH (JLON, JKK)-PGEOH (JLON, JKK))*ZRCPD+ZTEX 
          ZLU (JLON, JKK)=0.0_JPRB
          ZWU2H (JLON, JKK)=ZWS**2+0.1_JPRB
          PWU2H (JLON, JKK)=ZWU2H (JLON, JKK)
          ZTVENH=(1.0_JPRB+YDCST%RETV*ZQENH (JLON, JKK))*(ZSENH (JLON, JKK)-PGEOH (JLON, JKK))*ZRCPD
          ZTVUH=(1.0_JPRB+YDCST%RETV*ZQU (JLON, JKK))*ZTU (JLON, JKK)
          ZBUOH (JLON, JKK)=(ZTVUH-ZTVENH)*YDCST%RG/ZTVENH
        ELSE
          LLGO_ON =.FALSE.
        ENDIF

      ENDIF

    
    ELSE

      

      IF (LLGO_ON ) THEN
        ZRHO=PAPH (JLON, JKK+1)/(YDCST%RD*(PTEN (JLON, JKK)*(1.+YDCST%RETV*PQEN (JLON, JKK))))
        ILAB (JLON, JKK)=1
        ZTEXC=0.2_JPRB
        ZQEXC=1.E-4_JPRB

        IF (JKK==KLEV-1) THEN
          ZTEXC=MAX (ZTEXC, ZTEX )
          ZQEXC=MAX (ZQEXC, ZQEX )

          IF (LDTDKMF) THEN
            ZTEXC=MIN (ZTEXC, 3.0_JPRB)
            ZQEXC=MIN (ZQEXC, 2.E-3_JPRB)
          ELSE
            ZTEXC=MIN (ZTEXC, 1.0_JPRB)
            ZQEXC=MIN (ZQEXC, 5.E-4_JPRB)
          ENDIF

        ENDIF

        ZQU (JLON, JKK)=ZQENH (JLON, JKK)+ZQEXC
        ZSUH (JLON, JKK)=ZSENH (JLON, JKK)+YDCST%RCPD*ZTEXC
        ZTU (JLON, JKK)=(ZSENH (JLON, JKK)-PGEOH (JLON, JKK))*ZRCPD+ZTEXC
        ZLU (JLON, JKK)=0.0_JPRB

        IF (PAPH (JLON, KLEV+1)-PAPH (JLON, JKK-1)<60.E2_JPRB) THEN
          ZQU (JLON, JKK)=0.0_JPRB
          ZSUH (JLON, JKK)=0.0_JPRB
          ZWORK1=0.0_JPRB

          DO JLEV=JKK+1, JKK-1,-1

            IF (ZWORK1<50.E2_JPRB) THEN
              ZWORK2=PAPH (JLON, JLEV)-PAPH (JLON, JLEV-1)
              ZWORK1=ZWORK1+ZWORK2
              ZQU (JLON, JKK)=ZQU (JLON, JKK)+ZQENH (JLON, JLEV)*ZWORK2
              ZSUH (JLON, JKK)=ZSUH (JLON, JKK)+ZSENH (JLON, JLEV)*ZWORK2
            ENDIF

          ENDDO

          ZQU (JLON, JKK)=ZQU (JLON, JKK)/ZWORK1+ZQEXC
          ZSUH (JLON, JKK)=ZSUH (JLON, JKK)/ZWORK1+YDCST%RCPD*ZTEXC
          ZTU (JLON, JKK)=(ZSUH (JLON, JKK)-PGEOH (JLON, JKK))*ZRCPD+ZTEXC
        ENDIF

        ZWU2H (JLON, JKK)=1.0_JPRB
        ZTVENH=(1.0_JPRB+YDCST%RETV*ZQENH (JLON, JKK))*(ZSENH (JLON, JKK)-PGEOH (JLON, JKK))*ZRCPD
        ZTVUH=(1.0_JPRB+YDCST%RETV*ZQU (JLON, JKK))*ZTU (JLON, JKK)
        ZBUOH (JLON, JKK)=(ZTVUH-ZTVENH)*YDCST%RG/ZTVENH
      ENDIF

    
    ENDIF

  ENDIF


  DO JLEV=JKK-1, JKT2,-1
    IS=0

    IF (JKK==KLEV.OR.KINDEX==KLEV-1) THEN
      
      
      ZXENTSTPC1=YDECUMF%ENTSTPC1

      

      IF (LLGO_ON ) THEN
        IS=IS+1
        ZDZ =(PGEOH (JLON, JLEV)-PGEOH (JLON, JLEV+1))*ZRG

        IF (LDTDKMF) THEN
          ZEPS=ZXENTSTPC1/((PGEOH (JLON, JLEV)-PGEOH (JLON, KLEV+1))*ZRG*PPLRG)+YDECUMF%ENTSTPC2
        ELSE
          ZEPS=ZXENTSTPC1/((PGEO (JLON, JLEV)-PGEOH (JLON, KLEV+1))*ZRG*PPLRG)+YDECUMF%ENTSTPC2

          IF (LDMIXS.AND.KINDEX==KLEV.AND.ZLU (JLON, JLEV+1)>0.0_JPRB)  THEN
              ZEPS=ZEPS*YDECUMF%ENTSTPC3
          ENDIF

        ENDIF

        ZMIX =0.5_JPRB*ZDZ *PPLRG*ZEPS

        IF (.NOT.LDTDKMF)  THEN
            ZMIX =MIN (1.0_JPRB, ZMIX )
        ENDIF

        ZQF=(PQENH (JLON, JLEV+1)+PQENH (JLON, JLEV))*0.5_JPRB
        ZSF=(ZSENH (JLON, JLEV+1)+ZSENH (JLON, JLEV))*0.5_JPRB
        ZTMP=1.0_JPRB/(1.0_JPRB+ZMIX )
        ZQU (JLON, JLEV)=(ZQU (JLON, JLEV+1)*(1.0_JPRB-ZMIX )+2.0_JPRB*ZMIX *ZQF)*ZTMP
        ZSUH (JLON, JLEV)=(ZSUH (JLON, JLEV+1)*(1.0_JPRB-ZMIX )+2.0_JPRB*ZMIX *ZSF)*ZTMP
        ZQOLD =ZQU (JLON, JLEV)
        ZTU (JLON, JLEV)=(ZSUH (JLON, JLEV)-PGEOH (JLON, JLEV))*ZRCPD
        ZPH =PAPH (JLON, JLEV)
      ENDIF

    
    ELSE
      ZXENTRORG=YDECUMF%ENTRORG

      

      IF (LLGO_ON ) THEN
        
        ZDZ =(PGEOH (JLON, JLEV)-PGEOH (JLON, JLEV+1))*ZRG
        ZMIX =YDECUMF%ENTRTEST*ZXENTRORG*ZDZ *MIN (1.0_JPRB,(PQSEN (JLON, JLEV)/PQSEN (JLON, KLEV))**3)
      ENDIF


      

      

      IF (LLGO_ON ) THEN
        IS=IS+1
        ZMIX =MIN (1.0_JPRB, ZMIX )
        ZQF=(PQENH (JLON, JLEV+1)+PQENH (JLON, JLEV))*0.5_JPRB
        ZSF=(ZSENH (JLON, JLEV+1)+ZSENH (JLON, JLEV))*0.5_JPRB
        ZQU (JLON, JLEV)=ZQU (JLON, JLEV+1)*(1.0_JPRB-ZMIX )+ZQF*ZMIX 
        ZSUH (JLON, JLEV)=ZSUH (JLON, JLEV+1)*(1.0_JPRB-ZMIX )+ZSF*ZMIX 
        ZQOLD =ZQU (JLON, JLEV)
        ZTU (JLON, JLEV)=(ZSUH (JLON, JLEV)-PGEOH (JLON, JLEV))*ZRCPD
        ZPH =PAPH (JLON, JLEV)
      ENDIF

    
    ENDIF


    IF (IS==0)  THEN
        EXIT
    ENDIF

    IK=JLEV
    
    
    
    
    
    
    
    ZQMAX=0.5_JPRB

    IF (.NOT.YDEPHLI%LPHYLIN) THEN
      
      LLFLAG =LLGO_ON 

      

      

      IF (LLFLAG ) THEN
        ZQP=1.0_JPRB/ZPH 
        ZL=1.0_JPRB/(ZTU (JLON, IK)-YDTHF%R4LES)
        ZI=1.0_JPRB/(ZTU (JLON, IK)-YDTHF%R4IES)
        ZQSAT=YDTHF%R2ES*(FOEALFCU (ZTU (JLON, IK))*EXP (YDTHF%R3LES*(ZTU (JLON, IK)-YDCST%RTT)*ZL&
        &)+(1.0_JPRB-FOEALFCU (ZTU (JLON, IK)))*EXP (YDTHF%R3IES*(ZTU (JLON, IK)-YDCST%RTT)*ZI))
        ZQSAT=ZQSAT*ZQP
        ZQSAT=MIN (0.5_JPRB, ZQSAT)
        ZCOR_CUADJTQ=1.0_JPRB-YDCST%RETV*ZQSAT
        ZF=FOEALFCU (ZTU (JLON, IK))*YDTHF%R5ALVCP*ZL**2+(1.0_JPRB&
        &-FOEALFCU (ZTU (JLON, IK)))*YDTHF%R5ALSCP*ZI**2
        ZCOND=(ZQU (JLON, IK)*ZCOR_CUADJTQ**2-ZQSAT*ZCOR_CUADJTQ)/(ZCOR_CUADJTQ**2+ZQSAT*ZF)
        ZCOND=MAX (ZCOND, 0.0_JPRB)
        ZTU (JLON, IK)=ZTU (JLON, IK)+FOELDCPMCU (ZTU (JLON, IK))*ZCOND
        ZQU (JLON, IK)=ZQU (JLON, IK)-ZCOND
        ZL=1.0_JPRB/(ZTU (JLON, IK)-YDTHF%R4LES)
        ZI=1.0_JPRB/(ZTU (JLON, IK)-YDTHF%R4IES)
        ZQSAT=YDTHF%R2ES*(FOEALFCU (ZTU (JLON, IK))*EXP (YDTHF%R3LES*(ZTU (JLON, IK)-YDCST%RTT)*ZL&
        &)+(1.0_JPRB-FOEALFCU (ZTU (JLON, IK)))*EXP (YDTHF%R3IES*(ZTU (JLON, IK)-YDCST%RTT)*ZI))
        ZQSAT=ZQSAT*ZQP
        ZQSAT=FMINJ (0.5_JPRB, ZQSAT)
        ZCOR_CUADJTQ=1.0_JPRB-YDCST%RETV*ZQSAT
        ZF=FOEALFCU (ZTU (JLON, IK))*YDTHF%R5ALVCP*ZL**2+(1.0_JPRB&
        &-FOEALFCU (ZTU (JLON, IK)))*YDTHF%R5ALSCP*ZI**2
        ZCOND1=(ZQU (JLON, IK)*ZCOR_CUADJTQ**2-ZQSAT*ZCOR_CUADJTQ)/(ZCOR_CUADJTQ**2+ZQSAT*ZF)

        IF (ZCOND==0.0_JPRB)  THEN
            ZCOND1=0.0_JPRB
        ENDIF

        ZTU (JLON, IK)=ZTU (JLON, IK)+FOELDCPMCU (ZTU (JLON, IK))*ZCOND1
        ZQU (JLON, IK)=ZQU (JLON, IK)-ZCOND1
      ENDIF

    
    
    
    
    
    
    
    
    ELSE

      

      

      IF (LLGO_ON ) THEN
        ZQP=1.0_JPRB/ZPH 
        ZTARG=ZTU (JLON, IK)
        ZOEALFA=0.5_JPRB*(TANH (YDEPHLI%RLPAL1*(ZTARG-YDEPHLI%RLPTRC))+1.0_JPRB)
        ZFOEEWL=YDTHF%R2ES*EXP (YDTHF%R3LES*(ZTARG-YDCST%RTT)/(ZTARG-YDTHF%R4LES))
        ZFOEEWI=YDTHF%R2ES*EXP (YDTHF%R3IES*(ZTARG-YDCST%RTT)/(ZTARG-YDTHF%R4IES))
        ZQSAT=ZQP*(ZOEALFA*ZFOEEWL+(1.0_JPRB-ZOEALFA)*ZFOEEWI)
        Z1S=TANH (YDEPHLI%RLPAL2*(ZQSAT-ZQMAX))
        ZQSAT=0.5_JPRB*((1.0_JPRB-Z1S)*ZQSAT+(1.0_JPRB+Z1S)*ZQMAX)
        ZCOR_CUADJTQ=1.0_JPRB/(1.0_JPRB-YDCST%RETV*ZQSAT)
        ZQSAT=ZQSAT*ZCOR_CUADJTQ
        Z2S=ZOEALFA*YDTHF%R5ALVCP*(1.0_JPRB/(ZTARG-YDTHF%R4LES)**2)+(1.0_JPRB&
        &-ZOEALFA)*YDTHF%R5ALSCP*(1.0_JPRB/(ZTARG-YDTHF%R4IES)**2)
        ZCOND=(ZQU (JLON, IK)-ZQSAT)/(1.0_JPRB+ZQSAT*ZCOR_CUADJTQ*Z2S)
        ZCOND=MAX (ZCOND, 0.0_JPRB)

        IF (ZCOND/=0.0_JPRB) THEN
          ZTU (JLON, IK)=ZTU (JLON, IK)+(ZOEALFA*YDTHF%RALVDCP+(1.0_JPRB-ZOEALFA)*YDTHF%RALSDCP)*ZCOND
          ZQU (JLON, IK)=ZQU (JLON, IK)-ZCOND
          ZTARG=ZTU (JLON, IK)
          ZOEALFA=0.5_JPRB*(TANH (YDEPHLI%RLPAL1*(ZTARG-YDEPHLI%RLPTRC))+1.0_JPRB)
          ZFOEEWL=YDTHF%R2ES*EXP (YDTHF%R3LES*(ZTARG-YDCST%RTT)/(ZTARG-YDTHF%R4LES))
          ZFOEEWI=YDTHF%R2ES*EXP (YDTHF%R3IES*(ZTARG-YDCST%RTT)/(ZTARG-YDTHF%R4IES))
          ZQSAT=ZQP*(ZOEALFA*ZFOEEWL+(1.0_JPRB-ZOEALFA)*ZFOEEWI)
          Z1S=TANH (YDEPHLI%RLPAL2*(ZQSAT-ZQMAX))
          ZQSAT=0.5_JPRB*((1.0_JPRB-Z1S)*ZQSAT+(1.0_JPRB+Z1S)*ZQMAX)
          ZCOR_CUADJTQ=1.0_JPRB/(1.0_JPRB-YDCST%RETV*ZQSAT)
          ZQSAT=ZQSAT*ZCOR_CUADJTQ
          Z2S=ZOEALFA*YDTHF%R5ALVCP*(1.0_JPRB/(ZTARG-YDTHF%R4LES)**2)+(1.0_JPRB&
          &-ZOEALFA)*YDTHF%R5ALSCP*(1.0_JPRB/(ZTARG-YDTHF%R4IES)**2)
          ZCOND1=(ZQU (JLON, IK)-ZQSAT)/(1.0_JPRB+ZQSAT*ZCOR_CUADJTQ*Z2S)
          ZTU (JLON, IK)=ZTU (JLON, IK)+(ZOEALFA*YDTHF%RALVDCP+(1.0_JPRB-ZOEALFA)*YDTHF%RALSDCP)*ZCOND1
          ZQU (JLON, IK)=ZQU (JLON, IK)-ZCOND1
        ENDIF

      ENDIF

    
    
    
    
    
    ENDIF


    

    

    

    

    IF (LLGO_ON ) THEN
      ZDQ=MAX (ZQOLD -ZQU (JLON, JLEV), 0.0_JPRB)
      ZLU (JLON, JLEV)=ZLU (JLON, JLEV+1)+ZDQ
      ZLGLAC=ZDQ*((1.0_JPRB-FOEALFCU (ZTU (JLON, JLEV)))-(1.0_JPRB-FOEALFCU (ZTU (JLON, JLEV+1))))
      ZLU (JLON, JLEV)=0.5_JPRB*ZLU (JLON, JLEV)
      ZTU (JLON, JLEV)=ZTU (JLON, JLEV)+YDTHF%RALFDCP*ZLGLAC
      ZSUH (JLON, JLEV)=YDCST%RCPD*ZTU (JLON, JLEV)+PGEOH (JLON, JLEV)
      ZTVUH=(1.0_JPRB+YDCST%RETV*ZQU (JLON, JLEV)-ZLU (JLON, JLEV))*ZTU (JLON, JLEV)+YDTHF%RALFDCP*ZLGLAC
      ZTVENH=(1.0_JPRB+YDCST%RETV*ZQENH (JLON, JLEV))*(ZSENH (JLON, JLEV)-PGEOH (JLON, JLEV))*ZRCPD
      ZBUOH (JLON, JLEV)=(ZTVUH-ZTVENH)*YDCST%RG/ZTVENH
      ZBUOF=(ZBUOH (JLON, JLEV)+ZBUOH (JLON, JLEV+1))*0.5_JPRB
      ZTMP=1.0_JPRB/(1.0_JPRB+2.0_JPRB*ZBW*ZMIX )
      ZWU2H (JLON, JLEV)=(ZWU2H (JLON, JLEV+1)*(1.0_JPRB-2.0_JPRB*ZBW*ZMIX )+2.0_JPRB*ZAW*ZBUOF*ZDZ )*ZTMP

      IF (JKK==KLEV) THEN
        PWU2H (JLON, JLEV)=ZWU2H (JLON, JLEV)
      ENDIF

      ZCAPE (JLON, JKK)=ZCAPE (JLON, JKK)+MAX (0.0_JPRB, ZBUOF*ZDZ )

      IF (ZLU (JLON, JLEV)>0.0_JPRB.AND.ILAB (JLON, JLEV+1)==1) THEN
        IK=JLEV+1
        ZQSU=FOEEWM (ZTU (JLON, IK))/PAPH (JLON, IK)
        ZESDP=ZQSU
        ZQSU=MIN (0.5_JPRB, ZQSU)
        ZCOR=1.0_JPRB/(1.0_JPRB-YDCST%RETV*ZQSU)
        ZQSU=ZQSU*ZCOR
        ZDQ=MIN (0._JPRB, ZQU (JLON, IK)-ZQSU)
        ZALFAW=FOEALFA (ZTU (JLON, IK))
        ZFACW=YDTHF%R5LES/((ZTU (JLON, IK)-YDTHF%R4LES)**2)
        ZFACI=YDTHF%R5IES/((ZTU (JLON, IK)-YDTHF%R4IES)**2)
        ZFAC=ZALFAW*ZFACW+(1.-ZALFAW)*ZFACI
        ZCOR=1.0_JPRB/(1.0_JPRB-YDCST%RETV*ZESDP)
        ZDQSDT=ZFAC*ZCOR*ZQSU
        ZDTDP=YDCST%RD*ZTU (JLON, IK)/(YDCST%RCPD*PAPH (JLON, IK))
        ZDP=ZDQ/(ZDQSDT*ZDTDP)
        ZCBASE =PAPH (JLON, IK)+ZDP
        ZPDIFFTOP=ZCBASE -PAPH (JLON, JLEV)
        ZPDIFFBOT=PAPH (JLON, JLEV+1)-ZCBASE 

        IF (ZPDIFFTOP>ZPDIFFBOT.AND.ZWU2H (JLON, JLEV+1)>0.0_JPRB) THEN
          JKB=MIN (KLEV-1, JLEV+1)
          ILAB (JLON, JKB)=2
          ILAB (JLON, JLEV)=2
          LL_LDBASE =.TRUE.
          LLDSC =.TRUE.
          IBOTSC =JKB
          ICBOT =JKB
          ZLU (JLON, JLEV+1)=YDECLDP%RLMIN
        ELSEIF (ZPDIFFTOP<=ZPDIFFBOT.AND.ZWU2H (JLON, JLEV)>0.0_JPRB) THEN
          ILAB (JLON, JLEV)=2
          LL_LDBASE =.TRUE.
          LLDSC =.TRUE.
          IBOTSC =JLEV
          ICBOT =JLEV
        ENDIF

      ENDIF


      IF (ZWU2H (JLON, JLEV)<0.0_JPRB) THEN
        LLGO_ON =.FALSE.

        IF (ZLU (JLON, JLEV+1)>0.0_JPRB) THEN
          ICTOP =JLEV
          LLDCUM =.TRUE.
        ELSE
          LLDCUM =.FALSE.
        ENDIF

      ELSE

        IF (ZLU (JLON, JLEV)>0.0_JPRB) THEN
          ILAB (JLON, JLEV)=2
        ELSE
          ILAB (JLON, JLEV)=1
        ENDIF

      ENDIF

    ENDIF

  
  ENDDO


  IF (JKK==KLEV.OR.(JKK==KLEV-1.AND.KINDEX==KLEV-1)) THEN
    
    LDSC (JLON)=LLDSC 

    IF (LDSC (JLON)) THEN
      KBOTSC (JLON)=IBOTSC 
    ELSE
      KBOTSC (JLON)=-1
    ENDIF

    JKT=ICTOP 
    JKB=ICBOT 
    LLDEEP =PAPH (JLON, JKB)-PAPH (JLON, JKT)>YDECUMF%RDEPTHS

    IF (LLDEEP .AND.KINDEX<KLEV-1)  THEN
        LLDCUM =.FALSE.
    ENDIF

    LLDEEP =.FALSE.
    LLGO_ON =.NOT.LLDEEP 

    IF (KINDEX==KLEV-1)  THEN
        LLGO_ON =.NOT.LLDCUM 
    ENDIF


    IF (LLDCUM ) THEN
      KCBOT (JLON)=ICBOT 
      KCTOP (JLON)=ICTOP 
      KDPL (JLON)=IDPL 
      LDCUM (JLON)=LLDCUM 
      PWUBASE (JLON)=SQRT (MAX (ZWU2H (JLON, JKB), 0.0_JPRB))
    ELSE
      KCTOP (JLON)=-1
      KCBOT (JLON)=-1
      KDPL (JLON)=KLEV-1
      LDCUM (JLON)=.FALSE.
      PWUBASE (JLON)=0.0_JPRB
    ENDIF


    

    DO JLEV=KLEV, 1,-1
      
      JKT=ICTOP 

      IF (JLEV>=JKT.OR.(KINDEX>=KLEV-1.AND.JKK==KLEV)) THEN
        KLAB (JLON, JLEV)=ILAB (JLON, JLEV)
        PTU (JLON, JLEV)=ZTU (JLON, JLEV)
        PQU (JLON, JLEV)=ZQU (JLON, JLEV)
        PLU (JLON, JLEV)=ZLU (JLON, JLEV)
      ENDIF

    
    ENDDO

  ENDIF


  IF (JKK<KLEV) THEN
    LLRESET=.FALSE.

    

    IF (.NOT.LLDEEP ) THEN
      JKT=ICTOP 
      JKB=ICBOT 
      LLDEEP =PAPH (JLON, JKB)-PAPH (JLON, JKT)>=YDECUMF%RDEPTHS
    ENDIF

    LLRESETJL =LLDEEP .AND.LLFIRST 
    LLRESET=LLRESET.OR.LLRESETJL 

    

    IF (LLRESET) THEN

      DO JLEV=KLEV, 1,-1

        

        IF (LLRESETJL ) THEN
          JKT=ICTOP 
          JKB=IDPL 

          IF (JLEV<=JKB.AND.JLEV>=JKT) THEN
            KLAB (JLON, JLEV)=ILAB (JLON, JLEV)
            PTU (JLON, JLEV)=ZTU (JLON, JLEV)
            PQU (JLON, JLEV)=ZQU (JLON, JLEV)
            PLU (JLON, JLEV)=ZLU (JLON, JLEV)
          ELSE
            KLAB (JLON, JLEV)=1
            PTU (JLON, JLEV)=PTENH (JLON, JLEV)
            PQU (JLON, JLEV)=PQENH (JLON, JLEV)
            PLU (JLON, JLEV)=0.0_JPRB
          ENDIF


          IF (JLEV<JKT)  THEN
              KLAB (JLON, JLEV)=0
          ENDIF

        ENDIF

      
      ENDDO

    ENDIF


    

    IF (LLDEEP .AND.LLFIRST ) THEN
      KDPL (JLON)=IDPL 
      KCTOP (JLON)=ICTOP 
      KCBOT (JLON)=ICBOT 
      LDCUM (JLON)=LLDCUM 
      LDSC (JLON)=.FALSE.
      KBOTSC (JLON)=-1
      JKB=KCBOT (JLON)
      PWUBASE (JLON)=SQRT (MAX (ZWU2H (JLON, JKB), 0.0_JPRB))
      LLFIRST =.FALSE.
    ENDIF

    LLGO_ON =.NOT.LLDEEP 
  
  ENDIF

ENDDO

PCAPE (JLON)=ZCAPE (JLON, 1)

DO JLEV=2, KLEV
  
  PCAPE (JLON)=MAX (PCAPE (JLON), ZCAPE (JLON, JLEV))
  
ENDDO



ENDSUBROUTINE CUBASEN_OPENACC

! e56ac8e1f86b1a9cc13b38d73abbf48f96ba2f2a
