SUBROUTINE CUDLFSN_OPENACC (YDTHF, YDCST, YDEPHLI, YDECUMF, KIDIA, KFDIA, KLON, KLEV&
&, KCBOT, KCTOP, LDCUM, PTENH, PQENH, PTEN, PQSEN, PGEO, PGEOH, PAPH, PTU, PQU, PMFUB&
&, PRFL, PTD, PQD, PMFD, PMFDS, PMFDQ, PDMFDP, KDTOP, LDDRAF, YDSTACK)
!$acc routine (CUDLFSN_OPENACC) seq
USE PARKIND1,ONLY:JPIM, JPRB

USE YOMCST,ONLY:TCST
USE YOETHF,ONLY:TTHF
USE YOECUMF,ONLY:TECUMF
USE YOEPHLI,ONLY:TEPHLI
USE ABOR1_ACC_MOD
USE STACK_MOD
#include "stack.h"

IMPLICIT NONE

TYPE (TTHF), INTENT (IN)::YDTHF
TYPE (TCST), INTENT (IN)::YDCST
TYPE (TECUMF), INTENT (IN)::YDECUMF
TYPE (TEPHLI), INTENT (IN)::YDEPHLI
INTEGER (KIND=JPIM), INTENT (IN)::KLON
INTEGER (KIND=JPIM), INTENT (IN)::KLEV
INTEGER (KIND=JPIM), INTENT (IN)::KIDIA
INTEGER (KIND=JPIM), INTENT (IN)::KFDIA
INTEGER (KIND=JPIM), INTENT (IN)::KCBOT (KLON)
INTEGER (KIND=JPIM), INTENT (IN)::KCTOP (KLON)
LOGICAL, INTENT (IN)::LDCUM (KLON)
REAL (KIND=JPRB), INTENT (IN)::PTENH (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PQENH (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PTEN (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PQSEN (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PGEO (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PGEOH (KLON, KLEV+1)
REAL (KIND=JPRB), INTENT (IN)::PAPH (KLON, KLEV+1)
REAL (KIND=JPRB), INTENT (IN)::PTU (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PQU (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PMFUB (KLON)
REAL (KIND=JPRB), INTENT (INOUT)::PRFL (KLON)
REAL (KIND=JPRB), INTENT (OUT)::PTD (KLON, KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PQD (KLON, KLEV)
REAL (KIND=JPRB), INTENT (INOUT)::PMFD (KLON, KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PMFDS (KLON, KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PMFDQ (KLON, KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PDMFDP (KLON, KLEV)
INTEGER (KIND=JPIM), INTENT (OUT)::KDTOP (KLON)
LOGICAL, INTENT (OUT)::LDDRAF (KLON)
TYPE(STACK) :: YDSTACK
TYPE(STACK) :: YLSTACK
INTEGER (KIND=JPIM)::IKHSMIN 

REAL (KIND=JPRB)::ZHSMIN 
REAL (KIND=JPRB)::ZPH 
REAL (KIND=JPRB)::ZCOND 
temp (REAL (KIND=JPRB), ZQENWB, (KLON, KLEV))
temp (REAL (KIND=JPRB), ZTENWB, (KLON, KLEV))
LOGICAL::LLO2 

INTEGER (KIND=JPIM)::JLON
INTEGER (KIND=JPIM)::JLEV
INTEGER (KIND=JPIM)::IS
INTEGER (KIND=JPIM)::IKE
INTEGER (KIND=JPIM)::IK

REAL (KIND=JPRB)::ZTTEST
REAL (KIND=JPRB)::ZTARG
REAL (KIND=JPRB)::ZQTEST
REAL (KIND=JPRB)::ZOELHM
REAL (KIND=JPRB)::ZOEALFA
REAL (KIND=JPRB)::ZMFTOP
REAL (KIND=JPRB)::ZHSK
REAL (KIND=JPRB)::ZBUO

#include "cuadjtq.func.h"

REAL (KIND=JPRB)::ZQP
REAL (KIND=JPRB)::ZTARG_CUADJTQ
REAL (KIND=JPRB)::ZQSAT
REAL (KIND=JPRB)::ZQMAX
REAL (KIND=JPRB)::ZOEALFA_CUADJTQ
REAL (KIND=JPRB)::ZFOEEWL
REAL (KIND=JPRB)::ZFOEEWI
REAL (KIND=JPRB)::ZCOR
REAL (KIND=JPRB)::ZCOND1
REAL (KIND=JPRB)::ZCOND_CUADJTQ
REAL (KIND=JPRB)::Z2S
REAL (KIND=JPRB)::Z1S
REAL (KIND=JPRB)::ZF
REAL (KIND=JPRB)::ZI
REAL (KIND=JPRB)::ZL
LOGICAL::LLFLAG 
#include "fcttre.func.h"

YLSTACK = YDSTACK


IF (KIND (ZQENWB) == 8) THEN
    alloc8 (ZQENWB)
ELSEIF (KIND (ZQENWB) == 4) THEN
    alloc4 (ZQENWB)
ELSE
    STOP 1
ENDIF


IF (KIND (ZTENWB) == 8) THEN
    alloc8 (ZTENWB)
ELSEIF (KIND (ZTENWB) == 4) THEN
    alloc4 (ZTENWB)
ELSE
    STOP 1
ENDIF




JLON = KIDIA



LDDRAF (JLON)=.FALSE.
KDTOP (JLON)=KLEV+1
IKHSMIN =KLEV+1
ZHSMIN =1.E8_JPRB


IF (YDECUMF%LMFDD) THEN

  DO JLEV=3, KLEV-2

    IF (YDEPHLI%LPHYLIN) THEN
      
      ZTARG=PTEN (JLON, JLEV)
      ZOEALFA=MIN (1.0_JPRB, 0.545_JPRB*(TANH (0.17_JPRB*(ZTARG-YDEPHLI%RLPTRC))+1.0_JPRB))
      ZOELHM=ZOEALFA*YDCST%RLVTT+(1.0_JPRB-ZOEALFA)*YDCST%RLSTT
      ZHSK=YDCST%RCPD*PTEN (JLON, JLEV)+PGEO (JLON, JLEV)+ZOELHM*PQSEN (JLON, JLEV)

      IF (ZHSK<ZHSMIN ) THEN
        ZHSMIN =ZHSK
        IKHSMIN =JLEV
      ENDIF

    
    ELSE
      
      ZHSK=YDCST%RCPD*PTEN (JLON, JLEV)+PGEO (JLON, JLEV)+FOELHMCU (PTEN (JLON, JLEV))*PQSEN (JLON, JLEV)

      IF (ZHSK<ZHSMIN ) THEN
        ZHSMIN =ZHSK
        IKHSMIN =JLEV
      ENDIF

    
    ENDIF

  ENDDO

  IKE=KLEV-3

  DO JLEV=3, IKE
    IS=0
    
    ZTENWB (JLON, JLEV)=PTENH (JLON, JLEV)
    ZQENWB (JLON, JLEV)=PQENH (JLON, JLEV)
    ZPH =PAPH (JLON, JLEV)
    LLO2 =LDCUM (JLON).AND.PRFL (JLON)>0.0_JPRB.AND..NOT.LDDRAF (JLON).AND&
    &.(JLEV<KCBOT (JLON).AND.JLEV>KCTOP (JLON)).AND.JLEV>=IKHSMIN 

    IF (LLO2 ) THEN
      IS=IS+1
    ENDIF


    

    IF (IS==0)  THEN
        CYCLE
    ENDIF

    IK=JLEV
    
    
    
    
    
    
    
    ZQMAX=0.5_JPRB

    IF (.NOT.YDEPHLI%LPHYLIN) THEN

      

      

      

      IF (LLO2 ) THEN
        ZQP=1.0_JPRB/ZPH 
        ZQSAT=FOEEWMCU (ZTENWB (JLON, IK))*ZQP
        ZQSAT=MIN (0.5_JPRB, ZQSAT)
        ZCOR=1.0_JPRB/(1.0_JPRB-YDCST%RETV*ZQSAT)
        ZQSAT=ZQSAT*ZCOR
        ZCOND_CUADJTQ=(ZQENWB (JLON, IK)-ZQSAT)/(1.0_JPRB+ZQSAT*ZCOR*FOEDEMCU (ZTENWB (JLON, IK)))
        ZCOND_CUADJTQ=MIN (ZCOND_CUADJTQ, 0.0_JPRB)
        ZTENWB (JLON, IK)=ZTENWB (JLON, IK)+FOELDCPMCU (ZTENWB (JLON, IK))*ZCOND_CUADJTQ
        ZQENWB (JLON, IK)=ZQENWB (JLON, IK)-ZCOND_CUADJTQ
        ZQSAT=FOEEWMCU (ZTENWB (JLON, IK))*ZQP
        ZQSAT=MIN (0.5_JPRB, ZQSAT)
        ZCOR=1.0_JPRB/(1.0_JPRB-YDCST%RETV*ZQSAT)
        ZQSAT=ZQSAT*ZCOR
        ZCOND1=(ZQENWB (JLON, IK)-ZQSAT)/(1.0_JPRB+ZQSAT*ZCOR*FOEDEMCU (ZTENWB (JLON, IK)))

        IF (ZCOND_CUADJTQ==0.0_JPRB)  THEN
            ZCOND1=MIN (ZCOND1, 0.0_JPRB)
        ENDIF

        ZTENWB (JLON, IK)=ZTENWB (JLON, IK)+FOELDCPMCU (ZTENWB (JLON, IK))*ZCOND1
        ZQENWB (JLON, IK)=ZQENWB (JLON, IK)-ZCOND1
      ENDIF

    
    
    
    
    
    
    ELSE

      

      

      

      IF (LLO2 ) THEN
        ZQP=1.0_JPRB/ZPH 
        ZTARG_CUADJTQ=ZTENWB (JLON, IK)
        ZOEALFA_CUADJTQ=0.5_JPRB*(TANH (YDEPHLI%RLPAL1*(ZTARG_CUADJTQ-YDEPHLI%RLPTRC))+1.0_JPRB)
        ZFOEEWL=YDTHF%R2ES*EXP (YDTHF%R3LES*(ZTARG_CUADJTQ-YDCST%RTT)/(ZTARG_CUADJTQ-YDTHF%R4LES))
        ZFOEEWI=YDTHF%R2ES*EXP (YDTHF%R3IES*(ZTARG_CUADJTQ-YDCST%RTT)/(ZTARG_CUADJTQ-YDTHF%R4IES))
        ZQSAT=ZQP*(ZOEALFA_CUADJTQ*ZFOEEWL+(1.0_JPRB-ZOEALFA_CUADJTQ)*ZFOEEWI)
        Z1S=TANH (YDEPHLI%RLPAL2*(ZQSAT-ZQMAX))
        ZQSAT=0.5_JPRB*((1.0_JPRB-Z1S)*ZQSAT+(1.0_JPRB+Z1S)*ZQMAX)
        ZCOR=1.0_JPRB/(1.0_JPRB-YDCST%RETV*ZQSAT)
        ZQSAT=ZQSAT*ZCOR
        Z2S=ZOEALFA_CUADJTQ*YDTHF%R5ALVCP*(1.0_JPRB/(ZTARG_CUADJTQ-YDTHF%R4LES)**2)+(1.0_JPRB&
        &-ZOEALFA_CUADJTQ)*YDTHF%R5ALSCP*(1.0_JPRB/(ZTARG_CUADJTQ-YDTHF%R4IES)**2)
        ZCOND_CUADJTQ=(ZQENWB (JLON, IK)-ZQSAT)/(1.0_JPRB+ZQSAT*ZCOR*Z2S)
        ZCOND_CUADJTQ=MIN (ZCOND_CUADJTQ, 0.0_JPRB)

        IF (ZCOND_CUADJTQ/=0.0_JPRB) THEN
          ZTENWB (JLON, IK)=ZTENWB (JLON, IK)+(ZOEALFA_CUADJTQ*YDTHF%RALVDCP&
          &+(1.0_JPRB-ZOEALFA_CUADJTQ)*YDTHF%RALSDCP)*ZCOND_CUADJTQ
          ZQENWB (JLON, IK)=ZQENWB (JLON, IK)-ZCOND_CUADJTQ
          ZTARG_CUADJTQ=ZTENWB (JLON, IK)
          ZOEALFA_CUADJTQ=0.5_JPRB*(TANH (YDEPHLI%RLPAL1*(ZTARG_CUADJTQ-YDEPHLI%RLPTRC))+1.0_JPRB)
          ZFOEEWL=YDTHF%R2ES*EXP (YDTHF%R3LES*(ZTARG_CUADJTQ-YDCST%RTT)/(ZTARG_CUADJTQ-YDTHF%R4LES))
          ZFOEEWI=YDTHF%R2ES*EXP (YDTHF%R3IES*(ZTARG_CUADJTQ-YDCST%RTT)/(ZTARG_CUADJTQ-YDTHF%R4IES))
          ZQSAT=ZQP*(ZOEALFA_CUADJTQ*ZFOEEWL+(1.0_JPRB-ZOEALFA_CUADJTQ)*ZFOEEWI)
          Z1S=TANH (YDEPHLI%RLPAL2*(ZQSAT-ZQMAX))
          ZQSAT=0.5_JPRB*((1.0_JPRB-Z1S)*ZQSAT+(1.0_JPRB+Z1S)*ZQMAX)
          ZCOR=1.0_JPRB/(1.0_JPRB-YDCST%RETV*ZQSAT)
          ZQSAT=ZQSAT*ZCOR
          Z2S=ZOEALFA_CUADJTQ*YDTHF%R5ALVCP*(1.0_JPRB/(ZTARG_CUADJTQ-YDTHF%R4LES)**2)+(1.0_JPRB&
          &-ZOEALFA_CUADJTQ)*YDTHF%R5ALSCP*(1.0_JPRB/(ZTARG_CUADJTQ-YDTHF%R4IES)**2)
          ZCOND1=(ZQENWB (JLON, IK)-ZQSAT)/(1.0_JPRB+ZQSAT*ZCOR*Z2S)
          ZTENWB (JLON, IK)=ZTENWB (JLON, IK)+(ZOEALFA_CUADJTQ*YDTHF%RALVDCP&
          &+(1.0_JPRB-ZOEALFA_CUADJTQ)*YDTHF%RALSDCP)*ZCOND1
          ZQENWB (JLON, IK)=ZQENWB (JLON, IK)-ZCOND1
        ENDIF

      ENDIF

    
    
    
    
    ENDIF


    

    

    

    

    IF (LLO2 ) THEN
      ZTTEST=0.5_JPRB*(PTU (JLON, JLEV)+ZTENWB (JLON, JLEV))
      ZQTEST=0.5_JPRB*(PQU (JLON, JLEV)+ZQENWB (JLON, JLEV))
      ZBUO=ZTTEST*(1.0_JPRB+YDCST%RETV*ZQTEST)-PTENH (JLON, JLEV)*(1.0_JPRB+YDCST%RETV*PQENH (JLON, JLEV))
      ZCOND =PQENH (JLON, JLEV)-ZQENWB (JLON, JLEV)
      ZMFTOP=-YDECUMF%RMFDEPS*PMFUB (JLON)

      IF (ZBUO<0.0_JPRB.AND.PRFL (JLON)>10._JPRB*ZMFTOP*ZCOND ) THEN
        KDTOP (JLON)=JLEV
        LDDRAF (JLON)=.TRUE.
        PTD (JLON, JLEV)=ZTTEST
        PQD (JLON, JLEV)=ZQTEST
        PMFD (JLON, JLEV)=ZMFTOP
        PMFDS (JLON, JLEV)=PMFD (JLON, JLEV)*(YDCST%RCPD*PTD (JLON, JLEV)+PGEOH (JLON, JLEV))
        PMFDQ (JLON, JLEV)=PMFD (JLON, JLEV)*PQD (JLON, JLEV)
        PDMFDP (JLON, JLEV-1)=-0.5_JPRB*PMFD (JLON, JLEV)*ZCOND 
        PRFL (JLON)=PRFL (JLON)+PDMFDP (JLON, JLEV-1)
      ENDIF

    ENDIF

  
  ENDDO

ENDIF



ENDSUBROUTINE CUDLFSN_OPENACC

! e56ac8e1f86b1a9cc13b38d73abbf48f96ba2f2a
