SUBROUTINE CUDUDV_OPENACC (YDCST, YDECUMF, YDSPP_CONFIG, YDPERTPAR, KIDIA, KFDIA,&
& KLON, KLEV, KTOPM2, KTYPE, KCBOT, KCTOP, LDCUM, PTSPHY, PAPH, PAP, PUEN, PVEN, PMFU&
&, PMFD, PMFUO, PMFDO, PUU, PUD, PVU, PVD, PGP2DSPP, PTENU, PTENV, YDSTACK)
!$acc routine (CUDUDV_OPENACC) seq
USE PARKIND1,ONLY:JPIM, JPRB

USE YOMCST,ONLY:TCST
USE YOECUMF,ONLY:TECUMF
USE SPP_MOD,ONLY:TSPP_CONFIG
USE YOMPERTPAR,ONLY:TPERTPAR
USE SPP_GEN_MOD,ONLY:SPP_PERT
USE ABOR1_ACC_MOD
USE STACK_MOD
#include "stack.h"

IMPLICIT NONE

TYPE (TCST), INTENT (IN)::YDCST
TYPE (TECUMF), INTENT (IN)::YDECUMF
TYPE (TSPP_CONFIG), INTENT (IN)::YDSPP_CONFIG
TYPE (TPERTPAR), INTENT (IN)::YDPERTPAR
INTEGER (KIND=JPIM), INTENT (IN)::KIDIA
INTEGER (KIND=JPIM), INTENT (IN)::KFDIA
INTEGER (KIND=JPIM), INTENT (IN)::KLON
INTEGER (KIND=JPIM), INTENT (IN)::KLEV
INTEGER (KIND=JPIM), INTENT (IN)::KTOPM2
INTEGER (KIND=JPIM), INTENT (IN)::KTYPE (KLON)
INTEGER (KIND=JPIM), INTENT (IN)::KCBOT (KLON)
INTEGER (KIND=JPIM), INTENT (IN)::KCTOP (KLON)
LOGICAL, INTENT (IN)::LDCUM (KLON)
REAL (KIND=JPRB), INTENT (IN)::PTSPHY
REAL (KIND=JPRB), INTENT (IN)::PAPH (KLON, KLEV+1)
REAL (KIND=JPRB), INTENT (IN)::PAP (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PUEN (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PVEN (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PMFU (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PMFD (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PMFUO (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PMFDO (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PUU (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PUD (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PVU (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PVD (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PGP2DSPP (KLON, YDSPP_CONFIG%SM%NRFTOTAL)
REAL (KIND=JPRB), INTENT (INOUT)::PTENU (KLON, KLEV)
REAL (KIND=JPRB), INTENT (INOUT)::PTENV (KLON, KLEV)
TYPE(STACK) :: YDSTACK
TYPE(STACK) :: YLSTACK

REAL (KIND=JPRB)::ZADVW 
temp (REAL (KIND=JPRB), ZMFDV, (KLON, KLEV))
temp (REAL (KIND=JPRB), ZMFUV, (KLON, KLEV))
temp (REAL (KIND=JPRB), ZMFDU, (KLON, KLEV))
temp (REAL (KIND=JPRB), ZMFUU, (KLON, KLEV))

INTEGER (KIND=JPIM)::JLON
INTEGER (KIND=JPIM)::JLEV
INTEGER (KIND=JPIM)::IKB
INTEGER (KIND=JPIM)::IM
INTEGER (KIND=JPIM)::IK

INTEGER (KIND=JPIM)::IPCUDVS
INTEGER (KIND=JPIM)::IPCUDUS
INTEGER (KIND=JPIM)::IPCUDV
INTEGER (KIND=JPIM)::IPCUDU

INTEGER (KIND=JPIM)::IPN2
INTEGER (KIND=JPIM)::IPN1

TYPE (SPP_PERT)::PN2
TYPE (SPP_PERT)::PN1

REAL (KIND=JPRB)::ZV
REAL (KIND=JPRB)::ZU
REAL (KIND=JPRB)::ZTSPHY
REAL (KIND=JPRB)::ZIMP
REAL (KIND=JPRB)::ZZP

REAL (KIND=JPRB)::ZLIMN2
REAL (KIND=JPRB)::ZMDV
REAL (KIND=JPRB)::ZMDU

REAL (KIND=JPRB)::ZFAC
REAL (KIND=JPRB)::ZN2
REAL (KIND=JPRB)::ZXV_MAG
REAL (KIND=JPRB)::ZXU_MAG
REAL (KIND=JPRB)::ZXV
REAL (KIND=JPRB)::ZXU

REAL (KIND=JPRB)::ZRDV
REAL (KIND=JPRB)::ZRDU

temp (REAL (KIND=JPRB), ZDP, (KLON, KLEV))
temp (REAL (KIND=JPRB), ZDVDT, (KLON, KLEV))
temp (REAL (KIND=JPRB), ZDUDT, (KLON, KLEV))

temp (REAL (KIND=JPRB), ZR2, (KLON, KLEV))
temp (REAL (KIND=JPRB), ZR1, (KLON, KLEV))
temp (REAL (KIND=JPRB), ZB, (KLON, KLEV))
temp (LOGICAL, LLCUMBAS, (KLON, KLEV))
LOGICAL::LLPPAR_CUDUV

LOGICAL::LLPERT_CUDUDVS
LOGICAL::LLPERT_CUDUDV

#include "cubidiag_openacc.intfb.h"

YLSTACK = YDSTACK


IF (KIND (ZMFDV) == 8) THEN
    alloc8 (ZMFDV)
ELSEIF (KIND (ZMFDV) == 4) THEN
    alloc4 (ZMFDV)
ELSE
    STOP 1
ENDIF


IF (KIND (ZMFUV) == 8) THEN
    alloc8 (ZMFUV)
ELSEIF (KIND (ZMFUV) == 4) THEN
    alloc4 (ZMFUV)
ELSE
    STOP 1
ENDIF


IF (KIND (ZMFDU) == 8) THEN
    alloc8 (ZMFDU)
ELSEIF (KIND (ZMFDU) == 4) THEN
    alloc4 (ZMFDU)
ELSE
    STOP 1
ENDIF


IF (KIND (ZMFUU) == 8) THEN
    alloc8 (ZMFUU)
ELSEIF (KIND (ZMFUU) == 4) THEN
    alloc4 (ZMFUU)
ELSE
    STOP 1
ENDIF


IF (KIND (ZDP) == 8) THEN
    alloc8 (ZDP)
ELSEIF (KIND (ZDP) == 4) THEN
    alloc4 (ZDP)
ELSE
    STOP 1
ENDIF


IF (KIND (ZDVDT) == 8) THEN
    alloc8 (ZDVDT)
ELSEIF (KIND (ZDVDT) == 4) THEN
    alloc4 (ZDVDT)
ELSE
    STOP 1
ENDIF


IF (KIND (ZDUDT) == 8) THEN
    alloc8 (ZDUDT)
ELSEIF (KIND (ZDUDT) == 4) THEN
    alloc4 (ZDUDT)
ELSE
    STOP 1
ENDIF


IF (KIND (ZR2) == 8) THEN
    alloc8 (ZR2)
ELSEIF (KIND (ZR2) == 4) THEN
    alloc4 (ZR2)
ELSE
    STOP 1
ENDIF


IF (KIND (ZR1) == 8) THEN
    alloc8 (ZR1)
ELSEIF (KIND (ZR1) == 4) THEN
    alloc4 (ZR1)
ELSE
    STOP 1
ENDIF


IF (KIND (ZB) == 8) THEN
    alloc8 (ZB)
ELSEIF (KIND (ZB) == 4) THEN
    alloc4 (ZB)
ELSE
    STOP 1
ENDIF


IF (KIND (LLCUMBAS) == 8) THEN
    alloc8 (LLCUMBAS)
ELSEIF (KIND (LLCUMBAS) == 4) THEN
    alloc4 (LLCUMBAS)
ELSE
    STOP 1
ENDIF




JLON = KIDIA


ZIMP=1.0_JPRB-YDECUMF%RMFSOLUV
ZTSPHY=1.0_JPRB/PTSPHY
LLPPAR_CUDUV=.FALSE.
LLPERT_CUDUDV=.FALSE.
LLPERT_CUDUDVS=.FALSE.

ZADVW =0.0_JPRB

IF (KTYPE (JLON)==1)  THEN
    ZADVW =YDECUMF%RMFADVW
ENDIF



DO JLEV=1, KLEV

  

  IF (LDCUM (JLON)) THEN
    ZDP (JLON, JLEV)=YDCST%RG/(PAPH (JLON, JLEV+1)-PAPH (JLON, JLEV))
  ENDIF

  
ENDDO


DO JLEV=KTOPM2, KLEV
  IK=JLEV-1

  

  IF (LDCUM (JLON)) THEN
    ZMFUU (JLON, JLEV)=PMFU (JLON, JLEV)*(PUU (JLON, JLEV)-ZIMP*PUEN (JLON, IK))
    ZMFUV (JLON, JLEV)=PMFU (JLON, JLEV)*(PVU (JLON, JLEV)-ZIMP*PVEN (JLON, IK))
    ZMFDU (JLON, JLEV)=PMFD (JLON, JLEV)*(PUD (JLON, JLEV)-ZIMP*PUEN (JLON, IK))
    ZMFDV (JLON, JLEV)=PMFD (JLON, JLEV)*(PVD (JLON, JLEV)-ZIMP*PVEN (JLON, IK))
  ENDIF

  
ENDDO


IF (YDECUMF%RMFSOLUV==0.0_JPRB) THEN

  DO JLEV=KTOPM2, KLEV

    

    IF (LDCUM (JLON).AND.JLEV>KCBOT (JLON)) THEN
      IKB=KCBOT (JLON)
      ZZP=((PAPH (JLON, KLEV+1)-PAPH (JLON, JLEV))/(PAPH (JLON, KLEV+1)-PAPH (JLON, IKB)))

      IF (KTYPE (JLON)==3) THEN
        ZZP=ZZP*ZZP
      ENDIF

      ZMFUU (JLON, JLEV)=ZMFUU (JLON, IKB)*ZZP
      ZMFUV (JLON, JLEV)=ZMFUV (JLON, IKB)*ZZP
      ZMFDU (JLON, JLEV)=ZMFDU (JLON, IKB)*ZZP
      ZMFDV (JLON, JLEV)=ZMFDV (JLON, IKB)*ZZP
    ENDIF

  
  ENDDO

ENDIF


DO JLEV=KTOPM2, KLEV

  IF (JLEV<KLEV) THEN
    IK=JLEV+1

    

    IF (LDCUM (JLON)) THEN
      ZDUDT (JLON, JLEV)=ZDP (JLON, JLEV)*(ZMFUU (JLON, IK)-ZMFUU&
      & (JLON, JLEV)+ZMFDU (JLON, IK)-ZMFDU (JLON, JLEV))
      ZDVDT (JLON, JLEV)=ZDP (JLON, JLEV)*(ZMFUV (JLON, IK)-ZMFUV&
      & (JLON, JLEV)+ZMFDV (JLON, IK)-ZMFDV (JLON, JLEV))
    ENDIF

  
  ELSE

    

    IF (LDCUM (JLON)) THEN
      ZDUDT (JLON, JLEV)=-ZDP (JLON, JLEV)*(ZMFUU (JLON, JLEV)+ZMFDU (JLON, JLEV))
      ZDVDT (JLON, JLEV)=-ZDP (JLON, JLEV)*(ZMFUV (JLON, JLEV)+ZMFDV (JLON, JLEV))
    ENDIF

  
  ENDIF

ENDDO


IF (YDECUMF%RMFSOLUV==0.0_JPRB) THEN

  DO JLEV=KTOPM2, KLEV

    

    IF (LDCUM (JLON)) THEN
      PTENU (JLON, JLEV)=PTENU (JLON, JLEV)+ZDUDT (JLON, JLEV)
      PTENV (JLON, JLEV)=PTENV (JLON, JLEV)+ZDVDT (JLON, JLEV)
    ENDIF

  
  ENDDO

ELSE
  LLCUMBAS (JLON,:)=.FALSE.
  ZB (JLON,:)=1.0_JPRB
  ZMFUU (JLON,:)=0.0_JPRB

  DO JLEV=KTOPM2, KLEV
    IK=JLEV+1
    IM=JLEV-1
    
    LLCUMBAS (JLON, JLEV)=LDCUM (JLON).AND.JLEV>=KCTOP (JLON)-1

    IF (LLCUMBAS (JLON, JLEV)) THEN
      ZZP=YDECUMF%RMFSOLUV*ZDP (JLON, JLEV)*PTSPHY
      ZMFUU (JLON, JLEV)=-ZZP*(PMFU (JLON, JLEV)+PMFD (JLON, JLEV))

      IF (JLEV<KLEV) THEN
        ZB (JLON, JLEV)=1.0_JPRB+ZZP*(PMFU (JLON, IK)+PMFD (JLON, IK))
      ELSE
        ZB (JLON, JLEV)=1.0_JPRB
      ENDIF

      ZZP=YDCST%RG*(PMFUO (JLON, JLEV)+YDECUMF%RMFADVWDD*PMFDO (JLON&
      &, JLEV))/(PAP (JLON, JLEV)-PAP (JLON, IM))*PTSPHY*ZADVW 
      ZU=ZZP*(PUEN (JLON, IM)-PUEN (JLON, JLEV))
      ZV=ZZP*(PVEN (JLON, IM)-PVEN (JLON, JLEV))
      ZDUDT (JLON, JLEV)=(ZDUDT (JLON, JLEV)+PTENU (JLON, JLEV&
      &)*YDECUMF%RMFSOLRHS)*PTSPHY+PUEN (JLON, JLEV)-ZU
      ZDVDT (JLON, JLEV)=(ZDVDT (JLON, JLEV)+PTENV (JLON, JLEV&
      &)*YDECUMF%RMFSOLRHS)*PTSPHY+PVEN (JLON, JLEV)-ZV
    ENDIF

  
  ENDDO

  CALL CUBIDIAG_OPENACC (KIDIA, KFDIA, KLON, KLEV, KCTOP&
  &, LLCUMBAS, ZMFUU, ZB, ZDUDT, ZR1, YDSTACK=YLSTACK)
  CALL CUBIDIAG_OPENACC (KIDIA, KFDIA, KLON, KLEV, KCTOP&
  &, LLCUMBAS, ZMFUU, ZB, ZDVDT, ZR2, YDSTACK=YLSTACK)
  LLPPAR_CUDUV=YDPERTPAR%LPERTPAR.AND.YDPERTPAR%LPERT_CUDUV
  
  LLPERT_CUDUDV=.FALSE.
  LLPERT_CUDUDVS=.FALSE.

  

  IF (LLPERT_CUDUDV.OR.LLPERT_CUDUDVS.OR.LLPPAR_CUDUV) THEN
    ZMDU=1.0_JPRB
    ZMDV=1.0_JPRB
    ZLIMN2=9.0_JPRB*PN1%SDEV**2

    

    IF ((KTYPE (JLON)==1.AND.(LLPERT_CUDUDV.OR.LLPPAR_CUDUV)).OR.(KTYPE&
      & (JLON)==2.AND.(LLPERT_CUDUDVS.OR.LLPPAR_CUDUV))) THEN

      IF (KTYPE (JLON)==1) THEN

        IF (.NOT.LLPPAR_CUDUV) THEN
          ZXU=PGP2DSPP (JLON, IPCUDU)
          ZXV=PGP2DSPP (JLON, IPCUDV)
          ZXU_MAG=PN1%XMAG (1)
          ZXV_MAG=PN1%XMAG (2)
        ELSE
          ZXU=YDPERTPAR%CUDU_MOD
          ZXV=YDPERTPAR%CUDV_MOD
        ENDIF

      ENDIF


      IF (KTYPE (JLON)==2) THEN

        IF (.NOT.LLPPAR_CUDUV) THEN
          ZXU=PGP2DSPP (JLON, IPCUDUS)
          ZXV=PGP2DSPP (JLON, IPCUDVS)
          ZXU_MAG=PN2%XMAG (1)
          ZXV_MAG=PN2%XMAG (2)
        ELSE
          ZXU=YDPERTPAR%CUDU_MOD
          ZXV=YDPERTPAR%CUDV_MOD
        ENDIF

      ENDIF

      ZN2=ZXU**2+ZXV**2

      IF (ZN2>ZLIMN2) THEN
        ZFAC=SQRT (ZLIMN2/ZN2)
        ZXU=ZFAC*ZXU
        ZXV=ZFAC*ZXV
      ENDIF


      IF (.NOT.LLPPAR_CUDUV) THEN
        ZRDU =ZMDU+ZXU_MAG*ZXU
        ZRDV =ZMDV+ZXV_MAG*ZXV
      ELSE
        ZRDU =ZMDU+ZXU
        ZRDV =ZMDV+ZXV
      ENDIF

    ELSE
      ZRDU =ZMDU
      ZRDV =ZMDV
    ENDIF

  
  ENDIF


  DO JLEV=KTOPM2, KLEV

    

    IF (LLCUMBAS (JLON, JLEV)) THEN

      IF ((LLPERT_CUDUDV).OR.(LLPPAR_CUDUV)) THEN
        PTENU (JLON, JLEV)=PTENU (JLON, JLEV)*(1.0_JPRB-YDECUMF%RMFSOLRHS&
        &)+ZRDU *(ZR1 (JLON, JLEV)-PUEN (JLON, JLEV))*ZTSPHY
        PTENV (JLON, JLEV)=PTENV (JLON, JLEV)*(1.0_JPRB-YDECUMF%RMFSOLRHS&
        &)+ZRDV *(ZR2 (JLON, JLEV)-PVEN (JLON, JLEV))*ZTSPHY
      ELSE
        PTENU (JLON, JLEV)=PTENU (JLON, JLEV)*(1.0_JPRB-YDECUMF%RMFSOLRHS&
        &)+(ZR1 (JLON, JLEV)-PUEN (JLON, JLEV))*ZTSPHY
        PTENV (JLON, JLEV)=PTENV (JLON, JLEV)*(1.0_JPRB-YDECUMF%RMFSOLRHS&
        &)+(ZR2 (JLON, JLEV)-PVEN (JLON, JLEV))*ZTSPHY
      ENDIF

    ENDIF

  
  ENDDO

ENDIF



ENDSUBROUTINE CUDUDV_OPENACC

! e56ac8e1f86b1a9cc13b38d73abbf48f96ba2f2a
