
SUBROUTINE CUFLXN_OPENACC (YDTHF, YDCST, YDEPHLI, YDECUMF, KIDIA, KFDIA, KLON, KLEV, PTSPHY, PTEN&
&, PQEN, PQSEN, PTENH, PQENH, PAPH, PAP, PGEOH, LDLAND, LDCUM, LDTDKMF, KCBOT, KCTOP, KDTOP, KTOPM2&
&, KTYPE, LDDRAF, PMFU, PMFD, PMFUS, PMFDS, PMFUQ, PMFDQ, PMFUL, PLUDE, PLUDELI, PLRAIN, PSNDE, PDMFUP&
&, PDMFDP, PDPMEL, PLGLAC, PMFLXR, PMFLXS, PRAIN, PMFUDE_RATE, PMFDDE_RATE, YDSTACK)
!$acc routine (CUFLXN_OPENACC) seq
USE PARKIND1,ONLY:JPIM, JPRB

USE YOMCST,ONLY:TCST
USE YOETHF,ONLY:TTHF
USE YOEPHLI,ONLY:TEPHLI
USE YOECUMF,ONLY:TECUMF
USE ABOR1_ACC_MOD
USE STACK_MOD
#include "stack.h"

IMPLICIT NONE

TYPE (TTHF), INTENT (IN)::YDTHF
TYPE (TCST), INTENT (IN)::YDCST
TYPE (TECUMF), INTENT (IN)::YDECUMF
TYPE (TEPHLI), INTENT (IN)::YDEPHLI
INTEGER (KIND=JPIM), INTENT (IN)::KLON
INTEGER (KIND=JPIM), INTENT (IN)::KLEV
INTEGER (KIND=JPIM), INTENT (IN)::KIDIA
INTEGER (KIND=JPIM), INTENT (IN)::KFDIA
REAL (KIND=JPRB), INTENT (IN)::PTSPHY
REAL (KIND=JPRB), INTENT (IN)::PTEN (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PQEN (KLON, KLEV)
REAL (KIND=JPRB), INTENT (INOUT)::PQSEN (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PTENH (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PQENH (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PAPH (KLON, KLEV+1)
REAL (KIND=JPRB), INTENT (IN)::PAP (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PGEOH (KLON, KLEV+1)
LOGICAL, INTENT (IN)::LDLAND (KLON)
LOGICAL, INTENT (IN)::LDCUM (KLON)
LOGICAL, INTENT (IN)::LDTDKMF
INTEGER (KIND=JPIM), INTENT (IN)::KCBOT (KLON)
INTEGER (KIND=JPIM), INTENT (IN)::KCTOP (KLON)
INTEGER (KIND=JPIM), INTENT (IN)::KDTOP (KLON)
INTEGER (KIND=JPIM), INTENT (OUT)::KTOPM2
INTEGER (KIND=JPIM), INTENT (INOUT)::KTYPE (KLON)
LOGICAL, INTENT (INOUT)::LDDRAF (KLON)
REAL (KIND=JPRB), INTENT (INOUT)::PMFU (KLON, KLEV)
REAL (KIND=JPRB), INTENT (INOUT)::PMFD (KLON, KLEV)
REAL (KIND=JPRB), INTENT (INOUT)::PMFUS (KLON, KLEV)
REAL (KIND=JPRB), INTENT (INOUT)::PMFDS (KLON, KLEV)
REAL (KIND=JPRB), INTENT (INOUT)::PMFUQ (KLON, KLEV)
REAL (KIND=JPRB), INTENT (INOUT)::PMFDQ (KLON, KLEV)
REAL (KIND=JPRB), INTENT (INOUT)::PMFUL (KLON, KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PLUDE (KLON, KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PLUDELI (KLON, KLEV, 2)
REAL (KIND=JPRB), INTENT (IN)::PLRAIN (KLON, KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PSNDE (KLON, KLEV, 2)
REAL (KIND=JPRB), INTENT (INOUT)::PDMFUP (KLON, KLEV)
REAL (KIND=JPRB), INTENT (INOUT)::PDMFDP (KLON, KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PDPMEL (KLON, KLEV)
REAL (KIND=JPRB), INTENT (INOUT)::PLGLAC (KLON, KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PMFLXR (KLON, KLEV+1)
REAL (KIND=JPRB), INTENT (OUT)::PMFLXS (KLON, KLEV+1)
REAL (KIND=JPRB), INTENT (OUT)::PRAIN (KLON)
REAL (KIND=JPRB), INTENT (IN)::PMFUDE_RATE (KLON, KLEV)
REAL (KIND=JPRB), INTENT (INOUT)::PMFDDE_RATE (KLON, KLEV)
TYPE(STACK) :: YDSTACK
TYPE(STACK) :: YLSTACK

REAL (KIND=JPRB)::ZRCUCOV 
REAL (KIND=JPRB)::ZMFS 
REAL (KIND=JPRB)::ZRHEBC 

INTEGER (KIND=JPIM)::JLON
INTEGER (KIND=JPIM)::JLEV
INTEGER (KIND=JPIM)::IKB
INTEGER (KIND=JPIM)::IK
INTEGER (KIND=JPIM)::IDBAS 
LOGICAL::LLDDRAF

REAL (KIND=JPRB)::ZRHM
REAL (KIND=JPRB)::ZMFMAX
REAL (KIND=JPRB)::ZGLAC
REAL (KIND=JPRB)::ZTEN
REAL (KIND=JPRB)::ZWETB
REAL (KIND=JPRB)::ZTWETB
REAL (KIND=JPRB)::ZZP
REAL (KIND=JPRB)::ZTMST
REAL (KIND=JPRB)::ZTARG
REAL (KIND=JPRB)::ZSNMLT
REAL (KIND=JPRB)::ZRNEW
REAL (KIND=JPRB)::ZRMIN
REAL (KIND=JPRB)::ZRFLN
REAL (KIND=JPRB)::ZRFL
REAL (KIND=JPRB)::ZPDS
REAL (KIND=JPRB)::ZPDR
REAL (KIND=JPRB)::ZOELHM
REAL (KIND=JPRB)::ZOEEWM
REAL (KIND=JPRB)::ZOEALFA
REAL (KIND=JPRB)::ZFOEEWL
REAL (KIND=JPRB)::ZFOEEWI
REAL (KIND=JPRB)::ZFAC
REAL (KIND=JPRB)::ZDRFL1
REAL (KIND=JPRB)::ZDRFL
REAL (KIND=JPRB)::ZDENOM
REAL (KIND=JPRB)::ZCONS2
REAL (KIND=JPRB)::ZCONS1A
REAL (KIND=JPRB)::ZCONS1
REAL (KIND=JPRB)::ZALFAW
REAL (KIND=JPRB), PARAMETER::ZTW1=1329.31_JPRB
REAL (KIND=JPRB), PARAMETER::ZTW2=0.0074615_JPRB
REAL (KIND=JPRB), PARAMETER::ZTW3=0.85E5_JPRB
REAL (KIND=JPRB), PARAMETER::ZTW4=40.637_JPRB
REAL (KIND=JPRB), PARAMETER::ZTW5=275.0_JPRB

#include "fcttre.func.h"

YLSTACK = YDSTACK




JLON = KIDIA


ZTMST=PTSPHY
ZCONS1A=YDCST%RCPD/(YDCST%RLMLT*YDCST%RG*YDECUMF%RTAUMEL)
ZCONS2=YDECUMF%RMFCFL/(YDCST%RG*ZTMST)

IF (YDECUMF%LMFWETB) THEN
  ZWETB=1.0_JPRB
ELSE
  ZWETB=0.0_JPRB
ENDIF


IF (YDECUMF%LMFGLAC) THEN
  ZGLAC=0.0_JPRB
ELSE
  ZGLAC=1.0_JPRB
ENDIF


PRAIN (JLON)=0.0_JPRB

IF (.NOT.LDCUM (JLON).OR.KDTOP (JLON)<KCTOP (JLON))  THEN
    LDDRAF (JLON)=.FALSE.
ENDIF


IF (.NOT.LDCUM (JLON))  THEN
    KTYPE (JLON)=0
ENDIF

IDBAS =KLEV

IF (LDLAND (JLON)) THEN
  ZRHEBC =0.75_JPRB

  IF (KTYPE (JLON)==1)  THEN
      ZRHEBC =0.70_JPRB
  ENDIF

ELSE
  ZRHEBC =YDECUMF%RHEBC

  IF (KTYPE (JLON)==1)  THEN
      ZRHEBC =0.85_JPRB
  ENDIF

ENDIF


KTOPM2=2

DO JLEV=KTOPM2, KLEV
  IKB=MIN (JLEV+1, KLEV)
  
  PMFLXR (JLON, JLEV)=0.0_JPRB
  PMFLXS (JLON, JLEV)=0.0_JPRB
  PDPMEL (JLON, JLEV)=0.0_JPRB
  PSNDE (JLON, JLEV, 1)=0.0_JPRB
  PSNDE (JLON, JLEV, 2)=0.0_JPRB

  IF (LDCUM (JLON).AND.JLEV>=KCTOP (JLON)) THEN
    PMFUS (JLON, JLEV)=PMFUS (JLON, JLEV)-PMFU (JLON, JLEV)&
    &*(YDCST%RCPD*PTENH (JLON, JLEV)+PGEOH (JLON, JLEV))
    PMFUQ (JLON, JLEV)=PMFUQ (JLON, JLEV)-PMFU (JLON, JLEV)*PQENH (JLON, JLEV)
    PLGLAC (JLON, JLEV)=PMFU (JLON, JLEV)*PLGLAC (JLON, JLEV)
    LLDDRAF=LDDRAF (JLON).AND.JLEV>=KDTOP (JLON)

    IF (LLDDRAF) THEN
      PMFDS (JLON, JLEV)=PMFDS (JLON, JLEV)-PMFD (JLON, JLEV)&
      &*(YDCST%RCPD*PTENH (JLON, JLEV)+PGEOH (JLON, JLEV))
      PMFDQ (JLON, JLEV)=PMFDQ (JLON, JLEV)-PMFD (JLON, JLEV)*PQENH (JLON, JLEV)
    ELSE
      PMFD (JLON, JLEV)=0.0_JPRB
      PMFDS (JLON, JLEV)=0.0_JPRB
      PMFDQ (JLON, JLEV)=0.0_JPRB
      PDMFDP (JLON, JLEV-1)=0.0_JPRB
    ENDIF


    IF (LLDDRAF.AND.PMFD (JLON, JLEV)<0._JPRB.AND.PMFD (JLON, IKB)==0._JPRB) THEN
      IDBAS =JLEV
    ENDIF

  ELSE
    PMFU (JLON, JLEV)=0.0_JPRB
    PMFD (JLON, JLEV)=0.0_JPRB
    PMFUS (JLON, JLEV)=0.0_JPRB
    PMFDS (JLON, JLEV)=0.0_JPRB
    PMFUQ (JLON, JLEV)=0.0_JPRB
    PMFDQ (JLON, JLEV)=0.0_JPRB
    PMFUL (JLON, JLEV)=0.0_JPRB
    PLGLAC (JLON, JLEV)=0.0_JPRB
    PDMFUP (JLON, JLEV-1)=0.0_JPRB
    PDMFDP (JLON, JLEV-1)=0.0_JPRB
    PLUDE (JLON, JLEV-1)=0.0_JPRB
    PLUDELI (JLON, JLEV-1, 1)=0.0_JPRB
    PLUDELI (JLON, JLEV-1, 2)=0.0_JPRB
  ENDIF

  
ENDDO

PMFLXR (JLON, KLEV+1)=0.0_JPRB
PMFLXS (JLON, KLEV+1)=0.0_JPRB
PMFLXR (JLON, 1)=0.0_JPRB
PMFLXS (JLON, 1)=0.0_JPRB
PSNDE (JLON, 1, 1)=0.0_JPRB
PSNDE (JLON, 1, 2)=0.0_JPRB


IF (LDCUM (JLON)) THEN
  IKB=KCBOT (JLON)
  IK=IKB+1
  ZZP=((PAPH (JLON, KLEV+1)-PAPH (JLON, IK))/(PAPH (JLON, KLEV+1)-PAPH (JLON, IKB)))

  IF (KTYPE (JLON)==3)  THEN
      ZZP=ZZP*ZZP
  ENDIF

  PMFU (JLON, IK)=PMFU (JLON, IKB)*ZZP

  IF (YDEPHLI%LPHYLIN) THEN
    ZTARG=PTENH (JLON, IKB)
    ZOEALFA=MIN (1.0_JPRB, 0.545_JPRB*(TANH (0.17_JPRB*(ZTARG-YDEPHLI%RLPTRC))+1.0_JPRB))
    ZOELHM=ZOEALFA*YDCST%RLVTT+(1.0_JPRB-ZOEALFA)*YDCST%RLSTT
    PMFUS (JLON, IK)=(PMFUS (JLON, IKB)-ZOELHM*PMFUL (JLON, IKB))*ZZP
  ELSE
    PMFUS (JLON, IK)=(PMFUS (JLON, IKB)-FOELHMCU (PTENH (JLON, IKB))*PMFUL (JLON, IKB))*ZZP
  ENDIF

  PMFUQ (JLON, IK)=(PMFUQ (JLON, IKB)+PMFUL (JLON, IKB))*ZZP
  PMFUL (JLON, IK)=0.0_JPRB
ENDIF



DO JLEV=KTOPM2, KLEV

  

  IF (LDCUM (JLON).AND.JLEV>KCBOT (JLON)+1) THEN
    IKB=KCBOT (JLON)+1
    ZZP=((PAPH (JLON, KLEV+1)-PAPH (JLON, JLEV))/(PAPH (JLON, KLEV+1)-PAPH (JLON, IKB)))

    IF (KTYPE (JLON)==3)  THEN
        ZZP=ZZP*ZZP
    ENDIF

    PMFU (JLON, JLEV)=PMFU (JLON, IKB)*ZZP
    PMFUS (JLON, JLEV)=PMFUS (JLON, IKB)*ZZP
    PMFUQ (JLON, JLEV)=PMFUQ (JLON, IKB)*ZZP
    PMFUL (JLON, JLEV)=0.0_JPRB
  ENDIF

  IK=IDBAS 
  LLDDRAF=LDDRAF (JLON).AND.JLEV>IK.AND.IK<KLEV

  IF (LLDDRAF.AND.IK==KCBOT (JLON)+1) THEN
    ZZP=((PAPH (JLON, KLEV+1)-PAPH (JLON, JLEV))/(PAPH (JLON, KLEV+1)-PAPH (JLON, IK)))

    IF (KTYPE (JLON)==3)  THEN
        ZZP=ZZP*ZZP
    ENDIF

    PMFD (JLON, JLEV)=PMFD (JLON, IK)*ZZP
    PMFDS (JLON, JLEV)=PMFDS (JLON, IK)*ZZP
    PMFDQ (JLON, JLEV)=PMFDQ (JLON, IK)*ZZP
    PMFDDE_RATE (JLON, JLEV)=-(PMFD (JLON, JLEV-1)-PMFD (JLON, JLEV))
  ELSEIF (LLDDRAF.AND.IK/=KCBOT (JLON)+1.AND.JLEV==IK+1) THEN
    PMFDDE_RATE (JLON, JLEV)=-(PMFD (JLON, JLEV-1)-PMFD (JLON, JLEV))
  ENDIF

  
ENDDO

ZMFS =1.0_JPRB

DO JLEV=2, KLEV

  

  IF (LDDRAF (JLON).AND.JLEV>=KDTOP (JLON)-1) THEN
    ZMFMAX=ABS (PMFU (JLON, JLEV))*0.98_JPRB

    IF (PMFD (JLON, JLEV)+ZMFMAX+1.E-15_JPRB<0.0_JPRB) THEN
      ZMFS =MIN (ZMFS ,-ZMFMAX/PMFD (JLON, JLEV))
    ENDIF

  ENDIF

  
ENDDO


DO JLEV=2, KLEV

  

  IF (ZMFS <1.0_JPRB.AND.JLEV>=KDTOP (JLON)-1) THEN
    PMFD (JLON, JLEV)=PMFD (JLON, JLEV)*ZMFS 
    PMFDS (JLON, JLEV)=PMFDS (JLON, JLEV)*ZMFS 
    PMFDQ (JLON, JLEV)=PMFDQ (JLON, JLEV)*ZMFS 
    PMFDDE_RATE (JLON, JLEV)=PMFDDE_RATE (JLON, JLEV)*ZMFS 
    PDMFDP (JLON, JLEV)=PDMFDP (JLON, JLEV)*ZMFS 
  ENDIF

  
ENDDO


DO JLEV=KTOPM2, KLEV

  

  IF (LDCUM (JLON).AND.JLEV>=KCTOP (JLON)-1) THEN
    PRAIN (JLON)=PRAIN (JLON)+PDMFUP (JLON, JLEV)
    ZTWETB=PTEN (JLON, JLEV)-MAX (0.0_JPRB, PQSEN (JLON, JLEV)-PQEN (JLON, JLEV&
    &))*(ZTW1+ZTW2*(PAP (JLON, JLEV)-ZTW3)-ZTW4*(PTEN (JLON, JLEV)-ZTW5))
    ZTEN=ZTWETB*ZWETB+(1.0_JPRB-ZWETB)*PTEN (JLON, JLEV)

    IF (PMFLXS (JLON, JLEV)>0.0_JPRB.AND.ZTEN>YDCST%RTT) THEN
      ZCONS1=ZCONS1A*(1.0_JPRB+0.5_JPRB*(ZTEN-YDCST%RTT))
      ZFAC=ZCONS1*(PAPH (JLON, JLEV+1)-PAPH (JLON, JLEV))
      ZSNMLT=MIN (PMFLXS (JLON, JLEV), ZFAC*(ZTEN-YDCST%RTT))
      PDPMEL (JLON, JLEV)=ZSNMLT

      IF (YDEPHLI%LPHYLIN) THEN
        ZTARG=ZTEN-ZSNMLT/ZFAC
        ZOEALFA=MIN (1.0_JPRB, 0.545_JPRB*(TANH (0.17_JPRB*(ZTARG-YDEPHLI%RLPTRC))+1.0_JPRB))
        ZFOEEWL=YDTHF%R2ES*EXP (YDTHF%R3LES*(ZTARG-YDCST%RTT)/(ZTARG-YDTHF%R4LES))
        ZFOEEWI=YDTHF%R2ES*EXP (YDTHF%R3IES*(ZTARG-YDCST%RTT)/(ZTARG-YDTHF%R4IES))
        ZOEEWM=ZOEALFA*ZFOEEWL+(1.0_JPRB-ZOEALFA)*ZFOEEWI
        PQSEN (JLON, JLEV)=ZOEEWM/PAP (JLON, JLEV)
      ELSE
        PQSEN (JLON, JLEV)=FOEEWMCU (ZTEN-ZSNMLT/ZFAC)/PAP (JLON, JLEV)
      ENDIF

    ENDIF


    IF (YDEPHLI%LPHYLIN) THEN
      ZALFAW=MIN (1.0_JPRB, 0.545_JPRB*(TANH (0.17_JPRB*(ZTEN-YDEPHLI%RLPTRC))+1.0_JPRB))
    ELSE
      ZALFAW=FOEALFCU (ZTEN)
    ENDIF


    IF (PTEN (JLON, JLEV)<=YDCST%RTT.AND.ZALFAW>0.0_JPRB) THEN
      PLGLAC (JLON, JLEV)=PLGLAC (JLON, JLEV)+ZGLAC*ZALFAW*PDMFUP (JLON, JLEV)+ZALFAW*PDMFDP (JLON, JLEV)
      ZALFAW=0.0_JPRB
    ENDIF


    IF (YDECUMF%LMFDSNOW.AND.JLEV<=KCBOT (JLON)) THEN
      PSNDE (JLON, JLEV, 2)=PLRAIN (JLON, JLEV+1)*PMFUDE_RATE (JLON, JLEV)
      PSNDE (JLON, JLEV, 1)=PSNDE (JLON, JLEV, 2)*ZALFAW
      PSNDE (JLON, JLEV, 2)=PSNDE (JLON, JLEV, 2)*(1.0_JPRB-ZALFAW)
      PSNDE (JLON, JLEV, 1)=MIN (PSNDE (JLON, JLEV, 1), ZALFAW*(PDMFUP (JLON, JLEV)+PDMFDP (JLON, JLEV)))
      PSNDE (JLON, JLEV, 2)=MIN (PSNDE (JLON, JLEV, 2),(1.0_JPRB-ZALFAW)&
      &*(PDMFUP (JLON, JLEV)+PDMFDP (JLON, JLEV))-PDPMEL (JLON, JLEV))
      PSNDE (JLON, JLEV, 1)=MAX (PSNDE (JLON, JLEV, 1), 0.0_JPRB)
      PSNDE (JLON, JLEV, 2)=MAX (PSNDE (JLON, JLEV, 2), 0.0_JPRB)
    ENDIF

    PMFLXR (JLON, JLEV+1)=PMFLXR (JLON, JLEV)+ZALFAW*(PDMFUP (JLON, JLEV&
    &)+PDMFDP (JLON, JLEV))+PDPMEL (JLON, JLEV)-PSNDE (JLON, JLEV, 1)
    PMFLXS (JLON, JLEV+1)=PMFLXS (JLON, JLEV)+(1.0_JPRB-ZALFAW)*(PDMFUP (JLON&
    &, JLEV)+PDMFDP (JLON, JLEV))-PDPMEL (JLON, JLEV)-PSNDE (JLON, JLEV, 2)

    IF (PMFLXR (JLON, JLEV+1)+PMFLXS (JLON, JLEV+1)<0.0_JPRB) THEN
      PDMFDP (JLON, JLEV)=-(PMFLXR (JLON, JLEV)+PMFLXS (JLON, JLEV)+PDMFUP (JLON, JLEV))
      PMFLXR (JLON, JLEV+1)=0.0_JPRB
      PMFLXS (JLON, JLEV+1)=0.0_JPRB
      PDPMEL (JLON, JLEV)=0.0_JPRB
    ELSEIF (PMFLXR (JLON, JLEV+1)<0.0_JPRB) THEN
      PMFLXS (JLON, JLEV+1)=PMFLXS (JLON, JLEV+1)+PMFLXR (JLON, JLEV+1)
      PMFLXR (JLON, JLEV+1)=0.0_JPRB
    ELSEIF (PMFLXS (JLON, JLEV+1)<0.0_JPRB) THEN
      PMFLXR (JLON, JLEV+1)=PMFLXR (JLON, JLEV+1)+PMFLXS (JLON, JLEV+1)
      PMFLXS (JLON, JLEV+1)=0.0_JPRB
    ENDIF

  ENDIF

  
ENDDO


IF (.NOT.LDTDKMF) THEN

  

  IF (KTYPE (JLON)>=2) THEN
    IKB=KCBOT (JLON)
    IK=KCTOP (JLON)
    ZRHM=0.5*(PQEN (JLON, IKB)/PQSEN (JLON, IKB)+PQEN (JLON, IK)/PQSEN (JLON, IK))
    ZRCUCOV =YDECUMF%RCUCOV*(1.0_JPRB+(MAX (0.8_JPRB, ZRHM)-0.8_JPRB)/0.025_JPRB)
  ELSE
    ZRCUCOV =YDECUMF%RCUCOV*0.6
  ENDIF

  
ELSE
  
  ZRCUCOV =YDECUMF%RCUCOV
  
ENDIF


DO JLEV=KTOPM2, KLEV

  

  IF (LDCUM (JLON).AND.JLEV>=KCBOT (JLON)) THEN
    ZRFL=PMFLXR (JLON, JLEV)+PMFLXS (JLON, JLEV)

    IF (ZRFL>1.E-12_JPRB) THEN
      ZDRFL1=YDECUMF%RCPECONS*MAX (0.0_JPRB, PQSEN (JLON, JLEV)-PQEN (JLON, JLEV&
      &))*ZRCUCOV *(SQRT (PAPH (JLON, JLEV)/PAPH (JLON, KLEV+1))/YDECUMF%RCVRFACTOR&
      &*ZRFL/ZRCUCOV )**0.5777_JPRB*(PAPH (JLON, JLEV+1)-PAPH (JLON, JLEV))
      ZRNEW=ZRFL-ZDRFL1
      ZRMIN=ZRFL-ZRCUCOV *MAX (0.0_JPRB, ZRHEBC *PQSEN (JLON, JLEV)-PQEN&
      & (JLON, JLEV))*ZCONS2*(PAPH (JLON, JLEV+1)-PAPH (JLON, JLEV))
      ZRNEW=MAX (ZRNEW, ZRMIN)
      ZRFLN=MAX (ZRNEW, 0.0_JPRB)
      ZDRFL=MIN (0.0_JPRB, ZRFLN-ZRFL)

      IF (YDEPHLI%LPHYLIN) THEN
        ZALFAW=MIN (1.0_JPRB, 0.545_JPRB*(TANH (0.17_JPRB*(PTEN (JLON, JLEV)-YDEPHLI%RLPTRC))+1.0_JPRB))
      ELSE
        ZALFAW=FOEALFCU (PTEN (JLON, JLEV))
      ENDIF


      IF (PTEN (JLON, JLEV)<YDCST%RTT)  THEN
          ZALFAW=0.0_JPRB
      ENDIF

      ZPDR=ZALFAW*PDMFDP (JLON, JLEV)
      ZPDS=(1.0_JPRB-ZALFAW)*PDMFDP (JLON, JLEV)
      ZDENOM=1.0_JPRB/MAX (1.E-12_JPRB, PMFLXR (JLON, JLEV)+PMFLXS (JLON, JLEV))
      PMFLXR (JLON, JLEV+1)=PMFLXR (JLON, JLEV)+ZPDR+PDPMEL (JLON, JLEV)+ZDRFL*PMFLXR (JLON, JLEV)*ZDENOM
      PMFLXS (JLON, JLEV+1)=PMFLXS (JLON, JLEV)+ZPDS-PDPMEL (JLON, JLEV)+ZDRFL*PMFLXS (JLON, JLEV)*ZDENOM
      PDMFUP (JLON, JLEV)=PDMFUP (JLON, JLEV)+ZDRFL

      IF (PMFLXR (JLON, JLEV+1)+PMFLXS (JLON, JLEV+1)<0.0_JPRB) THEN
        PDMFUP (JLON, JLEV)=PDMFUP (JLON, JLEV)-(PMFLXR (JLON, JLEV+1)+PMFLXS (JLON, JLEV+1))
        PMFLXR (JLON, JLEV+1)=0.0_JPRB
        PMFLXS (JLON, JLEV+1)=0.0_JPRB
        PDPMEL (JLON, JLEV)=0.0_JPRB
      ELSEIF (PMFLXR (JLON, JLEV+1)<0.0_JPRB) THEN
        PMFLXS (JLON, JLEV+1)=PMFLXS (JLON, JLEV+1)+PMFLXR (JLON, JLEV+1)
        PMFLXR (JLON, JLEV+1)=0.0_JPRB
      ELSEIF (PMFLXS (JLON, JLEV+1)<0.0_JPRB) THEN
        PMFLXR (JLON, JLEV+1)=PMFLXR (JLON, JLEV+1)+PMFLXS (JLON, JLEV+1)
        PMFLXS (JLON, JLEV+1)=0.0_JPRB
      ENDIF

    ELSE
      PMFLXR (JLON, JLEV+1)=0.0_JPRB
      PMFLXS (JLON, JLEV+1)=0.0_JPRB
      PDMFDP (JLON, JLEV)=0.0_JPRB
      PDPMEL (JLON, JLEV)=0.0_JPRB
    ENDIF

  ENDIF

  
ENDDO



ENDSUBROUTINE CUFLXN_OPENACC

! e56ac8e1f86b1a9cc13b38d73abbf48f96ba2f2a
