SUBROUTINE CUMASTRN_OPENACC (PPLDARE, PPLRG, YDTHF, YDCST, YDML_PHY_SLIN, YDML_PHY_EC, YGFL, YDCHEM&
&, YDSPP_CONFIG, YDPERTPAR, KIDIA, KFDIA, KLON, KLEV, PDX, LDTDKMF, LDMCAPEA, LDLAND, PTSPHY, PTEN&
&, PQEN, PUEN, PVEN, PLITOT, PVERVEL, PQSEN, PQHFL, PAHFS, PAP, PAPH, PGEO, PGEOH, PGAW, PCUCONVCA&
&, PGP2DSPP, PTENT, PTENQ, PTENU, PTENV, PTENTA, PTENQA, LDCUM, KTYPE, KCBOT, KCTOP, LDCUM_LIG,&
& KCBOT_LIG, KCTOP_LIG, KBOTSC, LDSC, LDSHCV, PLCRIT_AER, PTU, PQU, PLU, PLUDE, PLUDELI, PSNDE,&
& PENTH, PMFLXR, PMFLXS, PRAIN, PLRAIN, PRSUD, PMFU, PMFD, PLGLAC, PMFUDE_RATE, PMFDDE_RATE, PCAPE&
&, PWU, PWMEAN, PVDISCU, PDISS, KTRAC, PCEN, PTENC, PSCAV, PSCAV0, YDSTACK)
!$acc routine (CUMASTRN_OPENACC) seq
USE MODEL_PHYSICS_ECMWF_MOD,ONLY:MODEL_PHYSICS_ECMWF_TYPE
USE MODEL_PHYSICS_SIMPLINEAR_MOD,ONLY:MODEL_PHYSICS_SIMPLINEAR_TYPE
USE YOM_YGFL,ONLY:TYPE_GFLD
USE YOMCHEM,ONLY:TCHEM
USE PARKIND1,ONLY:JPIM, JPRB

USE YOMCST,ONLY:TCST
USE YOETHF,ONLY:TTHF
USE SPP_MOD,ONLY:TSPP_CONFIG
USE SPP_GEN_MOD,ONLY:SPP_PERT
USE YOMPERTPAR,ONLY:TPERTPAR
USE ABOR1_ACC_MOD
USE STACK_MOD
#include "stack.h"

IMPLICIT NONE

REAL (KIND=JPRB), INTENT (IN)::PPLDARE
REAL (KIND=JPRB), INTENT (IN)::PPLRG
TYPE (TTHF), INTENT (IN)::YDTHF
TYPE (TCST), INTENT (IN)::YDCST
TYPE (MODEL_PHYSICS_ECMWF_TYPE), INTENT (IN)::YDML_PHY_EC
TYPE (TCHEM), INTENT (IN)::YDCHEM
TYPE (TSPP_CONFIG), INTENT (IN)::YDSPP_CONFIG
TYPE (TPERTPAR), INTENT (IN)::YDPERTPAR
TYPE (MODEL_PHYSICS_SIMPLINEAR_TYPE), INTENT (IN)::YDML_PHY_SLIN
TYPE (TYPE_GFLD), INTENT (IN)::YGFL
INTEGER (KIND=JPIM), INTENT (IN)::KLON
INTEGER (KIND=JPIM), INTENT (IN)::KLEV
INTEGER (KIND=JPIM), INTENT (IN)::KIDIA
INTEGER (KIND=JPIM), INTENT (IN)::KFDIA
INTEGER (KIND=JPIM), INTENT (IN)::KTRAC
LOGICAL, INTENT (IN)::LDMCAPEA
LOGICAL, INTENT (IN)::LDLAND (KLON)
REAL (KIND=JPRB), INTENT (IN)::PTSPHY
REAL (KIND=JPRB), INTENT (IN)::PLCRIT_AER (KLON, KLEV)
REAL (KIND=JPRB), INTENT (INOUT)::PTEN (KLON, KLEV)
REAL (KIND=JPRB), INTENT (INOUT)::PQEN (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PUEN (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PVEN (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PLITOT (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PVERVEL (KLON, KLEV)
REAL (KIND=JPRB), INTENT (INOUT)::PQSEN (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PQHFL (KLON, KLEV+1)
REAL (KIND=JPRB), INTENT (IN)::PAHFS (KLON, KLEV+1)
REAL (KIND=JPRB), INTENT (IN)::PAP (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PAPH (KLON, KLEV+1)
REAL (KIND=JPRB), INTENT (IN)::PGEO (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PGEOH (KLON, KLEV+1)
REAL (KIND=JPRB), INTENT (IN)::PGAW (KLON)
REAL (KIND=JPRB), INTENT (IN)::PCUCONVCA (KLON)
REAL (KIND=JPRB), INTENT (IN)::PGP2DSPP (KLON, YDSPP_CONFIG%SM%NRFTOTAL)
REAL (KIND=JPRB), INTENT (IN)::PCEN (KLON, KLEV, KTRAC)
REAL (KIND=JPRB), INTENT (IN)::PSCAV (KTRAC)
REAL (KIND=JPRB), INTENT (IN)::PSCAV0 (KTRAC)
TYPE(STACK) :: YDSTACK
TYPE(STACK) :: YLSTACK
REAL (KIND=JPRB), INTENT (IN)::PDX (KLON)
LOGICAL, INTENT (IN)::LDTDKMF
REAL (KIND=JPRB), INTENT (INOUT)::PTENT (KLON, KLEV)
REAL (KIND=JPRB), INTENT (INOUT)::PTENQ (KLON, KLEV)
REAL (KIND=JPRB), INTENT (INOUT)::PTENU (KLON, KLEV)
REAL (KIND=JPRB), INTENT (INOUT)::PTENV (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PTENTA (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PTENQA (KLON, KLEV)
REAL (KIND=JPRB), INTENT (INOUT)::PTENC (KLON, KLEV, KTRAC)
LOGICAL, INTENT (OUT)::LDCUM (KLON)
INTEGER (KIND=JPIM), INTENT (OUT)::KTYPE (KLON)
INTEGER (KIND=JPIM), INTENT (OUT)::KCBOT (KLON)
INTEGER (KIND=JPIM), INTENT (OUT)::KCTOP (KLON)
LOGICAL, INTENT (OUT)::LDCUM_LIG (KLON)
INTEGER (KIND=JPIM), INTENT (OUT)::KCBOT_LIG (KLON)
INTEGER (KIND=JPIM), INTENT (OUT)::KCTOP_LIG (KLON)
INTEGER (KIND=JPIM), INTENT (OUT)::KBOTSC (KLON)
LOGICAL, INTENT (OUT)::LDSC (KLON)
LOGICAL, INTENT (IN)::LDSHCV (KLON)
REAL (KIND=JPRB), INTENT (OUT)::PTU (KLON, KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PQU (KLON, KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PLU (KLON, KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PLUDE (KLON, KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PLUDELI (KLON, KLEV, 4)
REAL (KIND=JPRB), INTENT (OUT)::PSNDE (KLON, KLEV, 2)
REAL (KIND=JPRB), INTENT (OUT)::PENTH (KLON, KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PMFLXR (KLON, KLEV+1)
REAL (KIND=JPRB), INTENT (OUT)::PMFLXS (KLON, KLEV+1)
REAL (KIND=JPRB), INTENT (OUT)::PRAIN (KLON)
REAL (KIND=JPRB), INTENT (OUT)::PLRAIN (KLON, KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PRSUD (KLON, KLEV, 2)
REAL (KIND=JPRB), INTENT (OUT)::PMFU (KLON, KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PMFD (KLON, KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PLGLAC (KLON, KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PMFUDE_RATE (KLON, KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PMFDDE_RATE (KLON, KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PCAPE (KLON)
REAL (KIND=JPRB), INTENT (OUT)::PWMEAN (KLON)
REAL (KIND=JPRB), INTENT (OUT)::PVDISCU (KLON)
REAL (KIND=JPRB), INTENT (OUT)::PWU (KLON, KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PDISS (KLON, KLEV)

temp (REAL (KIND=JPRB), ZKINED, (KLON, KLEV))
temp (REAL (KIND=JPRB), ZKINEU, (KLON, KLEV))
temp (REAL (KIND=JPRB), ZVD, (KLON, KLEV))
temp (REAL (KIND=JPRB), ZUD, (KLON, KLEV))
temp (REAL (KIND=JPRB), ZVU, (KLON, KLEV))
temp (REAL (KIND=JPRB), ZUU, (KLON, KLEV))
temp (REAL (KIND=JPRB), ZRFL, (KLON))
temp (REAL (KIND=JPRB), ZMFUL, (KLON, KLEV))
temp (REAL (KIND=JPRB), ZDMFDP, (KLON, KLEV))
temp (REAL (KIND=JPRB), ZDMFUP, (KLON, KLEV))
temp (REAL (KIND=JPRB), ZMFDQ, (KLON, KLEV))
temp (REAL (KIND=JPRB), ZMFUQ, (KLON, KLEV))
temp (REAL (KIND=JPRB), ZMFDS, (KLON, KLEV))
temp (REAL (KIND=JPRB), ZMFUS, (KLON, KLEV))
temp (REAL (KIND=JPRB), ZQD, (KLON, KLEV))
temp (REAL (KIND=JPRB), ZTD, (KLON, KLEV))
temp (REAL (KIND=JPRB), ZQSENH, (KLON, KLEV))
temp (REAL (KIND=JPRB), ZQENH2, (KLON, KLEV))
temp (REAL (KIND=JPRB), ZTENH2, (KLON, KLEV))
temp (REAL (KIND=JPRB), ZQENH, (KLON, KLEV))
temp (REAL (KIND=JPRB), ZTENH, (KLON, KLEV))

REAL (KIND=JPRB)::ZSATFR 
REAL (KIND=JPRB)::ZMFCFL 
REAL (KIND=JPRB)::ZFACCA 
REAL (KIND=JPRB)::ZDQCV 
REAL (KIND=JPRB)::ZKHFL 
REAL (KIND=JPRB)::ZKHVFL 
REAL (KIND=JPRB)::ZMFUB1 
temp (REAL (KIND=JPRB), ZMFUB, (KLON))
temp (REAL (KIND=JPRB), ZDPMEL, (KLON, KLEV))

temp (REAL (KIND=JPRB), ZWUBASE, (KLON))
REAL (KIND=JPRB)::ZDHPBL 

REAL (KIND=JPRB)::ZDX 
temp (REAL (KIND=JPRB), ZDMFDE, (KLON, KLEV))
temp (REAL (KIND=JPRB), ZDMFEN, (KLON, KLEV))

temp (INTEGER (KIND=JPIM), ICTOP0, (KLON))
temp (INTEGER (KIND=JPIM), IDTOP, (KLON))
temp (INTEGER (KIND=JPIM), ILAB, (KLON, KLEV))
temp (INTEGER (KIND=JPIM), IDPL, (KLON))

REAL (KIND=JPRB)::ZCAPDCYCLSE 
REAL (KIND=JPRB)::ZCAPDCYCLLD 
REAL (KIND=JPRB)::ZCAPDCYCL 
REAL (KIND=JPRB)::ZCAPPBL 
REAL (KIND=JPRB)::ZHEAT 
REAL (KIND=JPRB)::ZCAPE2 
REAL (KIND=JPRB)::ZCAPE 

temp (LOGICAL, LLSCVFLAG, (KLON))
temp (LOGICAL, LLDCUM, (KLON))
temp (LOGICAL, LLDDRAF3, (KLON))
temp (LOGICAL, LLDDRAF, (KLON))

LOGICAL::LLO3
LOGICAL::LLMIXS
LOGICAL::LLO2 
LOGICAL::LLO1

INTEGER (KIND=JPIM)::JLON
INTEGER (KIND=JPIM)::IK
INTEGER (KIND=JPIM)::JLEV
INTEGER (KIND=JPIM)::ITOPM2
INTEGER (KIND=JPIM)::IKD
INTEGER (KIND=JPIM)::IKB

REAL (KIND=JPRB)::ZIND
REAL (KIND=JPRB)::ZRG
REAL (KIND=JPRB)::ZAK
REAL (KIND=JPRB)::ZBS
REAL (KIND=JPRB)::ZBR
REAL (KIND=JPRB)::ZAS
REAL (KIND=JPRB)::ZAR
REAL (KIND=JPRB)::ZTAURES
REAL (KIND=JPRB)::ZTDIS
REAL (KIND=JPRB)::ZDVTEN
REAL (KIND=JPRB)::ZDUTEN
REAL (KIND=JPRB)::ZRDOCPD
REAL (KIND=JPRB)::ZORCPD
REAL (KIND=JPRB)::ZDERATE
REAL (KIND=JPRB)::ZERATE
REAL (KIND=JPRB)::ZMFA
REAL (KIND=JPRB)::ZRO
REAL (KIND=JPRB)::ZQUMQE
REAL (KIND=JPRB)::ZPBMPT
REAL (KIND=JPRB)::ZMFMAX
REAL (KIND=JPRB)::ZFAC
REAL (KIND=JPRB)::ZEPS
REAL (KIND=JPRB)::ZDZ
REAL (KIND=JPRB)::ZDQMIN
REAL (KIND=JPRB)::ZDH2
REAL (KIND=JPRB)::ZDH
REAL (KIND=JPRB)::ZCONS
REAL (KIND=JPRB)::ZCONS2

REAL (KIND=JPRB)::ZTAUPBL 
REAL (KIND=JPRB)::ZTAU 
REAL (KIND=JPRB)::ZXTAU 
LOGICAL::LLPERT_RTAU
INTEGER (KIND=JPIM)::IPRTAU
INTEGER (KIND=JPIM)::IPN
TYPE (SPP_PERT)::PN1

REAL (KIND=JPRB)::ZSUM22 
REAL (KIND=JPRB)::ZSUM12 
temp (REAL (KIND=JPRB), ZUV2, (KLON, KLEV))
temp (REAL (KIND=JPRB), ZDMFDPC, (KLON, KLEV))
temp (REAL (KIND=JPRB), ZDMFUPC, (KLON, KLEV))
temp (REAL (KIND=JPRB), ZKMFL, (KLON))
REAL (KIND=JPRB)::ZMF_SHAL 
REAL (KIND=JPRB)::ZMFUVB 
REAL (KIND=JPRB)::ZMFUUB 
temp (REAL (KIND=JPRB), ZTENV, (KLON, KLEV))
temp (REAL (KIND=JPRB), ZTENU, (KLON, KLEV))
temp (REAL (KIND=JPRB), ZMFDDR, (KLON, KLEV))
temp (REAL (KIND=JPRB), ZMFUDR, (KLON, KLEV))
temp (REAL (KIND=JPRB), ZMFDUS, (KLON, KLEV))
temp (REAL (KIND=JPRB), ZMFUUS, (KLON, KLEV))
REAL (KIND=JPRB)::ZMFS 

#include "cuascn_openacc.intfb.h"
#include "cubasen_openacc.intfb.h"
#include "cuddrafn_openacc.intfb.h"
#include "cudlfsn_openacc.intfb.h"
#include "cudtdqn_openacc.intfb.h"
#include "cududv_openacc.intfb.h"
#include "cuflxn_openacc.intfb.h"
#include "cuinin_openacc.intfb.h"
#include "cuctracer_openacc.intfb.h"
#include "fcttre.func.h"

YLSTACK = YDSTACK


IF (KIND (ZKINED) == 8) THEN
    alloc8 (ZKINED)
ELSEIF (KIND (ZKINED) == 4) THEN
    alloc4 (ZKINED)
ELSE
    STOP 1
ENDIF


IF (KIND (ZKINEU) == 8) THEN
    alloc8 (ZKINEU)
ELSEIF (KIND (ZKINEU) == 4) THEN
    alloc4 (ZKINEU)
ELSE
    STOP 1
ENDIF


IF (KIND (ZVD) == 8) THEN
    alloc8 (ZVD)
ELSEIF (KIND (ZVD) == 4) THEN
    alloc4 (ZVD)
ELSE
    STOP 1
ENDIF


IF (KIND (ZUD) == 8) THEN
    alloc8 (ZUD)
ELSEIF (KIND (ZUD) == 4) THEN
    alloc4 (ZUD)
ELSE
    STOP 1
ENDIF


IF (KIND (ZVU) == 8) THEN
    alloc8 (ZVU)
ELSEIF (KIND (ZVU) == 4) THEN
    alloc4 (ZVU)
ELSE
    STOP 1
ENDIF


IF (KIND (ZUU) == 8) THEN
    alloc8 (ZUU)
ELSEIF (KIND (ZUU) == 4) THEN
    alloc4 (ZUU)
ELSE
    STOP 1
ENDIF


IF (KIND (ZRFL) == 8) THEN
    alloc8 (ZRFL)
ELSEIF (KIND (ZRFL) == 4) THEN
    alloc4 (ZRFL)
ELSE
    STOP 1
ENDIF


IF (KIND (ZMFUL) == 8) THEN
    alloc8 (ZMFUL)
ELSEIF (KIND (ZMFUL) == 4) THEN
    alloc4 (ZMFUL)
ELSE
    STOP 1
ENDIF


IF (KIND (ZDMFDP) == 8) THEN
    alloc8 (ZDMFDP)
ELSEIF (KIND (ZDMFDP) == 4) THEN
    alloc4 (ZDMFDP)
ELSE
    STOP 1
ENDIF


IF (KIND (ZDMFUP) == 8) THEN
    alloc8 (ZDMFUP)
ELSEIF (KIND (ZDMFUP) == 4) THEN
    alloc4 (ZDMFUP)
ELSE
    STOP 1
ENDIF


IF (KIND (ZMFDQ) == 8) THEN
    alloc8 (ZMFDQ)
ELSEIF (KIND (ZMFDQ) == 4) THEN
    alloc4 (ZMFDQ)
ELSE
    STOP 1
ENDIF


IF (KIND (ZMFUQ) == 8) THEN
    alloc8 (ZMFUQ)
ELSEIF (KIND (ZMFUQ) == 4) THEN
    alloc4 (ZMFUQ)
ELSE
    STOP 1
ENDIF


IF (KIND (ZMFDS) == 8) THEN
    alloc8 (ZMFDS)
ELSEIF (KIND (ZMFDS) == 4) THEN
    alloc4 (ZMFDS)
ELSE
    STOP 1
ENDIF


IF (KIND (ZMFUS) == 8) THEN
    alloc8 (ZMFUS)
ELSEIF (KIND (ZMFUS) == 4) THEN
    alloc4 (ZMFUS)
ELSE
    STOP 1
ENDIF


IF (KIND (ZQD) == 8) THEN
    alloc8 (ZQD)
ELSEIF (KIND (ZQD) == 4) THEN
    alloc4 (ZQD)
ELSE
    STOP 1
ENDIF


IF (KIND (ZTD) == 8) THEN
    alloc8 (ZTD)
ELSEIF (KIND (ZTD) == 4) THEN
    alloc4 (ZTD)
ELSE
    STOP 1
ENDIF


IF (KIND (ZQSENH) == 8) THEN
    alloc8 (ZQSENH)
ELSEIF (KIND (ZQSENH) == 4) THEN
    alloc4 (ZQSENH)
ELSE
    STOP 1
ENDIF


IF (KIND (ZQENH2) == 8) THEN
    alloc8 (ZQENH2)
ELSEIF (KIND (ZQENH2) == 4) THEN
    alloc4 (ZQENH2)
ELSE
    STOP 1
ENDIF


IF (KIND (ZTENH2) == 8) THEN
    alloc8 (ZTENH2)
ELSEIF (KIND (ZTENH2) == 4) THEN
    alloc4 (ZTENH2)
ELSE
    STOP 1
ENDIF


IF (KIND (ZQENH) == 8) THEN
    alloc8 (ZQENH)
ELSEIF (KIND (ZQENH) == 4) THEN
    alloc4 (ZQENH)
ELSE
    STOP 1
ENDIF


IF (KIND (ZTENH) == 8) THEN
    alloc8 (ZTENH)
ELSEIF (KIND (ZTENH) == 4) THEN
    alloc4 (ZTENH)
ELSE
    STOP 1
ENDIF


IF (KIND (ZMFUB) == 8) THEN
    alloc8 (ZMFUB)
ELSEIF (KIND (ZMFUB) == 4) THEN
    alloc4 (ZMFUB)
ELSE
    STOP 1
ENDIF


IF (KIND (ZDPMEL) == 8) THEN
    alloc8 (ZDPMEL)
ELSEIF (KIND (ZDPMEL) == 4) THEN
    alloc4 (ZDPMEL)
ELSE
    STOP 1
ENDIF


IF (KIND (ZWUBASE) == 8) THEN
    alloc8 (ZWUBASE)
ELSEIF (KIND (ZWUBASE) == 4) THEN
    alloc4 (ZWUBASE)
ELSE
    STOP 1
ENDIF


IF (KIND (ZDMFDE) == 8) THEN
    alloc8 (ZDMFDE)
ELSEIF (KIND (ZDMFDE) == 4) THEN
    alloc4 (ZDMFDE)
ELSE
    STOP 1
ENDIF


IF (KIND (ZDMFEN) == 8) THEN
    alloc8 (ZDMFEN)
ELSEIF (KIND (ZDMFEN) == 4) THEN
    alloc4 (ZDMFEN)
ELSE
    STOP 1
ENDIF


IF (KIND (ICTOP0) == 8) THEN
    alloc8 (ICTOP0)
ELSEIF (KIND (ICTOP0) == 4) THEN
    alloc4 (ICTOP0)
ELSE
    STOP 1
ENDIF


IF (KIND (IDTOP) == 8) THEN
    alloc8 (IDTOP)
ELSEIF (KIND (IDTOP) == 4) THEN
    alloc4 (IDTOP)
ELSE
    STOP 1
ENDIF


IF (KIND (ILAB) == 8) THEN
    alloc8 (ILAB)
ELSEIF (KIND (ILAB) == 4) THEN
    alloc4 (ILAB)
ELSE
    STOP 1
ENDIF


IF (KIND (IDPL) == 8) THEN
    alloc8 (IDPL)
ELSEIF (KIND (IDPL) == 4) THEN
    alloc4 (IDPL)
ELSE
    STOP 1
ENDIF


IF (KIND (LLSCVFLAG) == 8) THEN
    alloc8 (LLSCVFLAG)
ELSEIF (KIND (LLSCVFLAG) == 4) THEN
    alloc4 (LLSCVFLAG)
ELSE
    STOP 1
ENDIF


IF (KIND (LLDCUM) == 8) THEN
    alloc8 (LLDCUM)
ELSEIF (KIND (LLDCUM) == 4) THEN
    alloc4 (LLDCUM)
ELSE
    STOP 1
ENDIF


IF (KIND (LLDDRAF3) == 8) THEN
    alloc8 (LLDDRAF3)
ELSEIF (KIND (LLDDRAF3) == 4) THEN
    alloc4 (LLDDRAF3)
ELSE
    STOP 1
ENDIF


IF (KIND (LLDDRAF) == 8) THEN
    alloc8 (LLDDRAF)
ELSEIF (KIND (LLDDRAF) == 4) THEN
    alloc4 (LLDDRAF)
ELSE
    STOP 1
ENDIF


IF (KIND (ZUV2) == 8) THEN
    alloc8 (ZUV2)
ELSEIF (KIND (ZUV2) == 4) THEN
    alloc4 (ZUV2)
ELSE
    STOP 1
ENDIF


IF (KIND (ZDMFDPC) == 8) THEN
    alloc8 (ZDMFDPC)
ELSEIF (KIND (ZDMFDPC) == 4) THEN
    alloc4 (ZDMFDPC)
ELSE
    STOP 1
ENDIF


IF (KIND (ZDMFUPC) == 8) THEN
    alloc8 (ZDMFUPC)
ELSEIF (KIND (ZDMFUPC) == 4) THEN
    alloc4 (ZDMFUPC)
ELSE
    STOP 1
ENDIF


IF (KIND (ZKMFL) == 8) THEN
    alloc8 (ZKMFL)
ELSEIF (KIND (ZKMFL) == 4) THEN
    alloc4 (ZKMFL)
ELSE
    STOP 1
ENDIF


IF (KIND (ZTENV) == 8) THEN
    alloc8 (ZTENV)
ELSEIF (KIND (ZTENV) == 4) THEN
    alloc4 (ZTENV)
ELSE
    STOP 1
ENDIF


IF (KIND (ZTENU) == 8) THEN
    alloc8 (ZTENU)
ELSEIF (KIND (ZTENU) == 4) THEN
    alloc4 (ZTENU)
ELSE
    STOP 1
ENDIF


IF (KIND (ZMFDDR) == 8) THEN
    alloc8 (ZMFDDR)
ELSEIF (KIND (ZMFDDR) == 4) THEN
    alloc4 (ZMFDDR)
ELSE
    STOP 1
ENDIF


IF (KIND (ZMFUDR) == 8) THEN
    alloc8 (ZMFUDR)
ELSEIF (KIND (ZMFUDR) == 4) THEN
    alloc4 (ZMFUDR)
ELSE
    STOP 1
ENDIF


IF (KIND (ZMFDUS) == 8) THEN
    alloc8 (ZMFDUS)
ELSEIF (KIND (ZMFDUS) == 4) THEN
    alloc4 (ZMFDUS)
ELSE
    STOP 1
ENDIF


IF (KIND (ZMFUUS) == 8) THEN
    alloc8 (ZMFUUS)
ELSEIF (KIND (ZMFUUS) == 4) THEN
    alloc4 (ZMFUUS)
ELSE
    STOP 1
ENDIF




JLON = KIDIA


ZCONS2=YDML_PHY_EC%YRECUMF%RMFCFL/(YDCST%RG*PTSPHY)
ZCONS=1.0_JPRB/(YDCST%RG*PTSPHY)
ZORCPD=1.0_JPRB/YDCST%RCPD
ZRDOCPD=YDCST%RD*ZORCPD
ZRG=1.0_JPRB/YDCST%RG
ZTAU =0.0

LLPERT_RTAU=.FALSE.


PCAPE (JLON)=0.0_JPRB
PVDISCU (JLON)=0.0_JPRB
LDCUM (JLON)=.FALSE.

CALL CUININ_OPENACC (YDCST, YDTHF, YDML_PHY_SLIN%YREPHLI, YDML_PHY_EC%YRECUMF, KIDIA&
&, KFDIA, KLON, KLEV, PTEN, PQEN, PQSEN, PUEN, PVEN, PGEO, PAPH, ILAB, ZTENH, ZQENH&
&, ZQSENH, PGEOH, PTU, PQU, ZTD, ZQD, ZUU, ZVU, ZUD, ZVD, PLU, YDSTACK=YLSTACK)
ZKMFL (JLON)=0.0_JPRB
LLMIXS=LDTDKMF
CALL CUBASEN_OPENACC (PPLDARE, PPLRG, YDTHF, YDCST, YDML_PHY_SLIN%YREPHLI, YDML_PHY_EC%YRECLDP, YDML_PHY_EC&
&%YRECUMF, YDSPP_CONFIG, KIDIA, KFDIA, KLON, KLEV, YDML_PHY_EC%YRECUMF%NJKT1, LLMIXS, LDTDKMF, ZTENH&
&, ZQENH, PGEOH, PAPH, PQHFL, PAHFS, PGP2DSPP, ZKMFL, PTEN, PQEN, PQSEN, PGEO, PTU, PQU, PLU, ZKINEU&
&, ZWUBASE, ILAB, LDCUM, LDSC, KCBOT, KBOTSC, ICTOP0, IDPL, PCAPE, YDSTACK=YLSTACK)

ZDHPBL =0.0_JPRB
IDTOP (JLON)=0
ZCAPPBL =0.
ZKHVFL =(-PAHFS (JLON, KLEV+1)*ZORCPD-YDCST%RETV*PTEN &
&(JLON, KLEV)*PQHFL (JLON, KLEV+1))/(PPLRG*PPLDARE)
ZKHFL =(-PAHFS (JLON, KLEV+1)-YDCST%RLVTT*PQHFL (JLON, KLEV+1))/(PPLRG*PPLDARE)


DO JLEV=YDML_PHY_EC%YRECUMF%NJKT2, KLEV

  

  IF (LDCUM (JLON).AND.JLEV>=KCBOT (JLON)) THEN
    ZDZ=(PAPH (JLON, JLEV+1)-PAPH (JLON, JLEV))
    ZDHPBL =ZDHPBL +(YDCST%RLVTT*PTENQ (JLON, JLEV)+YDCST%RCPD*PTENT (JLON, JLEV))*ZDZ
    ZCAPPBL =ZCAPPBL +(PTENT (JLON, JLEV)+YDCST%RETV*PTEN (JLON, JLEV)*PTENQ (JLON, JLEV))*ZDZ
  ENDIF

  
ENDDO



IF (LDCUM (JLON)) THEN
  IKB=KCBOT (JLON)
  ITOPM2=ICTOP0 (JLON)
  ZPBMPT=PAPH (JLON, IKB)-PAPH (JLON, ITOPM2)

  IF (ZPBMPT>=YDML_PHY_EC%YRECUMF%RDEPTHS) THEN
    KTYPE (JLON)=1
  ELSE
    KTYPE (JLON)=2
  ENDIF

ELSE
  KTYPE (JLON)=0
ENDIF



IF (YDML_PHY_EC%YRECUMF%LMFWSTAR) THEN

  

  IF (LDCUM (JLON)) THEN
    IKB=KCBOT (JLON)
    ZDZ=MAX (0.0_JPRB, MIN (1.5E3_JPRB,(PGEOH (JLON, IKB)-PGEOH (JLON, KLEV+1))/YDCST%RG))
    ZMF_SHAL =0.07_JPRB*(YDCST%RG/PTEN (JLON, KLEV)*ZDZ*MAX (0.0_JPRB, ZKHVFL ))**.3333
    ZMFMAX=(PAPH (JLON, IKB)-PAPH (JLON, IKB-1))*ZCONS2
    ZMF_SHAL =MIN (ZMF_SHAL , ZMFMAX)
  ENDIF

  
ENDIF



IF (LDCUM (JLON)) THEN
  IKB=KCBOT (JLON)
  ZMFMAX=(PAPH (JLON, IKB)-PAPH (JLON, IKB-1))*ZCONS2

  IF (KTYPE (JLON)==1) THEN
    ZMFUB (JLON)=ZMFMAX*0.1_JPRB
  ELSEIF (KTYPE (JLON)==2) THEN
    ZQUMQE=PQU (JLON, IKB)+PLU (JLON, IKB)-ZQENH (JLON, IKB)
    ZDQMIN=MAX (0.01_JPRB*ZQENH (JLON, IKB), 1.E-10_JPRB)
    ZDH=YDCST%RCPD*(PTU (JLON, IKB)-ZTENH (JLON, IKB))+YDCST%RLVTT*ZQUMQE
    ZDH=YDCST%RG*MAX (ZDH, 1.E5_JPRB*ZDQMIN)

    IF (ZDHPBL >0.0_JPRB) THEN
      ZMFUB (JLON)=ZDHPBL /ZDH
      ZMFUB (JLON)=MIN (ZMFUB (JLON), ZMFMAX)
    ELSE
      ZMFUB (JLON)=ZMFMAX*0.1_JPRB
      LDCUM (JLON)=.FALSE.
    ENDIF


    IF (YDML_PHY_EC%YRECUMF%LMFWSTAR)  THEN
        ZMFUB (JLON)=ZMF_SHAL 
    ENDIF

  ENDIF

ELSE
  ZMFUB (JLON)=0.0_JPRB
ENDIF


CALL CUASCN_OPENACC (YDTHF, YDCST, YDML_PHY_SLIN%YREPHLI, YDML_PHY_EC%YRECLDP, YDML_PHY_EC%YRECUMF, YDSPP_CONFIG&
&, YGFL, KIDIA, KFDIA, KLON, KLEV, LDTDKMF, PTSPHY, ZTENH, ZQENH, PUEN, PVEN, PTEN, PQEN, PQSEN, PLITOT&
&, PGEO, PGEOH, PAP, PAPH, PVERVEL, ZWUBASE, PGP2DSPP, LDLAND, LDCUM, KTYPE, ILAB, LLSCVFLAG, PTU, PQU&
&, PLU, PLRAIN, PMFU, ZMFUB, PLGLAC, ZMFUS, ZMFUQ, ZMFUL, PLUDE, PLUDELI, ZDMFUP, PLCRIT_AER, ZDMFEN&
&, KCBOT, KCTOP, ICTOP0, IDPL, PMFUDE_RATE, ZKINEU, PWU, PWMEAN, YDSTACK=YLSTACK)


IF (LDCUM (JLON)) THEN
  IKB=KCBOT (JLON)
  ITOPM2=KCTOP (JLON)
  ZPBMPT=PAPH (JLON, IKB)-PAPH (JLON, ITOPM2)

  IF (KTYPE (JLON)==1.AND.ZPBMPT<YDML_PHY_EC%YRECUMF%RDEPTHS)  THEN
      KTYPE (JLON)=2
  ENDIF


  IF (KTYPE (JLON)==2.AND.ZPBMPT>=YDML_PHY_EC%YRECUMF%RDEPTHS)  THEN
      KTYPE (JLON)=1
  ENDIF

  ICTOP0 (JLON)=KCTOP (JLON)
ENDIF

ZRFL (JLON)=ZDMFUP (JLON, 1)


DO JLEV=2, KLEV
  
  ZRFL (JLON)=ZRFL (JLON)+ZDMFUP (JLON, JLEV)
  
ENDDO


DO JLEV=1, KLEV
  
  PMFD (JLON, JLEV)=0.0_JPRB
  ZMFDS (JLON, JLEV)=0.0_JPRB
  ZMFDQ (JLON, JLEV)=0.0_JPRB
  ZDMFDP (JLON, JLEV)=0.0_JPRB
  ZDPMEL (JLON, JLEV)=0.0_JPRB
  
ENDDO


DO JLEV=1, KLEV
  
  ZTENU (JLON, JLEV)=PTENU (JLON, JLEV)
  ZTENV (JLON, JLEV)=PTENV (JLON, JLEV)
  
ENDDO


IF (YDML_PHY_EC%YRECUMF%LMFDD) THEN
  CALL CUDLFSN_OPENACC (YDTHF, YDCST, YDML_PHY_SLIN%YREPHLI, YDML_PHY_EC%YRECUMF, KIDIA, KFDIA&
  &, KLON, KLEV, KCBOT, KCTOP, LDCUM, ZTENH, ZQENH, PTEN, PQSEN, PGEO, PGEOH, PAPH, PTU, PQU&
  &, ZMFUB, ZRFL, ZTD, ZQD, PMFD, ZMFDS, ZMFDQ, ZDMFDP, IDTOP, LLDDRAF, YDSTACK=YLSTACK)
  CALL CUDDRAFN_OPENACC (YDCST, YDTHF, YDML_PHY_SLIN%YREPHLI, YDML_PHY_EC%YRECUMF, KIDIA&
  &, KFDIA, KLON, KLEV, LLDDRAF, ZTENH, ZQENH, PQSEN, PGEO, PGEOH, PAPH, ZRFL, ZTD, ZQD&
  &, PMFU, PMFD, ZMFDS, ZMFDQ, ZDMFDP, ZDMFDE, PMFDDE_RATE, ZKINED, YDSTACK=YLSTACK)
ENDIF


ZHEAT =0.0_JPRB
ZCAPE =0.0_JPRB
ZCAPE2 =0.0_JPRB
ZMFUB1 =ZMFUB (JLON)
ZDQCV =0.0_JPRB
ZSATFR =0.0_JPRB
ZDX =2*YDCST%RA*SQRT (YDCST%RPI*PGAW (JLON))
ZDX =MAX (ZDX , 1.E2_JPRB)


DO JLEV=YDML_PHY_EC%YRECUMF%NJKT2, KLEV
  
  LLO1=LDCUM (JLON).AND.KTYPE (JLON)==1
  LLO3=LLO1.AND.JLEV<=KCBOT (JLON).AND.JLEV>KCTOP (JLON)

  IF (LLO3) THEN
    ZDZ=(PGEO (JLON, JLEV-1)-PGEO (JLON, JLEV))

    IF (LDTDKMF) THEN
      ZHEAT =ZHEAT +((PTEN (JLON, JLEV-1)-PTEN (JLON, JLEV)+ZDZ*ZORCPD)/ZTENH (JLON, JLEV)+YDCST%RETV&
      &*(PQEN (JLON, JLEV-1)-PQEN (JLON, JLEV)))*(YDCST%RG*(PMFU (JLON, JLEV)+PMFD (JLON, JLEV)))
    ELSE
      ZHEAT =ZHEAT +MAX (0.0_JPRB,((PTEN (JLON, JLEV-1)-PTEN (JLON, JLEV)+ZDZ*ZORCPD)/ZTENH (JLON, JLEV)+YDCST&
      &%RETV*(PQEN (JLON, JLEV-1)-PQEN (JLON, JLEV)))*(YDCST%RG*(PMFU (JLON, JLEV)+PMFD (JLON, JLEV))))
    ENDIF

    ZDZ=(PAP (JLON, JLEV)-PAP (JLON, JLEV-1))
    ZCAPE =ZCAPE +((PTU (JLON, JLEV)-ZTENH (JLON, JLEV))/ZTENH (JLON, JLEV)+YDCST&
    &%RETV*(PQU (JLON, JLEV)-ZQENH (JLON, JLEV))-PLU (JLON, JLEV))*ZDZ
  ENDIF


  IF (LLO3.AND.YDML_PHY_EC%YRECUMF%RCAPQADV>0.0_JPRB) THEN
    ZTENH2 (JLON, JLEV)=ZTENH (JLON, JLEV)-0.5_JPRB*(PTENTA (JLON, JLEV)+PTENTA (JLON, JLEV-1))*PTSPHY
    ZQENH2 (JLON, JLEV)=ZQENH (JLON, JLEV)-0.5_JPRB*(PTENQA (JLON, JLEV)+PTENQA (JLON, JLEV-1))*PTSPHY
    ZCAPE2 =ZCAPE2 +((PTU (JLON, JLEV)-ZTENH2 (JLON, JLEV))/ZTENH2 (JLON, JLEV)&
    &+YDCST%RETV*(PQU (JLON, JLEV)-ZQENH2 (JLON, JLEV))-PLU (JLON, JLEV))*ZDZ
  ENDIF


  IF (LLO1) THEN
    ZDZ=(PAPH (JLON, JLEV+1)-PAPH (JLON, JLEV))
    ZDQCV =ZDQCV +PTENQA (JLON, JLEV)*ZDZ*(PQEN (JLON, JLEV)/PQSEN (JLON, JLEV))
  ENDIF


  IF (LLO1.AND.JLEV>=KCTOP (JLON)) THEN
    ZDZ=(PAPH (JLON, JLEV+1)-PAPH (JLON, JLEV))
    ZSATFR =ZSATFR +(PQEN (JLON, JLEV)/PQSEN (JLON, JLEV))*ZDZ
  ENDIF

  
ENDDO


ZCAPDCYCL =0.0_JPRB
ZTAU =0.0_JPRB

IF (LDTDKMF) THEN
  ZDX =PDX (JLON)
  ZDX =MAX (ZDX , 1.E2_JPRB)
ENDIF


IF (LDCUM (JLON).AND.KTYPE (JLON)==1) THEN

  IF (YDML_PHY_EC%YRECUMF%LNEWTAU) THEN
    ZTAURES=YDML_PHY_EC%YRECUMF%RTAULIM*(1._JPRB+YDML_PHY_EC%YRECUMF%RTAUFAC&
    &/((ZDX /1000._JPRB-YDML_PHY_EC%YRECUMF%RXMIN+1._JPRB)**2))
  ELSE
    ZTAURES=1.0_JPRB+1.60_JPRB*ZDX /125.E3_JPRB

    IF (ZDX <8.E3_JPRB) THEN
      ZTAURES=1.0_JPRB+(LOG (8.E3_JPRB/ZDX ))**2
    ENDIF

  ENDIF


  IF (ZDX >125.E3_JPRB)  THEN
      ZTAURES=MIN (3.0_JPRB, ZTAURES)
  ENDIF

  IKD=IDPL (JLON)
  IKB=KCBOT (JLON)
  IK=KCTOP (JLON)
  ZTAU =(PGEOH (JLON, IK)-PGEOH (JLON, IKB))/((2.0_JPRB+MIN (15.0_JPRB&
  &, PWMEAN (JLON)))*YDCST%RG)*ZTAURES*YDML_PHY_EC%YRECUMF%RTAUA
  
  ZXTAU =ZTAU 
  
  LLO1=PAPH (JLON, KLEV+1)-PAPH (JLON, IKD)<50.E2_JPRB

  IF (LLO1.AND.LDLAND (JLON).AND.YDML_PHY_EC%YRECUMF%RCAPDCYCL==1.0_JPRB) THEN
    ZDZ=MIN (1.E4_JPRB, PGEOH (JLON, IKB)-PGEOH (JLON, KLEV+1))/YDCST%RG
    ZCAPDCYCL =ZXTAU *MAX (0.0_JPRB, ZKHVFL )*YDCST%RCPD/ZDZ
  ENDIF


  IF (LLO1.AND.YDML_PHY_EC%YRECUMF%RCAPDCYCL==2.0_JPRB) THEN
    ZIND=MAX (0._JPRB, MIN (1._JPRB,(YDML_PHY_EC%YRECUMF%RDXMAX-ZDX&
    & )/(YDML_PHY_EC%YRECUMF%RDXMAX-YDML_PHY_EC%YRECUMF%RDXMIN)))

    IF (LDLAND (JLON))  THEN
        ZIND=1._JPRB
    ENDIF

    ZCAPDCYCLLD =ZCAPPBL *ZTAU /ZTAURES
    ZDUTEN=2.0_JPRB+SQRT (0.5*(PUEN (JLON, IKB)**2+PVEN (JLON, IKB)**2+PUEN (JLON,&
    & YDML_PHY_EC%YRECUMF%NJKT3)**2+PVEN (JLON, YDML_PHY_EC%YRECUMF%NJKT3)**2))
    ZTAUPBL =MIN (1.E4_JPRB, PGEOH (JLON, IKB)-PGEOH (JLON, KLEV+1))/(YDCST%RG*ZDUTEN)
    ZCAPDCYCLSE =ZCAPPBL *ZTAUPBL 
    ZCAPDCYCL =ZIND*ZCAPDCYCLLD +(1._JPRB-ZIND)*ZCAPDCYCLSE 
  ENDIF

  ZDQCV =ZDQCV *YDCST%RLVTT/PGEOH (JLON, IK)*ZXTAU /MAX&
  & (1.25_JPRB, ZTAURES)*YDML_PHY_EC%YRECUMF%RCAPQADV
  ZSATFR =ZSATFR /(PAPH (JLON, KLEV+1)-PAPH (JLON, IK))
ELSE
  ZTAU =0.0_JPRB
ENDIF



IF (YDML_PHY_EC%YRECUMF%LMFCUCA) THEN
  
  ZFACCA =MAX (0.3_JPRB, MIN (1.8_JPRB, PCUCONVCA (JLON)))
  
ELSE
  ZFACCA =1.0_JPRB
ENDIF



IF (LDCUM (JLON).AND.KTYPE (JLON)==1) THEN
  IKB=KCBOT (JLON)
  ZCAPE2 =YDML_PHY_EC%YRECUMF%RCAPQADV*ZCAPE2 +(1.0_JPRB-YDML_PHY_EC%YRECUMF%RCAPQADV)*ZCAPE 
  ZCAPDCYCL =MAX (ZCAPDCYCL ,-2*ZCAPE2 )

  IF (ZSATFR <=0.94.OR.PVERVEL (JLON, YDML_PHY_EC%YRECUMF%NJKT5)<-100._JPRB) THEN
    ZCAPE =MAX (YDML_PHY_EC%YRECUMF%RMINCAPE*ZCAPE , ZCAPE2 -ZCAPDCYCL +ZDQCV )
  ELSE
    ZCAPE =MAX (YDML_PHY_EC%YRECUMF%RMINCAPE*ZCAPE , ZCAPE -ZCAPDCYCL )
  ENDIF

  ZCAPE =MIN (ZCAPE , 5000.0_JPRB)
  ZHEAT =MAX (1.E-4_JPRB, ZHEAT )
  ZXTAU =MAX (3.6E3_JPRB/(5.0_JPRB*PPLRG*PPLDARE), MIN (3.0_JPRB*3.6E3_JPRB/(PPLRG*PPLDARE), ZXTAU ))
  ZMFUB1 =(ZCAPE *ZMFUB (JLON))/(ZHEAT *ZXTAU )
  ZMFUB1 =MAX (ZMFUB1 , 0.001_JPRB)*ZFACCA 
  ZMFMAX=(PAPH (JLON, IKB)-PAPH (JLON, IKB-1))*ZCONS2
  ZMFUB1 =MIN (ZMFUB1 , ZMFMAX)
ENDIF



IF (LDMCAPEA) THEN
  
  PCAPE (JLON)=YDCST%RG*ZCAPE 
  
ENDIF



IF (LDCUM (JLON).AND.KTYPE (JLON)>=2) THEN
  IKB=KCBOT (JLON)

  IF (PMFD (JLON, IKB)<0.0_JPRB) THEN
    ZEPS=-PMFD (JLON, IKB)/MAX (ZMFUB (JLON), 1.E-10_JPRB)
  ELSE
    ZEPS=0.0_JPRB
  ENDIF

  ZMFMAX=(PAPH (JLON, IKB)-PAPH (JLON, IKB-1))*ZCONS2

  IF (KTYPE (JLON)==2) THEN

    IF (ZDHPBL >0.0_JPRB) THEN
      ZQUMQE=PQU (JLON, IKB)+PLU (JLON, IKB)-ZEPS*ZQD (JLON, IKB)-(1.0_JPRB-ZEPS)*ZQENH (JLON, IKB)
      ZDH=YDCST%RCPD*(PTU (JLON, IKB)-ZEPS*ZTD (JLON, IKB)-(1&
      &.0_JPRB-ZEPS)*ZTENH (JLON, IKB))+YDCST%RLVTT*ZQUMQE
      ZDH2=YDCST%RCPD*(PTU (JLON, IKB-1)-ZEPS*ZTD (JLON, IKB-1)-&
      &(1.0_JPRB-ZEPS)*ZTENH (JLON, IKB-1))+YDCST%RLVTT*ZQUMQE
      ZDH=0.5_JPRB*(ZDH+ZDH2)
      ZDH=YDCST%RG*MAX (ZDH, 0.1_JPRB*YDCST%RCPD)
      ZMFUB1 =ZDHPBL /ZDH

      IF (.NOT.LDTDKMF) THEN

        IF (ZMFUB1 >0.9_JPRB*ZMFMAX/YDML_PHY_EC%YRECUMF%RMFCFL.AND.ZDH<0.5_JPRB*YDCST%RG*YDCST%RCPD) THEN
          ZDH=0.75_JPRB*YDCST%RCPD*YDCST%RG
          ZMFUB1 =ZDHPBL /ZDH
        ENDIF

      ENDIF

    ELSE
      ZMFUB1 =ZMFUB (JLON)
    ENDIF


    IF (YDML_PHY_EC%YRECUMF%LMFWSTAR)  THEN
        ZMFUB1 =ZMF_SHAL 
    ENDIF

    ZMFUB1 =MIN (ZMFUB1 , ZMFMAX)
  ENDIF


  IF (KTYPE (JLON)==3) THEN

    IF (LDTDKMF) THEN
      ZMFUB1 =MAX (ZMFUB (JLON), ZKHFL /PGEOH (JLON, IKB))*(1.0_JPRB+ZEPS)
    ELSE
      ZMFUB1 =MAX (ZMFUB (JLON), 5*ZKHFL /PGEOH (JLON, IKB))*(1.0_JPRB+ZEPS)
    ENDIF


    IF (PGEOH (JLON, IKB)<1.5E3_JPRB) THEN
      ZMFUB1 =MIN (ZMFUB1 , ZMFMAX/(1.05_JPRB*YDML_PHY_EC%YRECUMF%RMFCFL))
    ELSE
      ZMFUB1 =MIN (ZMFUB1 , ZMFMAX)
    ENDIF

  ENDIF

ENDIF



DO JLEV=1, KLEV

  

  IF (LLDDRAF (JLON).AND.(KTYPE (JLON)==1.OR.KTYPE (JLON)==2)) THEN
    ZFAC=ZMFUB1 /MAX (ZMFUB (JLON), 1.E-10_JPRB)
    PMFD (JLON, JLEV)=PMFD (JLON, JLEV)*ZFAC
    ZMFDS (JLON, JLEV)=ZMFDS (JLON, JLEV)*ZFAC
    ZMFDQ (JLON, JLEV)=ZMFDQ (JLON, JLEV)*ZFAC
    ZDMFDP (JLON, JLEV)=ZDMFDP (JLON, JLEV)*ZFAC
    PMFDDE_RATE (JLON, JLEV)=PMFDDE_RATE (JLON, JLEV)*ZFAC
  ENDIF

  
ENDDO



IF (LDCUM (JLON)) THEN
  ZMFS =ZMFUB1 /MAX (YDML_PHY_EC%YRECUMF%RMFCMIN, ZMFUB (JLON))
ENDIF



DO JLEV=2, KLEV

  

  IF (LDCUM (JLON).AND.JLEV>=KCTOP (JLON)-1) THEN
    IKB=KCBOT (JLON)

    IF (JLEV>IKB) THEN
      ZDZ=((PAPH (JLON, KLEV+1)-PAPH (JLON, JLEV))/(PAPH (JLON, KLEV+1)-PAPH (JLON, IKB)))
      PMFU (JLON, JLEV)=PMFU (JLON, IKB)*ZDZ
    ENDIF

    ZMFMAX=(PAPH (JLON, JLEV)-PAPH (JLON, JLEV-1))*ZCONS2

    IF (.NOT.LDTDKMF)  THEN
        ZMFMAX=MIN (ZMFMAX, YDML_PHY_EC%YRECUMF%RMFLIA)
    ENDIF


    IF (PMFU (JLON, JLEV)*ZMFS >ZMFMAX) THEN
      ZMFS =MIN (ZMFS , ZMFMAX/PMFU (JLON, JLEV))
      ZMFS =MAX (ZMFS , 1.E-10_JPRB)
    ENDIF

  ENDIF

  
ENDDO


IF (YDML_PHY_EC%YRECUMF%RMFADVW>0.0_JPRB) THEN

  DO JLEV=2, KLEV-1

    

    IF (KTYPE (JLON)==1.AND.JLEV>=KCTOP (JLON)-1) THEN
      ZFAC=ZMFS *YDCST%RG*YDML_PHY_EC%YRECUMF%RMFADVW*(PMFU (JLON, JLEV)-PMFU&
      & (JLON, JLEV+1)+YDML_PHY_EC%YRECUMF%RMFADVWDD*(PMFD (JLON, JLEV)-PMFD&
      & (JLON, JLEV+1)))/(PAPH (JLON, JLEV)-PAPH (JLON, JLEV+1))*PTSPHY

      IF (ABS (ZFAC)>0.98_JPRB)  THEN
          ZMFS =ZMFS /MAX (1.02_JPRB, ABS (ZFAC))
      ENDIF

    ENDIF

  
  ENDDO

  JLEV=KLEV

  

  IF (KTYPE (JLON)==1) THEN
    ZFAC=ZMFS *YDCST%RG*YDML_PHY_EC%YRECUMF%RMFADVW*(PMFU (JLON, JLEV)+YDML_PHY_EC%YRECUMF&
    &%RMFADVWDD*PMFD (JLON, JLEV))/(PAPH (JLON, JLEV)-PAPH (JLON, JLEV+1))*PTSPHY

    IF (ABS (ZFAC)>0.98_JPRB)  THEN
        ZMFS =ZMFS /MAX (1.02_JPRB, ABS (ZFAC))
    ENDIF

  ENDIF

  
ENDIF


DO JLEV=2, KLEV

  

  IF (LDCUM (JLON).AND.JLEV<=KCBOT (JLON).AND.JLEV>=KCTOP (JLON)-1) THEN
    PMFU (JLON, JLEV)=PMFU (JLON, JLEV)*ZMFS 
    ZMFUS (JLON, JLEV)=ZMFUS (JLON, JLEV)*ZMFS 
    ZMFUQ (JLON, JLEV)=ZMFUQ (JLON, JLEV)*ZMFS 
    ZMFUL (JLON, JLEV)=ZMFUL (JLON, JLEV)*ZMFS 
    ZDMFUP (JLON, JLEV)=ZDMFUP (JLON, JLEV)*ZMFS 
    ZDMFEN (JLON, JLEV)=ZDMFEN (JLON, JLEV)*ZMFS 
    PLUDE (JLON, JLEV)=PLUDE (JLON, JLEV)*ZMFS 
    PLUDELI (JLON, JLEV, 1)=PLUDELI (JLON, JLEV, 1)*ZMFS 
    PLUDELI (JLON, JLEV, 2)=PLUDELI (JLON, JLEV, 2)*ZMFS 
    PMFUDE_RATE (JLON, JLEV)=PMFUDE_RATE (JLON, JLEV)*ZMFS 
  ENDIF

  
ENDDO



IF (KTYPE (JLON)==2.AND.KCBOT (JLON)==KCTOP (JLON).AND.KCBOT (JLON)>=KLEV-1) THEN
  LDCUM (JLON)=.FALSE.
  KTYPE (JLON)=0
ENDIF



LLO2 =.FALSE.

IF ((.NOT.LDSHCV (JLON).AND.KTYPE (JLON)==2)) THEN
  LLO2 =.TRUE.
  LDCUM (JLON)=.FALSE.
ENDIF



LDCUM_LIG (JLON)=LDCUM (JLON)
KCTOP_LIG (JLON)=KCTOP (JLON)
KCBOT_LIG (JLON)=KCBOT (JLON)


IF (.NOT.YDML_PHY_EC%YRECUMF%LMFSCV.OR..NOT.YDML_PHY_EC%YRECUMF%LMFPEN) THEN

  

  IF ((.NOT.YDML_PHY_EC%YRECUMF%LMFSCV.AND.KTYPE (JLON)==2).OR.(&
    &.NOT.YDML_PHY_EC%YRECUMF%LMFPEN.AND.KTYPE (JLON)==1)) THEN
    LLO2 =.TRUE.
    LDCUM (JLON)=.FALSE.
  ENDIF

  
ENDIF



IF (LLDDRAF (JLON).AND.IDTOP (JLON)<=KCTOP (JLON)) THEN
  IDTOP (JLON)=KCTOP (JLON)+1
ENDIF



DO JLEV=2, KLEV

  

  IF (LLDDRAF (JLON)) THEN

    IF (JLEV<IDTOP (JLON)) THEN
      PMFD (JLON, JLEV)=0.0_JPRB
      ZMFDS (JLON, JLEV)=0.0_JPRB
      ZMFDQ (JLON, JLEV)=0.0_JPRB
      PMFDDE_RATE (JLON, JLEV)=0.0_JPRB
      ZDMFDP (JLON, JLEV)=0.0_JPRB
    ELSEIF (JLEV==IDTOP (JLON)) THEN
      PMFDDE_RATE (JLON, JLEV)=0.0_JPRB
    ENDIF

  ENDIF

  
ENDDO

CALL CUFLXN_OPENACC (YDTHF, YDCST, YDML_PHY_SLIN%YREPHLI, YDML_PHY_EC%YRECUMF, KIDIA&
&, KFDIA, KLON, KLEV, PTSPHY, PTEN, PQEN, PQSEN, ZTENH, ZQENH, PAPH, PAP, PGEOH, LDLAND&
&, LDCUM, LDTDKMF, KCBOT, KCTOP, IDTOP, ITOPM2, KTYPE, LLDDRAF, PMFU, PMFD, ZMFUS, ZMFDS&
&, ZMFUQ, ZMFDQ, ZMFUL, PLUDE, PLUDELI, PLRAIN, PSNDE, ZDMFUP, ZDMFDP, ZDPMEL, PLGLAC&
&, PMFLXR, PMFLXS, PRAIN, PMFUDE_RATE, PMFDDE_RATE, YDSTACK=YLSTACK)

DO JLEV=2, KLEV-1

  

  IF (LLDDRAF (JLON).AND.JLEV>=IDTOP (JLON)-1) THEN
    ZERATE=-PMFD (JLON, JLEV)+PMFD (JLON, JLEV-1)+PMFDDE_RATE (JLON, JLEV)

    IF (ZERATE<0.0_JPRB) THEN
      PMFDDE_RATE (JLON, JLEV)=PMFDDE_RATE (JLON, JLEV)-ZERATE
    ENDIF

  ENDIF


  IF (LDCUM (JLON).AND.JLEV>=KCTOP (JLON)-1) THEN
    ZERATE=PMFU (JLON, JLEV)-PMFU (JLON, JLEV+1)+PMFUDE_RATE (JLON, JLEV)

    IF (ZERATE<0.0_JPRB) THEN
      PMFUDE_RATE (JLON, JLEV)=PMFUDE_RATE (JLON, JLEV)-ZERATE
    ENDIF

    ZDMFUP (JLON, JLEV)=PMFLXR (JLON, JLEV+1)+PMFLXS (JLON&
    &, JLEV+1)-PMFLXR (JLON, JLEV)-PMFLXS (JLON, JLEV)
    ZDMFDP (JLON, JLEV)=0.0_JPRB
  ENDIF

  
ENDDO



IF (LLDDRAF (JLON)) THEN
  JLEV=IDTOP (JLON)
  IK=MIN (JLEV+1, KLEV)

  IF (ZMFDQ (JLON, JLEV)<0.3_JPRB*ZMFDQ (JLON, IK)) THEN

    IF (YDML_PHY_EC%YRECUMF%RMFSOLTQ==0.0_JPRB) THEN
      ZMFDQ (JLON, JLEV)=0.3_JPRB*ZMFDQ (JLON, IK)
    ELSE
      PMFD (JLON, JLEV)=0.3_JPRB*PMFD (JLON, IK)
    ENDIF

  ENDIF

ENDIF



DO JLEV=2, KLEV

  

  IF (LDCUM (JLON).AND.JLEV>=KCTOP (JLON)-1.AND.JLEV<KCBOT (JLON)) THEN
    ZDZ=PTSPHY*YDCST%RG/(PAPH (JLON, JLEV+1)-PAPH (JLON, JLEV))
    ZMFA=ZMFUQ (JLON, JLEV+1)+ZMFDQ (JLON, JLEV+1)-ZMFUQ (JLON, JLEV)-ZMFDQ (JLON, JLEV)+ZMFUL (JLON&
    &, JLEV+1)-ZMFUL (JLON, JLEV)+ZDMFUP (JLON, JLEV)-PSNDE (JLON, JLEV, 1)-PSNDE (JLON, JLEV, 2)
    ZMFA=(ZMFA-PLUDE (JLON, JLEV))*ZDZ

    IF (PQEN (JLON, JLEV)+ZMFA<0.0_JPRB.AND.PLUDE (JLON, JLEV)>0.0_JPRB) THEN
      ZFAC=MIN (-(PQEN (JLON, JLEV)+ZMFA)/ZDZ, PLUDE (JLON, JLEV))
      PLUDE (JLON, JLEV)=PLUDE (JLON, JLEV)+ZFAC
      PLUDELI (JLON, JLEV, 1)=PLUDELI (JLON, JLEV, 1)+ZFAC*PLUDELI (JLON, JLEV, 1)/PLUDE (JLON, JLEV)
      PLUDELI (JLON, JLEV, 2)=PLUDELI (JLON, JLEV, 2)+ZFAC*PLUDELI (JLON, JLEV, 2)/PLUDE (JLON, JLEV)
    ENDIF


    IF (PLUDE (JLON, JLEV)<0.0_JPRB) THEN
      PLUDE (JLON, JLEV)=0.0_JPRB
      PLUDELI (JLON, JLEV, 1)=0.0_JPRB
      PLUDELI (JLON, JLEV, 2)=0.0_JPRB
    ENDIF

  ENDIF


  IF (.NOT.LDCUM (JLON)) THEN
    PMFUDE_RATE (JLON, JLEV)=0.0_JPRB
  ENDIF


  IF (PMFD (JLON, JLEV-1)==0.0_JPRB) THEN
    PMFDDE_RATE (JLON, JLEV)=0.0_JPRB
  ENDIF

  
ENDDO


IF (YDML_PHY_EC%YRECUMF%RMFSOLTQ>0.0_JPRB) THEN

  DO JLEV=KLEV, 2,-1

    

    IF (LDCUM (JLON)) THEN

      IF (JLEV>KCBOT (JLON)) THEN
        ZMFA=1.0_JPRB/MAX (1.E-15_JPRB, PMFU (JLON, JLEV))
        PQU (JLON, JLEV)=ZQENH (JLON, JLEV)+ZMFUQ (JLON, JLEV)*ZMFA
        PTU (JLON, JLEV)=ZTENH (JLON, JLEV)+ZMFUS (JLON, JLEV)*ZMFA*ZORCPD
        ZMFUS (JLON, JLEV)=PMFU (JLON, JLEV)*(YDCST%RCPD*PTU (JLON, JLEV)+PGEOH (JLON, JLEV))
        ZMFUQ (JLON, JLEV)=PMFU (JLON, JLEV)*PQU (JLON, JLEV)

        IF (LLDDRAF (JLON)) THEN
          ZMFA=1.0_JPRB/MIN (-1.E-15_JPRB, PMFD (JLON, JLEV))
          ZQD (JLON, JLEV)=ZQENH (JLON, JLEV)+ZMFDQ (JLON, JLEV)*ZMFA
          ZTD (JLON, JLEV)=ZTENH (JLON, JLEV)+ZMFDS (JLON, JLEV)*ZMFA*ZORCPD
          ZMFDQ (JLON, JLEV)=PMFD (JLON, JLEV)*ZQD (JLON, JLEV)
          ZMFDS (JLON, JLEV)=PMFD (JLON, JLEV)*(YDCST%RCPD*ZTD (JLON, JLEV)+PGEOH (JLON, JLEV))
        ENDIF

      ELSEIF (JLEV<=KCBOT (JLON).AND.JLEV>=KCTOP (JLON)) THEN
        ZMFUS (JLON, JLEV)=PMFU (JLON, JLEV)*(YDCST%RCPD*PTU (JLON, JLEV)+PGEOH (JLON, JLEV))
        ZMFUQ (JLON, JLEV)=PMFU (JLON, JLEV)*PQU (JLON, JLEV)
        ZMFDS (JLON, JLEV)=PMFD (JLON, JLEV)*(YDCST%RCPD*ZTD (JLON, JLEV)+PGEOH (JLON, JLEV))
        ZMFDQ (JLON, JLEV)=PMFD (JLON, JLEV)*ZQD (JLON, JLEV)
      ENDIF

    ENDIF

  
  ENDDO

ENDIF

CALL CUDTDQN_OPENACC (YDTHF, YDCST, YDML_PHY_SLIN%YREPHLI, YDML_PHY_SLIN%YRPHNC, YDML_PHY_EC&
&%YRECUMF, YDML_PHY_EC%YREPHY, KIDIA, KFDIA, KLON, KLEV, ITOPM2, KTYPE, KCTOP, KCBOT, IDTOP&
&, LDTDKMF, LDCUM, LLDDRAF, LLSCVFLAG, PTSPHY, PAPH, PAP, PGEOH, PGEO, PTEN, ZTENH, PQEN&
&, ZQENH, PQSEN, PLGLAC, PLUDE, PLUDELI, PSNDE, PMFU, PMFD, ZMFUS, ZMFDS, ZMFUQ, ZMFDQ, ZMFUL&
&, ZDMFUP, ZDPMEL, PMFLXR, PMFLXS, PTENT, PTENQ, PENTH, YDSTACK=YLSTACK)

IF (YDML_PHY_EC%YRECUMF%LMFDUDV) THEN

  DO JLEV=KLEV-1, 2,-1
    IK=JLEV+1

    

    IF (LDCUM (JLON)) THEN

      IF (JLEV==KCBOT (JLON).AND.KTYPE (JLON)<3) THEN
        IKB=IDPL (JLON)
        ZUU (JLON, JLEV)=PUEN (JLON, IKB-1)
        ZVU (JLON, JLEV)=PVEN (JLON, IKB-1)
      ELSEIF (JLEV==KCBOT (JLON).AND.KTYPE (JLON)==3) THEN
        ZUU (JLON, JLEV)=PUEN (JLON, JLEV-1)
        ZVU (JLON, JLEV)=PVEN (JLON, JLEV-1)
      ENDIF


      IF (JLEV<KCBOT (JLON).AND.JLEV>=KCTOP (JLON)) THEN
        ZFAC=0.0_JPRB

        IF (LDTDKMF.AND.(KTYPE (JLON)==1.OR.KTYPE (JLON)==3))  THEN
            ZFAC=2.0_JPRB
        ENDIF

        ZERATE=PMFU (JLON, JLEV)-PMFU (JLON, IK)+(1.0_JPRB+ZFAC)*PMFUDE_RATE (JLON, JLEV)
        ZDERATE=(1.0_JPRB+ZFAC)*PMFUDE_RATE (JLON, JLEV)
        ZMFA=1.0_JPRB/MAX (YDML_PHY_EC%YRECUMF%RMFCMIN, PMFU (JLON, JLEV))
        ZUU (JLON, JLEV)=(ZUU (JLON, IK)*PMFU (JLON, IK)+ZERATE&
        &*PUEN (JLON, JLEV)-ZDERATE*ZUU (JLON, IK))*ZMFA
        ZVU (JLON, JLEV)=(ZVU (JLON, IK)*PMFU (JLON, IK)+ZERATE&
        &*PVEN (JLON, JLEV)-ZDERATE*ZVU (JLON, IK))*ZMFA
      ENDIF

    ENDIF

  
  ENDDO


  DO JLEV=3, KLEV
    IK=JLEV-1

    

    IF (LDCUM (JLON)) THEN

      IF (JLEV==IDTOP (JLON)) THEN
        ZUD (JLON, JLEV)=0.5_JPRB*(ZUU (JLON, JLEV)+PUEN (JLON, IK))
        ZVD (JLON, JLEV)=0.5_JPRB*(ZVU (JLON, JLEV)+PVEN (JLON, IK))
      ELSEIF (JLEV>IDTOP (JLON)) THEN
        ZERATE=-PMFD (JLON, JLEV)+PMFD (JLON, IK)+PMFDDE_RATE (JLON, JLEV)
        ZMFA=1.0_JPRB/MIN (-YDML_PHY_EC%YRECUMF%RMFCMIN, PMFD (JLON, JLEV))
        ZUD (JLON, JLEV)=(ZUD (JLON, IK)*PMFD (JLON, IK)-ZERATE*PUEN&
        & (JLON, IK)+PMFDDE_RATE (JLON, JLEV)*ZUD (JLON, IK))*ZMFA
        ZVD (JLON, JLEV)=(ZVD (JLON, IK)*PMFD (JLON, IK)-ZERATE*PVEN&
        & (JLON, IK)+PMFDDE_RATE (JLON, JLEV)*ZVD (JLON, IK))*ZMFA
      ENDIF

    ENDIF

  
  ENDDO

  ZMFS =1.0_JPRB

  IF (YDML_PHY_EC%YRECUMF%RMFSOLUV<=1.0_JPRB) THEN

    DO JLEV=2, KLEV

      

      IF (LDCUM (JLON).AND.JLEV>=KCTOP (JLON)-1) THEN
        ZMFMAX=(PAPH (JLON, JLEV)-PAPH (JLON, JLEV-1))*ZCONS

        IF (PMFU (JLON, JLEV)>ZMFMAX.AND.JLEV>=KCTOP (JLON))  THEN
            ZMFS =MIN (ZMFS , ZMFMAX/PMFU (JLON, JLEV))
        ENDIF

      ENDIF

    
    ENDDO

  ENDIF


  DO JLEV=1, KLEV
    
    ZMFUUS (JLON, JLEV)=PMFU (JLON, JLEV)
    ZMFDUS (JLON, JLEV)=PMFD (JLON, JLEV)

    IF (LDCUM (JLON).AND.JLEV>=KCTOP (JLON)-1) THEN
      ZMFUUS (JLON, JLEV)=PMFU (JLON, JLEV)*ZMFS 
      ZMFDUS (JLON, JLEV)=PMFD (JLON, JLEV)*ZMFS 
    ENDIF

  
  ENDDO


  IF (YDML_PHY_EC%YRECUMF%RMFSOLUV>0.0_JPRB) THEN

    

    IF (LDCUM (JLON)) THEN
      JLEV=KCBOT (JLON)
      IK=JLEV-1
      ZMFUUB =ZMFUUS (JLON, JLEV)*(ZUU (JLON, JLEV)-PUEN (JLON, IK))
      ZMFUVB =ZMFUUS (JLON, JLEV)*(ZVU (JLON, JLEV)-PVEN (JLON, IK))
    ENDIF


    

    DO JLEV=2, KLEV
      IK=JLEV-1

      

      IF (LDCUM (JLON).AND.JLEV>KCBOT (JLON)) THEN
        IKB=KCBOT (JLON)
        ZDZ=((PAPH (JLON, KLEV+1)-PAPH (JLON, JLEV))/(PAPH (JLON, KLEV+1)-PAPH (JLON, IKB)))

        IF (KTYPE (JLON)==3) THEN
          ZDZ=ZDZ*ZDZ
        ENDIF

        ZMFA=1.0_JPRB/MAX (YDML_PHY_EC%YRECUMF%RMFCMIN, ZMFUUS (JLON, JLEV))
        ZUU (JLON, JLEV)=PUEN (JLON, IK)+ZMFUUB *ZDZ*ZMFA
        ZVU (JLON, JLEV)=PVEN (JLON, IK)+ZMFUVB *ZDZ*ZMFA
        ZMFDUS (JLON, JLEV)=ZMFDUS (JLON, IKB)*ZDZ
        ZUD (JLON, JLEV)=PUEN (JLON, IK)+ZUD (JLON, IKB)-PUEN (JLON, IKB-1)
        ZVD (JLON, JLEV)=PVEN (JLON, IK)+ZVD (JLON, IKB)-PVEN (JLON, IKB-1)
      ENDIF


      IF (LDCUM (JLON).AND.JLEV>=KCTOP (JLON)) THEN

        IF (LDTDKMF) THEN
          ZUU (JLON, JLEV)=ZUU (JLON, JLEV)-YDML_PHY_EC%YRECUMF%RUVPER*SIGN (1.0_JPRB, ZUU (JLON, JLEV))
          ZVU (JLON, JLEV)=ZVU (JLON, JLEV)-YDML_PHY_EC%YRECUMF%RUVPER*SIGN (1.0_JPRB, ZVU (JLON, JLEV))
        ELSE
          ZUU (JLON, JLEV)=ZUU (JLON, JLEV)-MIN (ABS (ZUU (JLON, JLEV)), YDML_PHY_EC&
          &%YRECUMF%RUVPER)*SIGN (1.0_JPRB, ZUU (JLON, JLEV))
          ZVU (JLON, JLEV)=ZVU (JLON, JLEV)-MIN (ABS (ZVU (JLON, JLEV)), YDML_PHY_EC&
          &%YRECUMF%RUVPER)*SIGN (1.0_JPRB, ZVU (JLON, JLEV))
        ENDIF

      ENDIF

    
    ENDDO

  ENDIF

  CALL CUDUDV_OPENACC (YDCST, YDML_PHY_EC%YRECUMF, YDSPP_CONFIG, YDPERTPAR, KIDIA, KFDIA,&
  & KLON, KLEV, ITOPM2, KTYPE, KCBOT, KCTOP, LDCUM, PTSPHY, PAPH, PAP, PUEN, PVEN, ZMFUUS&
  &, ZMFDUS, PMFU, PMFD, ZUU, ZUD, ZVU, ZVD, PGP2DSPP, PTENU, PTENV, YDSTACK=YLSTACK)

  IF (YDML_PHY_EC%YRECUMF%LMFUVDIS) THEN
    
    ZSUM12 =0.0_JPRB
    ZSUM22 =0.0_JPRB

    

    DO JLEV=1, KLEV
      
      ZUV2 (JLON, JLEV)=0.0_JPRB

      IF (LDCUM (JLON).AND.JLEV>=KCTOP (JLON)-1) THEN
        ZDZ=(PAPH (JLON, JLEV+1)-PAPH (JLON, JLEV))
        ZDUTEN=PTENU (JLON, JLEV)-ZTENU (JLON, JLEV)
        ZDVTEN=PTENV (JLON, JLEV)-ZTENV (JLON, JLEV)
        ZUV2 (JLON, JLEV)=SQRT (ZDUTEN**2+ZDVTEN**2)
        ZSUM22 =ZSUM22 +ZUV2 (JLON, JLEV)*ZDZ
        ZSUM12 =ZSUM12 -(PUEN (JLON, JLEV)*ZDUTEN+PVEN (JLON, JLEV)*ZDVTEN)*ZDZ
      ENDIF

    
    ENDDO

    
    PVDISCU (JLON)=ZSUM12 *ZRG

    

    DO JLEV=1, KLEV

      

      IF (LDCUM (JLON).AND.JLEV>=KCTOP (JLON)-1) THEN
        ZTDIS=ZORCPD*ZSUM12 *ZUV2 (JLON, JLEV)/MAX (1.E-15_JPRB, ZSUM22 )
        PTENT (JLON, JLEV)=PTENT (JLON, JLEV)+ZTDIS
      ENDIF

    
    ENDDO

  ENDIF

ENDIF


IF (.NOT.YDML_PHY_EC%YRECUMF%LMFSCV.OR..NOT.YDML_PHY_EC%YRECUMF%LMFPEN) THEN

  DO JLEV=2, KLEV

    

    IF (LLO2 .AND.JLEV>=KCTOP (JLON)-1) THEN
      PMFUDE_RATE (JLON, JLEV)=0.0_JPRB
      PMFDDE_RATE (JLON, JLEV)=0.0_JPRB
    ENDIF

  
  ENDDO


  

  IF (LLO2 ) THEN
    KCTOP (JLON)=KLEV-1
    KCBOT (JLON)=KLEV-1
  ENDIF

  
ENDIF


IF (YDML_PHY_EC%YREPHY%LMFTRAC.AND.KTRAC>0) THEN

  

  IF (LDCUM (JLON).AND.KTYPE (JLON)/=3.AND.KCBOT (JLON)-KCTOP (JLON)>=1) THEN
    LLDCUM (JLON)=.TRUE.
    LLDDRAF3 (JLON)=LLDDRAF (JLON)
  ELSE
    LLDCUM (JLON)=.FALSE.
    LLDDRAF3 (JLON)=.FALSE.
  ENDIF

  
  ZMFS =1.0_JPRB

  IF (YDML_PHY_EC%YRECUMF%RMFSOLCT<=3.0_JPRB) THEN

    DO JLEV=2, KLEV

      

      IF (LLDCUM (JLON).AND.JLEV>=KCTOP (JLON)) THEN
        ZMFMAX=(PAPH (JLON, JLEV)-PAPH (JLON, JLEV-1))*0.8_JPRB*ZCONS

        IF (PMFU (JLON, JLEV)>ZMFMAX)  THEN
            ZMFS =MIN (ZMFS , ZMFMAX/PMFU (JLON, JLEV))
        ENDIF

      ENDIF

    
    ENDDO

  ENDIF


  DO JLEV=1, KLEV

    

    IF (LLDCUM (JLON).AND.JLEV>=KCTOP (JLON)-1) THEN
      ZMFUUS (JLON, JLEV)=PMFU (JLON, JLEV)*ZMFS 
      ZMFUDR (JLON, JLEV)=PMFUDE_RATE (JLON, JLEV)*ZMFS 
      ZDMFUPC (JLON, JLEV)=(PMFLXR (JLON, JLEV)+PMFLXS (JLON, JLEV))*ZMFS 
      IKB=KCBOT (JLON)

      IF (JLEV>IKB) THEN
        ZDMFUPC (JLON, JLEV)=ZDMFUPC (JLON, IKB)
      ENDIF

    ELSE
      ZMFUUS (JLON, JLEV)=0._JPRB
      ZMFUDR (JLON, JLEV)=0._JPRB
    ENDIF


    IF (LLDDRAF3 (JLON).AND.JLEV>=IDTOP (JLON)-1) THEN
      ZMFDUS (JLON, JLEV)=PMFD (JLON, JLEV)*ZMFS 
      ZMFDDR (JLON, JLEV)=PMFDDE_RATE (JLON, JLEV)*ZMFS 
      ZDMFDPC (JLON, JLEV)=0.0_JPRB
    ELSE
      ZMFDUS (JLON, JLEV)=0._JPRB
      ZMFDDR (JLON, JLEV)=0._JPRB
    ENDIF

  
  ENDDO


  IF (YDML_PHY_EC%YRECUMF%LMFSMOOTH) THEN

    DO JLEV=2, KLEV-1

      

      IF (LLDDRAF3 (JLON).AND.ZMFDUS (JLON, JLEV)<0.0_JPRB.AND.ZMFDUS (JLON, JLEV+1)==0.0_JPRB) THEN
        ZERATE=MIN (0._JPRB, ZMFDUS (JLON, JLEV)-0.5*ZMFDUS (JLON, JLEV-1))
        ZMFDUS (JLON, JLEV)=ZMFDUS (JLON, JLEV)-ZERATE
        ZMFDDR (JLON, JLEV)=ZMFDDR (JLON, JLEV)-ZERATE
        ZMFDDR (JLON, JLEV+1)=-ZMFDUS (JLON, JLEV)
      ENDIF


      IF (LLDCUM (JLON).AND.JLEV==KCTOP (JLON)) THEN
        ZERATE=MAX (0.0_JPRB, ZMFUUS (JLON, JLEV)-0.5_JPRB*ZMFUUS (JLON, JLEV+1))
        ZMFUUS (JLON, JLEV)=ZMFUUS (JLON, JLEV)-ZERATE
        ZMFUDR (JLON, JLEV)=ZMFUDR (JLON, JLEV)+ZERATE
        ZMFUDR (JLON, JLEV-1)=ZMFUUS (JLON, JLEV)
      ENDIF

    
    ENDDO


    DO JLEV=KLEV-1, 2,-1

      

      IF (LLDCUM (JLON)) THEN

        IF (ZMFUDR (JLON, JLEV)==0.0_JPRB.AND.ZMFUDR (JLON, JLEV-1)>0.0_JPRB) THEN
          ZMFUDR (JLON, JLEV)=0.5_JPRB*ZMFUDR (JLON, JLEV-1)
        ENDIF

      ENDIF

    
    ENDDO

  ENDIF


  IF (YDML_PHY_EC%YREPHY%LMFSCAV) THEN
    CALL CUCTRACER_OPENACC (YDCST, YDML_PHY_SLIN%YRCUMFS, YDML_PHY_SLIN%YRECUMF2, YDML_PHY_EC%YRECUMF,&
    & KIDIA, KFDIA, KLON, KLEV, KTRAC, KCTOP, IDTOP, KTYPE, LLDCUM, LLDDRAF3, PTSPHY, PAPH, PAP, ZMFUUS&
    &, ZMFDUS, PMFU, PMFD, ZMFUDR, ZMFDDR, ZDMFUPC, ZDMFDPC, PCEN, PTENC, PSCAV, YDSTACK=YLSTACK)
  ELSE
    ZDMFUPC (JLON,:)=0.0_JPRB
    CALL CUCTRACER_OPENACC (YDCST, YDML_PHY_SLIN%YRCUMFS, YDML_PHY_SLIN%YRECUMF2, YDML_PHY_EC%YRECUMF,&
    & KIDIA, KFDIA, KLON, KLEV, KTRAC, KCTOP, IDTOP, KTYPE, LLDCUM, LLDDRAF3, PTSPHY, PAPH, PAP, ZMFUUS&
    &, ZMFDUS, PMFU, PMFD, ZMFUDR, ZMFDDR, ZDMFUPC, ZDMFDPC, PCEN, PTENC, PSCAV0, YDSTACK=YLSTACK)
  ENDIF

ENDIF

PDISS (JLON, 1)=0.0_JPRB
ZAR=1.0_JPRB/20.89_JPRB
ZAS=1.0_JPRB/29.51_JPRB
ZBR=1.0_JPRB/1.15_JPRB
ZBS=1.0_JPRB/1.10_JPRB
ZAK=1.0_JPRB/5.09E-3_JPRB

DO JLEV=1, KLEV
  IK=MIN (JLEV+1, KLEV)
  IKD=MAX (JLEV-1, 1)
  
  PDISS (JLON, JLEV)=0.0_JPRB
  PRSUD (JLON, JLEV, 1)=0.0_JPRB
  PRSUD (JLON, JLEV, 2)=0.0_JPRB

  IF (LDCUM (JLON).AND.JLEV>=KCTOP (JLON)-1) THEN
    PLUDELI (JLON, JLEV, 3)=PMFUDE_RATE (JLON, JLEV)*(PQU (JLON, IK)-ZQENH (JLON&
    &, IK))+PMFDDE_RATE (JLON, JLEV)*(ZQD (JLON, IKD)-ZQENH (JLON, IKD))
    PLUDELI (JLON, JLEV, 4)=PMFUDE_RATE (JLON, JLEV)*(PTU (JLON, IK)-ZTENH (JLON&
    &, IK))+PMFDDE_RATE (JLON, JLEV)*(ZTD (JLON, IKD)-ZTENH (JLON, IKD))
    ZRO=YDCST%RG/(PGEOH (JLON, JLEV)-PGEOH (JLON, JLEV+1))
    PMFUDE_RATE (JLON, JLEV)=PMFUDE_RATE (JLON, JLEV)*ZRO
    PMFDDE_RATE (JLON, JLEV)=PMFDDE_RATE (JLON, JLEV)*ZRO
    ZRO=YDCST%RD*PTEN (JLON, JLEV)*(1.0_JPRB+YDCST%RETV*PQEN (JLON, JLEV))/PAP (JLON, JLEV)
    ZDUTEN=PTENU (JLON, JLEV)-ZTENU (JLON, JLEV)
    ZDVTEN=PTENV (JLON, JLEV)-ZTENV (JLON, JLEV)
    PDISS (JLON, JLEV)=ABS (PUEN (JLON, JLEV)*ZDUTEN+PVEN (JLON, JLEV)*ZDVTEN)**0.3333
    PRSUD (JLON, JLEV, 1)=1.E-3_JPRB*ZRO*(PMFLXR (JLON, JLEV)*3600._JPRB*ZAR)**ZBR
    PRSUD (JLON, JLEV, 2)=0.5*1.E-3_JPRB*ZRO*(10.0_JPRB*PMFLXS (JLON, JLEV)*3600._JPRB*ZAS)**ZBS
  ELSE
    PMFU (JLON, JLEV)=0.0_JPRB
    PMFD (JLON, JLEV)=0.0_JPRB
    PLUDE (JLON, JLEV)=0.0_JPRB
    PLUDELI (JLON, JLEV, 1)=0.0_JPRB
    PLUDELI (JLON, JLEV, 2)=0.0_JPRB
    PLUDELI (JLON, JLEV, 3)=0.0_JPRB
    PLUDELI (JLON, JLEV, 4)=0.0_JPRB
    PSNDE (JLON, JLEV, 1)=0.0_JPRB
    PSNDE (JLON, JLEV, 2)=0.0_JPRB
    PTU (JLON, JLEV)=PTEN (JLON, JLEV)
    PQU (JLON, JLEV)=PQEN (JLON, JLEV)
    PLU (JLON, JLEV)=0.0_JPRB
    PENTH (JLON, JLEV)=0.0_JPRB
    PMFUDE_RATE (JLON, JLEV)=0.0_JPRB
    PMFDDE_RATE (JLON, JLEV)=0.0_JPRB
  ENDIF

  
ENDDO



ENDSUBROUTINE CUMASTRN_OPENACC

! e56ac8e1f86b1a9cc13b38d73abbf48f96ba2f2a
