MODULE UTIL_TECUCONVCA_MOD

USE YOE_CUCONVCA, ONLY : TECUCONVCA

INTERFACE SAVE
MODULE PROCEDURE SAVE_TECUCONVCA
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TECUCONVCA
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TECUCONVCA
END INTERFACE

INTERFACE HOST
MODULE PROCEDURE HOST_TECUCONVCA
END INTERFACE

     
INTERFACE CRC64
MODULE PROCEDURE CRC64_TECUCONVCA
END INTERFACE

INTERFACE WIPE
MODULE PROCEDURE WIPE_TECUCONVCA
END INTERFACE

INTERFACE SIZE
MODULE PROCEDURE SIZE_TECUCONVCA
END INTERFACE


CONTAINS

SUBROUTINE SAVE_TECUCONVCA (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TECUCONVCA), INTENT (IN), TARGET :: YD
LOGICAL :: LNBEW, LNBLS, LNBNS, LNBSS, LNCELLCU, LNFERTCU, LNRNBLS, LNRNBSS, LRCAPECONVCA, LRCUCONVCA
LOGICAL :: LRLATDEP, LRLATLONNBLS, LRLATLONNBSS, LRLONDEP, LRNLCONVCA, LRWASALIVE, LRWGHTCU, LSLDDLAT, LSLDLAT, LSLDLONG
LOGICAL :: LSLLAT, LSLLONG
WRITE (KLUN) YD%NLIVES
WRITE (KLUN) YD%NFERTYRS
WRITE (KLUN) YD%NSPINUP
LNCELLCU = ALLOCATED (YD%NCELLCU)
WRITE (KLUN) LNCELLCU
IF (LNCELLCU) THEN
  WRITE (KLUN) LBOUND (YD%NCELLCU)
  WRITE (KLUN) UBOUND (YD%NCELLCU)
  WRITE (KLUN) YD%NCELLCU
ENDIF
LNFERTCU = ALLOCATED (YD%NFERTCU)
WRITE (KLUN) LNFERTCU
IF (LNFERTCU) THEN
  WRITE (KLUN) LBOUND (YD%NFERTCU)
  WRITE (KLUN) UBOUND (YD%NFERTCU)
  WRITE (KLUN) YD%NFERTCU
ENDIF
LNBLS = ALLOCATED (YD%NBLS)
WRITE (KLUN) LNBLS
IF (LNBLS) THEN
  WRITE (KLUN) LBOUND (YD%NBLS)
  WRITE (KLUN) UBOUND (YD%NBLS)
  WRITE (KLUN) YD%NBLS
ENDIF
LNBSS = ALLOCATED (YD%NBSS)
WRITE (KLUN) LNBSS
IF (LNBSS) THEN
  WRITE (KLUN) LBOUND (YD%NBSS)
  WRITE (KLUN) UBOUND (YD%NBSS)
  WRITE (KLUN) YD%NBSS
ENDIF
LNRNBLS = ALLOCATED (YD%NRNBLS)
WRITE (KLUN) LNRNBLS
IF (LNRNBLS) THEN
  WRITE (KLUN) LBOUND (YD%NRNBLS)
  WRITE (KLUN) UBOUND (YD%NRNBLS)
  WRITE (KLUN) YD%NRNBLS
ENDIF
LNRNBSS = ALLOCATED (YD%NRNBSS)
WRITE (KLUN) LNRNBSS
IF (LNRNBSS) THEN
  WRITE (KLUN) LBOUND (YD%NRNBSS)
  WRITE (KLUN) UBOUND (YD%NRNBSS)
  WRITE (KLUN) YD%NRNBSS
ENDIF
LNBEW = ALLOCATED (YD%NBEW)
WRITE (KLUN) LNBEW
IF (LNBEW) THEN
  WRITE (KLUN) LBOUND (YD%NBEW)
  WRITE (KLUN) UBOUND (YD%NBEW)
  WRITE (KLUN) YD%NBEW
ENDIF
LNBNS = ALLOCATED (YD%NBNS)
WRITE (KLUN) LNBNS
IF (LNBNS) THEN
  WRITE (KLUN) LBOUND (YD%NBNS)
  WRITE (KLUN) UBOUND (YD%NBNS)
  WRITE (KLUN) YD%NBNS
ENDIF
LRCUCONVCA = ALLOCATED (YD%RCUCONVCA)
WRITE (KLUN) LRCUCONVCA
IF (LRCUCONVCA) THEN
  WRITE (KLUN) LBOUND (YD%RCUCONVCA)
  WRITE (KLUN) UBOUND (YD%RCUCONVCA)
  WRITE (KLUN) YD%RCUCONVCA
ENDIF
LRNLCONVCA = ALLOCATED (YD%RNLCONVCA)
WRITE (KLUN) LRNLCONVCA
IF (LRNLCONVCA) THEN
  WRITE (KLUN) LBOUND (YD%RNLCONVCA)
  WRITE (KLUN) UBOUND (YD%RNLCONVCA)
  WRITE (KLUN) YD%RNLCONVCA
ENDIF
LRCAPECONVCA = ALLOCATED (YD%RCAPECONVCA)
WRITE (KLUN) LRCAPECONVCA
IF (LRCAPECONVCA) THEN
  WRITE (KLUN) LBOUND (YD%RCAPECONVCA)
  WRITE (KLUN) UBOUND (YD%RCAPECONVCA)
  WRITE (KLUN) YD%RCAPECONVCA
ENDIF
LRWASALIVE = ALLOCATED (YD%RWASALIVE)
WRITE (KLUN) LRWASALIVE
IF (LRWASALIVE) THEN
  WRITE (KLUN) LBOUND (YD%RWASALIVE)
  WRITE (KLUN) UBOUND (YD%RWASALIVE)
  WRITE (KLUN) YD%RWASALIVE
ENDIF
LRWGHTCU = ALLOCATED (YD%RWGHTCU)
WRITE (KLUN) LRWGHTCU
IF (LRWGHTCU) THEN
  WRITE (KLUN) LBOUND (YD%RWGHTCU)
  WRITE (KLUN) UBOUND (YD%RWGHTCU)
  WRITE (KLUN) YD%RWGHTCU
ENDIF
LRLATLONNBLS = ALLOCATED (YD%RLATLONNBLS)
WRITE (KLUN) LRLATLONNBLS
IF (LRLATLONNBLS) THEN
  WRITE (KLUN) LBOUND (YD%RLATLONNBLS)
  WRITE (KLUN) UBOUND (YD%RLATLONNBLS)
  WRITE (KLUN) YD%RLATLONNBLS
ENDIF
LRLATLONNBSS = ALLOCATED (YD%RLATLONNBSS)
WRITE (KLUN) LRLATLONNBSS
IF (LRLATLONNBSS) THEN
  WRITE (KLUN) LBOUND (YD%RLATLONNBSS)
  WRITE (KLUN) UBOUND (YD%RLATLONNBSS)
  WRITE (KLUN) YD%RLATLONNBSS
ENDIF
WRITE (KLUN) YD%RPROB_SURVIVE
WRITE (KLUN) YD%RPROB_BIRTH
WRITE (KLUN) YD%RPROB_FUN_FERT_S
WRITE (KLUN) YD%RPROB_FUN_UW_DW_S
WRITE (KLUN) YD%RPROB_FUN_FERT_B
WRITE (KLUN) YD%RPROB_FUN_UW_DW_B
LRLONDEP = ALLOCATED (YD%RLONDEP)
WRITE (KLUN) LRLONDEP
IF (LRLONDEP) THEN
  WRITE (KLUN) LBOUND (YD%RLONDEP)
  WRITE (KLUN) UBOUND (YD%RLONDEP)
  WRITE (KLUN) YD%RLONDEP
ENDIF
LRLATDEP = ALLOCATED (YD%RLATDEP)
WRITE (KLUN) LRLATDEP
IF (LRLATDEP) THEN
  WRITE (KLUN) LBOUND (YD%RLATDEP)
  WRITE (KLUN) UBOUND (YD%RLATDEP)
  WRITE (KLUN) YD%RLATDEP
ENDIF
WRITE (KLUN) YD%RCA_SEEDPROB
WRITE (KLUN) YD%RCADELX
WRITE (KLUN) YD%LCUCONV_CA
WRITE (KLUN) YD%LCA_ADVECT
WRITE (KLUN) YD%LCA_GLOBAL
WRITE (KLUN) YD%LCA_SMOOTH
WRITE (KLUN) YD%LCA_TEST
WRITE (KLUN) YD%LCA_ADVTEST
WRITE (KLUN) YD%LCA_RANTROP
WRITE (KLUN) YD%LCA_NBDEBUG
WRITE (KLUN) YD%LCA_EXTRACT
WRITE (KLUN) YD%CA_FORC
WRITE (KLUN) YD%CA_WIND
WRITE (KLUN) YD%CA_PROB
WRITE (KLUN) YD%NFRCASEED
WRITE (KLUN) YD%NTESTPROC
WRITE (KLUN) YD%NTESTGP
WRITE (KLUN) YD%NDXUNREAL
WRITE (KLUN) YD%NDYUNREAL
LSLLONG = ALLOCATED (YD%SLLONG)
WRITE (KLUN) LSLLONG
IF (LSLLONG) THEN
  WRITE (KLUN) LBOUND (YD%SLLONG)
  WRITE (KLUN) UBOUND (YD%SLLONG)
  WRITE (KLUN) YD%SLLONG
ENDIF
LSLLAT = ALLOCATED (YD%SLLAT)
WRITE (KLUN) LSLLAT
IF (LSLLAT) THEN
  WRITE (KLUN) LBOUND (YD%SLLAT)
  WRITE (KLUN) UBOUND (YD%SLLAT)
  WRITE (KLUN) YD%SLLAT
ENDIF
LSLDLONG = ALLOCATED (YD%SLDLONG)
WRITE (KLUN) LSLDLONG
IF (LSLDLONG) THEN
  WRITE (KLUN) LBOUND (YD%SLDLONG)
  WRITE (KLUN) UBOUND (YD%SLDLONG)
  WRITE (KLUN) YD%SLDLONG
ENDIF
LSLDLAT = ALLOCATED (YD%SLDLAT)
WRITE (KLUN) LSLDLAT
IF (LSLDLAT) THEN
  WRITE (KLUN) LBOUND (YD%SLDLAT)
  WRITE (KLUN) UBOUND (YD%SLDLAT)
  WRITE (KLUN) YD%SLDLAT
ENDIF
LSLDDLAT = ALLOCATED (YD%SLDDLAT)
WRITE (KLUN) LSLDDLAT
IF (LSLDDLAT) THEN
  WRITE (KLUN) LBOUND (YD%SLDDLAT)
  WRITE (KLUN) UBOUND (YD%SLDDLAT)
  WRITE (KLUN) YD%SLDDLAT
ENDIF
END SUBROUTINE

SUBROUTINE LOAD_TECUCONVCA (KLUN, YD)
USE PARKIND1, ONLY : JPRD

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TECUCONVCA), INTENT (OUT), TARGET :: YD
INTEGER :: IL1(1), IU1(1), IL2(2), IU2(2), IL3(3), IU3(3), IL4(4), IU4(4)
LOGICAL :: LNBEW, LNBLS, LNBNS, LNBSS, LNCELLCU, LNFERTCU, LNRNBLS, LNRNBSS, LRCAPECONVCA, LRCUCONVCA
LOGICAL :: LRLATDEP, LRLATLONNBLS, LRLATLONNBSS, LRLONDEP, LRNLCONVCA, LRWASALIVE, LRWGHTCU, LSLDDLAT, LSLDLAT, LSLDLONG
LOGICAL :: LSLLAT, LSLLONG
REAL(KIND=JPRD) :: ZTMP0
REAL(KIND=JPRD), ALLOCATABLE :: ZTMP1 (:)
REAL(KIND=JPRD), ALLOCATABLE :: ZTMP2 (:,:)
REAL(KIND=JPRD), ALLOCATABLE :: ZTMP3 (:,:,:)
REAL(KIND=JPRD), ALLOCATABLE :: ZTMP4 (:,:,:,:)
READ (KLUN) YD%NLIVES
READ (KLUN) YD%NFERTYRS
READ (KLUN) YD%NSPINUP
READ (KLUN) LNCELLCU
IF (LNCELLCU) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%NCELLCU (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%NCELLCU
ENDIF
READ (KLUN) LNFERTCU
IF (LNFERTCU) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%NFERTCU (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%NFERTCU
ENDIF
READ (KLUN) LNBLS
IF (LNBLS) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%NBLS (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%NBLS
ENDIF
READ (KLUN) LNBSS
IF (LNBSS) THEN
  READ (KLUN) IL4
  READ (KLUN) IU4
  ALLOCATE (YD%NBSS (IL4(1):IU4(1), IL4(2):IU4(2), IL4(3):IU4(3), IL4(4):IU4(4)))
  READ (KLUN) YD%NBSS
ENDIF
READ (KLUN) LNRNBLS
IF (LNRNBLS) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NRNBLS (IL1(1):IU1(1)))
  READ (KLUN) YD%NRNBLS
ENDIF
READ (KLUN) LNRNBSS
IF (LNRNBSS) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%NRNBSS (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%NRNBSS
ENDIF
READ (KLUN) LNBEW
IF (LNBEW) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%NBEW (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  READ (KLUN) YD%NBEW
ENDIF
READ (KLUN) LNBNS
IF (LNBNS) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%NBNS (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  READ (KLUN) YD%NBNS
ENDIF
READ (KLUN) LRCUCONVCA
IF (LRCUCONVCA) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%RCUCONVCA (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(YD%RCUCONVCA,1):UBOUND(YD%RCUCONVCA,1)))
  READ (KLUN) ZTMP1
  YD%RCUCONVCA = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LRNLCONVCA
IF (LRNLCONVCA) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%RNLCONVCA (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(YD%RNLCONVCA,1):UBOUND(YD%RNLCONVCA,1)))
  READ (KLUN) ZTMP1
  YD%RNLCONVCA = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LRCAPECONVCA
IF (LRCAPECONVCA) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%RCAPECONVCA (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(YD%RCAPECONVCA,1):UBOUND(YD%RCAPECONVCA,1)))
  READ (KLUN) ZTMP1
  YD%RCAPECONVCA = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LRWASALIVE
IF (LRWASALIVE) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%RWASALIVE (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(YD%RWASALIVE,1):UBOUND(YD%RWASALIVE,1)))
  READ (KLUN) ZTMP1
  YD%RWASALIVE = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LRWGHTCU
IF (LRWGHTCU) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%RWGHTCU (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(YD%RWGHTCU,1):UBOUND(YD%RWGHTCU,1)))
  READ (KLUN) ZTMP1
  YD%RWGHTCU = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LRLATLONNBLS
IF (LRLATLONNBLS) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%RLATLONNBLS (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  ALLOCATE (ZTMP3(LBOUND(YD%RLATLONNBLS,1):UBOUND(YD%RLATLONNBLS,1), LBOUND(YD%RLATLONNBLS,2):UBOUND(YD%RLATLONNBLS,2), LBOUND(YD%RLATLONNBLS,3):UBOUND(YD%RLATLONNBLS,3)))
  READ (KLUN) ZTMP3
  YD%RLATLONNBLS = ZTMP3
  DEALLOCATE (ZTMP3)
ENDIF
READ (KLUN) LRLATLONNBSS
IF (LRLATLONNBSS) THEN
  READ (KLUN) IL4
  READ (KLUN) IU4
  ALLOCATE (YD%RLATLONNBSS (IL4(1):IU4(1), IL4(2):IU4(2), IL4(3):IU4(3), IL4(4):IU4(4)))
  ALLOCATE (ZTMP4(LBOUND(YD%RLATLONNBSS,1):UBOUND(YD%RLATLONNBSS,1), LBOUND(YD%RLATLONNBSS,2):UBOUND(YD%RLATLONNBSS,2), LBOUND(YD%RLATLONNBSS,3):UBOUND(YD%RLATLONNBSS,3), LBOUND(YD%RLATLONNBSS,4):UBOUND(YD%RLATLONNBSS,4)))
  READ (KLUN) ZTMP4
  YD%RLATLONNBSS = ZTMP4
  DEALLOCATE (ZTMP4)
ENDIF
ALLOCATE (ZTMP2(LBOUND(YD%RPROB_SURVIVE,1):UBOUND(YD%RPROB_SURVIVE,1), LBOUND(YD%RPROB_SURVIVE,2):UBOUND(YD%RPROB_SURVIVE,2)))
READ (KLUN) ZTMP2
YD%RPROB_SURVIVE = ZTMP2
DEALLOCATE (ZTMP2)
ALLOCATE (ZTMP2(LBOUND(YD%RPROB_BIRTH,1):UBOUND(YD%RPROB_BIRTH,1), LBOUND(YD%RPROB_BIRTH,2):UBOUND(YD%RPROB_BIRTH,2)))
READ (KLUN) ZTMP2
YD%RPROB_BIRTH = ZTMP2
DEALLOCATE (ZTMP2)
ALLOCATE (ZTMP1(LBOUND(YD%RPROB_FUN_FERT_S,1):UBOUND(YD%RPROB_FUN_FERT_S,1)))
READ (KLUN) ZTMP1
YD%RPROB_FUN_FERT_S = ZTMP1
DEALLOCATE (ZTMP1)
ALLOCATE (ZTMP1(LBOUND(YD%RPROB_FUN_UW_DW_S,1):UBOUND(YD%RPROB_FUN_UW_DW_S,1)))
READ (KLUN) ZTMP1
YD%RPROB_FUN_UW_DW_S = ZTMP1
DEALLOCATE (ZTMP1)
ALLOCATE (ZTMP1(LBOUND(YD%RPROB_FUN_FERT_B,1):UBOUND(YD%RPROB_FUN_FERT_B,1)))
READ (KLUN) ZTMP1
YD%RPROB_FUN_FERT_B = ZTMP1
DEALLOCATE (ZTMP1)
ALLOCATE (ZTMP1(LBOUND(YD%RPROB_FUN_UW_DW_B,1):UBOUND(YD%RPROB_FUN_UW_DW_B,1)))
READ (KLUN) ZTMP1
YD%RPROB_FUN_UW_DW_B = ZTMP1
DEALLOCATE (ZTMP1)
READ (KLUN) LRLONDEP
IF (LRLONDEP) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%RLONDEP (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  ALLOCATE (ZTMP3(LBOUND(YD%RLONDEP,1):UBOUND(YD%RLONDEP,1), LBOUND(YD%RLONDEP,2):UBOUND(YD%RLONDEP,2), LBOUND(YD%RLONDEP,3):UBOUND(YD%RLONDEP,3)))
  READ (KLUN) ZTMP3
  YD%RLONDEP = ZTMP3
  DEALLOCATE (ZTMP3)
ENDIF
READ (KLUN) LRLATDEP
IF (LRLATDEP) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%RLATDEP (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  ALLOCATE (ZTMP3(LBOUND(YD%RLATDEP,1):UBOUND(YD%RLATDEP,1), LBOUND(YD%RLATDEP,2):UBOUND(YD%RLATDEP,2), LBOUND(YD%RLATDEP,3):UBOUND(YD%RLATDEP,3)))
  READ (KLUN) ZTMP3
  YD%RLATDEP = ZTMP3
  DEALLOCATE (ZTMP3)
ENDIF
READ (KLUN) ZTMP0
YD%RCA_SEEDPROB = ZTMP0
READ (KLUN) ZTMP0
YD%RCADELX = ZTMP0
READ (KLUN) YD%LCUCONV_CA
READ (KLUN) YD%LCA_ADVECT
READ (KLUN) YD%LCA_GLOBAL
READ (KLUN) YD%LCA_SMOOTH
READ (KLUN) YD%LCA_TEST
READ (KLUN) YD%LCA_ADVTEST
READ (KLUN) YD%LCA_RANTROP
READ (KLUN) YD%LCA_NBDEBUG
READ (KLUN) YD%LCA_EXTRACT
READ (KLUN) YD%CA_FORC
READ (KLUN) YD%CA_WIND
READ (KLUN) YD%CA_PROB
READ (KLUN) YD%NFRCASEED
READ (KLUN) YD%NTESTPROC
READ (KLUN) YD%NTESTGP
READ (KLUN) YD%NDXUNREAL
READ (KLUN) YD%NDYUNREAL
READ (KLUN) LSLLONG
IF (LSLLONG) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%SLLONG (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(YD%SLLONG,1):UBOUND(YD%SLLONG,1)))
  READ (KLUN) ZTMP1
  YD%SLLONG = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LSLLAT
IF (LSLLAT) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%SLLAT (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(YD%SLLAT,1):UBOUND(YD%SLLAT,1)))
  READ (KLUN) ZTMP1
  YD%SLLAT = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LSLDLONG
IF (LSLDLONG) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%SLDLONG (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(YD%SLDLONG,1):UBOUND(YD%SLDLONG,1)))
  READ (KLUN) ZTMP1
  YD%SLDLONG = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LSLDLAT
IF (LSLDLAT) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%SLDLAT (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(YD%SLDLAT,1):UBOUND(YD%SLDLAT,1)))
  READ (KLUN) ZTMP1
  YD%SLDLAT = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LSLDDLAT
IF (LSLDDLAT) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%SLDDLAT (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(YD%SLDDLAT,1):UBOUND(YD%SLDDLAT,1)))
  READ (KLUN) ZTMP1
  YD%SLDDLAT = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
END SUBROUTINE


SUBROUTINE COPY_TECUCONVCA (YD, LDCREATED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TECUCONVCA), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI
LOGICAL :: LNBEW, LNBLS, LNBNS, LNBSS, LNCELLCU, LNFERTCU, LNRNBLS, LNRNBSS, LRCAPECONVCA, LRCUCONVCA
LOGICAL :: LRLATDEP, LRLATLONNBLS, LRLATLONNBSS, LRLONDEP, LRNLCONVCA, LRWASALIVE, LRWGHTCU, LSLDDLAT, LSLDLAT, LSLDLONG
LOGICAL :: LSLLAT, LSLLONG

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$acc enter data create (YD)
  !$acc update device (YD)
ENDIF



LNCELLCU = ALLOCATED (YD%NCELLCU)
IF (LNCELLCU) THEN
  !$acc enter data create (YD%NCELLCU)
  !$acc update device (YD%NCELLCU)
  !$acc enter data attach (YD%NCELLCU)
ENDIF

LNFERTCU = ALLOCATED (YD%NFERTCU)
IF (LNFERTCU) THEN
  !$acc enter data create (YD%NFERTCU)
  !$acc update device (YD%NFERTCU)
  !$acc enter data attach (YD%NFERTCU)
ENDIF

LNBLS = ALLOCATED (YD%NBLS)
IF (LNBLS) THEN
  !$acc enter data create (YD%NBLS)
  !$acc update device (YD%NBLS)
  !$acc enter data attach (YD%NBLS)
ENDIF

LNBSS = ALLOCATED (YD%NBSS)
IF (LNBSS) THEN
  !$acc enter data create (YD%NBSS)
  !$acc update device (YD%NBSS)
  !$acc enter data attach (YD%NBSS)
ENDIF

LNRNBLS = ALLOCATED (YD%NRNBLS)
IF (LNRNBLS) THEN
  !$acc enter data create (YD%NRNBLS)
  !$acc update device (YD%NRNBLS)
  !$acc enter data attach (YD%NRNBLS)
ENDIF

LNRNBSS = ALLOCATED (YD%NRNBSS)
IF (LNRNBSS) THEN
  !$acc enter data create (YD%NRNBSS)
  !$acc update device (YD%NRNBSS)
  !$acc enter data attach (YD%NRNBSS)
ENDIF

LNBEW = ALLOCATED (YD%NBEW)
IF (LNBEW) THEN
  !$acc enter data create (YD%NBEW)
  !$acc update device (YD%NBEW)
  !$acc enter data attach (YD%NBEW)
ENDIF

LNBNS = ALLOCATED (YD%NBNS)
IF (LNBNS) THEN
  !$acc enter data create (YD%NBNS)
  !$acc update device (YD%NBNS)
  !$acc enter data attach (YD%NBNS)
ENDIF

LRCUCONVCA = ALLOCATED (YD%RCUCONVCA)
IF (LRCUCONVCA) THEN
  !$acc enter data create (YD%RCUCONVCA)
  !$acc update device (YD%RCUCONVCA)
  !$acc enter data attach (YD%RCUCONVCA)
ENDIF

LRNLCONVCA = ALLOCATED (YD%RNLCONVCA)
IF (LRNLCONVCA) THEN
  !$acc enter data create (YD%RNLCONVCA)
  !$acc update device (YD%RNLCONVCA)
  !$acc enter data attach (YD%RNLCONVCA)
ENDIF

LRCAPECONVCA = ALLOCATED (YD%RCAPECONVCA)
IF (LRCAPECONVCA) THEN
  !$acc enter data create (YD%RCAPECONVCA)
  !$acc update device (YD%RCAPECONVCA)
  !$acc enter data attach (YD%RCAPECONVCA)
ENDIF

LRWASALIVE = ALLOCATED (YD%RWASALIVE)
IF (LRWASALIVE) THEN
  !$acc enter data create (YD%RWASALIVE)
  !$acc update device (YD%RWASALIVE)
  !$acc enter data attach (YD%RWASALIVE)
ENDIF

LRWGHTCU = ALLOCATED (YD%RWGHTCU)
IF (LRWGHTCU) THEN
  !$acc enter data create (YD%RWGHTCU)
  !$acc update device (YD%RWGHTCU)
  !$acc enter data attach (YD%RWGHTCU)
ENDIF

LRLATLONNBLS = ALLOCATED (YD%RLATLONNBLS)
IF (LRLATLONNBLS) THEN
  !$acc enter data create (YD%RLATLONNBLS)
  !$acc update device (YD%RLATLONNBLS)
  !$acc enter data attach (YD%RLATLONNBLS)
ENDIF

LRLATLONNBSS = ALLOCATED (YD%RLATLONNBSS)
IF (LRLATLONNBSS) THEN
  !$acc enter data create (YD%RLATLONNBSS)
  !$acc update device (YD%RLATLONNBSS)
  !$acc enter data attach (YD%RLATLONNBSS)
ENDIF







LRLONDEP = ALLOCATED (YD%RLONDEP)
IF (LRLONDEP) THEN
  !$acc enter data create (YD%RLONDEP)
  !$acc update device (YD%RLONDEP)
  !$acc enter data attach (YD%RLONDEP)
ENDIF

LRLATDEP = ALLOCATED (YD%RLATDEP)
IF (LRLATDEP) THEN
  !$acc enter data create (YD%RLATDEP)
  !$acc update device (YD%RLATDEP)
  !$acc enter data attach (YD%RLATDEP)
ENDIF




















LSLLONG = ALLOCATED (YD%SLLONG)
IF (LSLLONG) THEN
  !$acc enter data create (YD%SLLONG)
  !$acc update device (YD%SLLONG)
  !$acc enter data attach (YD%SLLONG)
ENDIF

LSLLAT = ALLOCATED (YD%SLLAT)
IF (LSLLAT) THEN
  !$acc enter data create (YD%SLLAT)
  !$acc update device (YD%SLLAT)
  !$acc enter data attach (YD%SLLAT)
ENDIF

LSLDLONG = ALLOCATED (YD%SLDLONG)
IF (LSLDLONG) THEN
  !$acc enter data create (YD%SLDLONG)
  !$acc update device (YD%SLDLONG)
  !$acc enter data attach (YD%SLDLONG)
ENDIF

LSLDLAT = ALLOCATED (YD%SLDLAT)
IF (LSLDLAT) THEN
  !$acc enter data create (YD%SLDLAT)
  !$acc update device (YD%SLDLAT)
  !$acc enter data attach (YD%SLDLAT)
ENDIF

LSLDDLAT = ALLOCATED (YD%SLDDLAT)
IF (LSLDDLAT) THEN
  !$acc enter data create (YD%SLDDLAT)
  !$acc update device (YD%SLDDLAT)
  !$acc enter data attach (YD%SLDDLAT)
ENDIF

END SUBROUTINE

SUBROUTINE HOST_TECUCONVCA (YD)

IMPLICIT NONE
TYPE (TECUCONVCA), TARGET :: YD
LOGICAL :: LNBEW, LNBLS, LNBNS, LNBSS, LNCELLCU, LNFERTCU, LNRNBLS, LNRNBSS, LRCAPECONVCA, LRCUCONVCA
LOGICAL :: LRLATDEP, LRLATLONNBLS, LRLATLONNBSS, LRLONDEP, LRNLCONVCA, LRWASALIVE, LRWGHTCU, LSLDDLAT, LSLDLAT, LSLDLONG
LOGICAL :: LSLLAT, LSLLONG


















































END SUBROUTINE

     

SUBROUTINE CRC64_TECUCONVCA (YD, KLUN, CDPATH)
USE CRC64_INTRINSIC

IMPLICIT NONE
TYPE (TECUCONVCA), TARGET :: YD
INTEGER, INTENT (IN) :: KLUN
CHARACTER(LEN=*), INTENT (IN) :: CDPATH
CHARACTER(LEN=128) :: CLIND
LOGICAL :: LNBEW, LNBLS, LNBNS, LNBSS, LNCELLCU, LNFERTCU, LNRNBLS, LNRNBSS, LRCAPECONVCA, LRCUCONVCA
LOGICAL :: LRLATDEP, LRLATLONNBLS, LRLATLONNBSS, LRLONDEP, LRNLCONVCA, LRWASALIVE, LRWGHTCU, LSLDDLAT, LSLDLAT, LSLDLONG
LOGICAL :: LSLLAT, LSLLONG
WRITE (KLUN, '(Z16.16," ",A)') CRC64 (YD%NLIVES), CDPATH//'%NLIVES'

WRITE (KLUN, '(Z16.16," ",A)') CRC64 (YD%NFERTYRS), CDPATH//'%NFERTYRS'

WRITE (KLUN, '(Z16.16," ",A)') CRC64 (YD%NSPINUP), CDPATH//'%NSPINUP'

WRITE (KLUN, '(Z16.16," ",A)') CRC64 (YD%NCELLCU), CDPATH//'%NCELLCU'

WRITE (KLUN, '(Z16.16," ",A)') CRC64 (YD%NFERTCU), CDPATH//'%NFERTCU'

WRITE (KLUN, '(Z16.16," ",A)') CRC64 (YD%NBLS), CDPATH//'%NBLS'

WRITE (KLUN, '(Z16.16," ",A)') CRC64 (YD%NBSS), CDPATH//'%NBSS'

WRITE (KLUN, '(Z16.16," ",A)') CRC64 (YD%NRNBLS), CDPATH//'%NRNBLS'

WRITE (KLUN, '(Z16.16," ",A)') CRC64 (YD%NRNBSS), CDPATH//'%NRNBSS'

WRITE (KLUN, '(Z16.16," ",A)') CRC64 (YD%NBEW), CDPATH//'%NBEW'

WRITE (KLUN, '(Z16.16," ",A)') CRC64 (YD%NBNS), CDPATH//'%NBNS'

WRITE (KLUN, '(Z16.16," ",A)') CRC64 (YD%RCUCONVCA), CDPATH//'%RCUCONVCA'

WRITE (KLUN, '(Z16.16," ",A)') CRC64 (YD%RNLCONVCA), CDPATH//'%RNLCONVCA'

WRITE (KLUN, '(Z16.16," ",A)') CRC64 (YD%RCAPECONVCA), CDPATH//'%RCAPECONVCA'

WRITE (KLUN, '(Z16.16," ",A)') CRC64 (YD%RWASALIVE), CDPATH//'%RWASALIVE'

WRITE (KLUN, '(Z16.16," ",A)') CRC64 (YD%RWGHTCU), CDPATH//'%RWGHTCU'

WRITE (KLUN, '(Z16.16," ",A)') CRC64 (YD%RLATLONNBLS), CDPATH//'%RLATLONNBLS'

WRITE (KLUN, '(Z16.16," ",A)') CRC64 (YD%RLATLONNBSS), CDPATH//'%RLATLONNBSS'

WRITE (KLUN, '(Z16.16," ",A)') CRC64 (YD%RPROB_SURVIVE), CDPATH//'%RPROB_SURVIVE'

WRITE (KLUN, '(Z16.16," ",A)') CRC64 (YD%RPROB_BIRTH), CDPATH//'%RPROB_BIRTH'

WRITE (KLUN, '(Z16.16," ",A)') CRC64 (YD%RPROB_FUN_FERT_S), CDPATH//'%RPROB_FUN_FERT_S'

WRITE (KLUN, '(Z16.16," ",A)') CRC64 (YD%RPROB_FUN_UW_DW_S), CDPATH//'%RPROB_FUN_UW_DW_S'

WRITE (KLUN, '(Z16.16," ",A)') CRC64 (YD%RPROB_FUN_FERT_B), CDPATH//'%RPROB_FUN_FERT_B'

WRITE (KLUN, '(Z16.16," ",A)') CRC64 (YD%RPROB_FUN_UW_DW_B), CDPATH//'%RPROB_FUN_UW_DW_B'

WRITE (KLUN, '(Z16.16," ",A)') CRC64 (YD%RLONDEP), CDPATH//'%RLONDEP'

WRITE (KLUN, '(Z16.16," ",A)') CRC64 (YD%RLATDEP), CDPATH//'%RLATDEP'

WRITE (KLUN, '(Z16.16," ",A)') CRC64 (YD%RCA_SEEDPROB), CDPATH//'%RCA_SEEDPROB'

WRITE (KLUN, '(Z16.16," ",A)') CRC64 (YD%RCADELX), CDPATH//'%RCADELX'

WRITE (KLUN, '(Z16.16," ",A)') CRC64 (YD%LCUCONV_CA), CDPATH//'%LCUCONV_CA'

WRITE (KLUN, '(Z16.16," ",A)') CRC64 (YD%LCA_ADVECT), CDPATH//'%LCA_ADVECT'

WRITE (KLUN, '(Z16.16," ",A)') CRC64 (YD%LCA_GLOBAL), CDPATH//'%LCA_GLOBAL'

WRITE (KLUN, '(Z16.16," ",A)') CRC64 (YD%LCA_SMOOTH), CDPATH//'%LCA_SMOOTH'

WRITE (KLUN, '(Z16.16," ",A)') CRC64 (YD%LCA_TEST), CDPATH//'%LCA_TEST'

WRITE (KLUN, '(Z16.16," ",A)') CRC64 (YD%LCA_ADVTEST), CDPATH//'%LCA_ADVTEST'

WRITE (KLUN, '(Z16.16," ",A)') CRC64 (YD%LCA_RANTROP), CDPATH//'%LCA_RANTROP'

WRITE (KLUN, '(Z16.16," ",A)') CRC64 (YD%LCA_NBDEBUG), CDPATH//'%LCA_NBDEBUG'

WRITE (KLUN, '(Z16.16," ",A)') CRC64 (YD%LCA_EXTRACT), CDPATH//'%LCA_EXTRACT'

WRITE (KLUN, '(Z16.16," ",A)') CRC64 (YD%CA_FORC), CDPATH//'%CA_FORC'

WRITE (KLUN, '(Z16.16," ",A)') CRC64 (YD%CA_WIND), CDPATH//'%CA_WIND'

WRITE (KLUN, '(Z16.16," ",A)') CRC64 (YD%CA_PROB), CDPATH//'%CA_PROB'

WRITE (KLUN, '(Z16.16," ",A)') CRC64 (YD%NFRCASEED), CDPATH//'%NFRCASEED'

WRITE (KLUN, '(Z16.16," ",A)') CRC64 (YD%NTESTPROC), CDPATH//'%NTESTPROC'

WRITE (KLUN, '(Z16.16," ",A)') CRC64 (YD%NTESTGP), CDPATH//'%NTESTGP'

WRITE (KLUN, '(Z16.16," ",A)') CRC64 (YD%NDXUNREAL), CDPATH//'%NDXUNREAL'

WRITE (KLUN, '(Z16.16," ",A)') CRC64 (YD%NDYUNREAL), CDPATH//'%NDYUNREAL'

WRITE (KLUN, '(Z16.16," ",A)') CRC64 (YD%SLLONG), CDPATH//'%SLLONG'

WRITE (KLUN, '(Z16.16," ",A)') CRC64 (YD%SLLAT), CDPATH//'%SLLAT'

WRITE (KLUN, '(Z16.16," ",A)') CRC64 (YD%SLDLONG), CDPATH//'%SLDLONG'

WRITE (KLUN, '(Z16.16," ",A)') CRC64 (YD%SLDLAT), CDPATH//'%SLDLAT'

WRITE (KLUN, '(Z16.16," ",A)') CRC64 (YD%SLDDLAT), CDPATH//'%SLDDLAT'

END SUBROUTINE

SUBROUTINE WIPE_TECUCONVCA (YD, LDDELETED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TECUCONVCA), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI
LOGICAL :: LNBEW, LNBLS, LNBNS, LNBSS, LNCELLCU, LNFERTCU, LNRNBLS, LNRNBSS, LRCAPECONVCA, LRCUCONVCA
LOGICAL :: LRLATDEP, LRLATLONNBLS, LRLATLONNBSS, LRLONDEP, LRNLCONVCA, LRWASALIVE, LRWGHTCU, LSLDDLAT, LSLDLAT, LSLDLONG
LOGICAL :: LSLLAT, LSLLONG

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF



LNCELLCU = ALLOCATED (YD%NCELLCU)
IF (LNCELLCU) THEN
  !$acc exit data detach (YD%NCELLCU)
  !$acc exit data delete (YD%NCELLCU)
ENDIF

LNFERTCU = ALLOCATED (YD%NFERTCU)
IF (LNFERTCU) THEN
  !$acc exit data detach (YD%NFERTCU)
  !$acc exit data delete (YD%NFERTCU)
ENDIF

LNBLS = ALLOCATED (YD%NBLS)
IF (LNBLS) THEN
  !$acc exit data detach (YD%NBLS)
  !$acc exit data delete (YD%NBLS)
ENDIF

LNBSS = ALLOCATED (YD%NBSS)
IF (LNBSS) THEN
  !$acc exit data detach (YD%NBSS)
  !$acc exit data delete (YD%NBSS)
ENDIF

LNRNBLS = ALLOCATED (YD%NRNBLS)
IF (LNRNBLS) THEN
  !$acc exit data detach (YD%NRNBLS)
  !$acc exit data delete (YD%NRNBLS)
ENDIF

LNRNBSS = ALLOCATED (YD%NRNBSS)
IF (LNRNBSS) THEN
  !$acc exit data detach (YD%NRNBSS)
  !$acc exit data delete (YD%NRNBSS)
ENDIF

LNBEW = ALLOCATED (YD%NBEW)
IF (LNBEW) THEN
  !$acc exit data detach (YD%NBEW)
  !$acc exit data delete (YD%NBEW)
ENDIF

LNBNS = ALLOCATED (YD%NBNS)
IF (LNBNS) THEN
  !$acc exit data detach (YD%NBNS)
  !$acc exit data delete (YD%NBNS)
ENDIF

LRCUCONVCA = ALLOCATED (YD%RCUCONVCA)
IF (LRCUCONVCA) THEN
  !$acc exit data detach (YD%RCUCONVCA)
  !$acc exit data delete (YD%RCUCONVCA)
ENDIF

LRNLCONVCA = ALLOCATED (YD%RNLCONVCA)
IF (LRNLCONVCA) THEN
  !$acc exit data detach (YD%RNLCONVCA)
  !$acc exit data delete (YD%RNLCONVCA)
ENDIF

LRCAPECONVCA = ALLOCATED (YD%RCAPECONVCA)
IF (LRCAPECONVCA) THEN
  !$acc exit data detach (YD%RCAPECONVCA)
  !$acc exit data delete (YD%RCAPECONVCA)
ENDIF

LRWASALIVE = ALLOCATED (YD%RWASALIVE)
IF (LRWASALIVE) THEN
  !$acc exit data detach (YD%RWASALIVE)
  !$acc exit data delete (YD%RWASALIVE)
ENDIF

LRWGHTCU = ALLOCATED (YD%RWGHTCU)
IF (LRWGHTCU) THEN
  !$acc exit data detach (YD%RWGHTCU)
  !$acc exit data delete (YD%RWGHTCU)
ENDIF

LRLATLONNBLS = ALLOCATED (YD%RLATLONNBLS)
IF (LRLATLONNBLS) THEN
  !$acc exit data detach (YD%RLATLONNBLS)
  !$acc exit data delete (YD%RLATLONNBLS)
ENDIF

LRLATLONNBSS = ALLOCATED (YD%RLATLONNBSS)
IF (LRLATLONNBSS) THEN
  !$acc exit data detach (YD%RLATLONNBSS)
  !$acc exit data delete (YD%RLATLONNBSS)
ENDIF







LRLONDEP = ALLOCATED (YD%RLONDEP)
IF (LRLONDEP) THEN
  !$acc exit data detach (YD%RLONDEP)
  !$acc exit data delete (YD%RLONDEP)
ENDIF

LRLATDEP = ALLOCATED (YD%RLATDEP)
IF (LRLATDEP) THEN
  !$acc exit data detach (YD%RLATDEP)
  !$acc exit data delete (YD%RLATDEP)
ENDIF




















LSLLONG = ALLOCATED (YD%SLLONG)
IF (LSLLONG) THEN
  !$acc exit data detach (YD%SLLONG)
  !$acc exit data delete (YD%SLLONG)
ENDIF

LSLLAT = ALLOCATED (YD%SLLAT)
IF (LSLLAT) THEN
  !$acc exit data detach (YD%SLLAT)
  !$acc exit data delete (YD%SLLAT)
ENDIF

LSLDLONG = ALLOCATED (YD%SLDLONG)
IF (LSLDLONG) THEN
  !$acc exit data detach (YD%SLDLONG)
  !$acc exit data delete (YD%SLDLONG)
ENDIF

LSLDLAT = ALLOCATED (YD%SLDLAT)
IF (LSLDLAT) THEN
  !$acc exit data detach (YD%SLDLAT)
  !$acc exit data delete (YD%SLDLAT)
ENDIF

LSLDDLAT = ALLOCATED (YD%SLDDLAT)
IF (LSLDDLAT) THEN
  !$acc exit data detach (YD%SLDDLAT)
  !$acc exit data delete (YD%SLDDLAT)
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$acc exit data delete (YD)
ENDIF
END SUBROUTINE

INTEGER*8 FUNCTION SIZE_TECUCONVCA (YD, CDPATH, LDPRINT) RESULT (KSIZE)

IMPLICIT NONE
TYPE (TECUCONVCA),     INTENT (IN), TARGET :: YD
CHARACTER(LEN=*), INTENT (IN), OPTIONAL :: CDPATH
LOGICAL,          INTENT (IN), OPTIONAL :: LDPRINT
INTEGER*8 :: ISIZE, JSIZE
LOGICAL :: LLPRINT
CHARACTER(LEN=128) :: CLPATH
LOGICAL :: LNBEW, LNBLS, LNBNS, LNBSS, LNCELLCU, LNFERTCU, LNRNBLS, LNRNBSS, LRCAPECONVCA, LRCUCONVCA
LOGICAL :: LRLATDEP, LRLATLONNBLS, LRLATLONNBSS, LRLONDEP, LRNLCONVCA, LRWASALIVE, LRWGHTCU, LSLDDLAT, LSLDLAT, LSLDLONG
LOGICAL :: LSLLAT, LSLLONG

LLPRINT = .FALSE.
IF (PRESENT (LDPRINT)) THEN
  LLPRINT = LDPRINT
ENDIF
CLPATH=''
IF (PRESENT (CDPATH)) THEN
  CLPATH = CDPATH
ENDIF
KSIZE = 0
ISIZE = KIND (YD%NLIVES)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NLIVES'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NFERTYRS)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NFERTYRS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NSPINUP)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NSPINUP'
ENDIF
KSIZE = KSIZE + ISIZE
LNCELLCU = ALLOCATED (YD%NCELLCU)
IF (LNCELLCU) THEN
  ISIZE = KIND (YD%NCELLCU) * SIZE (YD%NCELLCU)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%NCELLCU'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LNFERTCU = ALLOCATED (YD%NFERTCU)
IF (LNFERTCU) THEN
  ISIZE = KIND (YD%NFERTCU) * SIZE (YD%NFERTCU)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%NFERTCU'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LNBLS = ALLOCATED (YD%NBLS)
IF (LNBLS) THEN
  ISIZE = KIND (YD%NBLS) * SIZE (YD%NBLS)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%NBLS'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LNBSS = ALLOCATED (YD%NBSS)
IF (LNBSS) THEN
  ISIZE = KIND (YD%NBSS) * SIZE (YD%NBSS)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%NBSS'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LNRNBLS = ALLOCATED (YD%NRNBLS)
IF (LNRNBLS) THEN
  ISIZE = KIND (YD%NRNBLS) * SIZE (YD%NRNBLS)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%NRNBLS'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LNRNBSS = ALLOCATED (YD%NRNBSS)
IF (LNRNBSS) THEN
  ISIZE = KIND (YD%NRNBSS) * SIZE (YD%NRNBSS)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%NRNBSS'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LNBEW = ALLOCATED (YD%NBEW)
IF (LNBEW) THEN
  ISIZE = KIND (YD%NBEW) * SIZE (YD%NBEW)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%NBEW'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LNBNS = ALLOCATED (YD%NBNS)
IF (LNBNS) THEN
  ISIZE = KIND (YD%NBNS) * SIZE (YD%NBNS)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%NBNS'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LRCUCONVCA = ALLOCATED (YD%RCUCONVCA)
IF (LRCUCONVCA) THEN
  ISIZE = KIND (YD%RCUCONVCA) * SIZE (YD%RCUCONVCA)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%RCUCONVCA'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LRNLCONVCA = ALLOCATED (YD%RNLCONVCA)
IF (LRNLCONVCA) THEN
  ISIZE = KIND (YD%RNLCONVCA) * SIZE (YD%RNLCONVCA)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%RNLCONVCA'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LRCAPECONVCA = ALLOCATED (YD%RCAPECONVCA)
IF (LRCAPECONVCA) THEN
  ISIZE = KIND (YD%RCAPECONVCA) * SIZE (YD%RCAPECONVCA)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%RCAPECONVCA'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LRWASALIVE = ALLOCATED (YD%RWASALIVE)
IF (LRWASALIVE) THEN
  ISIZE = KIND (YD%RWASALIVE) * SIZE (YD%RWASALIVE)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%RWASALIVE'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LRWGHTCU = ALLOCATED (YD%RWGHTCU)
IF (LRWGHTCU) THEN
  ISIZE = KIND (YD%RWGHTCU) * SIZE (YD%RWGHTCU)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%RWGHTCU'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LRLATLONNBLS = ALLOCATED (YD%RLATLONNBLS)
IF (LRLATLONNBLS) THEN
  ISIZE = KIND (YD%RLATLONNBLS) * SIZE (YD%RLATLONNBLS)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%RLATLONNBLS'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LRLATLONNBSS = ALLOCATED (YD%RLATLONNBSS)
IF (LRLATLONNBSS) THEN
  ISIZE = KIND (YD%RLATLONNBSS) * SIZE (YD%RLATLONNBSS)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%RLATLONNBSS'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
ISIZE = KIND (YD%RPROB_SURVIVE) * SIZE (YD%RPROB_SURVIVE)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RPROB_SURVIVE'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RPROB_BIRTH) * SIZE (YD%RPROB_BIRTH)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RPROB_BIRTH'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RPROB_FUN_FERT_S) * SIZE (YD%RPROB_FUN_FERT_S)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RPROB_FUN_FERT_S'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RPROB_FUN_UW_DW_S) * SIZE (YD%RPROB_FUN_UW_DW_S)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RPROB_FUN_UW_DW_S'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RPROB_FUN_FERT_B) * SIZE (YD%RPROB_FUN_FERT_B)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RPROB_FUN_FERT_B'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RPROB_FUN_UW_DW_B) * SIZE (YD%RPROB_FUN_UW_DW_B)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RPROB_FUN_UW_DW_B'
ENDIF
KSIZE = KSIZE + ISIZE
LRLONDEP = ALLOCATED (YD%RLONDEP)
IF (LRLONDEP) THEN
  ISIZE = KIND (YD%RLONDEP) * SIZE (YD%RLONDEP)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%RLONDEP'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LRLATDEP = ALLOCATED (YD%RLATDEP)
IF (LRLATDEP) THEN
  ISIZE = KIND (YD%RLATDEP) * SIZE (YD%RLATDEP)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%RLATDEP'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
ISIZE = KIND (YD%RCA_SEEDPROB)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RCA_SEEDPROB'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RCADELX)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RCADELX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LCUCONV_CA)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LCUCONV_CA'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LCA_ADVECT)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LCA_ADVECT'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LCA_GLOBAL)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LCA_GLOBAL'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LCA_SMOOTH)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LCA_SMOOTH'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LCA_TEST)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LCA_TEST'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LCA_ADVTEST)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LCA_ADVTEST'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LCA_RANTROP)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LCA_RANTROP'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LCA_NBDEBUG)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LCA_NBDEBUG'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LCA_EXTRACT)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LCA_EXTRACT'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%CA_FORC) * LEN (YD%CA_FORC)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%CA_FORC'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%CA_WIND) * LEN (YD%CA_WIND)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%CA_WIND'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%CA_PROB) * LEN (YD%CA_PROB)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%CA_PROB'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NFRCASEED)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NFRCASEED'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NTESTPROC)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NTESTPROC'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NTESTGP)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NTESTGP'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NDXUNREAL)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NDXUNREAL'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NDYUNREAL)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NDYUNREAL'
ENDIF
KSIZE = KSIZE + ISIZE
LSLLONG = ALLOCATED (YD%SLLONG)
IF (LSLLONG) THEN
  ISIZE = KIND (YD%SLLONG) * SIZE (YD%SLLONG)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%SLLONG'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LSLLAT = ALLOCATED (YD%SLLAT)
IF (LSLLAT) THEN
  ISIZE = KIND (YD%SLLAT) * SIZE (YD%SLLAT)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%SLLAT'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LSLDLONG = ALLOCATED (YD%SLDLONG)
IF (LSLDLONG) THEN
  ISIZE = KIND (YD%SLDLONG) * SIZE (YD%SLDLONG)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%SLDLONG'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LSLDLAT = ALLOCATED (YD%SLDLAT)
IF (LSLDLAT) THEN
  ISIZE = KIND (YD%SLDLAT) * SIZE (YD%SLDLAT)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%SLDLAT'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LSLDDLAT = ALLOCATED (YD%SLDDLAT)
IF (LSLDDLAT) THEN
  ISIZE = KIND (YD%SLDDLAT) * SIZE (YD%SLDDLAT)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%SLDDLAT'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
END FUNCTION

END MODULE
