SUBROUTINE CUBIDIAG_OPENACC (KIDIA, KFDIA, KLON, KLEV, KCTOP, LD_LCUMASK, PA, PB, PR, PU, YDSTACK)
!$acc routine (CUBIDIAG_OPENACC) seq
USE PARKIND1,ONLY:JPIM, JPRB

USE ABOR1_ACC_MOD
USE STACK_MOD
#include "stack.h"

IMPLICIT NONE

INTEGER (KIND=JPIM), INTENT (IN)::KIDIA
INTEGER (KIND=JPIM), INTENT (IN)::KFDIA
INTEGER (KIND=JPIM), INTENT (IN)::KLON
INTEGER (KIND=JPIM), INTENT (IN)::KLEV
INTEGER (KIND=JPIM), INTENT (IN)::KCTOP (KLON)
LOGICAL, INTENT (IN)::LD_LCUMASK (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PA (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PB (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PR (KLON, KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PU (KLON, KLEV)
TYPE(STACK) :: YDSTACK
TYPE(STACK) :: YLSTACK

INTEGER (KIND=JPIM)::JLON
INTEGER (KIND=JPIM)::JLEV
REAL (KIND=JPRB)::ZBET


YLSTACK = YDSTACK




JLON = KIDIA

PU (JLON,:)=0.0_JPRB

DO JLEV=2, KLEV

  

  IF (LD_LCUMASK (JLON, JLEV)) THEN

    IF (JLEV==KCTOP (JLON)-1) THEN
      ZBET=1.0_JPRB/(PB (JLON, JLEV)+1.E-35_JPRB)
      PU (JLON, JLEV)=PR (JLON, JLEV)*ZBET
    ELSEIF (JLEV>KCTOP (JLON)-1) THEN
      ZBET=1.0_JPRB/(PB (JLON, JLEV)+1.E-35_JPRB)
      PU (JLON, JLEV)=(PR (JLON, JLEV)-PA (JLON, JLEV)*PU (JLON, JLEV-1))*ZBET
    ENDIF

  ENDIF

  
ENDDO


ENDSUBROUTINE CUBIDIAG_OPENACC

! e56ac8e1f86b1a9cc13b38d73abbf48f96ba2f2a
