SUBROUTINE CUCTRACER_OPENACC (YDCST, YDCUMFS, YDECUMF2, YDECUMF, KIDIA, KFDIA, KLON&
&, KLEV, KTRAC, KCTOP, KDTOP, KTYPE, LDCUM, LDDRAF, PTSPHY, PAPH, PAP, PMFU, PMFD,&
& PMFUO, PMFDO, PUDRATE, PDDRATE, PDMFUP, PDMFDP, PCEN, PTENC, PSCAV, YDSTACK)
!$acc routine (CUCTRACER_OPENACC) seq
USE PARKIND1,ONLY:JPIM, JPRB

USE YOMCST,ONLY:TCST
USE YOECUMF,ONLY:TECUMF
USE YOECUMF2,ONLY:TECUMF2
USE YOMCUMFS,ONLY:TCUMFS
USE ABOR1_ACC_MOD
USE STACK_MOD
#include "stack.h"

IMPLICIT NONE

TYPE (TCST), INTENT (IN)::YDCST
TYPE (TCUMFS), INTENT (IN)::YDCUMFS
TYPE (TECUMF), INTENT (IN)::YDECUMF
TYPE (TECUMF2), INTENT (IN)::YDECUMF2
INTEGER (KIND=JPIM), INTENT (IN)::KLON
INTEGER (KIND=JPIM), INTENT (IN)::KLEV
INTEGER (KIND=JPIM), INTENT (IN)::KTRAC
INTEGER (KIND=JPIM), INTENT (IN)::KIDIA
INTEGER (KIND=JPIM), INTENT (IN)::KFDIA
INTEGER (KIND=JPIM), INTENT (IN)::KCTOP (KLON)
INTEGER (KIND=JPIM), INTENT (IN)::KDTOP (KLON)
INTEGER (KIND=JPIM), INTENT (IN)::KTYPE (KLON)
LOGICAL, INTENT (IN)::LDCUM (KLON)
LOGICAL, INTENT (IN)::LDDRAF (KLON)
REAL (KIND=JPRB), INTENT (IN)::PTSPHY
REAL (KIND=JPRB), INTENT (IN)::PAPH (KLON, KLEV+1)
REAL (KIND=JPRB), INTENT (IN)::PAP (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PMFU (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PMFD (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PMFUO (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PMFDO (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PUDRATE (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PDDRATE (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PDMFUP (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PDMFDP (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PCEN (KLON, KLEV, KTRAC)
REAL (KIND=JPRB), INTENT (IN)::PSCAV (KTRAC)
TYPE(STACK) :: YDSTACK
TYPE(STACK) :: YLSTACK
REAL (KIND=JPRB), INTENT (INOUT)::PTENC (KLON, KLEV, KTRAC)

INTEGER (KIND=JPIM)::JN
INTEGER (KIND=JPIM)::JLON
INTEGER (KIND=JPIM)::JLEV
INTEGER (KIND=JPIM)::IM
INTEGER (KIND=JPIM)::IK

REAL (KIND=JPRB)::ZADVW 
REAL (KIND=JPRB)::ZC
REAL (KIND=JPRB)::ZTSPHY
REAL (KIND=JPRB)::ZPOSI
REAL (KIND=JPRB)::ZERATE
REAL (KIND=JPRB)::ZIMP
REAL (KIND=JPRB)::ZMFA
REAL (KIND=JPRB)::ZZP

REAL (KIND=JPRB)::ZRMFSOLCT
REAL (KIND=JPRB)::ZRMFCMIN

temp (REAL (KIND=JPRB), ZMFC, (KLON, KLEV, KTRAC))
temp (REAL (KIND=JPRB), ZTENC, (KLON, KLEV, KTRAC))
temp (REAL (KIND=JPRB), ZCD, (KLON, KLEV, KTRAC))
temp (REAL (KIND=JPRB), ZCU, (KLON, KLEV, KTRAC))
temp (REAL (KIND=JPRB), ZCEN, (KLON, KLEV, KTRAC))

temp (REAL (KIND=JPRB), ZR1, (KLON, KLEV))
temp (REAL (KIND=JPRB), ZB, (KLON, KLEV))
temp (REAL (KIND=JPRB), ZDP, (KLON, KLEV))

temp (LOGICAL, LLCUMBAS, (KLON, KLEV))
temp (LOGICAL, LLCUMASK, (KLON, KLEV))

#include "cubidiag_openacc.intfb.h"

YLSTACK = YDSTACK


IF (KIND (ZMFC) == 8) THEN
    alloc8 (ZMFC)
ELSEIF (KIND (ZMFC) == 4) THEN
    alloc4 (ZMFC)
ELSE
    STOP 1
ENDIF


IF (KIND (ZTENC) == 8) THEN
    alloc8 (ZTENC)
ELSEIF (KIND (ZTENC) == 4) THEN
    alloc4 (ZTENC)
ELSE
    STOP 1
ENDIF


IF (KIND (ZCD) == 8) THEN
    alloc8 (ZCD)
ELSEIF (KIND (ZCD) == 4) THEN
    alloc4 (ZCD)
ELSE
    STOP 1
ENDIF


IF (KIND (ZCU) == 8) THEN
    alloc8 (ZCU)
ELSEIF (KIND (ZCU) == 4) THEN
    alloc4 (ZCU)
ELSE
    STOP 1
ENDIF


IF (KIND (ZCEN) == 8) THEN
    alloc8 (ZCEN)
ELSEIF (KIND (ZCEN) == 4) THEN
    alloc4 (ZCEN)
ELSE
    STOP 1
ENDIF


IF (KIND (ZR1) == 8) THEN
    alloc8 (ZR1)
ELSEIF (KIND (ZR1) == 4) THEN
    alloc4 (ZR1)
ELSE
    STOP 1
ENDIF


IF (KIND (ZB) == 8) THEN
    alloc8 (ZB)
ELSEIF (KIND (ZB) == 4) THEN
    alloc4 (ZB)
ELSE
    STOP 1
ENDIF


IF (KIND (ZDP) == 8) THEN
    alloc8 (ZDP)
ELSEIF (KIND (ZDP) == 4) THEN
    alloc4 (ZDP)
ELSE
    STOP 1
ENDIF


IF (KIND (LLCUMBAS) == 8) THEN
    alloc8 (LLCUMBAS)
ELSEIF (KIND (LLCUMBAS) == 4) THEN
    alloc4 (LLCUMBAS)
ELSE
    STOP 1
ENDIF


IF (KIND (LLCUMASK) == 8) THEN
    alloc8 (LLCUMASK)
ELSEIF (KIND (LLCUMASK) == 4) THEN
    alloc4 (LLCUMASK)
ELSE
    STOP 1
ENDIF




JLON = KIDIA



IF (YDCUMFS%LECUMFS) THEN
  ZRMFSOLCT=YDECUMF2%RMFSOLCT2
  ZRMFCMIN=YDECUMF2%RMFCMIN2
ELSE
  ZRMFSOLCT=YDECUMF%RMFSOLCT
  ZRMFCMIN=YDECUMF%RMFCMIN
ENDIF

ZIMP=1.0_JPRB-ZRMFSOLCT
ZTSPHY=1.0_JPRB/PTSPHY

ZADVW =0.0_JPRB

IF (KTYPE (JLON)==1)  THEN
    ZADVW =YDECUMF%RMFADVW
ENDIF



DO JLEV=2, KLEV
  
  LLCUMASK (JLON, JLEV)=.FALSE.

  IF (LDCUM (JLON)) THEN
    ZDP (JLON, JLEV)=YDCST%RG/(PAPH (JLON, JLEV+1)-PAPH (JLON, JLEV))

    IF (JLEV>=KCTOP (JLON)-1) THEN
      LLCUMASK (JLON, JLEV)=.TRUE.
    ENDIF

  ENDIF

  
ENDDO


DO JN=1, KTRAC

  DO JLEV=2, KLEV
    IK=JLEV-1
    
    ZCEN (JLON, JLEV, JN)=PCEN (JLON, JLEV, JN)
    ZCD (JLON, JLEV, JN)=PCEN (JLON, IK, JN)
    ZCU (JLON, JLEV, JN)=PCEN (JLON, IK, JN)
    ZMFC (JLON, JLEV, JN)=0.0_JPRB
    ZTENC (JLON, JLEV, JN)=0.0_JPRB
  
  ENDDO

  
  ZCU (JLON, KLEV, JN)=PCEN (JLON, KLEV, JN)

  

  DO JLEV=KLEV-1, 3,-1
    IK=JLEV+1

    

    IF (LLCUMASK (JLON, JLEV)) THEN
      ZERATE=PMFU (JLON, JLEV)-PMFU (JLON, IK)+PUDRATE (JLON, JLEV)
      ZMFA=1.0_JPRB/MAX (ZRMFCMIN, PMFU (JLON, JLEV))

      IF (JLEV>=KCTOP (JLON)) THEN
        ZCU (JLON, JLEV, JN)=(PMFU (JLON, IK)*ZCU (JLON, IK, JN)+ZERATE*PCEN (JLON, JLEV, JN&
        &)-(PUDRATE (JLON, JLEV)+PDMFUP (JLON, JLEV)*PSCAV (JN))*ZCU (JLON, IK, JN))*ZMFA
      ENDIF

    ENDIF

  
  ENDDO


  DO JLEV=3, KLEV
    IK=JLEV-1

    

    IF (LDDRAF (JLON).AND.JLEV==KDTOP (JLON)) THEN
      ZCD (JLON, JLEV, JN)=0.1_JPRB*ZCU (JLON, JLEV, JN)+0.9_JPRB*PCEN (JLON, IK, JN)
    ELSEIF (LDDRAF (JLON).AND.JLEV>KDTOP (JLON)) THEN
      ZERATE=-PMFD (JLON, JLEV)+PMFD (JLON, IK)+PDDRATE (JLON, JLEV)
      ZMFA=1._JPRB/MIN (-ZRMFCMIN, PMFD (JLON, JLEV))
      ZCD (JLON, JLEV, JN)=(PMFD (JLON, IK)*ZCD (JLON, IK, JN)-ZERATE*PCEN (JLON, IK, JN)&
      &+(PDDRATE (JLON, JLEV)+PDMFDP (JLON, JLEV)*PSCAV (JN))*ZCD (JLON, IK, JN))*ZMFA
    ENDIF

  
  ENDDO

  JLEV=KLEV
  IK=JLEV-1

  

  IF (LDDRAF (JLON)) THEN
    ZPOSI=-ZDP (JLON, JLEV)*(PMFU (JLON, JLEV)*ZCU (JLON, JLEV, JN)+PMFD (JLON, JLEV)*ZCD&
    & (JLON, JLEV, JN)-(PMFU (JLON, JLEV)+PMFD (JLON, JLEV))*PCEN (JLON, IK, JN))

    IF (PCEN (JLON, JLEV, JN)+ZPOSI*PTSPHY<0.0_JPRB) THEN
      ZMFA=1._JPRB/MIN (-ZRMFCMIN, PMFD (JLON, JLEV))
      ZCD (JLON, JLEV, JN)=((PMFU (JLON, JLEV)+PMFD (JLON, JLEV))*PCEN (JLON, IK, JN)-PMFU (JLON&
      &, JLEV)*ZCU (JLON, JLEV, JN)+PCEN (JLON, JLEV, JN)/(PTSPHY*ZDP (JLON, JLEV)))*ZMFA
    ENDIF

  ENDIF

  
ENDDO


DO JN=1, KTRAC

  DO JLEV=2, KLEV
    IK=JLEV-1

    

    IF (LLCUMASK (JLON, JLEV)) THEN
      ZMFA=PMFU (JLON, JLEV)+PMFD (JLON, JLEV)
      ZMFC (JLON, JLEV, JN)=PMFU (JLON, JLEV)*ZCU (JLON, JLEV, JN)+PMFD &
      &(JLON, JLEV)*ZCD (JLON, JLEV, JN)-ZIMP*ZMFA*ZCEN (JLON, IK, JN)
    ENDIF

  
  ENDDO


  DO JLEV=2, KLEV-1
    IK=JLEV+1

    

    IF (LLCUMASK (JLON, JLEV)) THEN
      ZTENC (JLON, JLEV, JN)=ZDP (JLON, JLEV)*(ZMFC (JLON, IK, JN)-ZMFC (JLON, JLEV, JN))
    ENDIF

  
  ENDDO

  JLEV=KLEV

  

  IF (LDCUM (JLON)) THEN
    ZTENC (JLON, JLEV, JN)=-ZDP (JLON, JLEV)*ZMFC (JLON, JLEV, JN)
  ENDIF

  
ENDDO


IF (ZRMFSOLCT==0.0_JPRB) THEN

  DO JN=1, KTRAC

    DO JLEV=2, KLEV

      

      IF (LLCUMASK (JLON, JLEV)) THEN
        PTENC (JLON, JLEV, JN)=PTENC (JLON, JLEV, JN)+ZTENC (JLON, JLEV, JN)
      ENDIF

    
    ENDDO

  ENDDO

ELSE
  LLCUMBAS (JLON,:)=.FALSE.
  ZB (JLON,:)=1._JPRB

  DO JN=1, KTRAC

    DO JLEV=2, KLEV
      IK=JLEV+1
      IM=JLEV-1
      
      LLCUMBAS (JLON, JLEV)=LLCUMASK (JLON, JLEV)

      IF (LLCUMBAS (JLON, JLEV)) THEN
        ZZP=ZRMFSOLCT*ZDP (JLON, JLEV)*PTSPHY
        ZMFC (JLON, JLEV, JN)=-ZZP*(PMFU (JLON, JLEV)+PMFD (JLON, JLEV))

        IF (JLEV<KLEV) THEN
          ZB (JLON, JLEV)=1.0_JPRB+ZZP*(PMFU (JLON, IK)+PMFD (JLON, IK))
        ELSE
          ZB (JLON, JLEV)=1.0_JPRB
        ENDIF

        ZZP=YDCST%RG*(PMFUO (JLON, JLEV)+YDECUMF%RMFADVWDD*PMFDO (JLON&
        &, JLEV))/(PAP (JLON, JLEV)-PAP (JLON, IM))*PTSPHY*ZADVW 
        ZC=ZZP*(PCEN (JLON, IM, JN)-PCEN (JLON, JLEV, JN))
        ZTENC (JLON, JLEV, JN)=ZTENC (JLON, JLEV, JN)*PTSPHY+PCEN (JLON, JLEV, JN)-ZC
      ENDIF

    
    ENDDO

    CALL CUBIDIAG_OPENACC (KIDIA, KFDIA, KLON, KLEV, KCTOP, LLCUMBAS&
    &, ZMFC (:,:, JN), ZB, ZTENC (:,:, JN), ZR1, YDSTACK=YLSTACK)

    DO JLEV=2, KLEV

      

      IF (LLCUMBAS (JLON, JLEV)) THEN
        PTENC (JLON, JLEV, JN)=PTENC (JLON, JLEV, JN)+(ZR1 (JLON, JLEV)-PCEN (JLON, JLEV, JN))*ZTSPHY
      ENDIF

    
    ENDDO

  ENDDO

ENDIF



ENDSUBROUTINE CUCTRACER_OPENACC

! e56ac8e1f86b1a9cc13b38d73abbf48f96ba2f2a
