SUBROUTINE CUDDRAFN_OPENACC (YDCST, YDTHF, YDEPHLI, YDECUMF, KIDIA, KFDIA, KLON&
&, KLEV, LDDRAF, PTENH, PQENH, PQSEN, PGEO, PGEOH, PAPH, PRFL, PTD, PQD, PMFU&
&, PMFD, PMFDS, PMFDQ, PDMFDP, PDMFDE, PMFDDE_RATE, PKINED, YDSTACK)
!$acc routine (CUDDRAFN_OPENACC) seq
USE YOEPHLI,ONLY:TEPHLI
USE PARKIND1,ONLY:JPIM, JPRB

USE YOMCST,ONLY:TCST
USE YOETHF,ONLY:TTHF
USE YOECUMF,ONLY:TECUMF
USE ABOR1_ACC_MOD
USE STACK_MOD
#include "stack.h"

IMPLICIT NONE

TYPE (TCST), INTENT (IN)::YDCST
TYPE (TTHF), INTENT (IN)::YDTHF
TYPE (TECUMF), INTENT (IN)::YDECUMF
TYPE (TEPHLI), INTENT (IN)::YDEPHLI
INTEGER (KIND=JPIM), INTENT (IN)::KLON
INTEGER (KIND=JPIM), INTENT (IN)::KLEV
INTEGER (KIND=JPIM), INTENT (IN)::KIDIA
INTEGER (KIND=JPIM), INTENT (IN)::KFDIA
LOGICAL, INTENT (IN)::LDDRAF (KLON)
REAL (KIND=JPRB), INTENT (IN)::PTENH (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PQENH (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PQSEN (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PGEO (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PGEOH (KLON, KLEV+1)
REAL (KIND=JPRB), INTENT (IN)::PAPH (KLON, KLEV+1)
REAL (KIND=JPRB), INTENT (INOUT)::PRFL (KLON)
REAL (KIND=JPRB), INTENT (INOUT)::PTD (KLON, KLEV)
REAL (KIND=JPRB), INTENT (INOUT)::PQD (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PMFU (KLON, KLEV)
REAL (KIND=JPRB), INTENT (INOUT)::PMFD (KLON, KLEV)
REAL (KIND=JPRB), INTENT (INOUT)::PMFDS (KLON, KLEV)
REAL (KIND=JPRB), INTENT (INOUT)::PMFDQ (KLON, KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PDMFDP (KLON, KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PDMFDE (KLON, KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PMFDDE_RATE (KLON, KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PKINED (KLON, KLEV)
TYPE(STACK) :: YDSTACK
TYPE(STACK) :: YLSTACK

REAL (KIND=JPRB)::ZBUOY 
REAL (KIND=JPRB)::ZOENTR 
REAL (KIND=JPRB)::ZCOND 
REAL (KIND=JPRB)::ZDMFDE 
REAL (KIND=JPRB)::ZDMFEN 
REAL (KIND=JPRB)::ZPH 
LOGICAL::LLO2 

INTEGER (KIND=JPIM)::JLON
INTEGER (KIND=JPIM)::JLEV
INTEGER (KIND=JPIM)::ITOPDE
INTEGER (KIND=JPIM)::IS
INTEGER (KIND=JPIM)::IK

REAL (KIND=JPRB)::ZDKEN
REAL (KIND=JPRB)::ZDKBUO
REAL (KIND=JPRB)::Z_CWDRAG
REAL (KIND=JPRB)::ZFACBUO
REAL (KIND=JPRB)::ZRG
REAL (KIND=JPRB)::ZZENTR
REAL (KIND=JPRB)::ZSEEN
REAL (KIND=JPRB)::ZSDDE
REAL (KIND=JPRB)::ZRAIN
REAL (KIND=JPRB)::ZQEEN
REAL (KIND=JPRB)::ZQDDE
REAL (KIND=JPRB)::ZMFDSK
REAL (KIND=JPRB)::ZMFDQK
REAL (KIND=JPRB)::ZENTR
REAL (KIND=JPRB)::ZDZ
REAL (KIND=JPRB)::ZDMFDP
REAL (KIND=JPRB)::ZBUOYV
REAL (KIND=JPRB)::ZBUOYZ
REAL (KIND=JPRB)::ZBUO

REAL (KIND=JPRB)::ZQP
REAL (KIND=JPRB)::ZTARG
REAL (KIND=JPRB)::ZQSAT
REAL (KIND=JPRB)::ZQMAX
REAL (KIND=JPRB)::ZOEALFA
REAL (KIND=JPRB)::ZFOEEWL
REAL (KIND=JPRB)::ZFOEEWI
REAL (KIND=JPRB)::ZCOR
REAL (KIND=JPRB)::ZCOND1
REAL (KIND=JPRB)::ZCOND_CUADJTQ
REAL (KIND=JPRB)::Z2S
REAL (KIND=JPRB)::Z1S
REAL (KIND=JPRB)::ZF
REAL (KIND=JPRB)::ZI
REAL (KIND=JPRB)::ZL
LOGICAL::LLFLAG 
#include "cuadjtq.func.h"
#include "fcttre.func.h"


YLSTACK = YDSTACK




JLON = KIDIA


ITOPDE=YDECUMF%NJKT3
ZRG=1.0_JPRB/YDCST%RG
ZFACBUO=0.5_JPRB/1.5
Z_CWDRAG=(3._JPRB/8._JPRB)*0.506_JPRB/0.2_JPRB

ZOENTR =0.0_JPRB
ZBUOY =0.0_JPRB
ZDMFEN =0.0_JPRB
ZDMFDE =0.0_JPRB
PDMFDE (JLON,:)=0.0_JPRB
PMFDDE_RATE (JLON,:)=0.0_JPRB
PKINED (JLON,:)=0.0_JPRB


DO JLEV=3, KLEV
  IS=0
  
  ZPH =PAPH (JLON, JLEV)
  LLO2 =LDDRAF (JLON).AND.PMFD (JLON, JLEV-1)<0.0_JPRB

  IF (LLO2 ) THEN
    IS=IS+1
  ENDIF


  

  IF (IS==0)  THEN
      CYCLE
  ENDIF


  

  IF (LLO2 ) THEN
    ZENTR=YDECUMF%ENTRDD*PMFD (JLON, JLEV-1)*(PGEOH (JLON, JLEV-1)-PGEOH (JLON, JLEV))*ZRG
    ZDMFEN =ZENTR
    ZDMFDE =ZENTR
  ENDIF


  

  IF (JLEV>ITOPDE) THEN

    

    IF (LLO2 ) THEN
      ZDMFEN =0.0_JPRB
      ZDMFDE =PMFD (JLON, ITOPDE)*(PAPH (JLON, JLEV)-PAPH (JLON&
      &, JLEV-1))/(PAPH (JLON, KLEV+1)-PAPH (JLON, ITOPDE))
    ENDIF

  
  ENDIF


  IF (JLEV<=ITOPDE) THEN

    

    IF (LLO2 ) THEN
      ZDZ=-(PGEOH (JLON, JLEV-1)-PGEOH (JLON, JLEV))*ZRG
      ZZENTR=ZOENTR *ZDZ*PMFD (JLON, JLEV-1)
      ZDMFEN =ZDMFEN +ZZENTR
      ZDMFEN =MAX (ZDMFEN , 0.3_JPRB*PMFD (JLON, JLEV-1))
      ZDMFEN =MAX (ZDMFEN ,-0.75_JPRB*PMFU (JLON, JLEV)-(PMFD (JLON, JLEV-1)-ZDMFDE ))
      ZDMFEN =MIN (ZDMFEN , 0.0_JPRB)
    ENDIF

    PDMFDE (JLON, JLEV)=ZDMFEN -ZDMFDE 
  
  ENDIF


  

  IF (LLO2 ) THEN
    PMFD (JLON, JLEV)=PMFD (JLON, JLEV-1)+ZDMFEN -ZDMFDE 
    ZSEEN=(YDCST%RCPD*PTENH (JLON, JLEV-1)+PGEOH (JLON, JLEV-1))*ZDMFEN 
    ZQEEN=PQENH (JLON, JLEV-1)*ZDMFEN 
    ZSDDE=(YDCST%RCPD*PTD (JLON, JLEV-1)+PGEOH (JLON, JLEV-1))*ZDMFDE 
    ZQDDE=PQD (JLON, JLEV-1)*ZDMFDE 
    ZMFDSK=PMFDS (JLON, JLEV-1)+ZSEEN-ZSDDE
    ZMFDQK=PMFDQ (JLON, JLEV-1)+ZQEEN-ZQDDE
    PQD (JLON, JLEV)=ZMFDQK*(1.0_JPRB/MIN (-YDECUMF%RMFCMIN, PMFD (JLON, JLEV)))
    PTD (JLON, JLEV)=(ZMFDSK*(1.0_JPRB/MIN (-YDECUMF%RMFCMIN&
    &, PMFD (JLON, JLEV)))-PGEOH (JLON, JLEV))/YDCST%RCPD
    PTD (JLON, JLEV)=MIN (400._JPRB, PTD (JLON, JLEV))
    PTD (JLON, JLEV)=MAX (100._JPRB, PTD (JLON, JLEV))
    ZCOND =PQD (JLON, JLEV)
  ENDIF

  
  IK=JLEV
  
  
  
  
  
  
  
  ZQMAX=0.5_JPRB

  IF (.NOT.YDEPHLI%LPHYLIN) THEN

    

    

    

    IF (LLO2 ) THEN
      ZQP=1.0_JPRB/ZPH 
      ZQSAT=FOEEWMCU (PTD (JLON, IK))*ZQP
      ZQSAT=MIN (0.5_JPRB, ZQSAT)
      ZCOR=1.0_JPRB/(1.0_JPRB-YDCST%RETV*ZQSAT)
      ZQSAT=ZQSAT*ZCOR
      ZCOND_CUADJTQ=(PQD (JLON, IK)-ZQSAT)/(1.0_JPRB+ZQSAT*ZCOR*FOEDEMCU (PTD (JLON, IK)))
      ZCOND_CUADJTQ=MIN (ZCOND_CUADJTQ, 0.0_JPRB)
      PTD (JLON, IK)=PTD (JLON, IK)+FOELDCPMCU (PTD (JLON, IK))*ZCOND_CUADJTQ
      PQD (JLON, IK)=PQD (JLON, IK)-ZCOND_CUADJTQ
      ZQSAT=FOEEWMCU (PTD (JLON, IK))*ZQP
      ZQSAT=MIN (0.5_JPRB, ZQSAT)
      ZCOR=1.0_JPRB/(1.0_JPRB-YDCST%RETV*ZQSAT)
      ZQSAT=ZQSAT*ZCOR
      ZCOND1=(PQD (JLON, IK)-ZQSAT)/(1.0_JPRB+ZQSAT*ZCOR*FOEDEMCU (PTD (JLON, IK)))

      IF (ZCOND_CUADJTQ==0.0_JPRB)  THEN
          ZCOND1=MIN (ZCOND1, 0.0_JPRB)
      ENDIF

      PTD (JLON, IK)=PTD (JLON, IK)+FOELDCPMCU (PTD (JLON, IK))*ZCOND1
      PQD (JLON, IK)=PQD (JLON, IK)-ZCOND1
    ENDIF

  
  
  
  
  
  
  ELSE

    

    

    

    IF (LLO2 ) THEN
      ZQP=1.0_JPRB/ZPH 
      ZTARG=PTD (JLON, IK)
      ZOEALFA=0.5_JPRB*(TANH (YDEPHLI%RLPAL1*(ZTARG-YDEPHLI%RLPTRC))+1.0_JPRB)
      ZFOEEWL=YDTHF%R2ES*EXP (YDTHF%R3LES*(ZTARG-YDCST%RTT)/(ZTARG-YDTHF%R4LES))
      ZFOEEWI=YDTHF%R2ES*EXP (YDTHF%R3IES*(ZTARG-YDCST%RTT)/(ZTARG-YDTHF%R4IES))
      ZQSAT=ZQP*(ZOEALFA*ZFOEEWL+(1.0_JPRB-ZOEALFA)*ZFOEEWI)
      Z1S=TANH (YDEPHLI%RLPAL2*(ZQSAT-ZQMAX))
      ZQSAT=0.5_JPRB*((1.0_JPRB-Z1S)*ZQSAT+(1.0_JPRB+Z1S)*ZQMAX)
      ZCOR=1.0_JPRB/(1.0_JPRB-YDCST%RETV*ZQSAT)
      ZQSAT=ZQSAT*ZCOR
      Z2S=ZOEALFA*YDTHF%R5ALVCP*(1.0_JPRB/(ZTARG-YDTHF%R4LES)**2)+(1.0_JPRB&
      &-ZOEALFA)*YDTHF%R5ALSCP*(1.0_JPRB/(ZTARG-YDTHF%R4IES)**2)
      ZCOND_CUADJTQ=(PQD (JLON, IK)-ZQSAT)/(1.0_JPRB+ZQSAT*ZCOR*Z2S)
      ZCOND_CUADJTQ=MIN (ZCOND_CUADJTQ, 0.0_JPRB)

      IF (ZCOND_CUADJTQ/=0.0_JPRB) THEN
        PTD (JLON, IK)=PTD (JLON, IK)+(ZOEALFA*YDTHF%RALVDCP+(1.0_JPRB-ZOEALFA)*YDTHF%RALSDCP)*ZCOND_CUADJTQ
        PQD (JLON, IK)=PQD (JLON, IK)-ZCOND_CUADJTQ
        ZTARG=PTD (JLON, IK)
        ZOEALFA=0.5_JPRB*(TANH (YDEPHLI%RLPAL1*(ZTARG-YDEPHLI%RLPTRC))+1.0_JPRB)
        ZFOEEWL=YDTHF%R2ES*EXP (YDTHF%R3LES*(ZTARG-YDCST%RTT)/(ZTARG-YDTHF%R4LES))
        ZFOEEWI=YDTHF%R2ES*EXP (YDTHF%R3IES*(ZTARG-YDCST%RTT)/(ZTARG-YDTHF%R4IES))
        ZQSAT=ZQP*(ZOEALFA*ZFOEEWL+(1.0_JPRB-ZOEALFA)*ZFOEEWI)
        Z1S=TANH (YDEPHLI%RLPAL2*(ZQSAT-ZQMAX))
        ZQSAT=0.5_JPRB*((1.0_JPRB-Z1S)*ZQSAT+(1.0_JPRB+Z1S)*ZQMAX)
        ZCOR=1.0_JPRB/(1.0_JPRB-YDCST%RETV*ZQSAT)
        ZQSAT=ZQSAT*ZCOR
        Z2S=ZOEALFA*YDTHF%R5ALVCP*(1.0_JPRB/(ZTARG-YDTHF%R4LES)**2)+(1.0_JPRB&
        &-ZOEALFA)*YDTHF%R5ALSCP*(1.0_JPRB/(ZTARG-YDTHF%R4IES)**2)
        ZCOND1=(PQD (JLON, IK)-ZQSAT)/(1.0_JPRB+ZQSAT*ZCOR*Z2S)
        PTD (JLON, IK)=PTD (JLON, IK)+(ZOEALFA*YDTHF%RALVDCP+(1.0_JPRB-ZOEALFA)*YDTHF%RALSDCP)*ZCOND1
        PQD (JLON, IK)=PQD (JLON, IK)-ZCOND1
      ENDIF

    ENDIF

  
  
  
  
  ENDIF


  

  

  

  

  IF (LLO2 ) THEN
    ZCOND =ZCOND -PQD (JLON, JLEV)
    ZBUO=PTD (JLON, JLEV)*(1.0_JPRB+YDCST%RETV*PQD (JLON, JLEV))-PTENH&
    & (JLON, JLEV)*(1.0_JPRB+YDCST%RETV*PQENH (JLON, JLEV))

    IF (PRFL (JLON)>0.0_JPRB.AND.PMFU (JLON, JLEV)>0.0_JPRB) THEN
      ZRAIN=PRFL (JLON)/PMFU (JLON, JLEV)
      ZBUO=ZBUO-PTD (JLON, JLEV)*ZRAIN
    ENDIF


    IF (ZBUO>=0.0_JPRB.OR.PRFL (JLON)<=(PMFD (JLON, JLEV)*ZCOND )) THEN
      PMFD (JLON, JLEV)=0.0_JPRB
      ZBUO=0.0_JPRB
    ENDIF

    PMFDS (JLON, JLEV)=(YDCST%RCPD*PTD (JLON, JLEV)+PGEOH (JLON, JLEV))*PMFD (JLON, JLEV)
    PMFDQ (JLON, JLEV)=PQD (JLON, JLEV)*PMFD (JLON, JLEV)
    ZDMFDP=-PMFD (JLON, JLEV)*ZCOND 
    PDMFDP (JLON, JLEV-1)=ZDMFDP
    PRFL (JLON)=PRFL (JLON)+ZDMFDP
    ZBUOYZ=ZBUO/PTENH (JLON, JLEV)
    ZBUOYV=ZBUOYZ
    ZBUOYZ=MIN (ZBUOYZ, 0.0_JPRB)
    ZDZ=-(PGEO (JLON, JLEV-1)-PGEO (JLON, JLEV))
    ZBUOY =ZBUOY +ZBUOYZ*ZDZ
    ZOENTR =YDCST%RG*ZBUOYZ*0.5_JPRB/(1.0_JPRB+ZBUOY )
    PMFDDE_RATE (JLON, JLEV)=-ZDMFDE 
    ZDKBUO=ZDZ*ZBUOYV*ZFACBUO

    IF (ZDMFEN <0.0_JPRB) THEN
      ZDKEN=MIN (1.0_JPRB,(1+Z_CWDRAG)*ZDMFEN /MIN (-YDECUMF%RMFCMIN, PMFD (JLON, JLEV-1)))
    ELSE
      ZDKEN=MIN (1.0_JPRB,(1+Z_CWDRAG)*ZDMFDE /MIN (-YDECUMF%RMFCMIN, PMFD (JLON, JLEV-1)))
    ENDIF

    PKINED (JLON, JLEV)=MAX (0.0_JPRB,(PKINED (JLON, JLEV-1)*(1-ZDKEN)+ZDKBUO)/(1+ZDKEN))
  ENDIF

  
ENDDO



ENDSUBROUTINE CUDDRAFN_OPENACC

! e56ac8e1f86b1a9cc13b38d73abbf48f96ba2f2a
