SUBROUTINE CUDTDQN_OPENACC (YDTHF, YDCST, YDEPHLI, YDPHNC, YDECUMF, YDEPHY, KIDIA, KFDIA, KLON, KLEV&
&, KTOPM2, KTYPE, KCTOP, KCBOT, KDTOP, LDTDKMF, LDCUM, LDDRAF, LSCVFLAG, PTSPHY, PAPH, PAP, PGEOH&
&, PGEO, PTEN, PTENH, PQEN, PQENH, PQSEN, PLGLAC, PLUDE, PLUDELI, PSNDE, PMFU, PMFD, PMFUS, PMFDS&
&, PMFUQ, PMFDQ, PMFUL, PDMFUP, PDPMEL, PMFLXR, PMFLXS, PTENT, PTENQ, PENTH, YDSTACK)
!$acc routine (CUDTDQN_OPENACC) seq
USE PARKIND1,ONLY:JPIM, JPRB

USE YOMCST,ONLY:TCST
USE YOETHF,ONLY:TTHF
USE YOECUMF,ONLY:TECUMF
USE YOEPHY,ONLY:TEPHY
USE YOEPHLI,ONLY:TEPHLI
USE YOPHNC,ONLY:TPHNC
USE ABOR1_ACC_MOD
USE STACK_MOD
#include "stack.h"

IMPLICIT NONE

TYPE (TTHF), INTENT (IN)::YDTHF
TYPE (TCST), INTENT (IN)::YDCST
TYPE (TECUMF), INTENT (IN)::YDECUMF
TYPE (TEPHLI), INTENT (IN)::YDEPHLI
TYPE (TEPHY), INTENT (IN)::YDEPHY
TYPE (TPHNC), INTENT (IN)::YDPHNC
INTEGER (KIND=JPIM), INTENT (IN)::KLON
INTEGER (KIND=JPIM), INTENT (IN)::KLEV
INTEGER (KIND=JPIM), INTENT (IN)::KIDIA
INTEGER (KIND=JPIM), INTENT (IN)::KFDIA
INTEGER (KIND=JPIM), INTENT (IN)::KTOPM2
INTEGER (KIND=JPIM), INTENT (IN)::KTYPE (KLON)
INTEGER (KIND=JPIM), INTENT (IN)::KCTOP (KLON)
INTEGER (KIND=JPIM), INTENT (IN)::KCBOT (KLON)
INTEGER (KIND=JPIM), INTENT (IN)::KDTOP (KLON)
LOGICAL, INTENT (INOUT)::LDCUM (KLON)
LOGICAL, INTENT (IN)::LDDRAF (KLON)
LOGICAL, INTENT (IN)::LDTDKMF
LOGICAL, INTENT (IN)::LSCVFLAG (KLON)
REAL (KIND=JPRB), INTENT (IN)::PTSPHY
REAL (KIND=JPRB), INTENT (IN)::PAPH (KLON, KLEV+1)
REAL (KIND=JPRB), INTENT (IN)::PAP (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PGEO (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PGEOH (KLON, KLEV+1)
REAL (KIND=JPRB), INTENT (IN)::PTEN (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PQEN (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PTENH (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PQENH (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PQSEN (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PLGLAC (KLON, KLEV)
REAL (KIND=JPRB), INTENT (INOUT)::PLUDE (KLON, KLEV)
REAL (KIND=JPRB), INTENT (INOUT)::PLUDELI (KLON, KLEV, 2)
REAL (KIND=JPRB), INTENT (INOUT)::PSNDE (KLON, KLEV, 2)
REAL (KIND=JPRB), INTENT (IN)::PMFU (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PMFD (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PMFUS (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PMFDS (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PMFUQ (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PMFDQ (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PMFUL (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PDMFUP (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PDPMEL (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PMFLXR (KLON, KLEV+1)
REAL (KIND=JPRB), INTENT (IN)::PMFLXS (KLON, KLEV+1)
REAL (KIND=JPRB), INTENT (INOUT)::PTENT (KLON, KLEV)
REAL (KIND=JPRB), INTENT (INOUT)::PTENQ (KLON, KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PENTH (KLON, KLEV)
TYPE(STACK) :: YDSTACK
TYPE(STACK) :: YLSTACK
LOGICAL::LLTEST

INTEGER (KIND=JPIM)::JLON
INTEGER (KIND=JPIM)::IM
INTEGER (KIND=JPIM)::IK
INTEGER (KIND=JPIM)::JLEV

REAL (KIND=JPRB)::ZQ
REAL (KIND=JPRB)::ZS
REAL (KIND=JPRB)::ZGH
REAL (KIND=JPRB)::ZGS
REAL (KIND=JPRB)::ZGQ
REAL (KIND=JPRB)::ZZP
REAL (KIND=JPRB)::ZTARG
REAL (KIND=JPRB)::ZOEALFA
REAL (KIND=JPRB)::ZORCPD
REAL (KIND=JPRB)::ZIMP
REAL (KIND=JPRB)::ZTSPHY

REAL (KIND=JPRB)::ZINT2 
REAL (KIND=JPRB)::ZINT 
temp (REAL (KIND=JPRB), ZALV2, (KLON, KLEV))
temp (REAL (KIND=JPRB), ZALV, (KLON, KLEV))

REAL (KIND=JPRB)::ZADVW 
temp (REAL (KIND=JPRB), ZMFDQ, (KLON, KLEV))
temp (REAL (KIND=JPRB), ZMFDS, (KLON, KLEV))
temp (REAL (KIND=JPRB), ZMFUQ, (KLON, KLEV))
temp (REAL (KIND=JPRB), ZMFUS, (KLON, KLEV))

temp (REAL (KIND=JPRB), ZDP, (KLON, KLEV))
temp (REAL (KIND=JPRB), ZDQDT, (KLON, KLEV))
temp (REAL (KIND=JPRB), ZDTDT, (KLON, KLEV))

temp (REAL (KIND=JPRB), ZR2, (KLON, KLEV))
temp (REAL (KIND=JPRB), ZR1, (KLON, KLEV))
temp (REAL (KIND=JPRB), ZB, (KLON, KLEV))
temp (LOGICAL, LLCUMBAS, (KLON, KLEV))

#include "cubidiag_openacc.intfb.h"
#include "fcttre.func.h"

YLSTACK = YDSTACK


IF (KIND (ZALV2) == 8) THEN
    alloc8 (ZALV2)
ELSEIF (KIND (ZALV2) == 4) THEN
    alloc4 (ZALV2)
ELSE
    STOP 1
ENDIF


IF (KIND (ZALV) == 8) THEN
    alloc8 (ZALV)
ELSEIF (KIND (ZALV) == 4) THEN
    alloc4 (ZALV)
ELSE
    STOP 1
ENDIF


IF (KIND (ZMFDQ) == 8) THEN
    alloc8 (ZMFDQ)
ELSEIF (KIND (ZMFDQ) == 4) THEN
    alloc4 (ZMFDQ)
ELSE
    STOP 1
ENDIF


IF (KIND (ZMFDS) == 8) THEN
    alloc8 (ZMFDS)
ELSEIF (KIND (ZMFDS) == 4) THEN
    alloc4 (ZMFDS)
ELSE
    STOP 1
ENDIF


IF (KIND (ZMFUQ) == 8) THEN
    alloc8 (ZMFUQ)
ELSEIF (KIND (ZMFUQ) == 4) THEN
    alloc4 (ZMFUQ)
ELSE
    STOP 1
ENDIF


IF (KIND (ZMFUS) == 8) THEN
    alloc8 (ZMFUS)
ELSEIF (KIND (ZMFUS) == 4) THEN
    alloc4 (ZMFUS)
ELSE
    STOP 1
ENDIF


IF (KIND (ZDP) == 8) THEN
    alloc8 (ZDP)
ELSEIF (KIND (ZDP) == 4) THEN
    alloc4 (ZDP)
ELSE
    STOP 1
ENDIF


IF (KIND (ZDQDT) == 8) THEN
    alloc8 (ZDQDT)
ELSEIF (KIND (ZDQDT) == 4) THEN
    alloc4 (ZDQDT)
ELSE
    STOP 1
ENDIF


IF (KIND (ZDTDT) == 8) THEN
    alloc8 (ZDTDT)
ELSEIF (KIND (ZDTDT) == 4) THEN
    alloc4 (ZDTDT)
ELSE
    STOP 1
ENDIF


IF (KIND (ZR2) == 8) THEN
    alloc8 (ZR2)
ELSEIF (KIND (ZR2) == 4) THEN
    alloc4 (ZR2)
ELSE
    STOP 1
ENDIF


IF (KIND (ZR1) == 8) THEN
    alloc8 (ZR1)
ELSEIF (KIND (ZR1) == 4) THEN
    alloc4 (ZR1)
ELSE
    STOP 1
ENDIF


IF (KIND (ZB) == 8) THEN
    alloc8 (ZB)
ELSEIF (KIND (ZB) == 4) THEN
    alloc4 (ZB)
ELSE
    STOP 1
ENDIF


IF (KIND (LLCUMBAS) == 8) THEN
    alloc8 (LLCUMBAS)
ELSEIF (KIND (LLCUMBAS) == 4) THEN
    alloc4 (LLCUMBAS)
ELSE
    STOP 1
ENDIF




JLON = KIDIA


ZIMP=1.0_JPRB-YDECUMF%RMFSOLTQ
ZTSPHY=1.0_JPRB/PTSPHY
ZORCPD=1.0_JPRB/YDCST%RCPD

ZADVW =0.0_JPRB

IF (KTYPE (JLON)==1)  THEN
    ZADVW =YDECUMF%RMFADVW
ENDIF



DO JLEV=1, KLEV
  
  PENTH (JLON, JLEV)=0.0_JPRB
  
ENDDO



IF (KTYPE (JLON)/=1.AND.YDEPHLI%LPHYLIN)  THEN
    LDCUM (JLON)=.FALSE.
ENDIF


LLTEST=(.NOT.YDEPHY%LEPCLD.AND..NOT.YDPHNC%LENCLD2.AND..NOT.YDPHNC%LEPCLD2&
&).OR.(YDEPHLI%LPHYLIN.AND..NOT.YDPHNC%LENCLD2.AND..NOT.YDPHNC%LEPCLD2)

IF (LLTEST) THEN

  DO JLEV=1, KLEV
    
    PLUDE (JLON, JLEV)=0.0_JPRB
    PLUDELI (JLON, JLEV, 1)=0.0_JPRB
    PLUDELI (JLON, JLEV, 2)=0.0_JPRB
  
  ENDDO

ENDIF


DO JLEV=1, KLEV

  

  IF (LDCUM (JLON)) THEN
    ZDP (JLON, JLEV)=YDCST%RG/(PAPH (JLON, JLEV+1)-PAPH (JLON, JLEV))
    ZMFUS (JLON, JLEV)=PMFUS (JLON, JLEV)
    ZMFDS (JLON, JLEV)=PMFDS (JLON, JLEV)
    ZMFUQ (JLON, JLEV)=PMFUQ (JLON, JLEV)
    ZMFDQ (JLON, JLEV)=PMFDQ (JLON, JLEV)
  ENDIF

  
ENDDO


IF (YDECUMF%RMFSOLTQ>0.0_JPRB) THEN

  DO JLEV=KTOPM2, KLEV
    IK=JLEV-1

    

    IF (LDCUM (JLON).AND.JLEV>=KCTOP (JLON)-1) THEN
      ZGQ=(PQENH (JLON, JLEV)-PQEN (JLON, IK))/PQSEN (JLON, JLEV)
      ZGH=YDCST%RCPD*PTEN (JLON, JLEV)+PGEO (JLON, JLEV)
      ZGS=(YDCST%RCPD*(PTENH (JLON, JLEV)-PTEN (JLON, IK))+PGEOH (JLON, JLEV)-PGEO (JLON, IK))/ZGH
      ZS=YDCST%RCPD*(ZIMP*PTEN (JLON, IK)+ZGS*PTEN (JLON, JLEV))+PGEO (JLON, IK)+ZGS*PGEO (JLON, JLEV)
      ZQ=ZIMP*PQEN (JLON, IK)+ZGQ*PQSEN (JLON, JLEV)
      ZMFUS (JLON, JLEV)=PMFUS (JLON, JLEV)-PMFU (JLON, JLEV)*ZS
      ZMFUQ (JLON, JLEV)=PMFUQ (JLON, JLEV)-PMFU (JLON, JLEV)*ZQ

      IF (LDDRAF (JLON).AND.JLEV>=KDTOP (JLON)) THEN
        ZMFDS (JLON, JLEV)=PMFDS (JLON, JLEV)-PMFD (JLON, JLEV)*ZS
        ZMFDQ (JLON, JLEV)=PMFDQ (JLON, JLEV)-PMFD (JLON, JLEV)*ZQ
      ENDIF

    ENDIF

  
  ENDDO

ENDIF

ZINT=0._JPRB

DO JLEV=KTOPM2, KLEV
  
  ZALV (JLON, JLEV)=FOELHMCU (PTEN (JLON, JLEV))
  ZALV2 (JLON, JLEV)=ZALV (JLON, JLEV)
  
ENDDO


IF (YDECUMF%LMFENTHCONS) THEN

  DO JLEV=KTOPM2, KLEV-1

    

    IF (LSCVFLAG (JLON))  THEN
        ZALV (JLON, JLEV)=YDCST%RLVTT
    ENDIF

    ZINT =ZINT +YDCST%RLMLT*(PLGLAC (JLON, JLEV)-PDPMEL (JLON, JLEV))-ZALV (JLON, JLEV)*&
    &(PMFUL (JLON, JLEV+1)-PMFUL (JLON, JLEV))+ZALV2 (JLON, JLEV)*PDMFUP (JLON, JLEV)
  
  ENDDO

  JLEV=KLEV

  

  IF (LSCVFLAG (JLON))  THEN
      ZALV (JLON, JLEV)=YDCST%RLVTT
  ENDIF

  ZINT =ZINT +YDCST%RLMLT*(PLGLAC (JLON, JLEV)-PDPMEL (JLON, JLEV))+ZALV (JLON&
  &, JLEV)*PMFUL (JLON, JLEV)+ZALV2 (JLON, JLEV)*PDMFUP (JLON, JLEV)
  ZINT2 =ZINT -YDCST%RLVTT*PMFLXR (JLON, KLEV+1)-YDCST%RLSTT*PMFLXS (JLON, KLEV+1)

  IF (ABS (ZINT )>0.1_JPRB) THEN
    ZINT =ZINT2 /(ZINT +1.E-3_JPRB)
  ELSE
    ZINT =0.0_JPRB
  ENDIF


  IF (ABS (ZINT )>2.0_JPRB)  THEN
      ZINT =0.0_JPRB
  ENDIF

  
ENDIF


DO JLEV=KTOPM2, KLEV

  IF (JLEV<KLEV) THEN

    

    IF (LDCUM (JLON)) THEN

      IF (YDEPHLI%LPHYLIN) THEN
        ZTARG=PTEN (JLON, JLEV)
        ZOEALFA=MIN (1.0_JPRB, 0.545_JPRB*(TANH (0.17_JPRB*(ZTARG-YDEPHLI%RLPTRC))+1.0_JPRB))
        ZALV (JLON, JLEV)=ZOEALFA*YDCST%RLVTT+(1.0_JPRB-ZOEALFA)*YDCST%RLSTT
        ZALV2 (JLON, JLEV)=ZALV (JLON, JLEV)
      ENDIF


      IF (LDTDKMF) THEN
        ZDTDT (JLON, JLEV)=ZDP (JLON, JLEV)*ZORCPD*(ZMFUS (JLON, JLEV+1)-ZMFUS (JLON, JLEV)+ZMFDS (JLON, JLEV&
        &+1)-ZMFDS (JLON, JLEV)+YDCST%RLMLT*PLGLAC (JLON, JLEV)-YDCST%RLMLT*PDPMEL (JLON, JLEV)-ZALV (JLON&
        &, JLEV)*(PMFUL (JLON, JLEV+1)-PMFUL (JLON, JLEV)-PLUDE (JLON, JLEV)-PDMFUP (JLON, JLEV)))
        ZDQDT (JLON, JLEV)=ZDP (JLON, JLEV)*(ZMFUQ (JLON, JLEV+1)-ZMFUQ (JLON, JLEV)+ZMFDQ (JLON, JLEV+1)-ZMFDQ&
        & (JLON, JLEV)+PMFUL (JLON, JLEV+1)-PMFUL (JLON, JLEV)-PLUDE (JLON, JLEV)-PDMFUP (JLON, JLEV))
      ELSE
        ZDTDT (JLON, JLEV)=ZDP (JLON, JLEV)*ZORCPD*(ZMFUS (JLON, JLEV+1)-ZMFUS (JLON, JLEV)+ZMFDS&
        & (JLON, JLEV+1)-ZMFDS (JLON, JLEV)+(YDCST%RLMLT*(PLGLAC (JLON, JLEV)-PDPMEL (JLON, JLEV&
        &))-ZALV (JLON, JLEV)*(PMFUL (JLON, JLEV+1)-PMFUL (JLON, JLEV))+ZALV2 (JLON, JLEV)*PDMFUP&
        & (JLON, JLEV))*(1.0_JPRB-ZINT )+YDCST%RLVTT*(PLUDELI (JLON, JLEV, 1)+PSNDE (JLON, JLEV&
        &, 1))+YDCST%RLSTT*(PLUDELI (JLON, JLEV, 2)+PSNDE (JLON, JLEV, 2)))
        ZDQDT (JLON, JLEV)=ZDP (JLON, JLEV)*(ZMFUQ (JLON, JLEV+1)-ZMFUQ (JLON, JLEV)+ZMFDQ&
        & (JLON, JLEV+1)-ZMFDQ (JLON, JLEV)+PMFUL (JLON, JLEV+1)-PMFUL (JLON, JLEV)-PLUDE &
        &(JLON, JLEV)-PDMFUP (JLON, JLEV)-PSNDE (JLON, JLEV, 1)-PSNDE (JLON, JLEV, 2))
      ENDIF

    ENDIF

  
  ELSE

    

    IF (LDCUM (JLON)) THEN

      IF (YDEPHLI%LPHYLIN) THEN
        ZTARG=PTEN (JLON, JLEV)
        ZOEALFA=MIN (1.0_JPRB, 0.545_JPRB*(TANH (0.17_JPRB*(ZTARG-YDEPHLI%RLPTRC))+1.0_JPRB))
        ZALV (JLON, JLEV)=ZOEALFA*YDCST%RLVTT+(1.0_JPRB-ZOEALFA)*YDCST%RLSTT
        ZALV2 (JLON, JLEV)=ZALV (JLON, JLEV)
      ENDIF

      ZDTDT (JLON, JLEV)=-ZDP (JLON, JLEV)*ZORCPD*(ZMFUS (JLON, JLEV)+ZMFDS (JLON, JLEV&
      &)+(YDCST%RLMLT*(PDPMEL (JLON, JLEV)-PLGLAC (JLON, JLEV))-ZALV (JLON, JLEV)*PMFUL&
      & (JLON, JLEV)-ZALV2 (JLON, JLEV)*PDMFUP (JLON, JLEV))*(1.0_JPRB-ZINT ))
      ZDQDT (JLON, JLEV)=-ZDP (JLON, JLEV)*(ZMFUQ (JLON, JLEV)+ZMFDQ&
      & (JLON, JLEV)+(PMFUL (JLON, JLEV)+PDMFUP (JLON, JLEV)))
    ENDIF

  
  ENDIF

ENDDO


IF (YDECUMF%RMFSOLTQ==0.0_JPRB) THEN

  DO JLEV=KTOPM2, KLEV

    

    IF (LDCUM (JLON)) THEN
      PTENT (JLON, JLEV)=PTENT (JLON, JLEV)+ZDTDT (JLON, JLEV)
      PTENQ (JLON, JLEV)=PTENQ (JLON, JLEV)+ZDQDT (JLON, JLEV)
      PENTH (JLON, JLEV)=ZDTDT (JLON, JLEV)*YDCST%RCPD
    ENDIF

  
  ENDDO

ELSE
  LLCUMBAS (JLON,:)=.FALSE.
  ZB (JLON,:)=1.0_JPRB
  ZMFUS (JLON,:)=0.0_JPRB

  DO JLEV=KTOPM2, KLEV
    IK=JLEV+1
    IM=JLEV-1
    
    LLCUMBAS (JLON, JLEV)=LDCUM (JLON).AND.JLEV>=KCTOP (JLON)-1

    IF (LLCUMBAS (JLON, JLEV)) THEN
      ZZP=YDECUMF%RMFSOLTQ*ZDP (JLON, JLEV)*PTSPHY
      ZMFUS (JLON, JLEV)=-ZZP*(PMFU (JLON, JLEV)+PMFD (JLON, JLEV))

      IF (JLEV<KLEV) THEN
        ZB (JLON, JLEV)=1.0_JPRB+ZZP*(PMFU (JLON, IK)+PMFD (JLON, IK))
      ELSE
        ZB (JLON, JLEV)=1.0_JPRB
      ENDIF


      IF (LDTDKMF) THEN
        ZDTDT (JLON, JLEV)=ZDTDT (JLON, JLEV)*PTSPHY+PTEN (JLON, JLEV)
        ZDQDT (JLON, JLEV)=ZDQDT (JLON, JLEV)*PTSPHY+PQEN (JLON, JLEV)
      ELSE
        ZZP=YDCST%RG*(PMFU (JLON, JLEV)+YDECUMF%RMFADVWDD*PMFD (JLON&
        &, JLEV))/(PAP (JLON, JLEV)-PAP (JLON, IM))*PTSPHY*ZADVW 
        ZS=ZZP*(PTEN (JLON, IM)-PTEN (JLON, JLEV)+ZORCPD*(PGEO (JLON, IM)-PGEO (JLON, JLEV)))
        ZQ=ZZP*(PQEN (JLON, IM)-PQEN (JLON, JLEV))
        ZDTDT (JLON, JLEV)=(ZDTDT (JLON, JLEV)+PTENT (JLON, JLEV&
        &)*YDECUMF%RMFSOLRHS)*PTSPHY+PTEN (JLON, JLEV)-ZS
        ZDQDT (JLON, JLEV)=(ZDQDT (JLON, JLEV)+PTENQ (JLON, JLEV&
        &)*YDECUMF%RMFSOLRHS)*PTSPHY+PQEN (JLON, JLEV)-ZQ
      ENDIF

    ENDIF

  
  ENDDO

  CALL CUBIDIAG_OPENACC (KIDIA, KFDIA, KLON, KLEV, KCTOP&
  &, LLCUMBAS, ZMFUS, ZB, ZDTDT, ZR1, YDSTACK=YLSTACK)
  CALL CUBIDIAG_OPENACC (KIDIA, KFDIA, KLON, KLEV, KCTOP&
  &, LLCUMBAS, ZMFUS, ZB, ZDQDT, ZR2, YDSTACK=YLSTACK)

  DO JLEV=KTOPM2, KLEV

    

    IF (LLCUMBAS (JLON, JLEV)) THEN

      IF (LDTDKMF) THEN
        PTENT (JLON, JLEV)=PTENT (JLON, JLEV)+(ZR1 (JLON, JLEV)-PTEN (JLON, JLEV))*ZTSPHY
        PTENQ (JLON, JLEV)=PTENQ (JLON, JLEV)+(ZR2 (JLON, JLEV)-PQEN (JLON, JLEV))*ZTSPHY
      ELSE
        PTENT (JLON, JLEV)=PTENT (JLON, JLEV)*(1.0_JPRB-YDECUMF%RMFSOLRHS&
        &)+(ZR1 (JLON, JLEV)-PTEN (JLON, JLEV))*ZTSPHY
        PTENQ (JLON, JLEV)=PTENQ (JLON, JLEV)*(1.0_JPRB-YDECUMF%RMFSOLRHS&
        &)+(ZR2 (JLON, JLEV)-PQEN (JLON, JLEV))*ZTSPHY
      ENDIF

      PENTH (JLON, JLEV)=(ZR1 (JLON, JLEV)-PTEN (JLON, JLEV))*ZTSPHY
    ENDIF

  
  ENDDO

ENDIF



ENDSUBROUTINE CUDTDQN_OPENACC

! e56ac8e1f86b1a9cc13b38d73abbf48f96ba2f2a
