FCFLAGS=-mp -fPIC -Minfo -gopt -Mlarge_arrays -Mlist -traceback -Mnofma -Mbyteswapio -Mbackslash -Mstack_arrays -cuda -acc=gpu -O2 -gopt -gpu=cc70,cc80 -Minfo=accel,all,ccff 
ARCH=gpu_nvhpc_d
LIBS=-lnvhpcwrapnvtx -lnvToolsExt


FC=fxtran-f90 \
  --user-directory-in user-in \
  --user-directory-out user-out \
  --config $(SRC)/fxtran.conf -- \
  pgf90 \
  $(FCFLAGS) -DARCH="'$(ARCH)'"
CC=/bin/cc
