FC=/home/gmap/mrpm/marguina/fxtran-acdc/canonic-layout-outline/bin/fxtran-f90 --config fxtran.conf -- \
    /home/gmap/mrpm/marguina/gpupack/support/wrap/NVHPC2405ECTRANSGPU/mpif90 \
    -mp -fPIC -Minfo -gopt -Mlarge_arrays -Mlist -traceback -Mnofma -Mbyteswapio -Mbackslash -Mstack_arrays \
    -cuda -acc=gpu -O2 -gopt -gpu=cc70,cc80 -Minfo=accel,all,ccff -DARCH="'$(ARCH)'"
CC=gcc
