FC=/home/gmap/mrpm/marguina/gpupack/support/wrap/INTEL2302/mpif90 -convert big_endian -assume byterecl -align array64byte,all -traceback -fpic -qopenmp -qopenmp-threadprivate compat -fp-model source -qopt-report=5 -qopt-report-phase=vec -ftz -diag-disable=remark,cpu-dispatch -g -O2 -march=core-avx2 -finline-functions -finline-limit=500 -Winline -qopt-prefetch=4 -fast-transcendentals -fimf-use-svml -no-fma -DARCH="'$(ARCH)'" -DPARKIND1_SINGLE
CC=/bin/cc

