[
  '--stack84', 
  '--methods-list', 'save,load,copy,wipe',
  '--tmp', '/home/gmap/mrpm/marguina/cucalln2/master-parallel/compile.cpu_intel_d/tmp',
  '--type-bound-methods',
  '--merge-interfaces',
  '--parallelmethod-section',
  '--inlined', 'cuadjtq.F90,cubasmcn.F90,cuentr.F90,cuadjtqs.F90',
  '--drhooktonvtx',
  '--numbered-submodules',
  '--use-stack-manyblocks',
# '--use-bit-repro-intrinsics',
  '--stack-method',
]
