[
  '--stack84', 
  '--methods-list', 'save,load,copy,wipe',
  '--debug',
  '--tmp', '/home/gmap/mrpm/marguina/cucalln2/master-parallel/compile.cpu_intel_d/tmp',
  '--type-bound-methods',
  '--merge-interfaces',
  '--parallelmethod-section',
  '--inlined', 'cuadjtq.F90,cubasmcn.F90,cuentr.F90,cuadjtqs.F90',
  '--numbered-submodules',
  '--object-merge-method', 'concatenate-include',
  '--use-stack-manyblocks',
  '--max-statements-per-parallel', 30,
# '--array-slice-to-address',
]
