PROGRAM MAIN_CUCALLN_MF 

#ifdef PGI
USE NVTX
#endif

USE MODEL_PHYSICS_ECMWF_MOD      , ONLY : MODEL_PHYSICS_ECMWF_TYPE
USE MODEL_PHYSICS_SIMPLINEAR_MOD , ONLY : MODEL_PHYSICS_SIMPLINEAR_TYPE
USE YOERAD                       , ONLY : TERAD
USE YOM_YGFL                     , ONLY : TYPE_GFLD
USE YOMCHEM                      , ONLY : TCHEM
USE SPP_MOD                      , ONLY : TSPP_CONFIG
USE PARKIND1                     , ONLY : JPIM     ,JPRB
USE YOMHOOK                      , ONLY : LHOOK,   DR_HOOK, JPHOOK

USE YOMCST                       , ONLY : TCST  
USE YOETHF                       , ONLY : TTHF 
USE YOMPERTPAR                   , ONLY : TPERTPAR

USE CPG_OPTS_TYPE_MOD            , ONLY : CPG_OPTS_TYPE, CPG_BNDS_TYPE

USE FIELD_MODULE
USE FIELD_FACTORY_MODULE
USE FIELD_ACCESS_MODULE

USE YOMDATA

USE XRD_GETOPTIONS
USE XRD_UNIX_ENV

USE YOMHOOK
USE ABOR1_ACC_MOD

#include "stack.h"

USE STACK_MOD

USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY : STDOUT => OUTPUT_UNIT

IMPLICIT NONE


REAL(KIND=JPRB)                      :: PPLDARE
REAL(KIND=JPRB)                      :: PPLRG
INTEGER(KIND=JPIM)                   :: KSTEP
TYPE(TTHF)                           :: YDTHF
TYPE(TCST)                           :: YDCST
TYPE(TERAD)                          :: YDERAD
TYPE(MODEL_PHYSICS_SIMPLINEAR_TYPE)  :: YDML_PHY_SLIN
TYPE(MODEL_PHYSICS_ECMWF_TYPE)       :: YDML_PHY_EC
TYPE(TYPE_GFLD)                      :: YGFL
TYPE(TCHEM)                          :: YDCHEM
TYPE(TSPP_CONFIG)                    :: YDSPP_CONFIG
TYPE(TPERTPAR)                       :: YDPERTPAR
INTEGER(KIND=JPIM)                   :: KLON,KGPBLKS
INTEGER(KIND=JPIM)                   :: KSMAX 
INTEGER(KIND=JPIM)                   :: KLEV 
INTEGER(KIND=JPIM)                   :: KSPPN2D
INTEGER(KIND=JPIM)                   :: KTRAC 
LOGICAL                              :: LDMCAPEA
LOGICAL                              :: LDSLPHY 
REAL(KIND=JPRB)                      :: PTSPHY 
REAL(KIND=JPRB)                      :: PVDIFTS

TYPE (CPG_OPTS_TYPE) :: YDCPG_OPTS
TYPE (CPG_BNDS_TYPE) :: YDCPG_BNDS


CLASS (FIELD_2LM), POINTER :: YD_LDLAND           ; LOGICAL, POINTER::LDLAND (:,:)                     
CLASS (FIELD_3RB), POINTER :: YD_PLCRIT_AER       ; REAL (KIND=JPRB), POINTER::PLCRIT_AER (:,:,:)      
CLASS (FIELD_3RB), POINTER :: YD_PTM1             ; REAL (KIND=JPRB), POINTER::PTM1 (:,:,:)            
CLASS (FIELD_3RB), POINTER :: YD_PQM1             ; REAL (KIND=JPRB), POINTER::PQM1 (:,:,:)            
CLASS (FIELD_3RB), POINTER :: YD_PUM1             ; REAL (KIND=JPRB), POINTER::PUM1 (:,:,:)            
CLASS (FIELD_3RB), POINTER :: YD_PVM1             ; REAL (KIND=JPRB), POINTER::PVM1 (:,:,:)            
CLASS (FIELD_4RB), POINTER :: YD_PCM1             ; REAL (KIND=JPRB), POINTER::PCM1 (:,:,:,:)          
CLASS (FIELD_3RB), POINTER :: YD_PLITOT           ; REAL (KIND=JPRB), POINTER::PLITOT (:,:,:)          
CLASS (FIELD_3RB), POINTER :: YD_PVERVEL          ; REAL (KIND=JPRB), POINTER::PVERVEL (:,:,:)         
CLASS (FIELD_3RB), POINTER :: YD_PQHFL            ; REAL (KIND=JPRB), POINTER::PQHFL (:,:,:)           
CLASS (FIELD_3RB), POINTER :: YD_PAHFS            ; REAL (KIND=JPRB), POINTER::PAHFS (:,:,:)           
CLASS (FIELD_3RB), POINTER :: YD_PAPHM1           ; REAL (KIND=JPRB), POINTER::PAPHM1 (:,:,:)          
CLASS (FIELD_3RB), POINTER :: YD_PAP              ; REAL (KIND=JPRB), POINTER::PAP (:,:,:)             
CLASS (FIELD_3RB), POINTER :: YD_PAPH             ; REAL (KIND=JPRB), POINTER::PAPH (:,:,:)            
CLASS (FIELD_3RB), POINTER :: YD_PGEO             ; REAL (KIND=JPRB), POINTER::PGEO (:,:,:)            
CLASS (FIELD_3RB), POINTER :: YD_PGEOH            ; REAL (KIND=JPRB), POINTER::PGEOH (:,:,:)           
CLASS (FIELD_3RB), POINTER :: YD_PTENT            ; REAL (KIND=JPRB), POINTER::PTENT (:,:,:)           
CLASS (FIELD_3RB), POINTER :: YD_PTENQ            ; REAL (KIND=JPRB), POINTER::PTENQ (:,:,:)           
CLASS (FIELD_3RB), POINTER :: YD_PTENU            ; REAL (KIND=JPRB), POINTER::PTENU (:,:,:)           
CLASS (FIELD_3RB), POINTER :: YD_PTENV            ; REAL (KIND=JPRB), POINTER::PTENV (:,:,:)           
CLASS (FIELD_3RB), POINTER :: YD_PTENTA           ; REAL (KIND=JPRB), POINTER::PTENTA (:,:,:)          
CLASS (FIELD_3RB), POINTER :: YD_PTENQA           ; REAL (KIND=JPRB), POINTER::PTENQA (:,:,:)          
CLASS (FIELD_2RB), POINTER :: YD_PGAW             ; REAL (KIND=JPRB), POINTER::PGAW (:,:)              
CLASS (FIELD_2RB), POINTER :: YD_PCUCONVCA        ; REAL (KIND=JPRB), POINTER::PCUCONVCA (:,:)         
CLASS (FIELD_3RB), POINTER :: YD_PGP2DSPP         ; REAL (KIND=JPRB), POINTER::PGP2DSPP (:,:,:)        
CLASS (FIELD_2RB), POINTER :: YD_PDX              ; REAL (KIND=JPRB), POINTER::PDX (:,:)               
CLASS (FIELD_4RB), POINTER :: YD_PTENC            ; REAL (KIND=JPRB), POINTER::PTENC (:,:,:,:)         
CLASS (FIELD_2RB), POINTER :: YD_PARPRC           ; REAL (KIND=JPRB), POINTER::PARPRC (:,:)            
CLASS (FIELD_2IM), POINTER :: YD_KTOPC            ; INTEGER (KIND=JPIM), POINTER::KTOPC (:,:)          
CLASS (FIELD_2IM), POINTER :: YD_KBASEC           ; INTEGER (KIND=JPIM), POINTER::KBASEC (:,:)         
CLASS (FIELD_2IM), POINTER :: YD_KTYPE            ; INTEGER (KIND=JPIM), POINTER::KTYPE (:,:)          
CLASS (FIELD_2IM), POINTER :: YD_KCBOT            ; INTEGER (KIND=JPIM), POINTER::KCBOT (:,:)          
CLASS (FIELD_2IM), POINTER :: YD_KCTOP            ; INTEGER (KIND=JPIM), POINTER::KCTOP (:,:)          
CLASS (FIELD_2IM), POINTER :: YD_KCBOT_LIG        ; INTEGER (KIND=JPIM), POINTER::KCBOT_LIG (:,:)      
CLASS (FIELD_2IM), POINTER :: YD_KCTOP_LIG        ; INTEGER (KIND=JPIM), POINTER::KCTOP_LIG (:,:)      
CLASS (FIELD_2IM), POINTER :: YD_KBOTSC           ; INTEGER (KIND=JPIM), POINTER::KBOTSC (:,:)         
CLASS (FIELD_2LM), POINTER :: YD_LDCUM            ; LOGICAL, POINTER::LDCUM (:,:)                      
CLASS (FIELD_2LM), POINTER :: YD_LDCUM_LIG        ; LOGICAL, POINTER::LDCUM_LIG (:,:)                  
CLASS (FIELD_2LM), POINTER :: YD_LDSC             ; LOGICAL, POINTER::LDSC (:,:)                       
CLASS (FIELD_2LM), POINTER :: YD_LDSHCV           ; LOGICAL, POINTER::LDSHCV (:,:)                     
CLASS (FIELD_3RB), POINTER :: YD_PLU              ; REAL (KIND=JPRB), POINTER::PLU (:,:,:)             
CLASS (FIELD_3RB), POINTER :: YD_PLUDE            ; REAL (KIND=JPRB), POINTER::PLUDE (:,:,:)           
CLASS (FIELD_4RB), POINTER :: YD_PLUDELI          ; REAL (KIND=JPRB), POINTER::PLUDELI (:,:,:,:)       
CLASS (FIELD_4RB), POINTER :: YD_PSNDE            ; REAL (KIND=JPRB), POINTER::PSNDE (:,:,:,:)         
CLASS (FIELD_3RB), POINTER :: YD_PMFU             ; REAL (KIND=JPRB), POINTER::PMFU (:,:,:)            
CLASS (FIELD_3RB), POINTER :: YD_PMFD             ; REAL (KIND=JPRB), POINTER::PMFD (:,:,:)            
CLASS (FIELD_3RB), POINTER :: YD_PLGLAC           ; REAL (KIND=JPRB), POINTER::PLGLAC (:,:,:)          
CLASS (FIELD_3RB), POINTER :: YD_PDIFCQ           ; REAL (KIND=JPRB), POINTER::PDIFCQ (:,:,:)          
CLASS (FIELD_3RB), POINTER :: YD_PDIFCS           ; REAL (KIND=JPRB), POINTER::PDIFCS (:,:,:)          
CLASS (FIELD_3RB), POINTER :: YD_PFHPCL           ; REAL (KIND=JPRB), POINTER::PFHPCL (:,:,:)          
CLASS (FIELD_3RB), POINTER :: YD_PFHPCN           ; REAL (KIND=JPRB), POINTER::PFHPCN (:,:,:)          
CLASS (FIELD_3RB), POINTER :: YD_PFPLCL           ; REAL (KIND=JPRB), POINTER::PFPLCL (:,:,:)          
CLASS (FIELD_3RB), POINTER :: YD_PFPLCN           ; REAL (KIND=JPRB), POINTER::PFPLCN (:,:,:)          
CLASS (FIELD_3RB), POINTER :: YD_PLRAIN           ; REAL (KIND=JPRB), POINTER::PLRAIN (:,:,:)          
CLASS (FIELD_4RB), POINTER :: YD_PRSUD            ; REAL (KIND=JPRB), POINTER::PRSUD (:,:,:,:)         
CLASS (FIELD_3RB), POINTER :: YD_PSTRCU           ; REAL (KIND=JPRB), POINTER::PSTRCU (:,:,:)          
CLASS (FIELD_3RB), POINTER :: YD_PSTRCV           ; REAL (KIND=JPRB), POINTER::PSTRCV (:,:,:)          
CLASS (FIELD_3RB), POINTER :: YD_PFCQLF           ; REAL (KIND=JPRB), POINTER::PFCQLF (:,:,:)          
CLASS (FIELD_3RB), POINTER :: YD_PFCQIF           ; REAL (KIND=JPRB), POINTER::PFCQIF (:,:,:)          
CLASS (FIELD_3RB), POINTER :: YD_PMFUDE_RATE      ; REAL (KIND=JPRB), POINTER::PMFUDE_RATE (:,:,:)     
CLASS (FIELD_3RB), POINTER :: YD_PMFDDE_RATE      ; REAL (KIND=JPRB), POINTER::PMFDDE_RATE (:,:,:)     
CLASS (FIELD_2RB), POINTER :: YD_PCAPE            ; REAL (KIND=JPRB), POINTER::PCAPE (:,:)             
CLASS (FIELD_2RB), POINTER :: YD_PWMEAN           ; REAL (KIND=JPRB), POINTER::PWMEAN (:,:)            
CLASS (FIELD_2RB), POINTER :: YD_PVDISCU          ; REAL (KIND=JPRB), POINTER::PVDISCU (:,:)           
CLASS (FIELD_3RB), POINTER :: YD_PWU              ; REAL (KIND=JPRB), POINTER::PWU (:,:,:)             
CLASS (FIELD_3RB), POINTER :: YD_PDISS            ; REAL (KIND=JPRB), POINTER::PDISS (:,:,:)           

REAL(KIND=JPRB)                   , POINTER  :: PSCAV(:) 
REAL(KIND=JPRB)                   , POINTER  :: PSCAV0(:) 

#include "cucalln_mf.intfb.h"

INTEGER :: JLON, JBLK
INTEGER :: IIDIA, IFDIA
INTEGER :: ILUNCI, ILUNFI, ILUNFO, IOUT
INTEGER :: NPROMA, NGPBLKS
CHARACTER (LEN=128) :: CLOUT
CHARACTER (LEN=128) :: CLCASE_IN
CHARACTER (LEN=128) :: CLCASE_OUT
CHARACTER (LEN=32) :: CLMETHOD
TYPE (DD12), POINTER :: YLD
LOGICAL :: LLVERBOSE, LLDIFF, LLSTAT
INTEGER, POINTER :: IBLOCKLIST (:)
TYPE(STACK) :: YLSTACK
INTEGER :: ISIZE4, ISIZE8
INTEGER :: ITIME, NTIME
LOGICAL :: LLSAVE, LLEXIST
REAL(KIND=8) :: TSC, TEC, TSD, TED, ZTC, ZTD

#ifdef ARCH
CHARACTER (LEN=*), PARAMETER :: CLARCH = ARCH
#else
CHARACTER (LEN=*), PARAMETER :: CLARCH = 'unkwown'
#endif

REAL (KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK ('MAIN_CUCALLN_MF', 0, ZHOOK_HANDLE)

CALL LINUX_BIND (0, 1)
CALL LINUX_BIND_DUMP (0, 1)

YLD => NULL ()

CALL INITOPTIONS

NPROMA  = 0; CALL GETOPTION ("--nproma",  NPROMA)
NGPBLKS = 0; CALL GETOPTION ("--ngpblks", NGPBLKS)

CALL GETOPTION ("--case-in", CLCASE_IN, MND=.TRUE.)
CLCASE_OUT = ''; CALL GETOPTION ("--case-out", CLCASE_OUT)

CALL GETOPTION ("--verbose", LLVERBOSE)
CALL GETOPTION ("--diff", LLDIFF)
CALL GETOPTION ("--stat", LLSTAT)

CALL GETOPTION ("--method", CLMETHOD, MND=.TRUE.)


#ifdef PARKIND1_SINGLE
ISIZE4 = 80; 
ISIZE8 = 10; 
#else
ISIZE4 = 10; 
ISIZE8 = 80; 
#endif
CALL GETOPTION ("--stack-size-4", ISIZE4)
CALL GETOPTION ("--stack-size-8", ISIZE8)
NTIME = 1; CALL GETOPTION ("--times", NTIME)

IBLOCKLIST => NULL ()
CALL GETOPTION ("--block-list", IBLOCKLIST)

LLSAVE = CLCASE_OUT /= ''

IF (LLSAVE) THEN
  CALL XRD_MKDIR (TRIM (CLCASE_OUT))
ENDIF

CLOUT = '-'; CALL GETOPTION ("--out", CLOUT)

CALL CHECKOPTIONS

CALL LOADALL

IF (TRIM (CLMETHOD) == 'openmp') THEN

CALL GET_TIME (TSC)

DO ITIME = 1, NTIME
 
!$OMP PARALLEL DO PRIVATE (JBLK, IIDIA, IFDIA)
  DO JBLK = 1, KGPBLKS

    IIDIA = 1
    IFDIA = KLON

    CALL CUCALLN_MF (PPLDARE, PPLRG, KSTEP, YDTHF, YDCST, YDERAD, YDML_PHY_SLIN, YDML_PHY_EC, &
        & YGFL, YDCHEM, YDSPP_CONFIG, YDPERTPAR, IIDIA, IFDIA, KLON, KSMAX, KLEV, PDX (:,JBLK), KSPPN2D, &
        & LDMCAPEA, LDLAND (:,JBLK), LDSLPHY, PTSPHY, PVDIFTS, PTM1 (:,:,JBLK), PQM1 (:,:,JBLK), PUM1 (:,:,JBLK), PVM1 (:,:,JBLK), PLITOT (:,:,JBLK), PVERVEL (:,:,JBLK), &
        & PQHFL (:,:,JBLK), PAHFS (:,:,JBLK), PAPHM1 (:,:,JBLK), PAP (:,:,JBLK), PAPH (:,:,JBLK), PGEO (:,:,JBLK), PGEOH (:,:,JBLK), PGAW (:,JBLK), PCUCONVCA (:,JBLK), PGP2DSPP (:,:,JBLK), &
        & PTENT (:,:,JBLK), PTENQ (:,:,JBLK), PTENU (:,:,JBLK), PTENV (:,:,JBLK), PTENTA (:,:,JBLK), PTENQA (:,:,JBLK), PARPRC (:,JBLK), KTOPC (:,JBLK), KBASEC (:,JBLK), KTYPE (:,JBLK), &
        & KCBOT (:,JBLK), KCTOP (:,JBLK), KBOTSC (:,JBLK), LDCUM (:,JBLK), LDSC (:,JBLK), KCBOT_LIG (:,JBLK), KCTOP_LIG (:,JBLK), LDCUM_LIG (:,JBLK), LDSHCV (:,JBLK), &
        & PLCRIT_AER (:,:,JBLK), PLU (:,:,JBLK), PLUDE (:,:,JBLK), PLUDELI (:,:,:,JBLK), PSNDE (:,:,:,JBLK), PMFU (:,:,JBLK), PMFD (:,:,JBLK), PLGLAC (:,:,JBLK), PDIFCQ (:,:,JBLK), &
        & PDIFCS (:,:,JBLK), PFHPCL (:,:,JBLK), PFHPCN (:,:,JBLK), PFPLCL (:,:,JBLK), PFPLCN (:,:,JBLK), PLRAIN (:,:,JBLK), PRSUD (:,:,:,JBLK), PSTRCU (:,:,JBLK), PSTRCV (:,:,JBLK), &
        & PFCQLF (:,:,JBLK), PFCQIF (:,:,JBLK), PMFUDE_RATE (:,:,JBLK), PMFDDE_RATE (:,:,JBLK), PCAPE (:,JBLK), PWU (:,:,JBLK), PWMEAN (:,JBLK), PVDISCU (:,JBLK), &
        & PDISS (:,:,JBLK), KTRAC, PCM1 (:,:,:,JBLK), PTENC (:,:,:,JBLK), PSCAV, PSCAV0=PSCAV0)

  ENDDO

!$OMP END PARALLEL DO
    
ENDDO

CALL GET_TIME (TEC)

ELSEIF (TRIM (CLMETHOD) == 'parallel') THEN


CALL YDCPG_OPTS%INIT (KLON, KLEV, KGPBLKS)
CALL YDCPG_BNDS%INIT (YDCPG_OPTS)

CALL FIELD_NEW (YD_LDLAND      , DATA=LDLAND      , PERSISTENT=.TRUE., LBOUNDS=LBOUND (LDLAND))
CALL FIELD_NEW (YD_PLCRIT_AER  , DATA=PLCRIT_AER  , PERSISTENT=.TRUE., LBOUNDS=LBOUND (PLCRIT_AER))
CALL FIELD_NEW (YD_PTM1        , DATA=PTM1        , PERSISTENT=.TRUE., LBOUNDS=LBOUND (PTM1))
CALL FIELD_NEW (YD_PQM1        , DATA=PQM1        , PERSISTENT=.TRUE., LBOUNDS=LBOUND (PQM1))
CALL FIELD_NEW (YD_PUM1        , DATA=PUM1        , PERSISTENT=.TRUE., LBOUNDS=LBOUND (PUM1))
CALL FIELD_NEW (YD_PVM1        , DATA=PVM1        , PERSISTENT=.TRUE., LBOUNDS=LBOUND (PVM1))
CALL FIELD_NEW (YD_PCM1        , DATA=PCM1        , PERSISTENT=.TRUE., LBOUNDS=LBOUND (PCM1))
CALL FIELD_NEW (YD_PLITOT      , DATA=PLITOT      , PERSISTENT=.TRUE., LBOUNDS=LBOUND (PLITOT))
CALL FIELD_NEW (YD_PVERVEL     , DATA=PVERVEL     , PERSISTENT=.TRUE., LBOUNDS=LBOUND (PVERVEL))
CALL FIELD_NEW (YD_PQHFL       , DATA=PQHFL       , PERSISTENT=.TRUE., LBOUNDS=LBOUND (PQHFL))
CALL FIELD_NEW (YD_PAHFS       , DATA=PAHFS       , PERSISTENT=.TRUE., LBOUNDS=LBOUND (PAHFS))
CALL FIELD_NEW (YD_PAPHM1      , DATA=PAPHM1      , PERSISTENT=.TRUE., LBOUNDS=LBOUND (PAPHM1))
CALL FIELD_NEW (YD_PAP         , DATA=PAP         , PERSISTENT=.TRUE., LBOUNDS=LBOUND (PAP))
CALL FIELD_NEW (YD_PAPH        , DATA=PAPH        , PERSISTENT=.TRUE., LBOUNDS=LBOUND (PAPH))
CALL FIELD_NEW (YD_PGEO        , DATA=PGEO        , PERSISTENT=.TRUE., LBOUNDS=LBOUND (PGEO))
CALL FIELD_NEW (YD_PGEOH       , DATA=PGEOH       , PERSISTENT=.TRUE., LBOUNDS=LBOUND (PGEOH))
CALL FIELD_NEW (YD_PTENT       , DATA=PTENT       , PERSISTENT=.TRUE., LBOUNDS=LBOUND (PTENT))
CALL FIELD_NEW (YD_PTENQ       , DATA=PTENQ       , PERSISTENT=.TRUE., LBOUNDS=LBOUND (PTENQ))
CALL FIELD_NEW (YD_PTENU       , DATA=PTENU       , PERSISTENT=.TRUE., LBOUNDS=LBOUND (PTENU))
CALL FIELD_NEW (YD_PTENV       , DATA=PTENV       , PERSISTENT=.TRUE., LBOUNDS=LBOUND (PTENV))
CALL FIELD_NEW (YD_PTENTA      , DATA=PTENTA      , PERSISTENT=.TRUE., LBOUNDS=LBOUND (PTENTA))
CALL FIELD_NEW (YD_PTENQA      , DATA=PTENQA      , PERSISTENT=.TRUE., LBOUNDS=LBOUND (PTENQA))
CALL FIELD_NEW (YD_PGAW        , DATA=PGAW        , PERSISTENT=.TRUE., LBOUNDS=LBOUND (PGAW))
CALL FIELD_NEW (YD_PCUCONVCA   , DATA=PCUCONVCA   , PERSISTENT=.TRUE., LBOUNDS=LBOUND (PCUCONVCA))
CALL FIELD_NEW (YD_PGP2DSPP    , DATA=PGP2DSPP    , PERSISTENT=.TRUE., LBOUNDS=LBOUND (PGP2DSPP))
CALL FIELD_NEW (YD_PDX         , DATA=PDX         , PERSISTENT=.TRUE., LBOUNDS=LBOUND (PDX))
CALL FIELD_NEW (YD_PTENC       , DATA=PTENC       , PERSISTENT=.TRUE., LBOUNDS=LBOUND (PTENC))
CALL FIELD_NEW (YD_PARPRC      , DATA=PARPRC      , PERSISTENT=.TRUE., LBOUNDS=LBOUND (PARPRC))
CALL FIELD_NEW (YD_KTOPC       , DATA=KTOPC       , PERSISTENT=.TRUE., LBOUNDS=LBOUND (KTOPC))
CALL FIELD_NEW (YD_KBASEC      , DATA=KBASEC      , PERSISTENT=.TRUE., LBOUNDS=LBOUND (KBASEC))
CALL FIELD_NEW (YD_KTYPE       , DATA=KTYPE       , PERSISTENT=.TRUE., LBOUNDS=LBOUND (KTYPE))
CALL FIELD_NEW (YD_KCBOT       , DATA=KCBOT       , PERSISTENT=.TRUE., LBOUNDS=LBOUND (KCBOT))
CALL FIELD_NEW (YD_KCTOP       , DATA=KCTOP       , PERSISTENT=.TRUE., LBOUNDS=LBOUND (KCTOP))
CALL FIELD_NEW (YD_KCBOT_LIG   , DATA=KCBOT_LIG   , PERSISTENT=.TRUE., LBOUNDS=LBOUND (KCBOT_LIG))
CALL FIELD_NEW (YD_KCTOP_LIG   , DATA=KCTOP_LIG   , PERSISTENT=.TRUE., LBOUNDS=LBOUND (KCTOP_LIG))
CALL FIELD_NEW (YD_KBOTSC      , DATA=KBOTSC      , PERSISTENT=.TRUE., LBOUNDS=LBOUND (KBOTSC))
CALL FIELD_NEW (YD_LDCUM       , DATA=LDCUM       , PERSISTENT=.TRUE., LBOUNDS=LBOUND (LDCUM))
CALL FIELD_NEW (YD_LDCUM_LIG   , DATA=LDCUM_LIG   , PERSISTENT=.TRUE., LBOUNDS=LBOUND (LDCUM_LIG))
CALL FIELD_NEW (YD_LDSC        , DATA=LDSC        , PERSISTENT=.TRUE., LBOUNDS=LBOUND (LDSC))
CALL FIELD_NEW (YD_LDSHCV      , DATA=LDSHCV      , PERSISTENT=.TRUE., LBOUNDS=LBOUND (LDSHCV))
CALL FIELD_NEW (YD_PLU         , DATA=PLU         , PERSISTENT=.TRUE., LBOUNDS=LBOUND (PLU))
CALL FIELD_NEW (YD_PLUDE       , DATA=PLUDE       , PERSISTENT=.TRUE., LBOUNDS=LBOUND (PLUDE))
CALL FIELD_NEW (YD_PLUDELI     , DATA=PLUDELI     , PERSISTENT=.TRUE., LBOUNDS=LBOUND (PLUDELI))
CALL FIELD_NEW (YD_PSNDE       , DATA=PSNDE       , PERSISTENT=.TRUE., LBOUNDS=LBOUND (PSNDE))
CALL FIELD_NEW (YD_PMFU        , DATA=PMFU        , PERSISTENT=.TRUE., LBOUNDS=LBOUND (PMFU))
CALL FIELD_NEW (YD_PMFD        , DATA=PMFD        , PERSISTENT=.TRUE., LBOUNDS=LBOUND (PMFD))
CALL FIELD_NEW (YD_PLGLAC      , DATA=PLGLAC      , PERSISTENT=.TRUE., LBOUNDS=LBOUND (PLGLAC))
CALL FIELD_NEW (YD_PDIFCQ      , DATA=PDIFCQ      , PERSISTENT=.TRUE., LBOUNDS=LBOUND (PDIFCQ))
CALL FIELD_NEW (YD_PDIFCS      , DATA=PDIFCS      , PERSISTENT=.TRUE., LBOUNDS=LBOUND (PDIFCS))
CALL FIELD_NEW (YD_PFHPCL      , DATA=PFHPCL      , PERSISTENT=.TRUE., LBOUNDS=LBOUND (PFHPCL))
CALL FIELD_NEW (YD_PFHPCN      , DATA=PFHPCN      , PERSISTENT=.TRUE., LBOUNDS=LBOUND (PFHPCN))
CALL FIELD_NEW (YD_PFPLCL      , DATA=PFPLCL      , PERSISTENT=.TRUE., LBOUNDS=LBOUND (PFPLCL))
CALL FIELD_NEW (YD_PFPLCN      , DATA=PFPLCN      , PERSISTENT=.TRUE., LBOUNDS=LBOUND (PFPLCN))
CALL FIELD_NEW (YD_PLRAIN      , DATA=PLRAIN      , PERSISTENT=.TRUE., LBOUNDS=LBOUND (PLRAIN))
CALL FIELD_NEW (YD_PRSUD       , DATA=PRSUD       , PERSISTENT=.TRUE., LBOUNDS=LBOUND (PRSUD))
CALL FIELD_NEW (YD_PSTRCU      , DATA=PSTRCU      , PERSISTENT=.TRUE., LBOUNDS=LBOUND (PSTRCU))
CALL FIELD_NEW (YD_PSTRCV      , DATA=PSTRCV      , PERSISTENT=.TRUE., LBOUNDS=LBOUND (PSTRCV))
CALL FIELD_NEW (YD_PFCQLF      , DATA=PFCQLF      , PERSISTENT=.TRUE., LBOUNDS=LBOUND (PFCQLF))
CALL FIELD_NEW (YD_PFCQIF      , DATA=PFCQIF      , PERSISTENT=.TRUE., LBOUNDS=LBOUND (PFCQIF))
CALL FIELD_NEW (YD_PMFUDE_RATE , DATA=PMFUDE_RATE , PERSISTENT=.TRUE., LBOUNDS=LBOUND (PMFUDE_RATE))
CALL FIELD_NEW (YD_PMFDDE_RATE , DATA=PMFDDE_RATE , PERSISTENT=.TRUE., LBOUNDS=LBOUND (PMFDDE_RATE))
CALL FIELD_NEW (YD_PCAPE       , DATA=PCAPE       , PERSISTENT=.TRUE., LBOUNDS=LBOUND (PCAPE))
CALL FIELD_NEW (YD_PWMEAN      , DATA=PWMEAN      , PERSISTENT=.TRUE., LBOUNDS=LBOUND (PWMEAN))
CALL FIELD_NEW (YD_PVDISCU     , DATA=PVDISCU     , PERSISTENT=.TRUE., LBOUNDS=LBOUND (PVDISCU))
CALL FIELD_NEW (YD_PWU         , DATA=PWU         , PERSISTENT=.TRUE., LBOUNDS=LBOUND (PWU))
CALL FIELD_NEW (YD_PDISS       , DATA=PDISS       , PERSISTENT=.TRUE., LBOUNDS=LBOUND (PDISS))

IF (LLVERBOSE) THEN
WRITE (0, *) " NPROMA = ", NPROMA, " NGPBLKS = ", NGPBLKS, " KLEV = ", KLEV
WRITE (0, *) " ISIZE4 = ", ISIZE4, " ISIZE8 = ", ISIZE8, " NTIME = ", NTIME
ENDIF

IF (LLSAVE) THEN
  CALL SAVEIALL
ENDIF

CALL GET_TIME (TSD)

!$ACC DATA COPY (PSCAV, PSCAV0) 

CALL YDTHF%COPY ()
CALL YDCST%COPY ()
CALL YDERAD%COPY ()
CALL YDML_PHY_SLIN%COPY ()
CALL YDML_PHY_EC%COPY ()
CALL YGFL%COPY ()
CALL YDCHEM%COPY ()
CALL YDSPP_CONFIG%COPY ()
CALL YDPERTPAR%COPY ()

CALL GET_TIME (TSC)

YSTACK%IALIGN = 8 
ALLOCATE (YSTACK%ZDATA4 (NPROMA, KLEV, ISIZE4, NGPBLKS))
ALLOCATE (YSTACK%ZDATA8 (NPROMA, KLEV, ISIZE8, NGPBLKS))

!$ACC ENTER DATA CREATE (YSTACK%ZDATA4)
!$ACC ENTER DATA CREATE (YSTACK%ZDATA8)

!$ACC ENTER DATA CREATE (YSTACK)
!$ACC UPDATE DEVICE (YSTACK)
!$ACC ENTER DATA ATTACH (YSTACK%ZDATA4)
!$ACC ENTER DATA ATTACH (YSTACK%ZDATA8)

DO ITIME = 1, NTIME

  CALL CUCALLN_MF_PARALLEL (PPLDARE, PPLRG, KSTEP, YDTHF, YDCST, YDERAD, YDML_PHY_SLIN, YDML_PHY_EC, &
      & YGFL, YDCHEM, YDSPP_CONFIG, YDPERTPAR, YDCPG_OPTS, YDCPG_BNDS, KLON, KSMAX, KLEV, YD_PDX, KSPPN2D, &
      & LDMCAPEA, YD_LDLAND, LDSLPHY, PTSPHY, PVDIFTS, YD_PTM1, YD_PQM1, YD_PUM1, YD_PVM1, YD_PLITOT, YD_PVERVEL, &
      & YD_PQHFL, YD_PAHFS, YD_PAPHM1, YD_PAP, YD_PAPH, YD_PGEO, YD_PGEOH, YD_PGAW, YD_PCUCONVCA, YD_PGP2DSPP, &
      & YD_PTENT, YD_PTENQ, YD_PTENU, YD_PTENV, YD_PTENTA, YD_PTENQA, YD_PARPRC, YD_KTOPC, YD_KBASEC, YD_KTYPE, &
      & YD_KCBOT, YD_KCTOP, YD_KBOTSC, YD_LDCUM, YD_LDSC, YD_KCBOT_LIG, YD_KCTOP_LIG, YD_LDCUM_LIG, YD_LDSHCV, &
      & YD_PLCRIT_AER, YD_PLU, YD_PLUDE, YD_PLUDELI, YD_PSNDE, YD_PMFU, YD_PMFD, YD_PLGLAC, YD_PDIFCQ, &
      & YD_PDIFCS, YD_PFHPCL, YD_PFHPCN, YD_PFPLCL, YD_PFPLCN, YD_PLRAIN, YD_PRSUD, YD_PSTRCU, YD_PSTRCV, &
      & YD_PFCQLF, YD_PFCQIF, YD_PMFUDE_RATE, YD_PMFDDE_RATE, YD_PCAPE, YD_PWU, YD_PWMEAN, YD_PVDISCU, &
      & YD_PDISS, KTRAC, YD_PCM1, YD_PTENC, PSCAV, PSCAV0=PSCAV0)
    
ENDDO

CALL GET_TIME (TEC)

CALL YDPERTPAR%WIPE ()
CALL YDSPP_CONFIG%WIPE ()
CALL YDCHEM%WIPE ()
CALL YGFL%WIPE ()
CALL YDML_PHY_EC%WIPE ()
CALL YDML_PHY_SLIN%WIPE ()
CALL YDERAD%WIPE ()
CALL YDCST%WIPE ()
CALL YDTHF%WIPE ()

!$ACC END DATA

CALL GET_TIME (TED)

CALL FIELD_DELETE (YD_PDISS)
CALL FIELD_DELETE (YD_PWU)
CALL FIELD_DELETE (YD_PVDISCU)
CALL FIELD_DELETE (YD_PWMEAN)
CALL FIELD_DELETE (YD_PCAPE)
CALL FIELD_DELETE (YD_PMFDDE_RATE)
CALL FIELD_DELETE (YD_PMFUDE_RATE)
CALL FIELD_DELETE (YD_PFCQIF)
CALL FIELD_DELETE (YD_PFCQLF)
CALL FIELD_DELETE (YD_PSTRCV)
CALL FIELD_DELETE (YD_PSTRCU)
CALL FIELD_DELETE (YD_PRSUD)
CALL FIELD_DELETE (YD_PLRAIN)
CALL FIELD_DELETE (YD_PFPLCN)
CALL FIELD_DELETE (YD_PFPLCL)
CALL FIELD_DELETE (YD_PFHPCN)
CALL FIELD_DELETE (YD_PFHPCL)
CALL FIELD_DELETE (YD_PDIFCS)
CALL FIELD_DELETE (YD_PDIFCQ)
CALL FIELD_DELETE (YD_PLGLAC)
CALL FIELD_DELETE (YD_PMFD)
CALL FIELD_DELETE (YD_PMFU)
CALL FIELD_DELETE (YD_PSNDE)
CALL FIELD_DELETE (YD_PLUDELI)
CALL FIELD_DELETE (YD_PLUDE)
CALL FIELD_DELETE (YD_PLU)
CALL FIELD_DELETE (YD_LDSHCV)
CALL FIELD_DELETE (YD_LDSC)
CALL FIELD_DELETE (YD_LDCUM_LIG)
CALL FIELD_DELETE (YD_LDCUM)
CALL FIELD_DELETE (YD_KBOTSC)
CALL FIELD_DELETE (YD_KCTOP_LIG)
CALL FIELD_DELETE (YD_KCBOT_LIG)
CALL FIELD_DELETE (YD_KCTOP)
CALL FIELD_DELETE (YD_KCBOT)
CALL FIELD_DELETE (YD_KTYPE)
CALL FIELD_DELETE (YD_KBASEC)
CALL FIELD_DELETE (YD_KTOPC)
CALL FIELD_DELETE (YD_PARPRC)
CALL FIELD_DELETE (YD_PTENC)
CALL FIELD_DELETE (YD_PDX)
CALL FIELD_DELETE (YD_PGP2DSPP)
CALL FIELD_DELETE (YD_PCUCONVCA)
CALL FIELD_DELETE (YD_PGAW)
CALL FIELD_DELETE (YD_PTENQA)
CALL FIELD_DELETE (YD_PTENTA)
CALL FIELD_DELETE (YD_PTENV)
CALL FIELD_DELETE (YD_PTENU)
CALL FIELD_DELETE (YD_PTENQ)
CALL FIELD_DELETE (YD_PTENT)
CALL FIELD_DELETE (YD_PGEOH)
CALL FIELD_DELETE (YD_PGEO)
CALL FIELD_DELETE (YD_PAPH)
CALL FIELD_DELETE (YD_PAP)
CALL FIELD_DELETE (YD_PAPHM1)
CALL FIELD_DELETE (YD_PAHFS)
CALL FIELD_DELETE (YD_PQHFL)
CALL FIELD_DELETE (YD_PVERVEL)
CALL FIELD_DELETE (YD_PLITOT)
CALL FIELD_DELETE (YD_PCM1)
CALL FIELD_DELETE (YD_PVM1)
CALL FIELD_DELETE (YD_PUM1)
CALL FIELD_DELETE (YD_PQM1)
CALL FIELD_DELETE (YD_PTM1)
CALL FIELD_DELETE (YD_PLCRIT_AER)
CALL FIELD_DELETE (YD_LDLAND)

ENDIF

ZTC = TEC - TSC
ZTD = TED - TSD

LLEXIST = .FALSE.

IF (CLOUT == '-') THEN
  IOUT = STDOUT
ELSE
  IOUT = 77
  INQUIRE (FILE=TRIM (CLOUT), EXIST=LLEXIST)
  IF (LLEXIST) THEN
    OPEN (IOUT, FILE=TRIM (CLOUT), FORM='FORMATTED', STATUS='OLD', POSITION='APPEND')
  ELSE
    OPEN (IOUT, FILE=TRIM (CLOUT), FORM='FORMATTED', STATUS='NEW')
  ENDIF
ENDIF

IF (.NOT. LLEXIST) &
WRITE (IOUT, '(A16,";",A8,";",A8,";",A8,";",A8,4(";",A20))') &
              & "CLARCH", "NPROMA", "NGPBLKS", "NTIME", &
              & "ZTCTOT", "ZTC", "ZTDTOT", "ZTD"

WRITE (IOUT, '(A16,";",I8,";",I8,";",I8,4(";",E20.10))') &
              & CLARCH,  NPROMA, NGPBLKS, NTIME, &
              & ZTC, ZTC / REAL (NPROMA*NGPBLKS*NTIME, 8), &
              & ZTD, ZTD / REAL (NPROMA*NGPBLKS*NTIME, 8)

IF (IOUT /= STDOUT) THEN
  CLOSE (IOUT)
ENDIF


IF (LLDIFF) THEN
  CALL DIFFALL
ENDIF

IF (LLSTAT) THEN
  CALL STATALL
ENDIF

IF (LLSAVE) THEN
  CALL SAVEOALL
ENDIF

IF (LHOOK) CALL DR_HOOK ('MAIN_CUCALLN_MF', 1, ZHOOK_HANDLE)

CONTAINS

SUBROUTINE LOADALL

ILUNCI = 77
ILUNFI = 78

OPEN (ILUNCI, NAME=TRIM (CLCASE_IN)//'/CUCALLN_MF.CONST.dat', FORM='UNFORMATTED')
OPEN (ILUNFI, NAME=TRIM (CLCASE_IN)//'/CUCALLN_MF.IN.dat',    FORM='UNFORMATTED')

CALL LOAD (ILUNCI, PPLDARE)
CALL LOAD (ILUNCI, PPLRG)
CALL LOAD (ILUNCI, KSTEP)
CALL YDTHF%LOAD (ILUNCI)
CALL YDCST%LOAD (ILUNCI)
CALL YDERAD%LOAD (ILUNCI)
CALL YDML_PHY_SLIN%LOAD (ILUNCI)
CALL YDML_PHY_EC%LOAD (ILUNCI)
CALL YGFL%LOAD (ILUNCI)
CALL YDCHEM%LOAD (ILUNCI)
CALL YDSPP_CONFIG%LOAD (ILUNCI)
CALL YDPERTPAR%LOAD (ILUNCI)
CALL LOAD (ILUNCI, KLON)
CALL LOAD (ILUNCI, KGPBLKS)


IF (NPROMA == 0) NPROMA = KLON
IF (NGPBLKS == 0) THEN
  IF (ASSOCIATED (IBLOCKLIST)) THEN
    NGPBLKS = SIZE (IBLOCKLIST)
  ELSE
    NGPBLKS = KGPBLKS
  ENDIF
ENDIF

IF ((NPROMA /= KLON) .OR. (NGPBLKS /= KGPBLKS) .OR. ASSOCIATED (IBLOCKLIST)) THEN

  ALLOCATE (YLD)

  IF (ASSOCIATED (IBLOCKLIST)) THEN
    CALL YLD%INIT ([KLON, KGPBLKS], [NPROMA, NGPBLKS], IBLOCKLIST)
  ELSE
    CALL YLD%INIT ([KLON, KGPBLKS], [NPROMA, NGPBLKS])
  ENDIF
  
  NPROMA = YLD%IPROMA2
  NGPBLKS = YLD%IGPBLKS2

ENDIF

KLON = NPROMA
KGPBLKS = NGPBLKS


CALL LOAD (ILUNCI, KSMAX)
CALL LOAD (ILUNCI, KLEV)
CALL LOAD (ILUNFI, PDX,                  YDD=YLD)
CALL LOAD (ILUNCI, KSPPN2D)
CALL LOAD (ILUNCI, LDMCAPEA)
CALL LOAD (ILUNFI, LDLAND,               YDD=YLD)
CALL LOAD (ILUNCI, LDSLPHY)
CALL LOAD (ILUNCI, PTSPHY)
CALL LOAD (ILUNCI, PVDIFTS)
CALL LOAD (ILUNFI, PTM1,                 YDD=YLD)
CALL LOAD (ILUNFI, PQM1,                 YDD=YLD)
CALL LOAD (ILUNFI, PUM1,                 YDD=YLD)
CALL LOAD (ILUNFI, PVM1,                 YDD=YLD)
CALL LOAD (ILUNFI, PLITOT,               YDD=YLD)
CALL LOAD (ILUNFI, PVERVEL,              YDD=YLD)
CALL LOAD (ILUNFI, PQHFL,                YDD=YLD)
CALL LOAD (ILUNFI, PAHFS,                YDD=YLD)
CALL LOAD (ILUNFI, PAPHM1,               YDD=YLD)
CALL LOAD (ILUNFI, PAP,                  YDD=YLD)
CALL LOAD (ILUNFI, PAPH,                 YDD=YLD)
CALL LOAD (ILUNFI, PGEO,                 YDD=YLD)
CALL LOAD (ILUNFI, PGEOH,                YDD=YLD)
CALL LOAD (ILUNFI, PGAW,                 YDD=YLD)
CALL LOAD (ILUNFI, PCUCONVCA,            YDD=YLD)
CALL LOAD (ILUNFI, PGP2DSPP,             YDD=YLD)
CALL LOAD (ILUNFI, PTENT,                YDD=YLD)
CALL LOAD (ILUNFI, PTENQ,                YDD=YLD)
CALL LOAD (ILUNFI, PTENU,                YDD=YLD)
CALL LOAD (ILUNFI, PTENV,                YDD=YLD)
CALL LOAD (ILUNFI, PTENTA,               YDD=YLD)
CALL LOAD (ILUNFI, PTENQA,               YDD=YLD)
CALL LOAD (ILUNFI, PARPRC,               YDD=YLD)
CALL LOAD (ILUNFI, KTOPC,                YDD=YLD)
CALL LOAD (ILUNFI, KBASEC,               YDD=YLD)
CALL LOAD (ILUNFI, KTYPE,                YDD=YLD)
CALL LOAD (ILUNFI, KCBOT,                YDD=YLD)
CALL LOAD (ILUNFI, KCTOP,                YDD=YLD)
CALL LOAD (ILUNFI, KBOTSC,               YDD=YLD)
CALL LOAD (ILUNFI, LDCUM,                YDD=YLD)
CALL LOAD (ILUNFI, LDSC,                 YDD=YLD)
CALL LOAD (ILUNFI, KCBOT_LIG,            YDD=YLD)
CALL LOAD (ILUNFI, KCTOP_LIG,            YDD=YLD)
CALL LOAD (ILUNFI, LDCUM_LIG,            YDD=YLD)
CALL LOAD (ILUNFI, LDSHCV,               YDD=YLD)
CALL LOAD (ILUNFI, PLCRIT_AER,           YDD=YLD)
CALL LOAD (ILUNFI, PLU,                  YDD=YLD)
CALL LOAD (ILUNFI, PLUDE,                YDD=YLD)
CALL LOAD (ILUNFI, PLUDELI,              YDD=YLD)
CALL LOAD (ILUNFI, PSNDE,                YDD=YLD)
CALL LOAD (ILUNFI, PMFU,                 YDD=YLD)
CALL LOAD (ILUNFI, PMFD,                 YDD=YLD)
CALL LOAD (ILUNFI, PLGLAC,               YDD=YLD)
CALL LOAD (ILUNFI, PDIFCQ,               YDD=YLD)
CALL LOAD (ILUNFI, PDIFCS,               YDD=YLD)
CALL LOAD (ILUNFI, PFHPCL,               YDD=YLD)
CALL LOAD (ILUNFI, PFHPCN,               YDD=YLD)
CALL LOAD (ILUNFI, PFPLCL,               YDD=YLD)
CALL LOAD (ILUNFI, PFPLCN,               YDD=YLD)
CALL LOAD (ILUNFI, PLRAIN,               YDD=YLD)
CALL LOAD (ILUNFI, PRSUD,                YDD=YLD)
CALL LOAD (ILUNFI, PSTRCU,               YDD=YLD)
CALL LOAD (ILUNFI, PSTRCV,               YDD=YLD)
CALL LOAD (ILUNFI, PFCQLF,               YDD=YLD)
CALL LOAD (ILUNFI, PFCQIF,               YDD=YLD)
CALL LOAD (ILUNFI, PMFUDE_RATE,          YDD=YLD)
CALL LOAD (ILUNFI, PMFDDE_RATE,          YDD=YLD)
CALL LOAD (ILUNFI, PCAPE,                YDD=YLD)
CALL LOAD (ILUNFI, PWU,                  YDD=YLD)
CALL LOAD (ILUNFI, PWMEAN,               YDD=YLD)
CALL LOAD (ILUNFI, PVDISCU,              YDD=YLD)
CALL LOAD (ILUNFI, PDISS,                YDD=YLD)
CALL LOAD (ILUNCI, KTRAC)
CALL LOAD (ILUNFI, PCM1,                 YDD=YLD)
CALL LOAD (ILUNFI, PTENC,                YDD=YLD)
CALL LOAD (ILUNCI, PSCAV)
CALL LOAD (ILUNCI, PSCAV0)

CLOSE (ILUNFI)
CLOSE (ILUNCI)  

END SUBROUTINE

SUBROUTINE STATALL
IF (LLVERBOSE) PRINT *, " STAT..."

WRITE (*, '(A32," ",A30," ",A30," ",A30," ",A30)') "NAME", "AVG", "MAX", "AVGDIFF", "MAXDIFF"

ILUNFO = 79
OPEN (ILUNFO, NAME=TRIM (CLCASE_IN)//'/CUCALLN_MF.OUT.dat', FORM='UNFORMATTED')
CALL STAT ("PTENT      ", PTENT      , KLUN=ILUNFO, YDD=YLD)
CALL STAT ("PTENQ      ", PTENQ      , KLUN=ILUNFO, YDD=YLD)
CALL STAT ("PTENU      ", PTENU      , KLUN=ILUNFO, YDD=YLD)
CALL STAT ("PTENV      ", PTENV      , KLUN=ILUNFO, YDD=YLD)
CALL STAT ("PTENTA     ", PTENTA     , KLUN=ILUNFO, YDD=YLD)
CALL STAT ("PTENQA     ", PTENQA     , KLUN=ILUNFO, YDD=YLD)
CALL STAT ("PARPRC     ", PARPRC     , KLUN=ILUNFO, YDD=YLD)
CALL STAT ("KTOPC      ", KTOPC      , KLUN=ILUNFO, YDD=YLD)
CALL STAT ("KBASEC     ", KBASEC     , KLUN=ILUNFO, YDD=YLD)
CALL STAT ("KTYPE      ", KTYPE      , KLUN=ILUNFO, YDD=YLD)
CALL STAT ("KCBOT      ", KCBOT      , KLUN=ILUNFO, YDD=YLD)
CALL STAT ("KCTOP      ", KCTOP      , KLUN=ILUNFO, YDD=YLD)
CALL STAT ("KBOTSC     ", KBOTSC     , KLUN=ILUNFO, YDD=YLD)
CALL STAT ("LDCUM      ", LDCUM      , KLUN=ILUNFO, YDD=YLD)
CALL STAT ("LDSC       ", LDSC       , KLUN=ILUNFO, YDD=YLD)
CALL STAT ("KCBOT_LIG  ", KCBOT_LIG  , KLUN=ILUNFO, YDD=YLD)
CALL STAT ("KCTOP_LIG  ", KCTOP_LIG  , KLUN=ILUNFO, YDD=YLD)
CALL STAT ("LDCUM_LIG  ", LDCUM_LIG  , KLUN=ILUNFO, YDD=YLD)
CALL STAT ("PLU        ", PLU        , KLUN=ILUNFO, YDD=YLD)
CALL STAT ("PLUDE      ", PLUDE      , KLUN=ILUNFO, YDD=YLD)
CALL STAT ("PLUDELI    ", PLUDELI    , KLUN=ILUNFO, YDD=YLD)
CALL STAT ("PSNDE      ", PSNDE      , KLUN=ILUNFO, YDD=YLD)
CALL STAT ("PMFU       ", PMFU       , KLUN=ILUNFO, YDD=YLD)
CALL STAT ("PMFD       ", PMFD       , KLUN=ILUNFO, YDD=YLD)
CALL STAT ("PLGLAC     ", PLGLAC     , KLUN=ILUNFO, YDD=YLD)
CALL STAT ("PDIFCQ     ", PDIFCQ     , KLUN=ILUNFO, YDD=YLD)
CALL STAT ("PDIFCS     ", PDIFCS     , KLUN=ILUNFO, YDD=YLD)
CALL STAT ("PFHPCL     ", PFHPCL     , KLUN=ILUNFO, YDD=YLD)
CALL STAT ("PFHPCN     ", PFHPCN     , KLUN=ILUNFO, YDD=YLD)
CALL STAT ("PFPLCL     ", PFPLCL     , KLUN=ILUNFO, YDD=YLD)
CALL STAT ("PFPLCN     ", PFPLCN     , KLUN=ILUNFO, YDD=YLD)
CALL STAT ("PLRAIN     ", PLRAIN     , KLUN=ILUNFO, YDD=YLD)
CALL STAT ("PRSUD      ", PRSUD      , KLUN=ILUNFO, YDD=YLD)
CALL STAT ("PSTRCU     ", PSTRCU     , KLUN=ILUNFO, YDD=YLD)
CALL STAT ("PSTRCV     ", PSTRCV     , KLUN=ILUNFO, YDD=YLD)
CALL STAT ("PFCQLF     ", PFCQLF     , KLUN=ILUNFO, YDD=YLD)
CALL STAT ("PFCQIF     ", PFCQIF     , KLUN=ILUNFO, YDD=YLD)
CALL STAT ("PMFUDE_RATE", PMFUDE_RATE, KLUN=ILUNFO, YDD=YLD)
CALL STAT ("PMFDDE_RATE", PMFDDE_RATE, KLUN=ILUNFO, YDD=YLD)
CALL STAT ("PCAPE      ", PCAPE      , KLUN=ILUNFO, YDD=YLD)
CALL STAT ("PWU        ", PWU        , KLUN=ILUNFO, YDD=YLD)
CALL STAT ("PWMEAN     ", PWMEAN     , KLUN=ILUNFO, YDD=YLD)
CALL STAT ("PVDISCU    ", PVDISCU    , KLUN=ILUNFO, YDD=YLD)
CALL STAT ("PDISS      ", PDISS      , KLUN=ILUNFO, YDD=YLD)
CALL STAT ("PTENC      ", PTENC      , KLUN=ILUNFO, YDD=YLD)
CLOSE (ILUNFO)

IF (LLVERBOSE) PRINT *, " ...STAT"

END SUBROUTINE

SUBROUTINE DIFFALL
IF (LLVERBOSE) PRINT *, " DIFF..."

ILUNFO = 79
OPEN (ILUNFO, NAME=TRIM (CLCASE_IN)//'/CUCALLN_MF.OUT.dat', FORM='UNFORMATTED')
CALL DIFF ("PTENT      ", PTENT      , KLUN=ILUNFO, YDD=YLD)
CALL DIFF ("PTENQ      ", PTENQ      , KLUN=ILUNFO, YDD=YLD)
CALL DIFF ("PTENU      ", PTENU      , KLUN=ILUNFO, YDD=YLD)
CALL DIFF ("PTENV      ", PTENV      , KLUN=ILUNFO, YDD=YLD)
CALL DIFF ("PTENTA     ", PTENTA     , KLUN=ILUNFO, YDD=YLD)
CALL DIFF ("PTENQA     ", PTENQA     , KLUN=ILUNFO, YDD=YLD)
CALL DIFF ("PARPRC     ", PARPRC     , KLUN=ILUNFO, YDD=YLD)
CALL DIFF ("KTOPC      ", KTOPC      , KLUN=ILUNFO, YDD=YLD)
CALL DIFF ("KBASEC     ", KBASEC     , KLUN=ILUNFO, YDD=YLD)
CALL DIFF ("KTYPE      ", KTYPE      , KLUN=ILUNFO, YDD=YLD)
CALL DIFF ("KCBOT      ", KCBOT      , KLUN=ILUNFO, YDD=YLD)
CALL DIFF ("KCTOP      ", KCTOP      , KLUN=ILUNFO, YDD=YLD)
CALL DIFF ("KBOTSC     ", KBOTSC     , KLUN=ILUNFO, YDD=YLD)
CALL DIFF ("LDCUM      ", LDCUM      , KLUN=ILUNFO, YDD=YLD)
CALL DIFF ("LDSC       ", LDSC       , KLUN=ILUNFO, YDD=YLD)
CALL DIFF ("KCBOT_LIG  ", KCBOT_LIG  , KLUN=ILUNFO, YDD=YLD)
CALL DIFF ("KCTOP_LIG  ", KCTOP_LIG  , KLUN=ILUNFO, YDD=YLD)
CALL DIFF ("LDCUM_LIG  ", LDCUM_LIG  , KLUN=ILUNFO, YDD=YLD)
CALL DIFF ("PLU        ", PLU        , KLUN=ILUNFO, YDD=YLD)
CALL DIFF ("PLUDE      ", PLUDE      , KLUN=ILUNFO, YDD=YLD)
CALL DIFF ("PLUDELI    ", PLUDELI    , KLUN=ILUNFO, YDD=YLD)
CALL DIFF ("PSNDE      ", PSNDE      , KLUN=ILUNFO, YDD=YLD)
CALL DIFF ("PMFU       ", PMFU       , KLUN=ILUNFO, YDD=YLD)
CALL DIFF ("PMFD       ", PMFD       , KLUN=ILUNFO, YDD=YLD)
CALL DIFF ("PLGLAC     ", PLGLAC     , KLUN=ILUNFO, YDD=YLD)
CALL DIFF ("PDIFCQ     ", PDIFCQ     , KLUN=ILUNFO, YDD=YLD)
CALL DIFF ("PDIFCS     ", PDIFCS     , KLUN=ILUNFO, YDD=YLD)
CALL DIFF ("PFHPCL     ", PFHPCL     , KLUN=ILUNFO, YDD=YLD)
CALL DIFF ("PFHPCN     ", PFHPCN     , KLUN=ILUNFO, YDD=YLD)
CALL DIFF ("PFPLCL     ", PFPLCL     , KLUN=ILUNFO, YDD=YLD)
CALL DIFF ("PFPLCN     ", PFPLCN     , KLUN=ILUNFO, YDD=YLD)
CALL DIFF ("PLRAIN     ", PLRAIN     , KLUN=ILUNFO, YDD=YLD)
CALL DIFF ("PRSUD      ", PRSUD      , KLUN=ILUNFO, YDD=YLD)
CALL DIFF ("PSTRCU     ", PSTRCU     , KLUN=ILUNFO, YDD=YLD)
CALL DIFF ("PSTRCV     ", PSTRCV     , KLUN=ILUNFO, YDD=YLD)
CALL DIFF ("PFCQLF     ", PFCQLF     , KLUN=ILUNFO, YDD=YLD)
CALL DIFF ("PFCQIF     ", PFCQIF     , KLUN=ILUNFO, YDD=YLD)
CALL DIFF ("PMFUDE_RATE", PMFUDE_RATE, KLUN=ILUNFO, YDD=YLD)
CALL DIFF ("PMFDDE_RATE", PMFDDE_RATE, KLUN=ILUNFO, YDD=YLD)
CALL DIFF ("PCAPE      ", PCAPE      , KLUN=ILUNFO, YDD=YLD)
CALL DIFF ("PWU        ", PWU        , KLUN=ILUNFO, YDD=YLD)
CALL DIFF ("PWMEAN     ", PWMEAN     , KLUN=ILUNFO, YDD=YLD)
CALL DIFF ("PVDISCU    ", PVDISCU    , KLUN=ILUNFO, YDD=YLD)
CALL DIFF ("PDISS      ", PDISS      , KLUN=ILUNFO, YDD=YLD)
CALL DIFF ("PTENC      ", PTENC      , KLUN=ILUNFO, YDD=YLD)
CLOSE (ILUNFO)

IF (LLVERBOSE) PRINT *, " ...DIFF"

END SUBROUTINE

SUBROUTINE SAVEIALL

ILUNCI = 77
ILUNFI = 78

OPEN (ILUNCI, NAME=TRIM (CLCASE_OUT)//'/CUCALLN_MF.CONST.dat', FORM='UNFORMATTED')
OPEN (ILUNFI, NAME=TRIM (CLCASE_OUT)//'/CUCALLN_MF.IN.dat',    FORM='UNFORMATTED')

CALL SAVE (ILUNCI, PPLDARE)
CALL SAVE (ILUNCI, PPLRG)
CALL SAVE (ILUNCI, KSTEP)
CALL YDTHF%SAVE (ILUNCI)
CALL YDCST%SAVE (ILUNCI)
CALL YDERAD%SAVE (ILUNCI)
CALL YDML_PHY_SLIN%SAVE (ILUNCI)
CALL YDML_PHY_EC%SAVE (ILUNCI)
CALL YGFL%SAVE (ILUNCI)
CALL YDCHEM%SAVE (ILUNCI)
CALL YDSPP_CONFIG%SAVE (ILUNCI)
CALL YDPERTPAR%SAVE (ILUNCI)
CALL SAVE (ILUNCI, KLON)
CALL SAVE (ILUNCI, KGPBLKS)
CALL SAVE (ILUNCI, KSMAX)
CALL SAVE (ILUNCI, KLEV)
CALL SAVE (ILUNFI, PDX, KLBOUND=LBOUND (PDX))
CALL SAVE (ILUNCI, KSPPN2D)
CALL SAVE (ILUNCI, LDMCAPEA)
CALL SAVE (ILUNFI, LDLAND, KLBOUND=LBOUND (LDLAND))
CALL SAVE (ILUNCI, LDSLPHY)
CALL SAVE (ILUNCI, PTSPHY)
CALL SAVE (ILUNCI, PVDIFTS)
CALL SAVE (ILUNFI, PTM1, KLBOUND=LBOUND (PTM1))
CALL SAVE (ILUNFI, PQM1, KLBOUND=LBOUND (PQM1))
CALL SAVE (ILUNFI, PUM1, KLBOUND=LBOUND (PUM1))
CALL SAVE (ILUNFI, PVM1, KLBOUND=LBOUND (PVM1))
CALL SAVE (ILUNFI, PLITOT, KLBOUND=LBOUND (PLITOT))
CALL SAVE (ILUNFI, PVERVEL, KLBOUND=LBOUND (PVERVEL))
CALL SAVE (ILUNFI, PQHFL, KLBOUND=LBOUND (PQHFL))
CALL SAVE (ILUNFI, PAHFS, KLBOUND=LBOUND (PAHFS))
CALL SAVE (ILUNFI, PAPHM1, KLBOUND=LBOUND (PAPHM1))
CALL SAVE (ILUNFI, PAP, KLBOUND=LBOUND (PAP))
CALL SAVE (ILUNFI, PAPH, KLBOUND=LBOUND (PAPH))
CALL SAVE (ILUNFI, PGEO, KLBOUND=LBOUND (PGEO))
CALL SAVE (ILUNFI, PGEOH, KLBOUND=LBOUND (PGEOH))
CALL SAVE (ILUNFI, PGAW, KLBOUND=LBOUND (PGAW))
CALL SAVE (ILUNFI, PCUCONVCA, KLBOUND=LBOUND (PCUCONVCA))
CALL SAVE (ILUNFI, PGP2DSPP, KLBOUND=LBOUND (PGP2DSPP))
CALL SAVE (ILUNFI, PTENT, KLBOUND=LBOUND (PTENT))
CALL SAVE (ILUNFI, PTENQ, KLBOUND=LBOUND (PTENQ))
CALL SAVE (ILUNFI, PTENU, KLBOUND=LBOUND (PTENU))
CALL SAVE (ILUNFI, PTENV, KLBOUND=LBOUND (PTENV))
CALL SAVE (ILUNFI, PTENTA, KLBOUND=LBOUND (PTENTA))
CALL SAVE (ILUNFI, PTENQA, KLBOUND=LBOUND (PTENQA))
CALL SAVE (ILUNFI, PARPRC, KLBOUND=LBOUND (PARPRC))
CALL SAVE (ILUNFI, KTOPC, KLBOUND=LBOUND (KTOPC))
CALL SAVE (ILUNFI, KBASEC, KLBOUND=LBOUND (KBASEC))
CALL SAVE (ILUNFI, KTYPE, KLBOUND=LBOUND (KTYPE))
CALL SAVE (ILUNFI, KCBOT, KLBOUND=LBOUND (KCBOT))
CALL SAVE (ILUNFI, KCTOP, KLBOUND=LBOUND (KCTOP))
CALL SAVE (ILUNFI, KBOTSC, KLBOUND=LBOUND (KBOTSC))
CALL SAVE (ILUNFI, LDCUM, KLBOUND=LBOUND (LDCUM))
CALL SAVE (ILUNFI, LDSC, KLBOUND=LBOUND (LDSC))
CALL SAVE (ILUNFI, KCBOT_LIG, KLBOUND=LBOUND (KCBOT_LIG))
CALL SAVE (ILUNFI, KCTOP_LIG, KLBOUND=LBOUND (KCTOP_LIG))
CALL SAVE (ILUNFI, LDCUM_LIG, KLBOUND=LBOUND (LDCUM_LIG))
CALL SAVE (ILUNFI, LDSHCV, KLBOUND=LBOUND (LDSHCV))
CALL SAVE (ILUNFI, PLCRIT_AER, KLBOUND=LBOUND (PLCRIT_AER))
CALL SAVE (ILUNFI, PLU, KLBOUND=LBOUND (PLU))
CALL SAVE (ILUNFI, PLUDE, KLBOUND=LBOUND (PLUDE))
CALL SAVE (ILUNFI, PLUDELI, KLBOUND=LBOUND (PLUDELI))
CALL SAVE (ILUNFI, PSNDE, KLBOUND=LBOUND (PSNDE))
CALL SAVE (ILUNFI, PMFU, KLBOUND=LBOUND (PMFU))
CALL SAVE (ILUNFI, PMFD, KLBOUND=LBOUND (PMFD))
CALL SAVE (ILUNFI, PLGLAC, KLBOUND=LBOUND (PLGLAC))
CALL SAVE (ILUNFI, PDIFCQ, KLBOUND=LBOUND (PDIFCQ))
CALL SAVE (ILUNFI, PDIFCS, KLBOUND=LBOUND (PDIFCS))
CALL SAVE (ILUNFI, PFHPCL, KLBOUND=LBOUND (PFHPCL))
CALL SAVE (ILUNFI, PFHPCN, KLBOUND=LBOUND (PFHPCN))
CALL SAVE (ILUNFI, PFPLCL, KLBOUND=LBOUND (PFPLCL))
CALL SAVE (ILUNFI, PFPLCN, KLBOUND=LBOUND (PFPLCN))
CALL SAVE (ILUNFI, PLRAIN, KLBOUND=LBOUND (PLRAIN))
CALL SAVE (ILUNFI, PRSUD, KLBOUND=LBOUND (PRSUD))
CALL SAVE (ILUNFI, PSTRCU, KLBOUND=LBOUND (PSTRCU))
CALL SAVE (ILUNFI, PSTRCV, KLBOUND=LBOUND (PSTRCV))
CALL SAVE (ILUNFI, PFCQLF, KLBOUND=LBOUND (PFCQLF))
CALL SAVE (ILUNFI, PFCQIF, KLBOUND=LBOUND (PFCQIF))
CALL SAVE (ILUNFI, PMFUDE_RATE, KLBOUND=LBOUND (PMFUDE_RATE))
CALL SAVE (ILUNFI, PMFDDE_RATE, KLBOUND=LBOUND (PMFDDE_RATE))
CALL SAVE (ILUNFI, PCAPE, KLBOUND=LBOUND (PCAPE))
CALL SAVE (ILUNFI, PWU, KLBOUND=LBOUND (PWU))
CALL SAVE (ILUNFI, PWMEAN, KLBOUND=LBOUND (PWMEAN))
CALL SAVE (ILUNFI, PVDISCU, KLBOUND=LBOUND (PVDISCU))
CALL SAVE (ILUNFI, PDISS, KLBOUND=LBOUND (PDISS))
CALL SAVE (ILUNCI, KTRAC)
CALL SAVE (ILUNFI, PCM1, KLBOUND=LBOUND (PCM1))
CALL SAVE (ILUNFI, PTENC, KLBOUND=LBOUND (PTENC))
CALL SAVE (ILUNCI, PSCAV, KLBOUND=LBOUND (PSCAV))
CALL SAVE (ILUNCI, PSCAV0, KLBOUND=LBOUND (PSCAV0))

CLOSE (ILUNFI)
CLOSE (ILUNCI)  

END SUBROUTINE

SUBROUTINE SAVEOALL

ILUNFO = 79
OPEN (ILUNFO, NAME=TRIM (CLCASE_OUT)//'/CUCALLN_MF.OUT.dat', FORM='UNFORMATTED')
CALL SAVE (ILUNFO, PTENT, KLBOUND=LBOUND (PTENT))
CALL SAVE (ILUNFO, PTENQ, KLBOUND=LBOUND (PTENQ))
CALL SAVE (ILUNFO, PTENU, KLBOUND=LBOUND (PTENU))
CALL SAVE (ILUNFO, PTENV, KLBOUND=LBOUND (PTENV))
CALL SAVE (ILUNFO, PTENTA, KLBOUND=LBOUND (PTENTA))
CALL SAVE (ILUNFO, PTENQA, KLBOUND=LBOUND (PTENQA))
CALL SAVE (ILUNFO, PARPRC, KLBOUND=LBOUND (PARPRC))
CALL SAVE (ILUNFO, KTOPC, KLBOUND=LBOUND (KTOPC))
CALL SAVE (ILUNFO, KBASEC, KLBOUND=LBOUND (KBASEC))
CALL SAVE (ILUNFO, KTYPE, KLBOUND=LBOUND (KTYPE))
CALL SAVE (ILUNFO, KCBOT, KLBOUND=LBOUND (KCBOT))
CALL SAVE (ILUNFO, KCTOP, KLBOUND=LBOUND (KCTOP))
CALL SAVE (ILUNFO, KBOTSC, KLBOUND=LBOUND (KBOTSC))
CALL SAVE (ILUNFO, LDCUM, KLBOUND=LBOUND (LDCUM))
CALL SAVE (ILUNFO, LDSC, KLBOUND=LBOUND (LDSC))
CALL SAVE (ILUNFO, KCBOT_LIG, KLBOUND=LBOUND (KCBOT_LIG))
CALL SAVE (ILUNFO, KCTOP_LIG, KLBOUND=LBOUND (KCTOP_LIG))
CALL SAVE (ILUNFO, LDCUM_LIG, KLBOUND=LBOUND (LDCUM_LIG))
CALL SAVE (ILUNFO, PLU, KLBOUND=LBOUND (PLU))
CALL SAVE (ILUNFO, PLUDE, KLBOUND=LBOUND (PLUDE))
CALL SAVE (ILUNFO, PLUDELI, KLBOUND=LBOUND (PLUDELI))
CALL SAVE (ILUNFO, PSNDE, KLBOUND=LBOUND (PSNDE))
CALL SAVE (ILUNFO, PMFU, KLBOUND=LBOUND (PMFU))
CALL SAVE (ILUNFO, PMFD, KLBOUND=LBOUND (PMFD))
CALL SAVE (ILUNFO, PLGLAC, KLBOUND=LBOUND (PLGLAC))
CALL SAVE (ILUNFO, PDIFCQ, KLBOUND=LBOUND (PDIFCQ))
CALL SAVE (ILUNFO, PDIFCS, KLBOUND=LBOUND (PDIFCS))
CALL SAVE (ILUNFO, PFHPCL, KLBOUND=LBOUND (PFHPCL))
CALL SAVE (ILUNFO, PFHPCN, KLBOUND=LBOUND (PFHPCN))
CALL SAVE (ILUNFO, PFPLCL, KLBOUND=LBOUND (PFPLCL))
CALL SAVE (ILUNFO, PFPLCN, KLBOUND=LBOUND (PFPLCN))
CALL SAVE (ILUNFO, PLRAIN, KLBOUND=LBOUND (PLRAIN))
CALL SAVE (ILUNFO, PRSUD, KLBOUND=LBOUND (PRSUD))
CALL SAVE (ILUNFO, PSTRCU, KLBOUND=LBOUND (PSTRCU))
CALL SAVE (ILUNFO, PSTRCV, KLBOUND=LBOUND (PSTRCV))
CALL SAVE (ILUNFO, PFCQLF, KLBOUND=LBOUND (PFCQLF))
CALL SAVE (ILUNFO, PFCQIF, KLBOUND=LBOUND (PFCQIF))
CALL SAVE (ILUNFO, PMFUDE_RATE, KLBOUND=LBOUND (PMFUDE_RATE))
CALL SAVE (ILUNFO, PMFDDE_RATE, KLBOUND=LBOUND (PMFDDE_RATE))
CALL SAVE (ILUNFO, PCAPE, KLBOUND=LBOUND (PCAPE))
CALL SAVE (ILUNFO, PWU, KLBOUND=LBOUND (PWU))
CALL SAVE (ILUNFO, PWMEAN, KLBOUND=LBOUND (PWMEAN))
CALL SAVE (ILUNFO, PVDISCU, KLBOUND=LBOUND (PVDISCU))
CALL SAVE (ILUNFO, PDISS, KLBOUND=LBOUND (PDISS))
CALL SAVE (ILUNFO, PTENC, KLBOUND=LBOUND (PTENC))
CLOSE (ILUNFO)

END SUBROUTINE

END 

